const categoryMap={"Hand Reading":["Hand Reading"],"Preflop":["Preflop"],"Pot Odds":["Pot Odds"],"Tournament":["Tournament"],"Showdown":["Showdown"],"Mixed":["Hand Reading","Preflop","Pot Odds","Tournament","Showdown"]};
let state={mode:"diagnostic",questions:[],index:0,score:0,answered:false,streak:0,startedAt:0,timer:null,timeLeft:60,stats:{}};
function loadStats(){const saved=JSON.parse(localStorage.getItem("pokerTrainerStats")||"{}");saved.best=saved.best||0;saved.total=saved.total||0;saved.streak=saved.streak||0;saved.categories=saved.categories||{};document.getElementById("bestScore").textContent=saved.best?saved.best+"%":"—";document.getElementById("totalAnswered").textContent=saved.total;document.getElementById("globalStreak").textContent=saved.streak;let weakest="Unknown",low=101;for(const[cat,s]of Object.entries(saved.categories)){if(s.total>=3){const pct=s.correct/s.total*100;if(pct<low){low=pct;weakest=cat}}}document.getElementById("weakArea").textContent=weakest}
function saveAnswer(cat,correct){const saved=JSON.parse(localStorage.getItem("pokerTrainerStats")||"{}");saved.best=saved.best||0;saved.total=(saved.total||0)+1;saved.streak=correct?(saved.streak||0)+1:0;saved.categories=saved.categories||{};saved.categories[cat]=saved.categories[cat]||{correct:0,total:0};saved.categories[cat].total++;if(correct)saved.categories[cat].correct++;localStorage.setItem("pokerTrainerStats",JSON.stringify(saved));loadStats()}
function saveDiagnostic(pct){const saved=JSON.parse(localStorage.getItem("pokerTrainerStats")||"{}");saved.best=Math.max(saved.best||0,pct);localStorage.setItem("pokerTrainerStats",JSON.stringify(saved));loadStats()}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.screen===id))}
document.querySelectorAll(".nav button").forEach(b=>b.addEventListener("click",()=>{showScreen(b.dataset.screen);if(b.dataset.screen==="daily")renderDaily()}));
function startQuiz(mode,category){clearInterval(state.timer);state.mode=mode;state.index=0;state.score=0;state.answered=false;state.streak=0;state.startedAt=Date.now();state.stats={};let pool=[...Q];if(mode==="category"){const cats=categoryMap[category]||categoryMap.Mixed;pool=pool.filter(x=>cats.includes(x.cat));state.questions=shuffle(pool).slice(0,Math.min(8,pool.length))}else if(mode==="rapid"){state.questions=shuffle(pool);state.timeLeft=60}else{const selected=[];const targets={"Hand Reading":2,"Showdown":2,"Preflop":3,"Pot Odds":2,"Tournament":3};for(const[cat,n]of Object.entries(targets)){selected.push(...shuffle(pool.filter(x=>x.cat===cat)).slice(0,n))}state.questions=shuffle(selected)}showScreen("quiz");renderQuestion();if(mode==="rapid"){state.timer=setInterval(()=>{state.timeLeft--;const el=document.getElementById("timer");if(el)el.textContent=state.timeLeft+"s";if(state.timeLeft<=0){clearInterval(state.timer);finishQuiz()}},1000)}}
function cardHTML(card){const suit=card.slice(-1);const rank=card.slice(0,-1);const red=suit==="♥"||suit==="♦";return `<div class="playing-card ${red?"red":""}"><span>${rank}</span><span class="suit">${suit}</span></div>`}
function scenarioHTML(q){let out="";if(q.hole)out+=`<div class="board-label">Your hand</div><div class="cards-row">${q.hole.map(cardHTML).join("")}</div>`;if(q.board)out+=`<div class="board-label">Board</div><div class="cards-row">${q.board.map(cardHTML).join("")}</div>`;if(q.p1){out+=`<div class="board-label">Player 1</div><div class="cards-row">${q.p1.map(cardHTML).join("")}</div>`;out+=`<div class="board-label">Player 2</div><div class="cards-row">${q.p2.map(cardHTML).join("")}</div>`}return out}
function renderQuestion(){if(state.index>=state.questions.length&&state.mode!=="rapid"){finishQuiz();return}if(state.mode==="rapid"&&state.index>=state.questions.length)state.questions.push(...shuffle(Q));const q=state.questions[state.index];const total=state.mode==="rapid"?"∞":state.questions.length;const pct=state.mode==="rapid"?Math.min(100,(60-state.timeLeft)/60*100):state.index/state.questions.length*100;document.getElementById("quizArea").innerHTML=`<div class="quiz-wrap"><div class="question-card"><div class="progress"><div style="width:${pct}%"></div></div><div class="question-meta"><span>${q.cat}</span><span>${state.mode==="rapid"?`<span class="timer" id="timer">${state.timeLeft}s</span>`:`Question ${state.index+1} / ${total}`}</span></div><div class="question-title">${q.q}</div>${scenarioHTML(q)}<div class="answers">${q.answers.map((a,i)=>`<button class="answer" onclick="answerQuestion(${i})">${String.fromCharCode(65+i)}. ${a}</button>`).join("")}</div><div class="feedback" id="feedback"></div><div class="next-row"><button class="btn gold hidden" id="nextBtn" onclick="nextQuestion()">Next hand</button></div></div><aside class="sidebox"><h3>Session</h3><div class="mini-row"><span>Correct</span><b>${state.score}</b></div><div class="mini-row"><span>Answered</span><b>${state.index}</b></div><div class="mini-row"><span>Streak</span><b>${state.streak}</b></div><div class="mini-row"><span>Mode</span><b>${state.mode==="rapid"?"Rapid":"Study"}</b></div><button class="btn ghost" style="width:100%;margin-top:14px" onclick="finishQuiz()">End session</button></aside></div>`;state.answered=false}
function answerQuestion(choice){if(state.answered)return;state.answered=true;const q=state.questions[state.index];const correct=choice===q.correct;const buttons=[...document.querySelectorAll(".answer")];buttons.forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add("correct");if(i===choice&&!correct)b.classList.add("wrong")});const fb=document.getElementById("feedback");fb.className="feedback show "+(correct?"good":"bad");fb.innerHTML=`<strong>${correct?"Correct. Clean decision.":"Not quite."}</strong>${q.exp}`;if(correct){state.score++;state.streak++}else state.streak=0;state.stats[q.cat]=state.stats[q.cat]||{correct:0,total:0};state.stats[q.cat].total++;if(correct)state.stats[q.cat].correct++;saveAnswer(q.cat,correct);state.index++;if(state.mode==="rapid"){setTimeout(()=>{if(state.timeLeft>0)renderQuestion()},650)}else{document.getElementById("nextBtn").classList.remove("hidden");document.getElementById("nextBtn").textContent=state.index>=state.questions.length?"See results":"Next hand"}}
function nextQuestion(){renderQuestion()}
function finishQuiz(){clearInterval(state.timer);const answered=Object.values(state.stats).reduce((s,x)=>s+x.total,0);const pct=answered?Math.round(state.score/answered*100):0;if(state.mode==="diagnostic")saveDiagnostic(pct);let verdict,note;if(pct>=90){verdict="Final-table menace";note="You are making strong, disciplined decisions. Your biggest edge now is emotional control and observing your friends."}else if(pct>=75){verdict="Tournament ready";note="You have a solid base. Review your weakest category and avoid hero calls born from boredom."}else if(pct>=60){verdict="Dangerous, but leaky";note="You can absolutely compete, but a few repeated mistakes may drain your stack. Drill the lowest-scoring category once more."}else{verdict="Keep the buy-in friendly";note="The good news: your leaks are very fixable. Focus on hand rankings, position, and short-stack decisions before adding fancy bluffs."}const cats=Object.entries(state.stats);document.getElementById("quizArea").innerHTML=`<div class="result"><div class="score-ring" style="--pct:${pct}"><b>${pct}%</b></div><div class="eyebrow">${answered} decisions reviewed</div><h2>${verdict}</h2><p>${note}</p><div class="breakdown">${cats.length?cats.map(([cat,s])=>{const p=Math.round(s.correct/s.total*100);return `<div class="barrow"><div class="label"><span>${cat}</span><b>${s.correct}/${s.total} · ${p}%</b></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join(""):"<p>No hands answered yet.</p>"}</div><div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap"><button class="btn gold" onclick="startQuiz('diagnostic')">Run diagnostic again</button><button class="btn" onclick="showScreen('home')">Choose focused practice</button><button class="btn ghost" onclick="showScreen('cheat')">Open cheat sheet</button></div></div>`}
function localDateKey(date=new Date()){const y=date.getFullYear();const m=String(date.getMonth()+1).padStart(2,"0");const d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`}
function parseDateKey(key){const[y,m,d]=key.split("-").map(Number);return new Date(y,m-1,d)}
function previousDateKey(key){const dt=parseDateKey(key);dt.setDate(dt.getDate()-1);return localDateKey(dt)}
function getDailyStore(){const store=JSON.parse(localStorage.getItem("pokerDailyHands")||"{}");store.completed=store.completed||{};store.streak=store.streak||0;store.bestStreak=store.bestStreak||0;store.lastCompleted=store.lastCompleted||null;return store}
function saveDailyStore(store){localStorage.setItem("pokerDailyHands",JSON.stringify(store))}
function dailyHash(key){let h=2166136261;for(let i=0;i<key.length;i++){h^=key.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h>>>0)}
function getDailyQuestion(key=localDateKey()){return Q[dailyHash(key)%Q.length]}
function formatDailyDate(key){return parseDateKey(key).toLocaleDateString(undefined,{weekday:"long",day:"numeric",month:"long",year:"numeric"})}
function updateDailyBanner(){const store=getDailyStore();const key=localDateKey();const done=store.completed[key];const title=document.getElementById("dailyBannerTitle");const streak=document.getElementById("dailyBannerStreak");const stateEl=document.getElementById("dailyBannerState");const btn=document.getElementById("dailyBannerButton");if(!title)return;streak.textContent=`🔥 ${store.streak}-day streak`;if(done){title.textContent=done.correct?"Today’s hand: solved cleanly":"Today’s hand: lesson banked";stateEl.textContent=done.correct?"Correct today":"Completed today";btn.textContent="Review today’s hand"}else{title.textContent="Today’s hand is waiting";stateEl.textContent="Unsolved today";btn.textContent="Play today’s hand"}}
function openDaily(){showScreen("daily");renderDaily()}
function dailyCalendarHTML(store){const today=new Date();const cells=[];for(let offset=20;offset>=0;offset--){const d=new Date(today.getFullYear(),today.getMonth(),today.getDate()-offset);const key=localDateKey(d);const done=!!store.completed[key];cells.push(`<div class="day-dot ${done?"done":""} ${offset===0?"today":""}" title="${formatDailyDate(key)}">${d.getDate()}</div>`)}return `<div class="board-label">Last 21 days</div><div class="daily-calendar">${cells.join("")}</div>`}
function renderDaily(){const key=localDateKey();const store=getDailyStore();const saved=store.completed[key];const q=getDailyQuestion(key);const area=document.getElementById("dailyArea");area.innerHTML=`<div class="daily-card"><div class="daily-top"><div><div class="eyebrow">Daily tournament spot</div><div class="daily-date">${formatDailyDate(key)}</div></div><div class="streak-flame">🔥 ${store.streak} day${store.streak===1?"":"s"}</div></div><div class="question-title">${q.q}</div>${scenarioHTML(q)}<div class="answers">${q.answers.map((a,i)=>`<button class="answer ${saved&&i===q.correct?"correct":""} ${saved&&i===saved.choice&&!saved.correct?"wrong":""}" ${saved?"disabled":""} onclick="answerDaily(${i})">${String.fromCharCode(65+i)}. ${a}</button>`).join("")}</div><div class="feedback ${saved?"show "+(saved.correct?"good":"bad"):""}" id="dailyFeedback">${saved?`<strong>${saved.correct?"Correct. Daily chip secured.":"Completed. This one stung, so it will stick."}</strong>${q.exp}`:""}</div>${saved?`<div class="daily-complete"><h3>${saved.correct?"♠ Nice read.":"♦ Useful mistake."}</h3><p>${saved.correct?"Come back tomorrow for a new spot. The daily repetition is where tournament instincts are forged.":"You still earned the streak by committing to the decision and studying the explanation."}</p><b>Best streak: ${store.bestStreak} day${store.bestStreak===1?"":"s"}</b><div class="share-row"><button class="btn gold" onclick="shareDaily()">Share today’s result</button><button class="btn ghost" onclick="startQuiz('rapid')">Play rapid fire</button></div></div>`:`<div class="locked-note">Choose once. The answer and explanation unlock after your decision.</div>`}${dailyCalendarHTML(store)}</div>`}
function answerDaily(choice){const key=localDateKey();const store=getDailyStore();if(store.completed[key])return;const q=getDailyQuestion(key);const correct=choice===q.correct;const yesterday=previousDateKey(key);if(store.lastCompleted===yesterday)store.streak=(store.streak||0)+1;else if(store.lastCompleted!==key)store.streak=1;store.lastCompleted=key;store.bestStreak=Math.max(store.bestStreak||0,store.streak);store.completed[key]={choice,correct,category:q.cat,completedAt:new Date().toISOString()};saveDailyStore(store);saveAnswer(q.cat,correct);updateDailyBanner();renderDaily()}
function showToast(message){const el=document.getElementById("toast");if(!el)return;el.textContent=message;el.classList.add("show");clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>el.classList.remove("show"),1800)}
async function shareDaily(){const key=localDateKey();const store=getDailyStore();const result=store.completed[key];if(!result)return;const marker=result.correct?"🟩":"🟨";const text=`Daily Poker Hand ${key}\n${marker} Solved · 🔥 ${store.streak}-day streak\nNo spoilers — play the same hand:`;const url=`${location.origin}${location.pathname}#daily`;try{if(navigator.share){await navigator.share({title:"Daily Poker Hand",text,url})}else{await navigator.clipboard.writeText(`${text}\n${url}`);showToast("Result copied — send it to the table")}}catch(err){if(err&&err.name!=="AbortError")showToast("Copy the page link to share")}}
function openLinkedScreen(){if(location.hash==="#daily")openDaily()}
loadStats();updateDailyBanner();openLinkedScreen();
