let KB0=null,KB=null,EVAL=null,active=null,receiptMode='human';const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const stop='ich du er sie es wir ihr der die das ein eine einen und oder ist bin sind was wie wo wann muss brauche mit zu für fuer nach in von am im beim bitte hallo'.split(' ');let stats={queries:0,totalConf:0,handoff:0,intents:{},events:[],eval:null};
function tok(s=''){return s.toLowerCase().replace(/[ä]/g,'ae').replace(/[ö]/g,'oe').replace(/[ü]/g,'ue').replace(/[ß]/g,'ss').replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>2&&!stop.includes(w))}
function score(q,c){const T=tok(q),H=tok([c.topic,c.title,c.department,c.text,(c.steps||[]).join(' ')].join(' '));let n=0;T.forEach(t=>{if(H.includes(t))n+=3;else if(H.some(h=>h.includes(t)||t.includes(h)))n+=1});return n}
function confidence(n){return n>7?0.92:n>3?0.76:n>0?0.55:0.32}function confText(c){return c>.85?'starker Quellen-Treffer':c>.65?'brauchbarer Quellen-Treffer, ggf. Rückfrage':c>.45?'schwacher Treffer, Handoff prüfen':'unsicher, Rückfrage nötig'}
function sourceLabel(c){return c.source||('Demo-Wissensbasis · '+c.title)}function humanSource(c){return sourceLabel(c).replace('Beispielsburg Wissensbasis: ','').replace('Beispielsburg Prozess: ','')}function retrieve(q){let rows=KB.chunks.map(c=>({...c,score:score(q,c)})).sort((a,b)=>b.score-a.score);return rows[0]?.score?rows.slice(0,3):[{id:'fallback',topic:'unklar',title:'Rückfrage nötig',department:'Telefonzentrale',action:'callback',text:'Ich bin mir nicht sicher, welches Anliegen gemeint ist. Ich würde eine kurze Rückfrage stellen oder eine Rückrufbitte vorbereiten, statt eine unsichere Auskunft zu geben.',steps:['Rückfrage stellen','keine Antwort erfinden','menschliche Übergabe anbieten'],source:'Fallback-Regel · sichere Unsicherheit',score:0}]}
function actionLabel(a){return {appointment:'Termin vorbereiten',ticket:'Ticket vorbereiten',callback:'Rückruf vorbereiten',appointment_or_callback:'Termin oder Rückruf vorbereiten',eval:'Qualität prüfen',answer:'Auskunft geben'}[a]||'Auskunft geben'}
function actionPayload(c,q){let base={request_id:'CK-'+Math.floor(100000+Math.random()*900000),question:q,intent:c.topic,department:c.department,source:{label:humanSource(c),internal_id:c.id||'fallback'},action:c.action,missing_fields:[]};if(c.action==='appointment'||c.action==='appointment_or_callback')base.missing_fields=['Name','Geburtsdatum optional','gewünschter Zeitraum','Kontakt'];if(c.action==='ticket')base.missing_fields=['genauer Standort','Foto optional','Dringlichkeit'];if(c.action==='callback')base.missing_fields=['Name','Telefonnummer','Zeitfenster'];return base}
function makeReceipts(c,q,conf){const payload=actionPayload(c,q);const human=`Bürgeranliegen: ${q}\n\nEinschätzung: ${c.title}\nZuständig: ${c.department}\nQuelle: ${humanSource(c)}\nConfidence: ${Math.round(conf*100)}% (${confText(conf)})\n\nNächste Aktion: ${actionLabel(c.action)}\nFehlende Angaben: ${payload.missing_fields.length?payload.missing_fields.join(', '):'keine'}\n\nQualität: Quelle gefunden, Routing dokumentiert, nächste Aktion vorbereitet. Bei Unsicherheit: Rückfrage oder Handoff.`;const machine={version:'charlykit.receipt.v0',request_id:payload.request_id,user_question:q,intent:c.topic,department:c.department,source:{display_name:humanSource(c),internal_id:c.id||'fallback',score:c.score},retrieval_confidence:conf,next_action:c.action,missing_fields:payload.missing_fields,guardrails:['answer only from retrieved source','show uncertainty','human handoff when weak confidence'],payload};return {human,machine}}
function render(q){const hits=retrieve(q),c=hits[0],conf=confidence(c.score);active={q,c,hits,conf,receipts:makeReceipts(c,q,conf)};$('citizen').textContent=c.text;$('sourceName').textContent=humanSource(c);$('sourceMeta').textContent=(c.id&&c.id!=='fallback'?'Demo-Quelle · interne ID verborgen: '+c.id:'Fallback · keine sichere Quelle');$('conf').textContent=Math.round(conf*100)+'%';$('confText').textContent=confText(conf);$('dept').textContent=c.department;$('action').textContent=actionLabel(c.action);$('steps').innerHTML=(c.steps||[]).map((s,i)=>`<li><input type="checkbox"><span><b>Schritt ${i+1}:</b> ${esc(s)}<br><small>${helperText(c.action,s)}</small></span></li>`).join('');drawReceipt();logEvent(q,c,conf);drawDash()}
function helperText(action,step){if(action==='appointment'||action==='appointment_or_callback')return 'Charly kann daraus Terminart, Unterlagencheck und Rückrufoption vorbereiten.';if(action==='ticket')return 'Charly kann Standort/Kategorie/Dringlichkeit in ein Ticket-Payload überführen.';if(action==='callback')return 'Charly kann Rückrufdaten erfassen und den Kontext für den Fachbereich anhängen.';return 'Charly kann die Auskunft mit Quelle dokumentieren und Zufriedenheit abfragen.'}
function drawReceipt(){if(!active)return;$('receipt').textContent=receiptMode==='human'?active.receipts.human:JSON.stringify(active.receipts.machine,null,2)}
function logEvent(q,c,conf){stats.queries++;stats.totalConf+=conf;if(conf<.55||c.id==='fallback')stats.handoff++;stats.intents[c.topic]=(stats.intents[c.topic]||0)+1;stats.events.unshift({q,intent:c.topic,action:c.action,conf,time:new Date().toLocaleTimeString()});stats.events=stats.events.slice(0,8)}
function drawDash(){$('mQueries').textContent=stats.queries;$('mAvg').textContent=stats.queries?Math.round(stats.totalConf/stats.queries*100)+'%':'–';$('mHandoff').textContent=stats.queries?Math.round(stats.handoff/stats.queries*100)+'%':'–';$('mEval').textContent=stats.eval||'–';$('topIntents').innerHTML=Object.entries(stats.intents).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<li><b>${esc(k)}</b> · ${v}</li>`).join('')||'<li>Noch keine Daten.</li>';$('eventLog').innerHTML=stats.events.map(e=>`<li>${e.time} · ${esc(e.intent)} · ${Math.round(e.conf*100)}%<br><span>${esc(e.q)}</span></li>`).join('')||'<li>Noch keine Events.</li>'}
function fillAdmin(){const sel=$('chunkSelect');sel.innerHTML=KB.chunks.map((c,i)=>`<option value="${i}">${esc(c.title)} · ${esc(c.department)}</option>`).join('');loadAdmin(0)}function loadAdmin(i){const c=KB.chunks[i];$('adminSource').value=c.source||'';$('adminTitle').value=c.title||'';$('adminDept').value=c.department||'';$('adminAction').value=c.action||'answer';$('adminText').value=c.text||''}
function saveAdmin(){const i=+$('chunkSelect').value,c=KB.chunks[i];c.source=$('adminSource').value;c.title=$('adminTitle').value;c.department=$('adminDept').value;c.action=$('adminAction').value;c.text=$('adminText').value;localStorage.setItem('charlykit-kb',JSON.stringify(KB));render($('question').value);fillAdmin();$('chunkSelect').value=i;loadAdmin(i)}
function resetKb(){localStorage.removeItem('charlykit-kb');KB=structuredClone(KB0);fillAdmin();render($('question').value)}
function runEval(){let ok=0;const rows=EVAL.tests.map(t=>{let h=retrieve(t.q)[0],pass=h.topic===t.expectTopic&&h.action===t.expectAction;if(pass)ok++;return `${pass?'✅':'⚠️'} ${t.q} → ${h.topic}/${h.action}`});stats.eval=ok+'/'+EVAL.tests.length;drawDash();$('receipt').textContent='Eval Ergebnis:\n'+stats.eval+'\n\n'+rows.join('\n')}
async function askLlm(){const q=$('question').value;$('citizen').textContent='Günstiges OpenRouter-LLM läuft…';try{const r=await fetch('/api/charly',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})});const d=await r.json();if(!r.ok)throw new Error(d.error||d.detail||'API not available');$('citizen').textContent=d.citizen_answer||d.answer||'';$('sourceName').textContent=(d.sources?.[0]?.source)||'LLM/RAG Quelle';$('sourceMeta').textContent='Provider '+(d.provider||'')+' · Modell '+(d.model||'');$('conf').textContent=d.confidence?Math.round(Number(d.confidence)*100)+'%':'–';$('confText').textContent='LLM confidence aus strukturierter Antwort';$('dept').textContent=d.department||'–';$('action').textContent=d.action||'–';$('steps').innerHTML=(d.next_steps||[]).map((s,i)=>`<li><input type="checkbox"><span><b>Schritt ${i+1}:</b> ${esc(s)}</span></li>`).join('');$('receipt').textContent=JSON.stringify(d,null,2);logEvent(q,{topic:d.intent||'llm',action:d.action||'answer',id:'llm',department:d.department||'–',title:d.intent||'LLM'},Number(d.confidence)||.7);drawDash()}catch(e){render(q);$('receipt').textContent+='\n\nLLM nicht erreichbar: '+e.message+'\nTipp: Vercel + OPENROUTER_API_KEY setzen.'}}
function copyChecklist(){const txt=[...document.querySelectorAll('#steps li span')].map(x=>x.innerText).join('\n');navigator.clipboard?.writeText(txt);$('receipt').textContent='Checkliste kopiert:\n\n'+txt}function simulateAction(){if(!active)return;const p=actionPayload(active.c,active.q);$('receipt').textContent='Vorbereitete Aktion:\n'+JSON.stringify(p,null,2)}
function bind(){document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{$('question').value=b.dataset.q;render(b.dataset.q)});$('local').onclick=()=>render($('question').value);$('llm').onclick=askLlm;$('eval').onclick=runEval;$('copyChecklist').onclick=copyChecklist;$('simulateAction').onclick=simulateAction;document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');receiptMode=t.dataset.tab;drawReceipt()});$('chunkSelect').onchange=e=>loadAdmin(+e.target.value);$('saveChunk').onclick=saveAdmin;$('resetKb').onclick=resetKb}
document.addEventListener('DOMContentLoaded',async()=>{KB0=await fetch('../zaitgeist-v2/knowledge.json').then(r=>r.json());EVAL=await fetch('../zaitgeist-v2/eval.json').then(r=>r.json());KB=JSON.parse(localStorage.getItem('charlykit-kb')||'null')||structuredClone(KB0);bind();fillAdmin();render($('question').value)});