let state=TriD.start(),selected=null,selectedAB=null,rx=58,rz=-26,drag=false,lastX=0,lastY=0;
const $=id=>document.getElementById(id),FILES='abcdef';
function coordKey(c){return TriD.k(c.x,c.y,c.z)}
function pretty(c){return `${FILES[c.x]}${c.y}(${c.z})`}
function squareColor(x,y){return((x+y)%2===0)?'light':'dark'}
function render(){renderScene();renderPanel();renderStatus()}
function renderScene(){const w=$('world');w.innerHTML='';const legal=selected?new Set(TriD.legalTargets(state,selected).map(coordKey)):new Set();
 const boards=[...TriD.MAIN.map(b=>({...b,type:'main'})),...state.abs.map(ab=>({id:ab.id,type:'attack',kind:ab.kind,owner:ab.owner,squares:TriD.abSquares(ab),z:TriD.abSquares(ab)[0].z,label:`${ab.id} · ${ab.inverted?'INVERTED':'UPRIGHT'}`}))];
 boards.forEach(b=>{let plane=document.createElement('div');plane.className='board-plane '+b.type;let squares=[];let x0,y0,z;
   if(b.type==='main'){x0=b.x0;y0=b.y0;z=b.z;for(let y=y0+3;y>=y0;y--)for(let x=x0;x<x0+4;x++)squares.push({x,y,z})}
   else{const raw=b.squares;x0=Math.min(...raw.map(s=>s.x));y0=Math.min(...raw.map(s=>s.y));z=b.z;for(let y=Math.max(...raw.map(s=>s.y));y>=Math.min(...raw.map(s=>s.y));y--)for(let x=Math.min(...raw.map(s=>s.x));x<=Math.max(...raw.map(s=>s.x));x++)squares.push(raw.find(s=>s.x===x&&s.y===y));}
   const X=(x0-1)*54+145,Y=(7-y0)*54+75,Z=(z-4)*67;plane.style.transform=`translate3d(${X}px,${Y}px,${Z}px)`;
   let lab=document.createElement('div');lab.className='board-label '+(b.type==='attack'?`owner-${b.owner}`:'');lab.textContent=b.type==='main'?b.label:b.label;plane.appendChild(lab);
   if(b.type==='attack'){let post=document.createElement('div');post.className='post';plane.appendChild(post)}
   squares.forEach(c=>{let s=document.createElement('div');s.className='board-square '+squareColor(c.x,c.y);let key=coordKey(c);if(selected&&key===coordKey(selected))s.classList.add('selected');if(legal.has(key))s.classList.add('legal');const p=TriD.pieceAt(state,c);if(p){let pc=document.createElement('span');pc.className='piece '+(p[0]==='w'?'white':'black');pc.textContent=TriD.PIECE_SYMBOL[p];s.appendChild(pc)}s.dataset.key=key;s.addEventListener('pointerdown',e=>e.stopPropagation());s.onclick=e=>{e.stopPropagation();onSquare(c)};plane.appendChild(s)});w.appendChild(plane)
 })}
function onSquare(c){const p=TriD.pieceAt(state,c);if(selected){const res=TriD.movePiece(state,selected,c);if(res.ok){$('lastEvent').textContent=`${state.last.piece} ${pretty(state.last.from)} → ${pretty(state.last.to)}${state.last.captured?' · capture':''}`;selected=null;selectedAB=null;render();return}if(p&&p[0]===state.turn){selected=c;selectedAB=null;render();return}$('moveInfo').textContent=res.msg;return}
 if(p&&p[0]===state.turn){selected=c;selectedAB=null;render();return}
 const ab=TriD.findABAt(state,c);if(ab&&TriD.abEligible(state,ab)){selectedAB=ab.id;selected=null;render()}}
function renderStatus(){state.rookPawnOption=$('rookPawn').checked;let st=TriD.status(state);$('turnTop').textContent=st.turn==='w'?'WHITE':'BLACK';$('gameStatus').textContent=st.winner?`${st.winner==='w'?'White':'Black'} wins.`:`${st.turn==='w'?'White':'Black'} to move${st.check?' · CHECK':''}.`;}
function renderPanel(){if(selected){const p=TriD.pieceAt(state,selected),targets=TriD.legalTargets(state,selected);$('selectedText').textContent=`${p} · ${pretty(selected)}`;$('selectedSub').textContent=`${targets.length} legal vector${targets.length===1?'':'s'}`;$('moveInfo').textContent=targets.length?'Highlighted destinations obey projected movement + highest-path validation.':'No legal moves from this square.'}else if(selectedAB){let ab=state.abs.find(a=>a.id===selectedAB);$('selectedText').textContent=`Attack board ${ab.id}`;$('selectedSub').textContent=`Owned by ${ab.owner==='w'?'White':'Black'} · ${ab.inverted?'inverted':'upright'}`;$('moveInfo').textContent='Moving an attack board consumes the turn.'}else{$('selectedText').textContent='None';$('selectedSub').textContent='Choose a piece or attack board.';$('moveInfo').textContent=''}
 const list=$('abList');list.innerHTML='';state.abs.forEach(ab=>{let b=document.createElement('button');b.className='ab-btn '+(selectedAB===ab.id?'active':'');b.disabled=!TriD.abEligible(state,ab);b.innerHTML=`<b>${ab.id}</b> · ${ab.owner==='w'?'WHITE':'BLACK'}<div class="ab-meta">post ${FILES[ab.kind==='Q'?1:4]}${ab.anchor.r}(${ab.anchor.z}) · ${ab.inverted?'inverted':'upright'}</div>`;b.onclick=()=>{selectedAB=ab.id;selected=null;render()};list.appendChild(b)});
 const acts=$('abActions');acts.innerHTML='';if(selectedAB){let ab=state.abs.find(a=>a.id===selectedAB);TriD.abActions(state,ab).forEach(a=>{let b=document.createElement('button');b.className='ab-action';b.textContent=a.label;b.onclick=()=>{let r=TriD.moveAB(state,selectedAB,a);$('lastEvent').textContent=r.msg;selectedAB=null;render()};acts.appendChild(b)})}}
$('reset').onclick=()=>{state=TriD.start();selected=null;selectedAB=null;$('rookPawn').checked=true;$('lastEvent').textContent='Opening position loaded.';render()};$('undo').onclick=()=>{if(state.history.length){state=TriD.undo(state);selected=null;selectedAB=null;$('lastEvent').textContent='Temporal rollback complete.';render()}};$('rookPawn').onchange=()=>{state.rookPawnOption=$('rookPawn').checked;render()};
$('heroView').onclick=()=>{rx=58;rz=-26;applyView()};$('topView').onclick=()=>{rx=4;rz=0;applyView()};function applyView(){document.documentElement.style.setProperty('--rx',rx+'deg');document.documentElement.style.setProperty('--rz',rz+'deg')}
const scene=$('scene');scene.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;scene.setPointerCapture(e.pointerId)});scene.addEventListener('pointermove',e=>{if(!drag)return;rz+=(e.clientX-lastX)*.18;rx=Math.max(3,Math.min(76,rx-(e.clientY-lastY)*.14));lastX=e.clientX;lastY=e.clientY;applyView()});scene.addEventListener('pointerup',()=>drag=false);scene.addEventListener('pointercancel',()=>drag=false);
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));$(b.dataset.tab+'Tab').classList.add('active')});
const baseBack=['R','N','B','Q','K','B','N','R'];let oi=0,ply=0,acad={};function acadStart(){acad={};for(let i=0;i<8;i++){acad[FILES[i]+'1']='w'+baseBack[i];acad[FILES[i]+'2']='wP';acad[FILES[i]+'7']='bP';acad[FILES[i]+'8']='b'+baseBack[i]}}
const LINES=[['e2e4','e7e5','g1f3','b8c6','f1c4'],['e2e4','e7e5','g1f3','b8c6','f1b5'],['e2e4','e7e5','g1f3','b8c6','d2d4'],['e2e4','e7e5','b1c3','g8f6','f2f4'],['e2e4','c7c5','g1f3','d7d6','d2d4'],['e2e4','c7c6','d2d4','d7d5','b1c3'],['e2e4','e7e6','d2d4','d7d5','b1c3'],['d2d4','d7d5','c2c4','e7e6','b1c3'],['d2d4','d7d5','c2c4','c7c6','g1f3'],['d2d4','g8f6','c2c4','g7g6','b1c3','f8g7'],['d2d4','g8f6','c2c4','e7e6','b1c3','f8b4'],['d2d4','g8f6','c2c4','g7g6','b1c3','d7d5'],['d2d4','g8f6','c2c4','e7e6','g2g3','d7d5','f1g2'],['d2d4','d7d5','g1f3','g8f6','c1f4'],['c2c4','e7e5','b1c3','g8f6','g2g3'],['g1f3','d7d5','c2c4','e7e6','g2g3']];
function acadMove(m){let a=m.slice(0,2),b=m.slice(2),p=acad[a];if(p){delete acad[a];acad[b]=p}}
function renderAcademy(){acadStart();for(let i=0;i<ply;i++)acadMove(LINES[oi][i]);$('openingName').textContent=OPENINGS[oi].name;$('openingWhy').textContent=OPENINGS[oi].why;let ml=$('openingMoves');ml.innerHTML='';OPENINGS[oi].moves.forEach((m,i)=>{let s=document.createElement('span');s.textContent=m;s.className=i<ply?'done':i===ply?'current':'';ml.appendChild(s)});let b=$('academyBoard');b.innerHTML='';for(let r=8;r>=1;r--)for(let f=0;f<8;f++){let q=document.createElement('div');q.className='acad-sq '+squareColor(f,r);let p=acad[FILES[f]+r];if(p){q.textContent=TriD.PIECE_SYMBOL[p];q.classList.add(p[0])}b.appendChild(q)}document.querySelectorAll('.opening-item').forEach((e,i)=>e.classList.toggle('active',i===oi))}
function buildOpeningList(){let l=$('openingList');l.innerHTML='';OPENINGS.forEach((o,i)=>{let b=document.createElement('button');b.className='opening-item';b.innerHTML=`<b>${o.name}</b><small>${o.why}</small>`;b.onclick=()=>{oi=i;ply=0;renderAcademy()};l.appendChild(b)})}
$('nextOpening').onclick=()=>{ply=Math.min(LINES[oi].length,ply+1);renderAcademy()};$('prevOpening').onclick=()=>{ply=Math.max(0,ply-1);renderAcademy()};$('resetOpening').onclick=()=>{ply=0;renderAcademy()};buildOpeningList();renderAcademy();render();