function setConnectedUI(on){connected=on;$('#connect').textContent=on?'End encounter':(isAdult()?`Enter with ${currentChar().name}`:`Meet ${currentChar().name}`);$('#interrupt').disabled=!on||isAdult();$('#closeEncounter').disabled=!on;$('#textInput').disabled=!on;$('#send').disabled=!on;$$('.character,.portal').forEach(b=>b.disabled=on)}
async function disconnect(reason='user'){userEnded=reason==='user';clearInterval(statsTimer);dc?.close();pc?.getSenders().forEach(s=>s.track?.stop());pc?.close();pc=dc=null;micStream?.getTracks().forEach(t=>t.stop());micStream=null;micContext?.close().catch(()=>{});outContext?.close().catch(()=>{});micContext=outContext=null;cancelAnimationFrame(micRAF);cancelAnimationFrame(outRAF);if(callId){fetch('/api/hangup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({callId}),keepalive:true}).catch(()=>{});callId=''}setConnectedUI(false);setPhase(reason==='user'?'offline':'recovering');updateAvailability()}
$('#connect').onclick=connect;$('#interrupt').onclick=()=>{send({type:'response.cancel'});send({type:'output_audio_buffer.clear'});setPhase('idle')};$('#closeEncounter').onclick=()=>{if(isAdult())disconnect('user');else sendText($('#language').value==='de'?'Beende die Begegnung mit genau einem konkreten nächsten Schritt für mein reales Leben.':'Close this encounter with exactly one concrete next step for my real life.')};
async function adultChat(text){setPhase('thinking');$('#assistantTranscript').textContent=currentChar().name+' is composing…';const history=turns.filter(t=>t.adult).slice(-12).map(t=>({role:t.role==='assistant'?'assistant':'user',content:t.text}));const resp=await fetch('/api/adult-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({adultConfirmed:true,character:activeCharacter,intensity:Number($('#personalityIntensity').value),language:$('#language').value,memory:$('#memoryEnabled').checked?memories().slice(-8):[],messages:history})});const data=await resp.json().catch(()=>({}));if(!resp.ok)throw new Error(data.error||data.detail||`OpenRouter ${resp.status}`);const reply=String(data.reply||'').trim();$('#assistantTranscript').textContent=currentChar().name+': '+reply;addTurn('assistant',reply);applyOpenRouterUsage(data.usage);inspect(reply);setPhase('idle')}
async function sendText(override=''){const text=(override||$('#textInput').value).trim();if(!text||!connected)return;$('#textInput').value='';$('#userTranscript').textContent='You: '+text;addTurn('user',text);try{if(isAdult())await adultChat(text);else{send({type:'conversation.item.create',item:{type:'message',role:'user',content:[{type:'input_text',text}]}});send({type:'response.create'})}}catch(e){alertBox(e.message);setPhase('idle')}}
$('#send').onclick=()=>sendText();$('#textInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey)sendText()};
fetch('/api/health',{cache:'no-store'}).then(r=>r.json()).then(h=>{$('#engine').dataset.openai=String(!!h.openaiConfigured);$('#engine').dataset.openrouter=String(!!h.openrouterConfigured);$('#engine').textContent=h.openaiConfigured?'ready':'OpenAI key missing';$('#avatarState').textContent='VRM runtime';updatePortal()}).catch(()=>{alertBox('Server healthcheck unreachable');$('#engine').textContent='unreachable'});
addEventListener('beforeunload',()=>disconnect('user'));loadData();updateCharacter();updatePortal();setPhase('offline');renderCost();
window.SOULBODY={get character(){return activeCharacter},get portal(){return activePortal},get presence(){return presence},setAvatarLoaded(v){$('#stage').classList.toggle('vrm-ready',v);$('#avatarLoader').classList.toggle('hidden',v);$('#bodyState').textContent=v?'VRM live':'fallback';$('#avatarState').textContent=v?'VRM live':'VRM unavailable'},setExpression(name){presence.emotion=name;$('#emotion').textContent=name}};
