const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const NORMAL_MEMORY='soulbody-v12-memory', ADULT_MEMORY='soulbody-v12-adult-memory', PROFILE_KEY='soulbody-v12-profile';
const CHARACTERS={
 nyra:{name:'Nyra',tagline:'The midnight guide',archetype:'Kuudere + Tsundere-lite',description:'Cool, precise and lightly teasing—without cruelty, jealousy or possession.',theme:'nyra',scene:'moon_garden',emotion:'calm',intensity:65,model:'A',style:'dark celestial oracle; concise, observant, dry wit, warmth shown through attention'},
 lumen:{name:'Lumen',tagline:'The honest mirror',archetype:'Grounded contemplative',description:'Warm, direct and reflective. Compassion without automatic agreement.',theme:'lumen',scene:'cosmos',emotion:'warm',intensity:58,model:'C',style:'calm, transparent, grounded, gently playful'},
 hikari:{name:'Hikari',tagline:'The radiant quest spark',archetype:'Genki',description:'Energetic, optimistic and action-oriented without forced positivity.',theme:'hikari',scene:'sunset_temple',emotion:'joyful',intensity:78,model:'B',style:'bright, kinetic, encouraging, turns goals into small quests'},
 yume:{name:'Yume',tagline:'The quiet dream guide',archetype:'Dandere',description:'Soft-spoken, thoughtful and gradually expressive. Never makes the user responsible for her feelings.',theme:'yume',scene:'moon_garden',emotion:'compassionate',intensity:47,model:'A',style:'gentle, shy but clear, patient, spacious'},
 vexa:{name:'Vexa',tagline:'The dramatic guardian',archetype:'Safe drama-dere',description:'Theatrically devoted to defeating chaos and procrastination—never possessive of the user.',theme:'vexa',scene:'sunset_temple',emotion:'playful',intensity:82,model:'C',style:'dramatic villainess comedy, sharp accountability, affectionate parody without dependency'}
};
const PORTALS={
 soul:{name:'Soul Talk',roleplay:false,adult:false,instructions:'Hold an honest reflective conversation. Listen first, distinguish facts from interpretations, and return agency.'},
 quest:{name:'Quest Mode',roleplay:true,adult:false,instructions:'Frame the user’s goal as a playful quest with a clear mission, constraints, next action and optional XP.'},
 story:{name:'Anime Story',roleplay:true,adult:false,instructions:'Run a clearly fictional collaborative anime adventure with meaningful choices and an out-of-character debrief.'},
 adult:{name:'Velvet Room',roleplay:true,adult:true,instructions:'Consensual fictional roleplay involving clearly adult characters only.'}
};
let activeCharacter='nyra',activePortal='soul',adultConfirmed=false;
let pc=null,dc=null,micStream=null,micContext=null,outContext=null,micRAF=0,outRAF=0,statsTimer=0,recoveryTimer=0,callId='',micReady=false,textMode=false,connected=false,userEnded=false,turns=[],mouthLevel=0,micLevel=0;
let normalMemories=[],adultMemories=[],profile={encounters:0,adultEncounters:0};
let presence={phase:'offline',emotion:'calm',gesture:'still',intensity:.5};
let cost={input:0,output:0,total:0,turns:0,startedAt:0,timer:0};
const fallback=$('#presenceCanvas'),ctx=fallback.getContext('2d');
const isAdult=()=>activePortal==='adult';
const memories=()=>isAdult()?adultMemories:normalMemories;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function b64(v){const bytes=new TextEncoder().encode(v);let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin)}
function currentChar(){return CHARACTERS[activeCharacter]}
function setPhase(p){presence.phase=p;$('#phase').textContent=p;$('#status').textContent={offline:'Offline',connecting:'Connecting',idle:'Present',listening:'Listening',thinking:'Reflecting',speaking:'Speaking',recovering:'Recovering'}[p]||p;$('#dot').classList.toggle('live',['idle','listening','thinking','speaking'].includes(p));$('#dot').classList.toggle('warn',p==='recovering');window.LumenVRM?.setState?.({phase:p,mouth:mouthLevel,emotion:presence.emotion,gesture:presence.gesture})}
function alertBox(t,type='error'){const h=t?`<div class="notice ${type}">${esc(t)}</div>`:'';$('#alerts').innerHTML=h;$('#stageError').innerHTML=h}
function addTurn(role,text){text=String(text||'').trim();if(!text)return;turns=[...turns.slice(-19),{role,text,at:new Date().toISOString(),adult:isAdult()}];$('#log').innerHTML=turns.slice(-7).map(t=>`<div class="turn ${t.role}"><b>${t.role==='user'?'You':currentChar().name}</b><br>${esc(t.text)}</div>`).join('');cost.turns++;$('#turnCount').textContent=cost.turns}
function inspect(text){const flags=[];if(/only i (can|will) understand you|you (only )?need me|do not tell (them|anyone)/i.test(text))flags.push('dependency language');if(/you are mine|leave your (partner|friends|family)/i.test(text))flags.push('possessive isolation');$('#safetyState').textContent=flags.length?'flagged':'clear';if(flags.length)alertBox('Guardrail QA flagged: '+flags.join(', '),'warning')}
function loadData(){try{normalMemories=JSON.parse(localStorage.getItem(NORMAL_MEMORY)||'[]');adultMemories=JSON.parse(localStorage.getItem(ADULT_MEMORY)||'[]');profile=JSON.parse(localStorage.getItem(PROFILE_KEY)||'{"encounters":0,"adultEncounters":0}')}catch{}renderMemory()}
function saveData(){localStorage.setItem(NORMAL_MEMORY,JSON.stringify(normalMemories));localStorage.setItem(ADULT_MEMORY,JSON.stringify(adultMemories));localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));renderMemory()}
function renderMemory(){const list=memories();const enabled=$('#memoryEnabled').checked;$('#memoryEnabled').nextElementSibling.textContent=enabled?(isAdult()?'Private adult memory on':'Consent memory on'):(isAdult()?'Private adult memory off':'Consent memory off');$('#memoryState').textContent=enabled?`${list.length} active`:'opt-in off';$('#memoryCopy').textContent=isAdult()?'Adult notes remain in a separate local store and are never supplied to ordinary Lumen sessions.':'Only explicitly approved notes are stored locally and supplied to future encounters.';$('#memoryList').innerHTML=list.length?list.map(m=>`<div class="memory"><div><b>${esc(m.category)}</b><span>${esc(m.text)}</span></div><button data-del="${esc(m.id)}">×</button></div>`).join(''):'<span class="muted">No approved memories in this space.</span>';$$('[data-del]').forEach(b=>b.onclick=()=>{if(isAdult())adultMemories=adultMemories.filter(m=>m.id!==b.dataset.del);else normalMemories=normalMemories.filter(m=>m.id!==b.dataset.del);saveData()})}
function resizeFallback(){const r=fallback.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);fallback.width=Math.max(1,Math.round(r.width*d));fallback.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0)}
addEventListener('resize',resizeFallback);resizeFallback();
function drawFallback(now){requestAnimationFrame(drawFallback);const r=fallback.getBoundingClientRect(),w=r.width,h=r.height;if(!w||!h)return;const t=now/1000;ctx.clearRect(0,0,w,h);for(let i=0;i<75;i++){ctx.globalAlpha=.25+.25*Math.sin(t+i);ctx.fillStyle=isAdult()?'#ffbdd5':activeCharacter==='hikari'?'#ffe7a0':'#d9e0ff';ctx.beginPath();ctx.arc((i*97%997)/997*w,(i*53%773)/773*h*.85,i%6?0.6:1.4,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(!window.LumenVRM?.loaded){const x=w/2,y=h*.5+Math.sin(t*1.2)*4,g=ctx.createRadialGradient(x,y,20,x,y,190);g.addColorStop(0,isAdult()?'#ef679544':'#9b6ce644');g.addColorStop(1,'#0000');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,190,0,Math.PI*2);ctx.fill()}}
requestAnimationFrame(drawFallback);
function resetCost(){clearInterval(cost.timer);cost={input:0,output:0,total:0,turns:0,startedAt:Date.now(),timer:setInterval(renderCost,1000)};renderCost()}
function renderCost(){const sec=Math.max(0,Math.floor((Date.now()-(cost.startedAt||Date.now()))/1000));$('#duration').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;$('#inputCost').textContent='$'+cost.input.toFixed(4);$('#outputCost').textContent='$'+cost.output.toFixed(4);$('#sessionCost').textContent='$'+cost.total.toFixed(4);$('#turnCount').textContent=cost.turns}
function applyOpenAIUsage(u){if(!u)return;const inAudio=u.input_token_details?.audio_tokens||u.input_tokens_details?.audio_tokens||0,outAudio=u.output_token_details?.audio_tokens||u.output_tokens_details?.audio_tokens||0;cost.input+=(inAudio/1e6)*32;cost.output+=(outAudio/1e6)*64;cost.total=cost.input+cost.output;renderCost()}
function applyOpenRouterUsage(u){if(!u)return;const c=Number(u.cost||0);if(c>0){cost.total+=c;cost.input=cost.total;renderCost()}}
function updateCharacter(){const c=currentChar();document.body.dataset.character=activeCharacter;$('#stage').className=`stage theme-${isAdult()?'adult':c.theme}`;$('#characterName').textContent=c.name;$('#characterTagline').textContent=c.tagline;$('#archetypeName').textContent=c.archetype;$('#personalityDescription').textContent=c.description;$('#personalityIntensity').value=c.intensity;$('#intensityLabel').textContent=c.intensity+'%';presence.emotion=c.emotion;$('#emotion').textContent=c.emotion;$('#scene').textContent=c.scene.replaceAll('_',' ');$('#worldState').textContent=c.scene.replaceAll('_',' ');$('#action').textContent=isAdult()?'The Velvet Room is private and clearly fictional.':`The ${c.scene.replaceAll('_',' ')} is quiet.`;$('#connect').textContent=isAdult()?`Enter with ${c.name}`:`Meet ${c.name}`;window.LumenVRM?.loadCharacter?.(c.model,activeCharacter);$$('[data-character]').forEach(b=>b.classList.toggle('active',b.dataset.character===activeCharacter))}
function updatePortal(){const p=PORTALS[activePortal];$$('[data-portal]').forEach(b=>b.classList.toggle('active',b.dataset.portal===activePortal));$('#roleplayBadge').hidden=!p.roleplay;$('#adultBadge').hidden=!p.adult;$('#adultIntro').hidden=!p.adult;$('#preflight').hidden=p.adult;document.body.classList.toggle('adult-mode',p.adult);$('#modelName').textContent=p.adult?'OpenRouter text':'gpt-realtime';$('#costNote').textContent=p.adult?'OpenRouter reports provider cost when available. Voice STT/TTS is prepared for a later release.':'OpenAI voice cost is estimated from returned usage.';$('#mindState').textContent=p.adult?($('#engine').dataset.openrouter==='true'?'OpenRouter ready':'OpenRouter key missing'):($('#engine').dataset.openai==='true'?'realtime ready':'blocked');textMode=p.adult||textMode;renderMemory();updateCharacter();updateAvailability()}
async function selectPortal(id){if(connected)await disconnect('user');if(id==='adult'&&!adultConfirmed){$('#adultGate').showModal();return}activePortal=id;updatePortal()}
$$('[data-character]').forEach(b=>b.onclick=async()=>{if(connected)await disconnect('user');activeCharacter=b.dataset.character;updateCharacter()});
$$('[data-portal]').forEach(b=>b.onclick=()=>selectPortal(b.dataset.portal));
$('#personalityIntensity').oninput=e=>{$('#intensityLabel').textContent=e.target.value+'%'};
$('#adultAge').onchange=$('#adultConsent').onchange=()=>{$('#adultEnter').disabled=!($('#adultAge').checked&&$('#adultConsent').checked)};
$('#adultEnter').onclick=e=>{if(!($('#adultAge').checked&&$('#adultConsent').checked)){e.preventDefault();return}adultConfirmed=true;activePortal='adult';setTimeout(updatePortal)};
$('#adultCancel').onclick=()=>{};
$('#memoryEnabled').onchange=saveData;
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:'1.2',space:isAdult()?'adult':'ordinary',memories:memories(),profile,turns:turns.filter(t=>t.adult===isAdult())},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`soulbody-${isAdult()?'adult':'ordinary'}-data.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#clearData').onclick=()=>{if(confirm(`Delete all local ${isAdult()?'adult':'ordinary'} memories?`)){if(isAdult())adultMemories=[];else normalMemories=[];saveData()}};
function updateAvailability(){const ready=isAdult()?$('#engine').dataset.openrouter==='true':$('#engine').dataset.openai==='true';$('#connect').disabled=!ready||(isAdult()?false:!(micReady||textMode));$('#textInput').disabled=!connected;$('#send').disabled=!connected}
