import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {VRMLoaderPlugin,VRMUtils} from '@pixiv/three-vrm';
const canvas=document.querySelector('#vrmCanvas');
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(26,1,.1,100);camera.position.set(0,1.35,3.1);scene.add(camera);
scene.add(new THREE.HemisphereLight(0xd9ddff,0x24162c,2.15));const key=new THREE.DirectionalLight(0xffe4f5,3.1);key.position.set(2,3,2);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0x806dff,2.2);rim.position.set(-2,2,-1);scene.add(rim);
const loader=new GLTFLoader();loader.register(p=>new VRMLoaderPlugin(p));
const MODELS={A:'https://cdn.jsdelivr.net/gh/madjin/vrm-samples@master/vroid/stable/AvatarSample_A.vrm',B:'https://cdn.jsdelivr.net/gh/madjin/vrm-samples@master/vroid/stable/AvatarSample_B.vrm',C:'https://cdn.jsdelivr.net/gh/madjin/vrm-samples@master/vroid/stable/AvatarSample_C.vrm'};
let vrm=null,currentModel='',mouth=0,targetMouth=0,pointer={x:0,y:0},state={phase:'offline',emotion:'calm',gesture:'still'},clock=new THREE.Clock(),blinkAt=performance.now()+1800,blink=0;
function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=Math.max(.1,r.width/r.height);camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function expression(name,value){try{vrm?.expressionManager?.setValue(name,clamp(value))}catch{}}const clamp=v=>Math.max(0,Math.min(1,v));
function frameModel(){if(!vrm)return;const box=new THREE.Box3().setFromObject(vrm.scene),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());vrm.scene.position.x-=center.x;vrm.scene.position.y-=box.min.y;const h=Math.max(1,size.y);camera.position.set(0,h*.53,h*1.25);camera.lookAt(0,h*.56,0);camera.fov=27;camera.updateProjectionMatrix()}
async function loadCharacter(model,character){if(currentModel===model&&vrm)return;currentModel=model;window.SOULBODY?.setAvatarLoaded(false);try{const gltf=await loader.loadAsync(MODELS[model]||MODELS.A);const next=gltf.userData.vrm;if(!next)throw new Error('No VRM data');VRMUtils.removeUnnecessaryVertices(gltf.scene);VRMUtils.removeUnnecessaryJoints(gltf.scene);VRMUtils.rotateVRM0(next);if(vrm)scene.remove(vrm.scene);vrm=next;vrm.scene.traverse(o=>{o.frustumCulled=false;if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(vrm.scene);frameModel();window.SOULBODY?.setAvatarLoaded(true)}catch(e){console.error('VRM load failed',e);window.SOULBODY?.setAvatarLoaded(false)}}
function setMouth(v){targetMouth=clamp(v*1.65)}function setPointer(x,y){pointer={x:clamp(x,-1,1),y:clamp(y,-1,1)}}function setState(v){state={...state,...v}}
function animate(){requestAnimationFrame(animate);resize();const dt=Math.min(.05,clock.getDelta()),t=performance.now()/1000;mouth+=(targetMouth-mouth)*.28;targetMouth*=.9;if(vrm){const h=vrm.humanoid,head=h?.getNormalizedBoneNode('head'),chest=h?.getNormalizedBoneNode('chest'),hips=h?.getNormalizedBoneNode('hips'),lArm=h?.getNormalizedBoneNode('leftUpperArm'),rArm=h?.getNormalizedBoneNode('rightUpperArm');if(head){head.rotation.y+=(pointer.x*.25-head.rotation.y)*.07;head.rotation.x+=(-pointer.y*.12-head.rotation.x)*.07}if(chest)chest.rotation.z=Math.sin(t*.7)*.012;if(hips)hips.position.y=Math.sin(t*1.4)*.006;if(lArm&&rArm){const g=state.gesture==='open_palms'?.25:state.gesture==='hand_to_heart'?.4:.08;lArm.rotation.z=-.15-g;rArm.rotation.z=.15+g}const now=performance.now();if(now>blinkAt&&blink===0){blink=1;blinkAt=now+1800+Math.random()*2800}if(blink>0){blink+=dt*7;const v=blink<2?Math.sin(Math.min(Math.PI,blink*Math.PI/2)):0;expression('blink',v);if(blink>2){blink=0;expression('blink',0)}}expression('aa',mouth);expression('happy',state.emotion==='joyful'||state.emotion==='playful'?.35:0);expression('relaxed',state.emotion==='calm'||state.emotion==='warm'?.25:0);vrm.update(dt)}renderer.render(scene,camera)}animate();
window.LumenVRM={loaded:false,loadCharacter,setMouth,setPointer,setState};Object.defineProperty(window.LumenVRM,'loaded',{get:()=>!!vrm});
addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();setPointer(((e.clientX-r.left)/Math.max(1,r.width)-.5)*2,-((e.clientY-r.top)/Math.max(1,r.height)-.5)*2)});
setTimeout(()=>loadCharacter('A','nyra'),50);
