const ACTIONS={
 scope:{label:'Ask who is actually affected',verb:'ask',type:'Practice question',cost:5,requires:[],clue:true},
 changes:{label:'Ask what changed yesterday',verb:'ask',type:'Change history',cost:5,requires:[],clue:true},
 logs:{label:'Open assistant ingress logs',verb:'inspect',type:'Telemetry',cost:10,requires:[],clue:true},
 config:{label:'Check routing configuration',verb:'inspect',type:'Configuration',cost:10,requires:['scope'],clue:true},
 data:{label:'Check migration report',verb:'inspect',type:'Data quality',cost:10,requires:[],clue:true},
 api:{label:'Check assistant health',verb:'inspect',type:'Integration',cost:8,requires:[],clue:true},
 network:{label:'Check network / VPN path',verb:'inspect',type:'Infrastructure',cost:10,requires:[],clue:true},
 sample:{label:'Test a patient record',verb:'test',type:'Data test',cost:12,requires:[],clue:true},
 test:{label:'Run a targeted test call',verb:'test',type:'Critical path',cost:10,requires:['scope'],clue:true},
 fallback:{label:'Try the fallback route',verb:'test',type:'Safety path',cost:8,requires:[],clue:true},
 restart:{label:'Restart the healthy assistant',verb:'test',type:'Tempting shortcut',cost:7,requires:[],clue:false,bad:true}
};
const VERBS={ask:['scope','changes'],inspect:['logs','config','data','api','network'],test:['test','fallback','sample','restart']};
const CONTAIN={
 none:['No containment yet','Keep investigating with current exposure'],
 'keep-old-line':['Keep old phone line as fallback','Protect launch while fixing transfer'],
 quarantine:['Quarantine affected records','Keep clean records usable'],
 'b-fallback':['Route Location B directly to staff','Keep A healthy while B is fixed'],
 'ab-only':['Launch A/B; hold Location C','Preserve safe scope'],
 callback:['Use callback tasks for transfers','Keep booking + FAQ live'],
 'disable-all':['Turn everything off','Maximum disruption, minimum exposure']
};
const BASE_CASES=[
{id:'new-clinic',title:'New Clinic Go-Live',difficulty:'Foundation',tag:'Last-mile validation',featured:false,brief:'A two-doctor GP practice wants its AI phone assistant live on Monday. Patient import is complete. The team asks you to switch it on today.',objective:'Prove the critical patient journey works end to end before launch.',speech:'Everything looks green. Can we just switch it on today?',hyp:[['ready','Everything is ready'],['routing','Transfer routing is unverified'],['data','Migration is unsafe'],['api','API is unavailable']],correct:'routing',fix:'verify-routing',contain:'keep-old-line',rootOptions:[['routing','Transfer destination is wrong / unverified'],['data','Patient migration corruption'],['api','Assistant API outage'],['network','Practice network failure']],fixOptions:[['verify-routing','Correct destination + re-test transfer'],['restart','Restart assistant globally'],['remigrate','Repeat patient migration'],['wait','Launch and observe']],essential:['scope','config','test','fallback'],problemRoom:3,breakAt:3,queueStart:2,roomLabels:['PHONE','ROUTING','AI','DESK'],roomActions:['test','config','logs','scope'],insights:[{need:['scope','test'],title:'The booking path works — the handoff does not.',body:'The failure is late in the journey, not a general assistant outage.'}],ev:{scope:'Only calls to the main practice number are in scope. No live transfer path has been tested yet.',changes:'The forwarding rule changed yesterday afternoon.',logs:'Preflight logs are clean, but there are no production transfer events.',config:'The transfer destination was typed manually yesterday and never verified.',data:'2,184 patients imported; required fields are complete.',api:'API health is green.',network:'Connectivity is healthy; inbound routing has no VPN dependency.',sample:'A 20-record sample matches the source.',test:'Booking works. Transfer to the practice fails.',fallback:'The old practice line can remain active as rollback.'}},
{id:'dirty-migration',title:'Dirty Migration',difficulty:'Intermediate',tag:'Data integrity',featured:false,brief:'12,640 patient records were migrated. The report says 96.8% complete. Go-live is in three days.',objective:'Separate harmless incompleteness from identity-integrity risk.',speech:'96.8% sounds pretty good to us. Can we accept the rest and move on?',hyp:[['optional','Only optional fields are missing'],['identity','Identity mapping defects affect patients'],['api','Import API unstable'],['network','VPN caused the issue']],correct:'identity',fix:'remap',contain:'quarantine',rootOptions:[['optional','Only optional fields are missing'],['identity','External patient ID mapping is corrupt'],['api','Import API instability'],['network','VPN dropped records']],fixOptions:[['remap','Correct mapping + re-import affected records'],['restart','Restart import service'],['accept','Accept 96.8%'],['wipe','Delete all and restart']],essential:['scope','data','sample','config','fallback'],problemRoom:1,breakAt:1,queueStart:3,roomLabels:['EXPORT','MAPPING','RECORDS','DESK'],roomActions:['data','config','sample','scope'],insights:[{need:['data','sample'],title:'Completeness is not correctness.',body:'The risky records are plausible-looking identity mismatches, not just empty optional fields.'}],ev:{scope:'The 3.2% combines optional gaps, malformed phone numbers and unmatched patient IDs.',changes:'The source export format changed last month.',logs:'401 rows failed validation; 73 were retried automatically.',config:'patient_external_id maps from an outdated source column.',data:'217 duplicates, 184 unmatched IDs and 438 malformed phone numbers.',api:'The API stayed healthy throughout import.',network:'No tunnel resets occurred.',sample:'4 of 40 active patients are attached to the wrong external ID.',test:'Two active patients cannot be uniquely matched.',fallback:'The source system remains authoritative during re-import.'}},
{id:'broken-calls',title:'Broken Calls',difficulty:'Intermediate',tag:'Fault isolation',featured:true,brief:'A two-location specialist practice reports that since yesterday some calls never reach the assistant. Location A seems normal.',objective:'Localise the failing boundary before touching healthy systems.',speech:'Some calls are disappearing. The team thinks your AI is down again. Can you fix this?',hyp:[['ai','AI service intermittently unavailable'],['routing','Location B has stale forwarding'],['network','VPN / firewall path issue'],['data','Patient data corrupt']],correct:'routing',fix:'routing-fix',contain:'b-fallback',rootOptions:[['ai','Assistant service outage'],['routing','Location B points to an old forwarding number'],['network','Practice VPN / firewall issue'],['data','Location B patient data corruption']],fixOptions:[['routing-fix','Correct Location B forwarding + test call'],['restart','Restart assistant globally'],['vpn','Rebuild practice VPN'],['remigrate','Re-import Location B patients']],essential:['scope','changes','logs','config','test'],problemRoom:1,breakAt:1,queueStart:4,roomLabels:['PHONE','ROUTING','AI','DESK'],roomActions:['test','config','logs','scope'],insights:[{need:['scope','changes','logs'],title:'AHA! The failure is upstream of the assistant.',body:'Only Location B is affected, its provider changed yesterday, and failed calls never reach assistant ingress.'},{need:['config','test'],title:'AHA! The stale route is verified.',body:'Location B still points to the old destination and the targeted test dies at routing.'}],ev:{scope:'All confirmed failures are Location B. Location A has no confirmed failures.',changes:'Location B changed telecom provider yesterday morning.',logs:'Failed Location B calls never create an assistant-side ingress event.',config:'Location B still points to the previous provider number.',data:'No location-specific migration issue.',api:'Assistant API is healthy with normal latency.',network:'Practice connectivity is healthy; failed calls do not depend on VPN.',sample:'Patient records are valid.',test:'Location A passes. Location B fails before assistant ingress.',fallback:'Location B can temporarily route directly to staff.'}},
{id:'tomorrow',title:'Go-Live Tomorrow',difficulty:'Advanced',tag:'Risk triage',featured:false,brief:'A three-location clinic launches tomorrow. One warning remains. Leadership strongly prefers not to move the date.',objective:'Find the actual blocker and preserve the safe launch scope.',speech:'Leadership really does not want to delay tomorrow. Is this warning actually serious?',hyp:[['token','Expiring token is immediate blocker'],['hours','Location C has stale opening hours'],['data','Migration quality is bad'],['all','Everything is unsafe']],correct:'hours',fix:'hours-fix',contain:'ab-only',rootOptions:[['token','Integration token expiry'],['hours','Location C has stale opening hours'],['data','Patient migration defect'],['network','All-location connectivity failure']],fixOptions:[['hours-fix','Update Location C hours + boundary-test'],['token-renew','Delay until token renewal'],['all-delay','Delay all locations'],['restart','Restart all integrations']],essential:['scope','config','test','fallback'],problemRoom:1,breakAt:1,queueStart:2,roomLabels:['A/B','LOCATION C','RULES','DESK'],roomActions:['scope','config','test','fallback'],insights:[{need:['scope','config'],title:'The warning is isolated to Location C.',body:'A/B passed acceptance. The real decision is launch scope, not all-or-nothing.'}],ev:{scope:'The warning affects Location C only. A and B passed acceptance testing.',changes:'Location C changed Wednesday opening hours this week.',logs:'After-hours calls at C still follow the old branch.',config:'Location C still contains the previous Wednesday hours.',data:'Patient migration validation passed.',api:'API health and latency are normal.',network:'All three locations pass connectivity checks.',sample:'Active-patient sample passes.',test:'A/B pass. C fails only outside new opening hours.',fallback:'A/B can launch while C stays on its current workflow.'}},
{id:'incident',title:'Post-Launch Incident',difficulty:'Advanced',tag:'Incident response',featured:false,brief:'The assistant launched last week. This morning live transfers fail intermittently while booking and FAQ still work.',objective:'Contain the failing capability without throwing away healthy service.',speech:'Transfers are failing on and off. Booking still works. Should we switch the whole assistant off?',hyp:[['ai','Speech model regressed'],['network','New firewall degrades transfer path'],['data','Patient data degraded'],['rules','Appointment rules changed']],correct:'network',fix:'network-fix',contain:'callback',rootOptions:[['ai','Assistant model/service regression'],['network','New firewall causes transfer-path packet loss'],['data','Patient identity corruption'],['rules','Appointment rules misconfigured']],fixOptions:[['network-fix','Fix firewall path + verify repeated transfers'],['rollback-ai','Roll back assistant release'],['remigrate','Re-import patient data'],['disable-all','Disable everything']],essential:['scope','changes','logs','network','test','fallback'],problemRoom:3,breakAt:3,queueStart:5,roomLabels:['CALLER','ASSISTANT','TRANSFER','DESK'],roomActions:['scope','logs','network','fallback'],insights:[{need:['scope','logs','network'],title:'The assistant is healthy; the transfer path is not.',body:'Healthy booking plus transfer-only timeouts and new firewall packet loss isolate the boundary.'}],ev:{scope:'Only live transfers are affected. Booking, FAQ and identification remain healthy.',changes:'Practice IT replaced a firewall appliance this morning.',logs:'Transfer attempts time out while the assistant remains healthy.',config:'Transfer destination and business rules are unchanged.',data:'No migration changes since launch.',api:'Core API health is normal.',network:'Packet loss appears on the new firewall path.',sample:'Patient lookup succeeds.',test:'Fallback route passes; firewall path intermittently times out.',fallback:'Calls can create callback tasks instead of live transfers.'}}
];

const BROKEN_VARIANTS=[
 {id:'route',correct:'routing',fix:'routing-fix',problemRoom:1,breakAt:1,insights:[{need:['scope','changes','logs'],title:'AHA! The failure is upstream of the assistant.',body:'Only Location B is affected, its provider changed yesterday, and failed calls never reach assistant ingress.'},{need:['config','test'],title:'AHA! The stale route is verified.',body:'Location B still points to the old destination and the targeted test dies at routing.'}],ev:{changes:'Location B changed telecom provider yesterday morning.',logs:'Failed Location B calls never create an assistant-side ingress event.',config:'Location B still points to the previous provider number.',network:'Practice connectivity is healthy; failed calls do not depend on VPN.',test:'Location A passes. Location B fails before assistant ingress.'}},
 {id:'pbx',correct:'routing',fix:'routing-fix',problemRoom:1,breakAt:1,insights:[{need:['scope','changes','logs'],title:'AHA! The fault is local to Location B routing.',body:'Only Location B is affected, a PBX rule changed yesterday, and failed calls never reach assistant ingress.'},{need:['config','test'],title:'AHA! The PBX rule is verified.',body:'The affected extension group still points to the legacy route and the targeted test dies there.'}],ev:{changes:'The clinic added a new Location B PBX rule yesterday.',logs:'Failed Location B calls never create an assistant-side ingress event.',config:'The Location B PBX rule sends the affected extension group to the legacy route.',network:'Practice connectivity is healthy.',test:'Location A passes. Location B fails at the local routing rule.'}},
 {id:'firewall',correct:'network',fix:'vpn',problemRoom:1,breakAt:1,insights:[{need:['scope','changes','logs'],title:'AHA! The failure is upstream of assistant processing.',body:'Only Location B is affected, its firewall changed yesterday, and failed calls do not complete the assistant handoff.'},{need:['network','test'],title:'AHA! The new firewall is the boundary.',body:'Forwarding looks correct, but targeted traffic dies when it crosses the new Location B firewall.'}],ev:{changes:'Clinic IT replaced the Location B firewall yesterday.',logs:'Failed Location B calls never complete the handoff into the assistant path.',config:'Forwarding destinations match Location A and look correct.',network:'The new Location B firewall is dropping the required traffic on the call path.',test:'Location A passes. Location B fails when traffic crosses the new firewall.'},rootOptions:[['ai','Assistant service outage'],['routing','Location B points to an old forwarding number'],['network','New Location B firewall blocks the call path'],['data','Location B patient data corruption']],fixOptions:[['routing-fix','Correct Location B forwarding + test call'],['restart','Restart assistant globally'],['vpn','Correct firewall rule + repeat targeted test'],['remigrate','Re-import Location B patients']]}
];




function clone(obj){return JSON.parse(JSON.stringify(obj))}
let CASES=clone(BASE_CASES);
let state={idx:2,mode:'train',verb:'ask',used:[],insights:[],contain:'none',root:'',fix:'',seconds:7200,trust:70,risk:35,queue:4,running:false,timer:null,log:[],variant:0,sound:false,audio:null,introOpen:true,planApplied:false,verified:false,done:false,speaker:'mina'};

const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],cur=()=>CASES[state.idx],used=()=>new Set(state.used);

function applyVariant(){CASES=clone(BASE_CASES);const c=CASES[state.idx];if(!c||c.id!=='broken-calls')return;const v=BROKEN_VARIANTS[state.variant%BROKEN_VARIANTS.length];c.correct=v.correct;c.fix=v.fix;c.problemRoom=v.problemRoom;c.breakAt=v.breakAt;Object.assign(c.ev,v.ev);if(v.rootOptions)c.rootOptions=v.rootOptions;if(v.fixOptions)c.fixOptions=v.fixOptions;if(v.insights)c.insights=v.insights}
function stamp(){const elapsed=120-Math.floor(state.seconds/60),base=8*60+47+elapsed;return String(Math.floor(base/60)).padStart(2,'0')+':'+String(base%60).padStart(2,'0')}
function addLog(text){state.log.push({t:stamp(),text})}
function audioCtx(){if(!state.audio)state.audio=new (window.AudioContext||window.webkitAudioContext)();return state.audio}
function tone(freq,dur=.08,when=0,type='sine',gain=.04){if(!state.sound)return;const a=audioCtx(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,a.currentTime+when);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+when+dur);o.connect(g).connect(a.destination);o.start(a.currentTime+when);o.stop(a.currentTime+when+dur)}
const soundTap=()=>tone(260,.05,0,'triangle',.03),soundClue=()=>{tone(620,.08);tone(820,.1,.06)},soundAha=()=>{tone(440,.1);tone(554,.12,.09);tone(660,.14,.18)},soundFail=()=>{tone(260,.12);tone(190,.16,.09)},soundClear=()=>{tone(392,.12);tone(494,.12,.1);tone(587,.14,.2);tone(784,.2,.31)};

function populateCases(){q('#caseSelect').innerHTML=CASES.map((c,i)=>`<option value="${i}">${c.title}</option>`).join('');q('#caseSelect').value=String(state.idx)}
function reset(){stopClock();applyVariant();const c=cur();Object.assign(state,{verb:'ask',used:[],insights:[],contain:'none',root:'',fix:'',seconds:7200,trust:70,risk:35,queue:c.queueStart,running:false,log:[],introOpen:true,planApplied:false,verified:false,done:false,speaker:'mina'});closeAllModals();q('#decisionFeedback').className='decisionFeedback';q('#decisionFeedback').textContent='';q('#callBtn').querySelector('b').textContent='Make the call';q('#callBtn').querySelector('small').textContent='Contain · Fix · Verify';renderAll()}
function renderAll(){const c=cur();q('#missionTitle').textContent=c.title;q('#modeLabel').textContent=state.mode==='interview'?'Interview':'Training';q('#introTitle').textContent=c.title;q('#introCopy').textContent=c.speech;q('#queueBadge').innerHTML='<span></span>'+state.queue+' patient'+(state.queue===1?'':'s')+' waiting';q('#rootSelect').innerHTML='<option value="">Choose root cause…</option>'+c.rootOptions.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('');q('#rootSelect').value=state.root;q('#fixSelect').innerHTML='<option value="">Choose permanent fix…</option>'+c.fixOptions.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('');q('#fixSelect').value=state.fix;renderWorld();renderVerbs();renderActions();renderNotebookCount();renderContainment();clock()}

function renderWorld(){
  const c=cur(),u=used(),ids=['phone','route','ai','reception'];
  q('#introOverlay').classList.toggle('hidden',!state.introOpen);
  q('#speakerName').textContent=speakerLabel();
  q('#speech').textContent=worldSpeech();
  q('#sceneStatus').textContent=sceneStatus();
  renderPatients();
  ids.forEach((id,i)=>{const el=q('#scene-room-'+id);el.classList.remove('checked','problem','fixed');el.dataset.action=c.roomActions[i]||'';if(u.has(c.roomActions[i]))el.classList.add('checked')});
  if(u.size>=2&&!state.planApplied)q('#scene-room-'+ids[c.problemRoom]).classList.add('problem');
  if(state.planApplied&&state.fix===c.fix)q('#scene-room-'+ids[c.problemRoom]).classList.add('fixed');
  q('#fallbackPath').classList.toggle('on',state.contain===c.contain);
  if(state.planApplied&&state.fix===c.fix){q('#trackProgress').style.width='100%'}else if(u.has('test')){q('#trackProgress').style.width=(Math.max(.12,Math.min(.88,[.18,.38,.67,.88][c.breakAt]))*100)+'%'}else q('#trackProgress').style.width='0';
}
function renderPatients(){const box=q('#patientQueue');box.innerHTML='';for(let i=0;i<Math.min(state.queue,6);i++)box.insertAdjacentHTML('beforeend','<i class="qPerson"></i>')}
function speakerLabel(){return state.speaker==='alex'?'Alex · Reception':state.speaker==='jo'?'Jo · Clinic IT':'Mina · Practice Manager'}
function worldSpeech(){const c=cur();if(state.done)return 'That worked. We’re back in business.';if(state.planApplied)return 'The change is in. Can we prove the path is healthy?';if(state.contain===c.contain)return 'The fallback is working. The queue is easing.';if(state.insights.length)return state.insights[state.insights.length-1].title;if(state.used.length>=4)return 'What are you recommending?';if(state.used.length>=2)return 'What have you ruled out?';return c.speech}
function sceneStatus(){if(state.done)return 'Healthy end-to-end ✓';if(state.planApplied)return 'Fix applied · verify it';if(state.contain===cur().contain)return 'Problem contained';if(state.insights.length)return 'Pattern found';if(state.used.length)return 'Narrowing it down';return 'Everything looks normal… for now'}

function renderVerbs(){qa('[data-verb]').forEach(b=>b.classList.toggle('active',b.dataset.verb===state.verb))}
function unlocked(id){return ACTIONS[id].requires.every(r=>state.used.includes(r))}
function caseActionIds(){const map={'broken-calls':{ask:['scope','changes'],inspect:['logs','config','network'],test:['test','fallback','restart']},'new-clinic':{ask:['scope','changes'],inspect:['config','api','data'],test:['test','fallback','restart']},'dirty-migration':{ask:['scope','changes'],inspect:['data','config','api'],test:['sample','fallback','restart']},'tomorrow':{ask:['scope','changes'],inspect:['config','logs','api'],test:['test','fallback']},'incident':{ask:['scope','changes'],inspect:['logs','network','config'],test:['test','fallback','restart']}};return (map[cur().id]||VERBS)[state.verb]||[]}
function renderActions(){const u=used();q('#actionChoices').innerHTML=caseActionIds().map(id=>{const a=ACTIONS[id],locked=!unlocked(id)||state.introOpen;return `<button class="actionChoice ${a.bad?'bad':''} ${locked?'locked':''}" data-action="${id}" ${state.done||state.planApplied||u.has(id)||locked?'disabled':''}>${a.label}<small>${a.cost} min</small></button>`}).join('');qa('[data-action]').forEach(b=>b.addEventListener('click',()=>takeAction(b.dataset.action)))}
function takeAction(id){
  if(state.done||state.planApplied||state.used.includes(id)||!unlocked(id)||state.introOpen)return;
  const a=ACTIONS[id];soundTap();state.seconds=Math.max(0,state.seconds-a.cost*60);
  if(a.bad){state.trust=Math.max(0,state.trust-5);state.risk=Math.min(100,state.risk+2);state.queue=Math.min(9,state.queue+1);state.speaker='alex';addLog('Restarted a healthy assistant');showMessage('Whoops. The AI was healthy.','Location B is still broken. You spent time without shrinking the problem.',false);soundFail();renderWorld();clock();return}
  state.used.push(id);state.speaker=id==='scope'?'alex':(['changes','config','network'].includes(id)?'jo':'mina');
  if(id==='scope'||id==='changes')state.trust=Math.min(100,state.trust+3);
  if(id==='fallback')state.risk=Math.max(0,state.risk-7);
  if(state.used.length>=3&&state.contain==='none'){state.risk=Math.min(100,state.risk+5);state.queue=Math.min(9,state.queue+1)}
  addLog(a.label);setLatest(a.label,cur().ev[id]);if(id==='test')runSignal(false);checkInsights();soundClue();renderAll();focusRoom(id);
}
function focusRoom(actionId){const map={scope:'reception',changes:'route',logs:'ai',config:'route',network:'route',api:'ai',data:'ai',sample:'ai',test:'phone',fallback:'reception'},id=map[actionId];if(!id)return;const el=q('#scene-room-'+id);el.animate([{transform:'translateY(0)'},{transform:'translateY(-7px)'},{transform:'translateY(0)'}],{duration:480,easing:'ease-out'})}
function setLatest(title,body){q('#latestClueTitle').textContent=title;q('#latestClueBody').textContent=body;q('#latestClue').hidden=false;clearTimeout(setLatest.t);setLatest.t=setTimeout(()=>q('#latestClue').hidden=true,4200)}
function checkInsights(){const c=cur(),u=used();for(const ins of c.insights||[]){if(!state.insights.some(x=>x.title===ins.title)&&ins.need.every(x=>u.has(x))){state.insights.push(ins);addLog('Insight: '+ins.title);setTimeout(()=>{setLatest(ins.title,ins.body);showMessage(ins.title,ins.body,true);soundAha();renderNotebookCount()},180)}}}
function showMessage(title,body,insight){q('.aha')?.remove();const el=document.createElement('div');el.className='aha';el.innerHTML=`<small>${insight?'AHA!':'REACTION'}</small><strong>${title}</strong><div style="font-size:9px;line-height:1.4;margin-top:4px;color:#687068">${body}</div>`;q('#world').appendChild(el);setTimeout(()=>el.remove(),2400)}
function runSignal(success){
  const orb=q('#signalOrb'),duration=success?1200:930,stop=success?1:Math.max(.14,Math.min(.9,[.18,.38,.67,.88][cur().breakAt]));
  orb.style.opacity='1';orb.style.left='0%';orb.style.background='#73d3ff';
  const anim=orb.animate([{left:'0%'},{left:(stop*100)+'%'}],{duration,easing:'ease-in-out',fill:'forwards'});
  anim.onfinish=()=>{orb.style.background=success?'#64c978':'#ef725d';success?soundAha():soundFail();setTimeout(()=>{orb.style.opacity='0';orb.style.left='0%'},850)};
}

function renderNotebookCount(){const n=state.used.length+state.insights.length;q('#notebookCount').textContent=n;q('#floatingNotebookCount').textContent=n}
function renderNotebook(){const c=cur(),ev=state.used.filter(id=>ACTIONS[id].clue).map(id=>`<article class="noteCard"><b>${ACTIONS[id].label}</b><p>${c.ev[id]}</p></article>`),ins=state.insights.map(x=>`<article class="noteCard insight"><b>✦ ${x.title}</b><p>${x.body}</p></article>`);q('#notes').innerHTML=(ev.length+ins.length)?ev.concat(ins).join(''):'<p style="font-size:10px;color:var(--muted)">Nothing yet. Ask one useful question.</p>'}
function renderContainment(){const opts=['none',cur().contain,'disable-all'].filter((x,i,a)=>a.indexOf(x)===i);q('#containChoices').innerHTML=opts.map(id=>`<button class="containChoice ${state.contain===id?'selected':''}" data-contain="${id}" type="button">${CONTAIN[id][0]}</button>`).join('');qa('[data-contain]').forEach(b=>b.addEventListener('click',()=>setContain(b.dataset.contain)))}
function setContain(id){if(state.done||state.contain===id)return;soundTap();state.contain=id;state.speaker='alex';if(id===cur().contain){state.risk=Math.max(0,state.risk-15);state.trust=Math.min(100,state.trust+5);state.queue=Math.max(0,state.queue-2);soundAha()}else if(id==='disable-all'){state.risk=Math.max(0,state.risk-22);state.trust=Math.max(0,state.trust-7);state.queue=Math.max(0,state.queue-1);soundFail()}addLog('Containment: '+CONTAIN[id][0]);renderContainment();renderWorld()}

function openDecision(){if(state.planApplied){verifyPlan();return}renderContainment();q('#decisionModal').hidden=false}
function feedback(t){q('#decisionFeedback').textContent=t;q('#decisionFeedback').classList.add('show')}
function applyPlan(){state.root=q('#rootSelect').value;state.fix=q('#fixSelect').value;if(!state.root||!state.fix||state.contain==='none'){feedback('Choose containment, a root cause and a fix first.');soundFail();return}state.seconds=Math.max(0,state.seconds-8*60);const ok=state.fix===cur().fix;addLog('Applied plan: '+(cur().fixOptions.find(x=>x[0]===state.fix)?.[1]||state.fix));if(!ok){state.trust=Math.max(0,state.trust-4);state.risk=Math.min(100,state.risk+4);state.queue=Math.min(9,state.queue+1);feedback('The symptom is still there. That change did not repair the failing boundary.');showMessage('Still broken.','The change did not alter the failing path.',false);soundFail();renderWorld();clock();return}state.planApplied=true;state.speaker='jo';state.risk=Math.max(0,state.risk-7);state.trust=Math.min(100,state.trust+3);q('#decisionModal').hidden=true;q('#callBtn').querySelector('b').textContent='Run verification';q('#callBtn').querySelector('small').textContent='Prove it end-to-end';showMessage('Fix applied.','One last thing: prove the critical path works.',true);soundAha();renderAll()}
function verifyPlan(){if(!state.planApplied||state.verified)return;state.seconds=Math.max(0,state.seconds-5*60);addLog('Ran verification call');state.speaker='alex';runSignal(true);setTimeout(()=>{state.verified=true;state.done=true;state.risk=Math.max(0,state.risk-15);state.queue=Math.max(0,state.queue-2);state.trust=Math.min(100,state.trust+5);addLog('Verified healthy end-to-end');finishMission()},1250)}
function diagnosis(){return state.root===cur().correct?100:20}
function safety(){return state.contain===cur().contain?100:state.contain==='disable-all'?65:25}
function efficiency(){const ess=new Set(cur().essential),w=state.used.filter(x=>!ess.has(x)).length;return Math.max(0,100-w*15)}
function communication(){return Math.max(0,Math.min(100,55+Math.round((state.trust-50)*1.2)))}
function total(){const fix=state.fix===cur().fix?100:25;return Math.round(diagnosis()*.3+fix*.25+safety()*.25+efficiency()*.12+communication()*.08)}
function starCount(n){return n>=92?4:n>=78?3:n>=62?2:1}
function finishMission(){stopClock();const n=total(),stars=starCount(n);q('#clearTitle').textContent=stars>=3?'Mission Clear!':'Shift Complete';q('#stars').textContent='★'.repeat(stars)+'☆'.repeat(4-stars);q('#clearCopy').textContent=state.root===cur().correct?'You found the failing boundary, kept the safe scope running, and verified the repair.':'The clinic is running again, but your explanation still has a gap.';const scores=[['Diagnosis',diagnosis()],['Safety',safety()],['Efficiency',efficiency()],['Communication',communication()]];q('#scoreRows').innerHTML=scores.map(([k,v])=>`<div class="scoreRow"><span>${k}</span><div class="scoreBar"><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('');q('#debriefModal').hidden=false;q('#callBtn').querySelector('b').textContent='Resolved';q('#callBtn').querySelector('small').textContent='Healthy end-to-end ✓';renderWorld();soundClear()}
function clock(){const m=Math.floor(state.seconds/60),s=state.seconds%60;q('#clock').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function startClock(){if(state.running||state.done)return;state.running=true;state.timer=setInterval(()=>{state.seconds=Math.max(0,state.seconds-1);clock();if(!state.seconds)stopClock()},1000)}
function stopClock(){state.running=false;if(state.timer){clearInterval(state.timer);state.timer=null}}
function closeAllModals(){qa('.modal').forEach(m=>m.hidden=true)}
function share(){const url=location.origin+location.pathname+`?case=${cur().id}&mode=interview&variant=${state.variant}`;if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(url).then(()=>{q('#shareBtn').textContent='Copied ✓';setTimeout(()=>q('#shareBtn').textContent='Copy challenge',1500)})}else{prompt('Copy this challenge link:',url)}}
function nextShift(){q('#debriefModal').hidden=true;if(cur().id==='broken-calls')state.variant=(state.variant+1)%BROKEN_VARIANTS.length;else state.idx=(state.idx+1)%CASES.length;applyVariant();populateCases();reset()}

q('#caseSelect').addEventListener('change',e=>{state.idx=Number(e.target.value);state.variant=0;applyVariant();reset()});
qa('[data-verb]').forEach(b=>b.addEventListener('click',()=>{state.verb=b.dataset.verb;renderVerbs();renderActions();soundTap()}));
qa('.room').forEach(room=>room.addEventListener('click',()=>{if(state.introOpen)return;const id=room.dataset.action;if(id&&unlocked(id)&&!state.used.includes(id)){state.verb=ACTIONS[id].verb;renderVerbs();takeAction(id)}}));
q('#answerBtn').addEventListener('click',()=>{state.introOpen=false;addLog('Answered the practice call');soundAha();startClock();renderAll()});
q('#soundBtn').addEventListener('click',()=>{state.sound=!state.sound;if(state.sound){audioCtx();soundAha()}q('#soundBtn').classList.toggle('on',state.sound)});
const openNotebook=()=>{renderNotebook();q('#notebookModal').hidden=false};q('#notebookBtn').addEventListener('click',openNotebook);q('#floatingNotebook').addEventListener('click',openNotebook);
q('#callBtn').addEventListener('click',openDecision);q('#applyBtn').addEventListener('click',applyPlan);q('#rootSelect').addEventListener('change',e=>state.root=e.target.value);q('#fixSelect').addEventListener('change',e=>state.fix=e.target.value);q('#againBtn').addEventListener('click',nextShift);q('#shareBtn').addEventListener('click',share);
qa('[data-close]').forEach(b=>b.addEventListener('click',()=>q('#'+b.dataset.close).hidden=true));qa('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.hidden=true}));
const params=new URLSearchParams(location.search),requested=params.get('case'),mode=params.get('mode'),variant=params.get('variant');if(requested){const i=BASE_CASES.findIndex(c=>c.id===requested);if(i>=0)state.idx=i}if(mode==='interview')state.mode='interview';if(variant!==null&&!Number.isNaN(Number(variant)))state.variant=Math.max(0,Number(variant));applyVariant();populateCases();reset();
