import fs from 'node:fs';import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('./game.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('./game.css',import.meta.url),'utf8');
for(const m of ['cinematicStage','scene-room-phone','scene-room-route','scene-room-ai','scene-room-reception','signalTrack','controlDock','messageCard','floatingNotebook'])assert.ok(html.includes(m),`missing cinematic UI marker: ${m}`);
for(const m of ['BROKEN_VARIANTS','renderWorld','runSignal','applyPlan','verifyPlan','finishMission','caseActionIds'])assert.ok(js.includes(m),`missing engine marker: ${m}`);
for(const m of ['.practice','.upperFloor','.roomRoute','.aiBot','.controlDock','.messageCard'])assert.ok(css.includes(m),`missing visual marker: ${m}`);
assert.doesNotThrow(()=>new Function(js),'game.js should parse');
assert.ok(html.includes('no official Doctolib product UI or data'));
console.log('Onboarding Shift cinematic build QA PASS');