'use strict';
const C=window.ChessCore,D=window.CHESS_DATA,$=id=>document.getElementById(id);
const storeKey='chess-command-profile-v1';
let profile=loadProfile();
let game=C.start(),selected=null,flipped=false,botElo=600,botBusy=false,lastGameResult=null;
let engine=new StockfishBridge();
let openingIndex=0,openingPly=0,openingState=C.start(),openingSelected=null;
let puzzleIndex=0,puzzleState=C.fromFEN(D.puzzles[0].fen),puzzleSelected=null,puzzleDone=false;
const FILES='abcdefgh';
function loadProfile(){try{return Object.assign({rating:600,games:0,wins:0,draws:0,losses:0,openingMoves:0,puzzles:0,theme:'walnut',pieces:'classic',history:[]},JSON.parse(localStorage.getItem(storeKey)||'{}'))}catch{return{rating:600,games:0,wins:0,draws:0,losses:0,openingMoves:0,puzzles:0,theme:'walnut',pieces:'classic',history:[]}}}
function saveProfile(){try{localStorage.setItem(storeKey,JSON.stringify(profile))}catch{}renderProgress()}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function setScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>setScreen(b.dataset.go));
function renderBoard(el,state,onClick,opt={}){el.innerHTML='';const ranks=flipped&&!opt.fixed?[1,2,3,4,5,6,7,8]:[8,7,6,5,4,3,2,1],files=flipped&&!opt.fixed?[...'hgfedcba']:[...'abcdefgh'];const legal=opt.legal||new Set();for(const r of ranks)for(const f of files){const s=f+r,b=document.createElement('button');b.className='square '+(((FILES.indexOf(f)+r)%2===0)?'dark':'light');b.dataset.square=s;if(opt.selected===s)b.classList.add('selected');if(legal.has(s))b.classList.add('legal');if(opt.last&&[opt.last.from,opt.last.to].includes(s))b.classList.add('last');const p=C.pieceAt(state,s);if(p){const pc=document.createElement('span');pc.className='piece '+(p[0]==='w'?'white':'black');pc.textContent=C.SYMBOL[p];b.appendChild(pc)}if((r===(flipped&&!opt.fixed?8:1))){const c=document.createElement('span');c.className='coord file';c.textContent=f;b.appendChild(c)}if(f===(flipped&&!opt.fixed?'h':'a')){const c=document.createElement('span');c.className='coord rank';c.textContent=r;b.appendChild(c)}b.onclick=()=>onClick(s);el.appendChild(b)}}
function legalSetFor(state,from){return new Set(C.legalMoves(state,from).map(m=>m.to))}
function onGameSquare(s){if(botBusy||C.status(game).over)return;const p=C.pieceAt(game,s);if(selected){const mv=C.legalMoves(game,selected).find(m=>m.to===s&&(!m.promotion||m.promotion==='Q'));if(mv){game=C.make(game,C.moveUci(mv));selected=null;renderGame();afterHumanMove();return}if(p&&p[0]===game.turn){selected=s;renderGame();return}selected=null;renderGame();return}if(p&&p[0]===game.turn&&game.turn==='w'){selected=s;renderGame()}}
async function afterHumanMove(){const st=C.status(game);if(st.over){finishGame(st);return}botBusy=true;renderGame();let uci=null;if(botElo>=1400){$('engineState').textContent='Loading Stockfish 18…';try{uci=await engine.bestMove(C.fen(game),botElo)}catch(e){console.warn(e)}}if(!uci){const m=C.pickBotMove(game,botElo);uci=m?C.moveUci(m):null;$('engineState').textContent=botElo>=1400?'Local practice fallback':'Practice bot ready'}else $('engineState').textContent='Stockfish 18 online';if(uci){const next=C.make(game,uci);if(next)game=next}botBusy=false;renderGame();const st2=C.status(game);if(st2.over)finishGame(st2)}
function renderGame(){const legal=selected?legalSetFor(game,selected):new Set();renderBoard($('gameBoard'),game,onGameSquare,{selected,legal,last:game.last});const st=C.status(game);$('gameStatus').textContent=st.over?(st.checkmate?(st.winner==='w'?'You won by checkmate.':'Computer won by checkmate.'):st.draw?'Draw: '+st.reason:'Draw.'):(game.turn==='w'?(st.check?'Your king is in check.':'White to move.'):(botBusy?'Computer is thinking…':'Computer to move.'));$('thinking').textContent=botBusy?'THINKING':'';const level=D.levels.find(x=>x.elo===botElo)||D.levels[1];$('opponentName').textContent=`${level.name} · ${botElo===9999?'MAX':botElo}`;$('opponentNote').textContent=level.note;const hist=game.history||[];const lines=[];for(let i=0;i<hist.length;i+=2){const a=hist[i+1]?.last,b=hist[i+2]?.last;lines.push(`<span>${Math.floor(i/2)+1}.</span><b>${a?C.moveUci(a):''}</b><b>${b?C.moveUci(b):''}</b>`)}$('moveList').className='move-list'+(hist.length?'':' empty');$('moveList').innerHTML=hist.length?lines.join(''):'No moves yet.';renderMaterial()}
function renderMaterial(){const count={w:0,b:0},vals={P:1,N:3,B:3,R:5,Q:9,K:0};for(const p of Object.values(game.board))count[p[0]]+=vals[p[1]]||0;const diff=count.w-count.b;$('material').textContent=diff===0?'Even material':diff>0?`+${diff} White`:`+${-diff} Black`}
function expectedScore(r,opp){return 1/(1+Math.pow(10,(opp-r)/400))}
function finishGame(st,resign=false){if(lastGameResult)return;let score;if(resign)score=0;else if(st.winner==='w')score=1;else if(st.winner==='b')score=0;else score=.5;const old=Math.round(profile.rating),opp=botElo===9999?3200:botElo;profile.rating=Math.max(100,Math.round(profile.rating+24*(score-expectedScore(profile.rating,opp))));profile.games++;if(score===1)profile.wins++;else if(score===0)profile.losses++;else profile.draws++;profile.history.push({at:Date.now(),opp,score,before:old,after:profile.rating});profile.history=profile.history.slice(-50);lastGameResult={score};saveProfile();toast(score===1?`Victory. Rating ${old} → ${profile.rating}`:score===0?`Game over. Rating ${old} → ${profile.rating}`:`Draw. Rating ${old} → ${profile.rating}`)}
function newGame(){game=C.start();selected=null;botBusy=false;lastGameResult=null;renderGame();setSide('opponent')}
function undoPair(){if(botBusy)return;if(game.history.length){game=C.undo(game);if(game.history.length&&game.turn==='b')game=C.undo(game);selected=null;lastGameResult=null;renderGame()}}
function hintGame(){const moves=C.legalMoves(game);if(!moves.length)return;const best=C.pickBotMove(game,1600);if(!best)return;selected=best.from;renderGame();setSide('coach');$('coachTitle').textContent='A useful candidate';$('coachText').innerHTML=`Look at <b>${best.from.toUpperCase()} → ${best.to.toUpperCase()}</b>.<br><br>${best.capture?'There is a capture available. Check whether it wins material safely.':'This move improves activity without forcing anything dramatic.'}`}
function setSide(id){document.querySelectorAll('.panel-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.side===id));document.querySelectorAll('.side-view').forEach(v=>v.classList.toggle('active',v.id==='side-'+id))}
document.querySelectorAll('.panel-tabs button').forEach(b=>b.onclick=()=>setSide(b.dataset.side));
function buildLevels(){const g=$('levelGrid');g.innerHTML='';D.levels.forEach(l=>{const b=document.createElement('button');b.className='level '+(l.elo===botElo?'active':'');b.innerHTML=`<b>${l.elo===9999?'MAX':l.elo}</b><span>${l.name}</span>`;b.title=l.note;b.onclick=()=>{botElo=l.elo;buildLevels();newGame();if(botElo>=1400)engine.init().then(ok=>{$('engineState').textContent=ok?'Stockfish 18 online':'Local practice fallback';$('engineDot').classList.toggle('online',ok)})};g.appendChild(b)})}
function resetOpening(){openingState=C.start();openingPly=0;openingSelected=null;renderOpening()}
function onOpeningSquare(s){const op=D.openings[openingIndex],p=C.pieceAt(openingState,s);if(openingPly>=op.moves.length)return;if(openingSelected){const expected=op.moves[openingPly];const attempt=openingSelected+s;if(attempt===expected){openingState=C.make(openingState,attempt);openingPly++;openingSelected=null;profile.openingMoves++;saveProfile();toast('Correct. '+(op.notes[openingPly-1]||''));renderOpening();return}if(p&&p[0]===openingState.turn){openingSelected=s;renderOpening();return}toast('Not this move. Ask what the opening is trying to achieve.');openingSelected=null;renderOpening();return}if(p&&p[0]===openingState.turn){openingSelected=s;renderOpening()}}
function renderOpening(){const op=D.openings[openingIndex];$('openingName').textContent=op.name;$('openingWhy').textContent=op.why;$('openingPrompt').textContent=openingPly>=op.moves.length?'Line complete — run it again from memory.':`Find move ${openingPly+1} of ${op.moves.length}.`;$('openingNote').textContent=openingPly?op.notes[openingPly-1]:op.notes[0];$('openingProgress').style.width=(openingPly/op.moves.length*100)+'%';const legal=openingSelected?legalSetFor(openingState,openingSelected):new Set();renderBoard($('learnBoard'),openingState,onOpeningSquare,{selected:openingSelected,legal,last:openingState.last,fixed:true});document.querySelectorAll('.opening-item').forEach((b,i)=>b.classList.toggle('active',i===openingIndex))}
function buildOpenings(){const l=$('openingList');l.innerHTML='';D.openings.forEach((o,i)=>{const b=document.createElement('button');b.className='opening-item';b.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><div><b>${o.name}</b><small>${o.tag}</small></div>`;b.onclick=()=>{openingIndex=i;resetOpening()};l.appendChild(b)})}
function openingHint(){const op=D.openings[openingIndex];if(openingPly>=op.moves.length)return;const m=op.moves[openingPly];openingSelected=m.slice(0,2);renderOpening();$('openingNote').textContent=`Start from ${m.slice(0,2).toUpperCase()}. ${op.notes[openingPly]||''}`}
function openingReveal(){const op=D.openings[openingIndex];if(openingPly>=op.moves.length)return;openingState=C.make(openingState,op.moves[openingPly]);openingPly++;openingSelected=null;renderOpening()}
function loadPuzzle(i){puzzleIndex=(i+D.puzzles.length)%D.puzzles.length;const p=D.puzzles[puzzleIndex];puzzleState=C.fromFEN(p.fen);puzzleSelected=null;puzzleDone=false;$('puzzleRating').textContent=p.rating;$('puzzleTheme').textContent=p.theme.toUpperCase();$('puzzleTitle').textContent=p.title;$('puzzlePrompt').textContent=(puzzleState.turn==='w'?'White':'Black')+' to move. Find the best move.';$('puzzleFeedback').textContent='Look for checks, captures and threats — in that order.';renderPuzzle()}
function onPuzzleSquare(s){if(puzzleDone)return;const pz=D.puzzles[puzzleIndex],pc=C.pieceAt(puzzleState,s);if(puzzleSelected){const u=puzzleSelected+s;if(u===pz.solution){puzzleState=C.make(puzzleState,u);puzzleDone=true;profile.puzzles++;saveProfile();$('puzzleFeedback').innerHTML=`<b>Correct.</b> ${pz.explain}`;renderPuzzle();return}if(pc&&pc[0]===puzzleState.turn){puzzleSelected=s;renderPuzzle();return}$('puzzleFeedback').textContent='Not quite. Reset your scan: checks → captures → threats.';puzzleSelected=null;renderPuzzle();return}if(pc&&pc[0]===puzzleState.turn){puzzleSelected=s;renderPuzzle()}}
function renderPuzzle(){const legal=puzzleSelected?legalSetFor(puzzleState,puzzleSelected):new Set();renderBoard($('puzzleBoard'),puzzleState,onPuzzleSquare,{selected:puzzleSelected,legal,last:puzzleState.last,fixed:true})}
function applyTheme(){document.body.className=`theme-${profile.theme} pieces-${profile.pieces}`;document.querySelectorAll('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===profile.theme));document.querySelectorAll('[data-pieces]').forEach(b=>b.classList.toggle('active',b.dataset.pieces===profile.pieces))}
function renderProgress(){$('ratingTop').textContent=Math.round(profile.rating);$('ratingBig').textContent=Math.round(profile.rating);$('gamesStat').textContent=profile.games;$('recordStat').textContent=`${profile.wins}W · ${profile.draws}D · ${profile.losses}L`;$('openingStat').textContent=profile.openingMoves;$('puzzleStat').textContent=profile.puzzles;$('puzzleSolvedTop').textContent=profile.puzzles;const pct=Math.max(2,Math.min(100,(profile.rating-400)/(2000-400)*100));$('ratingTrack').style.width=pct+'%';const h=profile.history;if(h.length)$('ratingDelta').textContent=`Last game: ${h[h.length-1].before} → ${h[h.length-1].after}`}
$('newGameBtn').onclick=newGame;$('undoBtn').onclick=undoPair;$('flipBtn').onclick=()=>{flipped=!flipped;renderGame()};$('resignBtn').onclick=()=>{if(C.status(game).over)return;finishGame({winner:'b'},true);$('gameStatus').textContent='You resigned.'};$('hintBtn').onclick=hintGame;$('openingHint').onclick=openingHint;$('openingReveal').onclick=openingReveal;$('openingReset').onclick=resetOpening;$('puzzleHint').onclick=()=>{$('puzzleFeedback').textContent=D.puzzles[puzzleIndex].hint};$('nextPuzzle').onclick=()=>loadPuzzle(puzzleIndex+1);$('resetProgress').onclick=()=>{if(confirm('Reset your local Chess Command progress?')){localStorage.removeItem(storeKey);profile=loadProfile();applyTheme();renderProgress();toast('Progress reset. Fresh board.')}};document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{profile.theme=b.dataset.theme;saveProfile();applyTheme()});document.querySelectorAll('[data-pieces]').forEach(b=>b.onclick=()=>{profile.pieces=b.dataset.pieces;saveProfile();applyTheme()});$('shareBtn').onclick=async()=>{const data={title:'Chess Command',text:'I’m learning chess with this — play me when I stop hanging my queen 😄',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('Link copied.')}}catch{}};
buildLevels();buildOpenings();applyTheme();renderGame();renderOpening();loadPuzzle(0);renderProgress();
