(function(){
'use strict';
const C=window.ChessCore,D=window.CHESS_DATA,CC=window.ChessCommand,K=window.ChessCoachCore;if(!C||!D||!CC||!K)return;
const $=id=>document.getElementById(id),PROFILE='chess-command-profile-v1',LEARN='chess-command-learning-v5',KEY='chess-command-intelligence-v10';
const base={version:10,goal:1000,days:{},puzzleThemes:{},openings:{attempts:0,correct:0},opponents:{}};
function load(k,d={}){try{return Object.assign({},d,JSON.parse(localStorage.getItem(k)||'{}'))}catch{return JSON.parse(JSON.stringify(d))}}
let S=load(KEY,base);
function persist(renderNow=true){try{localStorage.setItem(KEY,JSON.stringify(S))}catch{}if(renderNow)render()}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dayKey=()=>new Date().toISOString().slice(0,10);
function day(){return S.days[dayKey()]||(S.days[dayKey()]={games:0,wins:0,puzzles:0,puzzleCorrect:0,openings:0,openingCorrect:0,study:0})}
function profile(){return load(PROFILE,{rating:600,games:0,wins:0,draws:0,losses:0,history:[]})}
function learning(){return load(LEARN,{srs:{},games:[],personalPuzzles:[],lessonProgress:{},analysisRuns:0,puzzleRating:500})}
function dueCount(L){const now=Date.now();return Object.values(L.srs||{}).filter(r=>r.due&&r.due<=now).length}
function skillModel(){const L=learning();return K.skillScores({games:L.games,puzzleStats:S.puzzleThemes,openingStats:S.openings,lessonProgress:L.lessonProgress})}
function activity(){const out=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=d.toISOString().slice(0,10),x=S.days[k]||{};out.push({label:d.toLocaleDateString(undefined,{weekday:'short'}).slice(0,2),value:(x.games||0)+(x.puzzles||0)+(x.openings||0)+(x.study||0)})}return out}
function openingName(moves){let best='Unclassified',nBest=0;for(const o of D.openings||[]){let n=0;while(n<o.moves.length&&n<moves.length&&o.moves[n]===moves[n])n++;if(n>nBest){nBest=n;best=o.name}}return nBest>=3?best:'Unclassified'}
function parseHeaders(pgn){const h={};for(const m of pgn.matchAll(/^\[([^\s]+)\s+"([^"]*)"\]/gm))h[m[1]]=m[2];return h}
function opponentSummary(name){return K.opponentSummary(S.opponents[name]?.games||[])}

const progress=$('progress');if(!progress)return;
const dash=document.createElement('section');dash.id='coachV10';dash.className='coach-v10';dash.innerHTML=`
<div class="coach-head"><div><span class="eyebrow">V10 / PERSONAL CHESS INTELLIGENCE</span><h2 id="coachHeadline">Your coach is collecting evidence.</h2><p id="coachWhy">Play, review and practise. Chess Command will decide what deserves your next 20 minutes.</p></div><label>Goal rating <select id="coachGoal">${[800,1000,1200,1400,1600,1800,2000,2200,2400].map(x=>`<option>${x}</option>`).join('')}</select></label></div>
<div class="coach-grid"><article class="coach-primary"><small>NEXT BEST ACTION</small><h3 id="coachNext">Play one focused game</h3><p id="coachNextWhy"></p><button class="primary" id="coachStart">Start training</button></article><article><small>TRAINING STREAK</small><b class="coach-number" id="coachStreak">0</b><span>active days</span></article><article><small>REVIEW MEMORY</small><b class="coach-number" id="coachReviews">0</b><span>games analysed</span></article><article><small>PERSONAL PUZZLES</small><b class="coach-number" id="coachPersonal">0</b><span>from your games</span></article></div>
<div class="coach-two"><section><div class="coach-section-head"><div><small>V6 / WEAKNESS MODEL</small><h3>Your chess profile</h3></div><span id="coachConfidence"></span></div><div id="skillBars" class="skill-bars"></div></section><section><div class="coach-section-head"><div><small>V9 / LONG-TERM MEMORY</small><h3>Last 7 days</h3></div><button id="exportMemory">Export memory</button></div><div id="memoryBars" class="memory-bars"></div><p class="coach-memory" id="memoryText"></p></section></div>
<section class="coach-plan"><div class="coach-section-head"><div><small>V7 / ADAPTIVE CURRICULUM</small><h3>Today's session</h3></div><span>≈ 20 minutes</span></div><div id="coachPlan" class="coach-plan-grid"></div></section>
<section class="opponent-prep"><div class="coach-section-head"><div><small>V8 / OPPONENT PREP</small><h3>Prepare for a friend</h3></div><span>local only</span></div><p>Paste one of their PGNs. Chess Command remembers the openings that keep appearing and turns them into a prep target.</p><div class="prep-form"><input id="oppName" placeholder="Friend's name"><textarea id="oppPgn" placeholder="Paste PGN here…"></textarea><button class="primary" id="addOppGame">Add game</button></div><div id="opponentCards" class="opponent-cards"></div></section>`;
const grid=progress.querySelector('.progress-grid');progress.insertBefore(dash,grid||progress.firstChild);$('coachGoal').value=String(S.goal||1000);

function act(kind){day().study++;persist(false);if(kind==='opening'){const b=$('memoryReview');b?b.click():CC.setScreen('learn')}else if(kind==='personal'){const b=$('personalPuzzleBtn');b&&!b.disabled?b.click():CC.setScreen('puzzles')}else if(kind==='endgame'){CC.setScreen('learn');setTimeout(()=>document.querySelector('#endLessons .lesson-row:not(.done)')?.click(),50)}else if(kind==='puzzle')CC.setScreen('puzzles');else if(kind==='learn')CC.setScreen('learn');else CC.setScreen('play')}
function planItems(model,L,p){const items=[];const due=dueCount(L);if(due)items.push({kind:'opening',title:'Opening review',meta:`${due} due · 4 min`});if(L.personalPuzzles?.length)items.push({kind:'personal',title:'Repair one game mistake',meta:'Personal puzzle · 4 min'});const [weak]=K.weakest(model.scores);if(weak==='endgame')items.push({kind:'endgame',title:'Endgame foundation',meta:'One drill · 5 min'});else items.push({kind:'puzzle',title:`Train ${K.prettySkill(weak)}`,meta:'Adaptive puzzles · 5 min'});const target=Math.min(S.goal||1000,Math.max(400,Math.round(((p.rating||600)+100)/100)*100));items.push({kind:'play',title:`Play around ${target} Elo`,meta:'Focused game · 8–12 min'});return items.slice(0,3)}
function renderSkills(model){$('skillBars').innerHTML=Object.entries(model.scores).map(([k,v])=>`<div class="skill-row"><div><b>${esc(K.prettySkill(k))}</b><span>${model.confidence[k]||0} evidence</span></div><div class="skill-track"><i style="width:${v}%"></i></div><strong>${v}</strong></div>`).join('')}
function renderMemory(){const a=activity(),max=Math.max(1,...a.map(x=>x.value));$('memoryBars').innerHTML=a.map(x=>`<div><i style="height:${Math.max(7,x.value/max*72)}px"></i><b>${x.value}</b><span>${x.label}</span></div>`).join('');const p=profile(),L=learning(),st=K.streak(S.days);$('memoryText').textContent=st?`${st}-day training streak · ${p.games||0} games · ${L.analysisRuns||0} reviews · ${p.puzzles||0} solved puzzles.`:'Start today. One game + one review is enough to create useful memory.'}
function renderOpponents(){const names=Object.keys(S.opponents);$('opponentCards').innerHTML=names.length?names.map(name=>{const x=opponentSummary(name);return`<article><div><b>${esc(name)}</b><span>${x.games} imported game${x.games===1?'':'s'}</span></div><strong>${esc(x.topOpening||'No opening yet')}</strong><small>${x.topOpening?`Seen ${x.topCount}× · practise this family before your next game.`:'Add another PGN to build a pattern.'}</small><button data-prep="${esc(name)}">Prep this opponent</button></article>`}).join(''):'<div class="coach-empty">No opponent profile yet. Add a PGN when your friend sends you a game.</div>';$('opponentCards').querySelectorAll('[data-prep]').forEach(b=>b.onclick=()=>{const x=opponentSummary(b.dataset.prep),idx=(D.openings||[]).findIndex(o=>o.name===x.topOpening);CC.setScreen('learn');if(idx>=0)setTimeout(()=>CC.startOpeningAt(idx,0),30)})}
function render(){if(!document.body.contains(dash))return;const p=profile(),L=learning(),model=skillModel(),rec=K.recommendation({rating:p.rating,goal:S.goal,scores:model.scores,due:dueCount(L),personalPuzzles:L.personalPuzzles?.length||0});const weak=K.weakest(model.scores)[0];$('coachHeadline').textContent=model.rows<5?'Build your first real chess profile.':`${K.prettySkill(weak)} is the next lever.`;$('coachWhy').textContent=model.rows<5?'Finish a game and run Review. V10 needs evidence before pretending to know you.':`Goal ${S.goal}. Your coach prioritises measured weakness instead of random content.`;$('coachNext').textContent=rec.title;$('coachNextWhy').textContent=rec.why;$('coachStart').dataset.kind=rec.kind;$('coachStreak').textContent=K.streak(S.days);$('coachReviews').textContent=L.analysisRuns||0;$('coachPersonal').textContent=L.personalPuzzles?.length||0;$('coachConfidence').textContent=`${model.rows} reviewed moves`;renderSkills(model);renderMemory();$('coachPlan').innerHTML=planItems(model,L,p).map((x,i)=>`<button data-kind="${x.kind}"><span>0${i+1}</span><b>${esc(x.title)}</b><small>${esc(x.meta)}</small></button>`).join('');$('coachPlan').querySelectorAll('button').forEach(b=>b.onclick=()=>act(b.dataset.kind));renderOpponents()}
$('coachGoal').onchange=e=>{S.goal=+e.target.value;persist()};$('coachStart').onclick=()=>act($('coachStart').dataset.kind);
$('addOppGame').onclick=()=>{const name=$('oppName').value.trim()||'Chess friend',text=$('oppPgn').value.trim();if(!text)return CC.toast('Paste a PGN first.');const parsed=C.parsePgn(text);if(!parsed.moves?.length||parsed.errors?.length)return CC.toast(parsed.errors?.[0]||'Could not parse that PGN.');const h=parseHeaders(text),asColor=h.White===name?'White':h.Black===name?'Black':'Unknown',opening=openingName(parsed.moves),o=S.opponents[name]||(S.opponents[name]={name,games:[]});o.games.unshift({at:Date.now(),opening,asColor,moves:parsed.moves.slice(0,30)});o.games=o.games.slice(0,40);$('oppPgn').value='';persist();CC.toast(`${name}: ${opening} added.`)};
$('exportMemory').onclick=()=>{const payload={exportedAt:new Date().toISOString(),profile:profile(),learning:learning(),intelligence:S,skills:skillModel()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='chess-command-memory.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
function mark(kind,correct=false,theme=''){const d=day();if(kind==='puzzle'){d.puzzles++;if(correct)d.puzzleCorrect++;const k=theme||'Tactics',x=S.puzzleThemes[k]||(S.puzzleThemes[k]={attempts:0,correct:0});x.attempts++;if(correct)x.correct++}else{d.openings++;S.openings.attempts++;if(correct){d.openingCorrect++;S.openings.correct++}}persist()}
document.addEventListener('cc:puzzle',e=>mark('puzzle',!!e.detail.correct,e.detail.puzzle?.theme));document.addEventListener('cc:opening',e=>mark('opening',!!e.detail.correct));document.addEventListener('cc:gameover',e=>{const d=day();d.games++;if(e.detail.score===1)d.wins++;persist()});document.querySelector('[data-go="progress"]')?.addEventListener('click',()=>setTimeout(render,20));window.addEventListener('storage',render);setInterval(()=>{if(progress.classList.contains('active'))render()},5000);render();
})();
