(function(){
'use strict';
const C=window.ChessCore,CC=window.ChessCommand,KEY='chess-command-gamefeel-v17',PROFILE='chess-command-profile-v1';
function load(){try{return Object.assign({sound:true,haptics:true,motion:true},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return{sound:true,haptics:true,motion:true}}}
let S=load(),ctx=null,drag=null,suppressUntil=0,lastPieces=32;
const reduced=()=>matchMedia?.('(prefers-reduced-motion: reduce)').matches;
function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch{}}
function audio(){if(!S.sound)return null;try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}catch{return null}}
function tone(freq=420,dur=.035,gain=.032,type='sine',delay=0){const a=audio();if(!a)return;const t=a.currentTime+delay,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(a.destination);o.start(t);o.stop(t+dur)}
function buzz(pattern){if(S.haptics&&navigator.vibrate)navigator.vibrate(pattern)}
function piecesInFen(fen){return((fen||'').split(' ')[0].match(/[prnbqkPRNBQK]/g)||[]).length}
function pulse(cls,ms=420){const shell=document.querySelector('#play .board-shell');if(!shell)return;shell.classList.remove(cls);requestAnimationFrame(()=>shell.classList.add(cls));setTimeout(()=>shell.classList.remove(cls),ms)}
function sq(board,name){return board?.querySelector(`.square[data-square="${name}"]`)}
function fixedClone(piece,rect,cls){if(!piece||!rect)return null;const g=piece.cloneNode(true);g.classList.add('cc-motion-piece',cls||'');Object.assign(g.style,{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px'});document.body.appendChild(g);return g}
function stageMove(board,from,to,extraClass=''){
 if(!S.motion||reduced()||!board)return null;const a=sq(board,from),b=sq(board,to),piece=a?.querySelector('.piece');if(!a||!b||!piece)return null;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),ghost=fixedClone(piece,ar,extraClass),captured=b.querySelector('.piece'),capGhost=captured?fixedClone(captured,br,'cc-captured-ghost'):null;return{ghost,capGhost,from,to,dx:br.left-ar.left,dy:br.top-ar.top,distance:Math.hypot(br.left-ar.left,br.top-ar.top)}
}
function runStage(stage){if(!stage?.ghost)return;requestAnimationFrame(()=>requestAnimationFrame(()=>{const board=document.getElementById('gameBoard'),dest=sq(board,stage.to)?.querySelector('.piece');if(dest)dest.style.opacity='0';const dur=Math.max(115,Math.min(205,110+stage.distance*.16));const anim=stage.ghost.animate([{transform:'translate3d(0,0,0) scale(1.04)'},{transform:`translate3d(${stage.dx}px,${stage.dy}px,0) scale(1)`}],{duration:dur,easing:'cubic-bezier(.2,.78,.2,1)',fill:'forwards'});if(stage.capGhost)stage.capGhost.animate([{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(.72)'}],{duration:Math.min(130,dur),delay:35,easing:'ease-out',fill:'forwards'});anim.finished.catch(()=>{}).finally(()=>{stage.ghost.remove();stage.capGhost?.remove();if(dest)dest.style.opacity=''})}))}
function stageUci(uci){const board=document.getElementById('gameBoard');if(!board||!uci||uci.length<4)return[];const from=uci.slice(0,2),to=uci.slice(2,4),out=[stageMove(board,from,to)];const castle={e1g1:['h1','f1'],e1c1:['a1','d1'],e8g8:['h8','f8'],e8c8:['a8','d8']}[from+to];if(castle)out.push(stageMove(board,castle[0],castle[1],'cc-rook-motion'));return out.filter(Boolean)}
function settings(){
 if(document.getElementById('feelV17'))return;const actions=document.querySelector('.top-actions');if(!actions)return;document.getElementById('feelToggle')?.remove();const b=document.createElement('button');b.id='feelV17';b.className='icon-btn';b.title='Board feel';b.textContent='♪';actions.prepend(b);const sheet=document.createElement('div');sheet.id='feelSheetV17';sheet.className='feel-sheet-v17';sheet.hidden=true;sheet.innerHTML=`<button class="feel-backdrop-v17" data-feel-close></button><section><div><small>BOARD FEEL</small><h3>Make the board yours.</h3></div><label><span>Move sounds</span><input id="feelSound" type="checkbox"></label><label><span>Haptics</span><input id="feelHaptics" type="checkbox"></label><label><span>Smooth motion</span><input id="feelMotion" type="checkbox"></label><button data-feel-close>Done</button></section>`;document.body.appendChild(sheet);const sync=()=>{document.getElementById('feelSound').checked=S.sound;document.getElementById('feelHaptics').checked=S.haptics;document.getElementById('feelMotion').checked=S.motion;b.textContent=S.sound?'♪':'·'};b.onclick=()=>{sync();sheet.hidden=false};sheet.querySelectorAll('[data-feel-close]').forEach(x=>x.onclick=()=>sheet.hidden=true);document.getElementById('feelSound').onchange=e=>{S.sound=e.target.checked;save();sync();if(S.sound)tone(620,.06,.04)};document.getElementById('feelHaptics').onchange=e=>{S.haptics=e.target.checked;save();sync();buzz(12)};document.getElementById('feelMotion').onchange=e=>{S.motion=e.target.checked;save();sync()};sync();
}
function resultCard(detail){
 let el=document.getElementById('gameResultV17');if(!el){el=document.createElement('div');el.id='gameResultV17';el.className='game-result-v17';el.hidden=true;el.innerHTML=`<button class="game-result-backdrop" data-result-close></button><section><div class="game-result-crown">♟</div><small id="resultKicker">GAME COMPLETE</small><h2 id="resultTitle">Game over</h2><p id="resultRating"></p><div class="game-result-actions"><button id="resultReview">Review game</button><button id="resultRematch" class="primary">Rematch</button></div><button class="game-result-close" data-result-close>×</button></section>`;document.body.appendChild(el);el.querySelectorAll('[data-result-close]').forEach(x=>x.onclick=()=>el.hidden=true);document.getElementById('resultReview').onclick=()=>{el.hidden=true;CC?.setScreen('review')};document.getElementById('resultRematch').onclick=()=>{el.hidden=true;document.getElementById('newGameBtn')?.click()}}
 const profile=(()=>{try{return JSON.parse(localStorage.getItem(PROFILE)||'{}')}catch{return{}}})(),h=profile.history||[],last=h[h.length-1],score=detail.score;document.getElementById('resultKicker').textContent=score===1?'VICTORY':score===.5?'DRAW':'GAME COMPLETE';document.getElementById('resultTitle').textContent=score===1?'Beautiful. Bank the win.':score===.5?'Hold the draw. Learn the edge.':'Good. Now turn the loss into training.';document.getElementById('resultRating').textContent=last?`Rating ${last.before} → ${last.after} · ${last.after-last.before>=0?'+':''}${last.after-last.before}`:'Open Review and find the turning point.';el.hidden=false;
}
// Capture geometry synchronously: Chess Command emits before it rerenders the board.
document.addEventListener('cc:move',e=>{const stages=stageUci(e.detail.uci);requestAnimationFrame(()=>stages.forEach(runStage));const n=piecesInFen(e.detail.fen),capture=n<lastPieces;lastPieces=n;let st=null;try{st=C?.status(C.fromFEN(e.detail.fen))}catch{}if(st?.check){tone(760,.055,.045,'triangle');tone(520,.05,.03,'triangle',.065);buzz([15,18,24]);pulse('cc-check-flash-v17',500)}else if(capture){tone(215,.045,.045,'square');buzz(13);pulse('cc-capture-pulse-v17',260)}else{tone(e.detail.side==='w'?475:405,.028,.023);buzz(6)}});
document.addEventListener('cc:newgame',()=>{lastPieces=32;const r=document.getElementById('gameResultV17');if(r)r.hidden=true});
document.addEventListener('cc:gameover',e=>{if(e.detail.score===1){tone(523,.07,.045);tone(659,.07,.04,'sine',.075);tone(784,.12,.045,'sine',.15);buzz([22,28,45]);pulse('cc-win-glow-v17',1100)}else if(e.detail.score===.5){tone(420,.06,.03);tone(520,.08,.03,'sine',.07);buzz(18)}else{tone(245,.11,.034,'triangle');buzz(20)};setTimeout(()=>resultCard(e.detail),260)});
document.addEventListener('cc:puzzle',e=>{if(e.detail.correct){tone(650,.045,.03);tone(870,.055,.028,'sine',.05);buzz(8)}else{tone(175,.045,.022,'square');buzz(14)}});
// Native-feeling pointer drag, while preserving tap-to-move.
function dragStart(e){if(e.button!==undefined&&e.button!==0)return;const square=e.target.closest('.square'),board=e.target.closest('.chess-board');if(!square||!board||!square.querySelector('.piece'))return;const r=square.getBoundingClientRect(),ghost=square.querySelector('.piece').cloneNode(true);ghost.classList.add('cc-drag-ghost-v17');document.body.appendChild(ghost);drag={board,from:square,ghost,x:e.clientX,y:e.clientY,moved:false,pid:e.pointerId,size:r.width};placeDrag(e.clientX,e.clientY);try{square.setPointerCapture?.(e.pointerId)}catch{}}
function placeDrag(x,y){if(!drag)return;const s=drag.size;Object.assign(drag.ghost.style,{width:s+'px',height:s+'px',left:(x-s/2)+'px',top:(y-s/2)+'px'})}
function dragMove(e){if(!drag||e.pointerId!==drag.pid)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>7){drag.moved=true;drag.from.classList.add('cc-drag-source')}placeDrag(e.clientX,e.clientY)}
function dragEnd(e){if(!drag||e.pointerId!==drag.pid)return;const d=drag;drag=null;d.from.classList.remove('cc-drag-source');d.ghost.remove();if(!d.moved)return;const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('.square');if(!hit||hit.closest('.chess-board')!==d.board)return;suppressUntil=Date.now()+420;d.from.click();hit.click()}
document.addEventListener('pointerdown',dragStart,{passive:true});document.addEventListener('pointermove',dragMove,{passive:true});document.addEventListener('pointerup',dragEnd,{passive:true});document.addEventListener('click',e=>{if(Date.now()<suppressUntil){e.preventDefault();e.stopImmediatePropagation()}},true);
settings();new MutationObserver(settings).observe(document.body,{childList:true,subtree:true});
})();
