(function(){
'use strict';
const KEY='chess-command-meta-v15',PROFILE='chess-command-profile-v1',TACTICS='chess-command-tactics-v12',$=id=>document.getElementById(id);
const RANKS=[['Cadet',1],['Solver',4],['Tactician',7],['Strategist',11],['Commander',16],['Mastermind',22]];
function load(k,d={}){try{return Object.assign({},d,JSON.parse(localStorage.getItem(k)||'{}'))}catch{return JSON.parse(JSON.stringify(d))}}
const old=load(TACTICS,{xp:0,solved:0});const base={version:15,xp:old.xp||0,lastDay:null,dayStreak:0,days:{},deepSeen:{},achievements:{}};let S=load(KEY,base);
const dayKey=()=>new Date().toISOString().slice(0,10),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function level(){return Math.max(1,Math.floor(Math.sqrt(Math.max(0,S.xp)/90))+1)}function nextXp(l=level()+1){return 90*Math.pow(l-1,2)}function prevXp(l=level()){return 90*Math.pow(l-1,2)}function rank(){const l=level();let out=RANKS[0][0];for(const [name,min] of RANKS)if(l>=min)out=name;return out}
function today(){const k=dayKey();return S.days[k]||(S.days[k]={puzzles:0,openings:0,games:0,reviews:0,xp:0})}
function touchDay(){const k=dayKey();if(S.lastDay===k)return;if(S.lastDay){const a=new Date(S.lastDay+'T00:00:00Z'),b=new Date(k+'T00:00:00Z'),diff=Math.round((b-a)/86400000);S.dayStreak=diff===1?S.dayStreak+1:1}else S.dayStreak=1;S.lastDay=k}
function unlock(id,label){if(S.achievements[id])return;S.achievements[id]={label,at:Date.now()}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch{}render()}
function award(kind,xp){touchDay();const d=today();d[kind]=(d[kind]||0)+1;d.xp+=xp;S.xp+=xp;const p=load(PROFILE,{rating:600,games:0});if(kind==='puzzles')unlock('puzzle','Pattern spotted · solve a puzzle');if(kind==='games')unlock('game','First game logged');if(kind==='reviews')unlock('review','Learn from the board · finish a deep review');if(S.dayStreak>=3)unlock('streak3','Momentum · train 3 days in a row');if(S.dayStreak>=7)unlock('streak7','A real habit · train 7 days in a row');if((p.rating||0)>=800)unlock('rating800','Road to 1000 · cross 800');if((p.rating||0)>=1000)unlock('rating1000','Four digits · reach 1000');if(S.xp>=1000)unlock('xp1000','Thousand XP club');save()}
function ensure(){const progress=$('progress');if(!progress||$('metaV15'))return;const el=document.createElement('section');el.id='metaV15';el.className='meta-v15';el.innerHTML=`
<div class="meta-v15-head"><div><span class="eyebrow">V15 / PLAYER JOURNEY</span><h2>Make getting better feel visible.</h2><p>XP rewards consistency. Ratings and mastery still come from chess performance.</p></div><div class="meta-v15-rank"><small id="metaLevel">LEVEL 1</small><b id="metaRank">Cadet</b><span id="metaXp">0 XP</span></div></div>
<div class="meta-v15-grid"><article class="meta-road"><div><small>ROAD TO 1000</small><b id="metaRating">600</b><span id="metaRoadText">400 Elo to go</span></div><div class="meta-road-track"><i id="metaRoadBar"></i><em style="left:0%">400</em><em style="left:33%">600</em><em style="left:66%">800</em><em style="left:100%">1000</em></div></article><article><small>TRAINING STREAK</small><b id="metaStreak">0</b><span>consecutive days</span></article><article><small>TOTAL XP</small><b id="metaTotalXp">0</b><span id="metaNext">next level</span></article></div>
<div class="meta-v15-quests"><div class="meta-v15-title"><div><small>DAILY MISSIONS</small><h3>Three small wins.</h3></div><span id="metaDailyXp">0 XP today</span></div><div id="metaQuestGrid" class="meta-quest-grid"></div></div>
<div class="meta-v15-ach"><div class="meta-v15-title"><div><small>MILESTONES</small><h3>Things you have earned.</h3></div></div><div id="metaAchievements"></div></div>`;const coach=$('coachV10');progress.insertBefore(el,coach||progress.firstChild);const badge=document.createElement('button');badge.id='metaBadge';badge.className='meta-badge';badge.onclick=()=>{window.ChessCommand?.setScreen('progress');setTimeout(()=>el.scrollIntoView({behavior:'smooth',block:'start'}),30)};document.querySelector('.top-actions')?.prepend(badge);render()}
function quest(name,n,target,xp,label){const done=n>=target;return`<article class="${done?'done':''}"><div><span>${done?'✓':'○'}</span><div><b>${name}</b><small>${Math.min(n,target)} / ${target} · ${label}</small></div></div><strong>+${xp} XP</strong></article>`}
function render(){if(!$('metaV15'))return;const p=load(PROFILE,{rating:600}),d=today(),l=level(),px=prevXp(l),nx=nextXp(l+1),pct=clamp((S.xp-px)/Math.max(1,nx-px)*100,0,100),rating=Math.round(p.rating||600),road=clamp((rating-400)/600*100,0,100);$('metaLevel').textContent=`LEVEL ${l}`;$('metaRank').textContent=rank();$('metaXp').textContent=`${Math.round(pct)}% to level ${l+1}`;$('metaRating').textContent=rating;$('metaRoadText').textContent=rating>=1000?'Goal reached · choose the next mountain':`${Math.max(0,1000-rating)} Elo to go`;$('metaRoadBar').style.width=road+'%';$('metaStreak').textContent=S.dayStreak||0;$('metaTotalXp').textContent=S.xp;$('metaNext').textContent=`${Math.max(0,nx-S.xp)} XP to level ${l+1}`;$('metaDailyXp').textContent=`${d.xp||0} XP today`;$('metaQuestGrid').innerHTML=quest('Pattern reps',d.puzzles||0,5,50,'solve five puzzles')+quest('Opening memory',d.openings||0,3,30,'three correct opening moves')+quest('Create evidence',(d.games||0)+(d.reviews||0),1,40,'play or review one game');const a=Object.values(S.achievements).sort((x,y)=>x.at-y.at);$('metaAchievements').innerHTML=a.length?a.map(x=>`<span>✓ ${x.label}</span>`).join(''):'<span class="locked">Your first puzzle, game and review unlock milestones here.</span>';const badge=$('metaBadge');if(badge)badge.innerHTML=`<small>LV ${l}</small><b>${rank()}</b><i style="--p:${pct}%"></i>`}
document.addEventListener('cc:puzzle',e=>{if(e.detail.correct)award('puzzles',12)});document.addEventListener('cc:opening',e=>{if(e.detail.correct)award('openings',6)});document.addEventListener('cc:gameover',e=>award('games',e.detail.score===1?55:40));document.addEventListener('cc:deepreview',e=>{const id=e.detail.gameId||'unknown';if(S.deepSeen[id])return;S.deepSeen[id]=Date.now();award('reviews',25)});window.addEventListener('storage',render);ensure();new MutationObserver(ensure).observe(document.body,{childList:true,subtree:true});
})();
