(function(){
'use strict';
const KEY='chess-command-meta-v18',OLD='chess-command-meta-v15',PROFILE='chess-command-profile-v1',TACTICS='chess-command-tactics-v12',SESSIONS='chess-command-puzzle-sessions-v18',$=id=>document.getElementById(id);
const RANKS=[['Cadet',1],['Pattern Scout',3],['Solver',5],['Tactician',8],['Strategist',12],['Commander',17],['Mastermind',23],['Board Sage',30]];
function load(k,d={}){try{return Object.assign({},d,JSON.parse(localStorage.getItem(k)||'{}'))}catch{return JSON.parse(JSON.stringify(d))}}
function localDay(d=new Date()){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function mondayKey(){const d=new Date(),x=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-x);return localDay(d)}
const old=load(OLD,{}),tactics=load(TACTICS,{xp:0,solved:0,bestStreak:0});
const base={version:18,xp:old.xp||tactics.xp||0,lastDay:old.lastDay||null,dayStreak:old.dayStreak||0,bestDayStreak:old.dayStreak||0,days:old.days||{},deepSeen:old.deepSeen||{},achievements:old.achievements||{},questRewarded:{},weekRewarded:{},events:0};
let S=load(KEY,base);if(!localStorage.getItem(KEY)){S=base;saveRaw()}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function level(){return Math.max(1,Math.floor(Math.sqrt(Math.max(0,S.xp)/85))+1)}
function xpAt(l){return 85*Math.pow(Math.max(0,l-1),2)}
function rank(){const l=level();let out=RANKS[0][0];for(const [name,min] of RANKS)if(l>=min)out=name;return out}
function nextRank(){const l=level();return RANKS.find(([,min])=>min>l)||[null,null]}
function today(){const k=localDay();return S.days[k]||(S.days[k]={puzzles:0,openings:0,games:0,reviews:0,sessions:0,xp:0})}
function saveRaw(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch{}}
function touchDay(){const k=localDay();if(S.lastDay===k)return;if(S.lastDay){const a=new Date(S.lastDay+'T12:00:00'),b=new Date(k+'T12:00:00'),diff=Math.round((b-a)/86400000);S.dayStreak=diff===1?S.dayStreak+1:1}else S.dayStreak=1;S.bestDayStreak=Math.max(S.bestDayStreak||0,S.dayStreak);S.lastDay=k}
function unlock(id,label){if(S.achievements[id])return false;S.achievements[id]={label,at:Date.now()};return true}
function popup(xp,label){const p=document.createElement('div');p.className='xp-pop-v18';p.innerHTML=`<b>+${xp} XP</b><span>${label}</span>`;document.body.appendChild(p);requestAnimationFrame(()=>p.classList.add('show'));setTimeout(()=>{p.classList.remove('show');setTimeout(()=>p.remove(),250)},1350)}
function addXp(xp,label,show=true){S.xp+=xp;today().xp+=xp;S.events++;if(show)popup(xp,label)}
function activeDaysThisWeek(){const mon=mondayKey(),start=new Date(mon+'T12:00:00');let n=0;for(let i=0;i<7;i++){const d=new Date(start);d.setDate(d.getDate()+i);const v=S.days[localDay(d)];if(v&&((v.puzzles||0)+(v.openings||0)+(v.games||0)+(v.reviews||0)>0))n++}return n}
function checkRewards(){
 const d=today(),k=localDay(),q=S.questRewarded[k]||(S.questRewarded[k]={});
 if(d.puzzles>=5&&!q.puzzles){q.puzzles=true;addXp(40,'Daily puzzle mission')}
 if(d.openings>=3&&!q.openings){q.openings=true;addXp(30,'Opening memory mission')}
 if((d.games+d.reviews)>=1&&!q.evidence){q.evidence=true;addXp(35,'Game evidence mission')}
 if(q.puzzles&&q.openings&&q.evidence&&!q.all){q.all=true;addXp(75,'Daily board cleared');unlock('daily-clear','Full board · complete all daily missions')}
 const wk=mondayKey(),days=activeDaysThisWeek();if(days>=5&&!S.weekRewarded[wk]){S.weekRewarded[wk]=true;addXp(120,'Five-day training week');unlock('week5','Consistency beats intensity · train 5 days in a week')}
 const t=load(TACTICS,{solved:0,bestStreak:0,rating:600});if(t.solved>=25)unlock('p25','Pattern hunter · 25 puzzles');if(t.solved>=100)unlock('p100','Century · 100 puzzles');if(t.solved>=500)unlock('p500','Pattern library · 500 puzzles');if((t.bestStreak||0)>=10)unlock('flow10','In the flow · 10 puzzle streak');if(S.dayStreak>=3)unlock('days3','Momentum · train 3 days in a row');if(S.dayStreak>=7)unlock('days7','Habit formed · train 7 days in a row');if(S.dayStreak>=30)unlock('days30','Thirty-day board · serious consistency');const p=load(PROFILE,{rating:600});if((p.rating||0)>=800)unlock('r800','Road to 1000 · cross 800');if((p.rating||0)>=1000)unlock('r1000','Four digits · reach 1000');if(S.xp>=2500)unlock('xp2500','Training engine · earn 2,500 XP')
}
function save(){checkRewards();saveRaw();render()}
function award(kind,xp,label){touchDay();const d=today();d[kind]=(d[kind]||0)+1;addXp(xp,label);save()}
function ensure(){
 const progress=$('progress');if(!progress)return;document.getElementById('metaV15')?.remove();document.getElementById('metaBadge')?.remove();if($('metaV18'))return;
 const el=document.createElement('section');el.id='metaV18';el.className='meta-v18';el.innerHTML=`
 <header class="meta-v18-hero"><div><span class="eyebrow">PLAYER JOURNEY / V18</span><h2>Every session should move something.</h2><p>Ratings measure chess. XP measures the work you put in.</p></div><div class="meta-v18-level"><small id="meta18Level">LEVEL 1</small><b id="meta18Rank">Cadet</b><div><i id="meta18LevelBar"></i></div><span id="meta18NextLevel">0 XP</span></div></header>
 <div class="meta-v18-dashboard">
  <article class="meta-v18-road"><div><small>ROAD TO 1000</small><b id="meta18Rating">600</b><span id="meta18RoadText">400 Elo to go</span></div><div class="meta-v18-roadbar"><i id="meta18RoadBar"></i><em style="left:0">400</em><em style="left:33.3%">600</em><em style="left:66.6%">800</em><em style="left:100%">1000</em></div></article>
  <article><small>TRAINING STREAK</small><b id="meta18Streak">0</b><span id="meta18BestStreak">best 0 days</span></article>
  <article><small>THIS WEEK</small><b id="meta18Week">0/5</b><span>active training days</span></article>
  <article><small>PUZZLE RATING</small><b id="meta18PuzzleRating">600</b><span id="meta18PuzzleSolved">0 solved</span></article>
 </div>
 <section class="meta-v18-quests"><div class="meta-v18-title"><div><small>TODAY</small><h3>Three useful wins.</h3></div><strong id="meta18DailyXp">0 XP</strong></div><div id="meta18QuestGrid" class="meta-v18-questgrid"></div></section>
 <div class="meta-v18-split"><section><div class="meta-v18-title"><div><small>TACTICAL FORM</small><h3>Patterns becoming automatic.</h3></div></div><div id="meta18Mastery" class="meta-v18-mastery"></div></section><section><div class="meta-v18-title"><div><small>PERSONAL BESTS</small><h3>Beat yesterday's you.</h3></div></div><div id="meta18Bests" class="meta-v18-bests"></div></section></div>
 <section class="meta-v18-ach"><div class="meta-v18-title"><div><small>MILESTONES</small><h3>Earned, not collected.</h3></div><span id="meta18AchievementCount"></span></div><div id="meta18Achievements"></div></section>`;
 const coach=$('coachV10');progress.insertBefore(el,coach||progress.firstChild);const badge=document.createElement('button');badge.id='metaBadgeV18';badge.className='meta-badge-v18';badge.onclick=()=>{CC()?.setScreen('progress');setTimeout(()=>el.scrollIntoView({behavior:'smooth',block:'start'}),30)};document.querySelector('.top-actions')?.prepend(badge);render();
}
function CC(){return window.ChessCommand}
function quest(name,n,target,reward,desc,doneReward){const done=n>=target;return`<article class="${done?'done':''}"><div class="meta-v18-check">${done?'✓':'○'}</div><div><b>${name}</b><small>${Math.min(n,target)} / ${target} · ${desc}</small><div><i style="width:${clamp(n/target*100,0,100)}%"></i></div></div><strong>${done?'+'+doneReward+' ✓':'+'+reward+' XP'}</strong></article>`}
function masteryRows(t){const P=window.PuzzleCoreV12,themes=t.themes||{},names=['Mate','Fork','Pin','Skewer','Hanging piece','Deflection','Removing defender','Defense','Discovered attack'];const arr=names.map(name=>{const s=themes[name]||{},m=P?.mastery?P.mastery(s):s.attempts?Math.round((s.correct||0)/s.attempts*100):0;return{name,m,attempts:s.attempts||0}}).sort((a,b)=>b.attempts-a.attempts||b.m-a.m);const shown=arr.filter(x=>x.attempts).slice(0,5);if(!shown.length)return'<p class="meta-v18-empty">Solve a few themed puzzles and your tactical profile will appear here.</p>';return shown.map(x=>`<div><span>${x.name}<small>${x.attempts} reps</small></span><div><i style="width:${x.m}%"></i></div><b>${x.m}%</b></div>`).join('')}
function render(){if(!$('metaV18'))return;checkRewards();saveRaw();const p=load(PROFILE,{rating:600}),t=load(TACTICS,{rating:600,solved:0,bestStreak:0,themes:{}}),ps=load(SESSIONS,{best:{rush:0,survival:0,focus:0},sessions:0}),d=today(),l=level(),lo=xpAt(l),hi=xpAt(l+1),pct=clamp((S.xp-lo)/Math.max(1,hi-lo)*100,0,100),rating=Math.round(p.rating||600),road=clamp((rating-400)/600*100,0,100),nr=nextRank();$('meta18Level').textContent=`LEVEL ${l}`;$('meta18Rank').textContent=rank();$('meta18LevelBar').style.width=pct+'%';$('meta18NextLevel').textContent=`${Math.max(0,hi-S.xp)} XP to level ${l+1}${nr[0]?` · ${nr[0]} at ${nr[1]}`:''}`;$('meta18Rating').textContent=rating;$('meta18RoadText').textContent=rating>=1000?'1000 reached · choose the next mountain':`${Math.max(0,1000-rating)} Elo to go`;$('meta18RoadBar').style.width=road+'%';$('meta18Streak').textContent=`🔥 ${S.dayStreak||0}`;$('meta18BestStreak').textContent=`best ${S.bestDayStreak||0} days`;$('meta18Week').textContent=`${activeDaysThisWeek()}/5`;$('meta18PuzzleRating').textContent=Math.round(t.rating||600);$('meta18PuzzleSolved').textContent=`${t.solved||0} solved · best flow ${t.bestStreak||0}`;$('meta18DailyXp').textContent=`${d.xp||0} XP today`;$('meta18QuestGrid').innerHTML=quest('Pattern reps',d.puzzles||0,5,10,'solve five puzzles',40)+quest('Opening memory',d.openings||0,3,6,'three correct opening moves',30)+quest('Create evidence',(d.games||0)+(d.reviews||0),1,30,'play or review one game',35);$('meta18Mastery').innerHTML=masteryRows(t);$('meta18Bests').innerHTML=`<div><small>RUSH 3:00</small><b>${ps.best?.rush||0}</b><span>puzzles</span></div><div><small>SURVIVAL</small><b>${ps.best?.survival||0}</b><span>puzzles</span></div><div><small>THEME RUN</small><b>${ps.best?.focus||0}</b><span>puzzles</span></div><div><small>TRAINING XP</small><b>${S.xp}</b><span>lifetime</span></div>`;const a=Object.values(S.achievements).sort((x,y)=>y.at-x.at);$('meta18AchievementCount').textContent=`${a.length} earned`;$('meta18Achievements').innerHTML=a.length?a.slice(0,12).map(x=>`<span>✓ ${x.label}</span>`).join(''):'<span class="locked">Your first puzzle, game and review unlock the journey.</span>';const badge=$('metaBadgeV18');if(badge)badge.innerHTML=`<small>LV ${l}</small><b>${rank()}</b><i style="--p:${pct}%"></i>`}
document.addEventListener('cc:puzzle',e=>{if(e.detail.correct)award('puzzles',10,'Puzzle solved')});document.addEventListener('cc:opening',e=>{if(e.detail.correct)award('openings',6,'Opening rep')});document.addEventListener('cc:gameover',e=>award('games',e.detail.score===1?50:e.detail.score===.5?40:32,e.detail.score===1?'Game won':'Game completed'));document.addEventListener('cc:deepreview',e=>{const id=e.detail.gameId||'unknown';if(S.deepSeen[id])return;S.deepSeen[id]=Date.now();award('reviews',25,'Deep Review')});document.addEventListener('cc:puzzlesession',e=>{touchDay();today().sessions=(today().sessions||0)+1;const bonus=15+(e.detail.newBest?25:0)+(e.detail.accuracy===100?15:0);addXp(bonus,e.detail.newBest?'New puzzle personal best':e.detail.accuracy===100?'Perfect puzzle session':'Puzzle session complete');save()});window.addEventListener('storage',render);ensure();new MutationObserver(ensure).observe(document.body,{childList:true,subtree:true});
})();
