(function(global){
'use strict';
const ASM_URL='https://cdn.jsdelivr.net/npm/stockfish@18.0.8/bin/stockfish-18-asm.js';
class StockfishBridge{
 constructor(){this.worker=null;this.ready=false;this.loading=null;this.waiters=[];this.mode='fallback';this.info=null;this.chain=Promise.resolve();}
 async init(){if(this.ready)return true;if(this.loading)return this.loading;this.loading=(async()=>{try{const res=await fetch(ASM_URL,{cache:'force-cache'});if(!res.ok)throw new Error('engine download failed');const code=await res.text();const blob=new Blob([code],{type:'text/javascript'});this.worker=new Worker(URL.createObjectURL(blob));this.worker.onmessage=e=>this._line(typeof e.data==='string'?e.data:String(e.data));this.worker.postMessage('uci');await this._wait('uciok',12000);this.worker.postMessage('isready');await this._wait('readyok',12000);this.ready=true;this.mode='stockfish-18';return true}catch(err){console.warn('Stockfish unavailable; using local practice bot.',err);this.mode='fallback';return false}})();return this.loading}
 _line(line){if(line.startsWith('info ')){const d=Number((line.match(/\bdepth\s+(\d+)/)||[])[1]||0);const cp=(line.match(/\bscore\s+cp\s+(-?\d+)/)||[])[1];const mate=(line.match(/\bscore\s+mate\s+(-?\d+)/)||[])[1];const pv=(line.match(/\bpv\s+(.+)$/)||[])[1];if(cp!==undefined||mate!==undefined)this.info={depth:d,cp:cp===undefined?null:Number(cp),mate:mate===undefined?null:Number(mate),pv:pv?pv.trim().split(/\s+/):[]};}
  for(const w of [...this.waiters])if(line.includes(w.token)){this.waiters.splice(this.waiters.indexOf(w),1);w.resolve(line)}}
 _wait(token,ms=8000){return new Promise((resolve,reject)=>{const w={token,resolve};this.waiters.push(w);setTimeout(()=>{const i=this.waiters.indexOf(w);if(i>=0){this.waiters.splice(i,1);reject(new Error('timeout '+token))}},ms)})}
 _enqueue(fn){const p=this.chain.then(fn,fn);this.chain=p.catch(()=>{});return p}
 _setStrength(elo){if(elo===9999){this.worker.postMessage('setoption name UCI_LimitStrength value false')}else{this.worker.postMessage('setoption name UCI_LimitStrength value true');this.worker.postMessage('setoption name UCI_Elo value '+Math.max(1320,Math.min(3190,elo)))}}
 async bestMove(fen,elo){return this._enqueue(async()=>{const ok=await this.init();if(!ok)return null;this.worker.postMessage('stop');this.worker.postMessage('ucinewgame');this._setStrength(elo);this.worker.postMessage('position fen '+fen);this.worker.postMessage('go movetime '+(elo>=2400?550:elo>=1800?380:260));const line=await this._wait('bestmove',10000);const m=line.match(/bestmove\s+([a-h][1-8][a-h][1-8][qrbn]?)/);return m?m[1]:null})}
 async analyse(fen,opt={}){return this._enqueue(async()=>{const ok=await this.init();if(!ok)return null;const movetime=Math.max(80,Math.min(1500,opt.movetime||180));this.worker.postMessage('stop');this.worker.postMessage('setoption name UCI_LimitStrength value false');this.info=null;this.worker.postMessage('position fen '+fen);this.worker.postMessage('go movetime '+movetime);const line=await this._wait('bestmove',Math.max(10000,movetime+4000));const m=line.match(/bestmove\s+([a-h][1-8][a-h][1-8][qrbn]?)/);const bestMove=m?m[1]:null,info=this.info||{};const turn=(fen.split(/\s+/)[1]||'w');let scoreWhite=0;if(info.mate!==null&&info.mate!==undefined){const sideScore=Math.sign(info.mate||1)*(100000-Math.min(99,Math.abs(info.mate))*1000);scoreWhite=turn==='w'?sideScore:-sideScore}else if(Number.isFinite(info.cp)){scoreWhite=turn==='w'?info.cp:-info.cp}return{bestMove,scoreWhite,cp:info.cp??null,mate:info.mate??null,pv:info.pv||[],depth:info.depth||0}})}
}
global.StockfishBridge=StockfishBridge;
})(window);
