const CACHE='chess-command-v21-premium-clarity1';
const CORE=[
  './','./index.html','./chess-styles.css','./piece-skin.css','./learning-v5.css','./review-v11.css','./coach-v10.css','./puzzle-v12.css','./puzzle-modes-v18.css','./opening-v14.css','./gamefeel-v17.css','./progress-v18.css','./mobile.css','./puzzle-mobile-v19.css','./viewport-v20.css','./clarity-v21.css',
  './chess-core.js','./coach-core.js','./review-core-v11.js','./puzzle-core-v12.js','./puzzle-pack-v15.js','./puzzle-pack-lichess-v16.js','./puzzle-provider-v16.js','./data.js','./stockfish-bridge.js','./chess-app.js','./learning-v5.js','./review-v11.js','./coach-v10.js','./puzzle-v12.js','./puzzle-modes-v18.js','./puzzle-mobile-v12.js','./opening-v14.js','./gamefeel-v17.js','./progress-v18.js','./layout-v20.js','./clarity-v21.js',
  './piece-skin.js','./mobile-ui.js','./pwa-init.js','./pieces.svg','./manifest.webmanifest','./chess-command-icon.svg'
];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==self.location.origin){const pieceAsset=url.hostname==='raw.githubusercontent.com'&&url.pathname.includes('/lichess-org/lila/')&&url.pathname.includes('/public/piece/');if(pieceAsset){event.respondWith(caches.match(req).then(hit=>hit||fetch(req).then(res=>{caches.open(CACHE).then(cache=>cache.put(req,res.clone()));return res}).catch(()=>new Response('',{status:503,statusText:'Piece skin offline'}))));return}event.respondWith(fetch(req).catch(()=>new Response('',{status:503,statusText:'Offline'})));return}if(req.mode==='navigate'){event.respondWith(fetch(req).then(res=>{const copy=res.clone();caches.open(CACHE).then(cache=>cache.put('./index.html',copy));return res}).catch(()=>caches.match('./index.html')));return}event.respondWith(caches.match(req).then(hit=>hit||fetch(req).then(res=>{if(res.ok){const copy=res.clone();caches.open(CACHE).then(cache=>cache.put(req,copy))}return res}))) });
