$('#micCheck').onclick=micCheck;$('#micSelect').onchange=()=>{micReady=false;$('#micMsg').textContent='Device changed. Run the microphone check again.';updateConnectAvailability()};$('#textOnly').onclick=()=>{textMode=!textMode;$('#textOnly').classList.toggle('sel',textMode);$('#textOnly').textContent=textMode?'Text-only selected':'Use text only';updateConnectAvailability()};
function updateConnectAvailability(){const ready=$('#engine').textContent==='ready';$('#connect').disabled=!ready||!(micReady||textMode)}
function waitIce(pc,timeout=2800){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(resolve=>{const timer=setTimeout(done,timeout);function done(){clearTimeout(timer);pc.removeEventListener('icegatheringstatechange',change);resolve()}function change(){if(pc.iceGatheringState==='complete')done()}pc.addEventListener('icegatheringstatechange',change)})}
function waitDataChannel(timeout=12000){return new Promise((resolve,reject)=>{if(dc?.readyState==='open')return resolve();const timer=setTimeout(()=>reject(new Error('Realtime data channel did not open in time.')),timeout);dc.addEventListener('open',()=>{clearTimeout(timer);resolve()},{once:true});dc.addEventListener('error',()=>{clearTimeout(timer);reject(new Error('Realtime data channel failed.'))},{once:true})})}
async function startStats(){clearInterval(statsTimer);statsTimer=setInterval(async()=>{if(!pc||pc.connectionState!=='connected')return;try{const stats=await pc.getStats();let rtt=null,jitter=null,lost=0,received=0;stats.forEach(s=>{if(s.type==='candidate-pair'&&s.state==='succeeded'&&s.currentRoundTripTime!=null)rtt=s.currentRoundTripTime;if(s.type==='inbound-rtp'&&s.kind==='audio'){jitter=s.jitter;lost+=s.packetsLost||0;received+=s.packetsReceived||0}});const loss=received+lost>0?lost/(received+lost):0;let quality='good';if((rtt!=null&&rtt>.35)||(jitter!=null&&jitter>.05)||loss>.05)quality='poor';else if((rtt!=null&&rtt>.18)||(jitter!=null&&jitter>.025)||loss>.02)quality='fair';$('#quality').textContent=quality+(rtt!=null?` · ${Math.round(rtt*1000)}ms`:'')}catch{}},2200)}
function setConnectedUI(on){connected=on;$('#connect').textContent=on?'End encounter':($('#connectionState').textContent==='recovering'?'Reconnect Lumen':'Meet Lumen');$('#interrupt').disabled=!on;$('#closeEncounter').disabled=!on;$('#send').disabled=!on;$('#textInput').disabled=!on;$('#userName').disabled=on;$('#language').disabled=on;$('#turnMode').disabled=on;$('#micSelect').disabled=on}
async function connect(){if(connected){userEnded=true;await disconnect('user');return}if(!(micReady||textMode))return;userEnded=false;alertBox('');setPhase('connecting');$('#connectionState').textContent='negotiating';$('#connect').disabled=true;const started=performance.now();try{connectAbort=new AbortController();pc=new RTCPeerConnection();const remote=new MediaStream();pc.ontrack=e=>{if(!remote.getTracks().some(t=>t.id===e.track.id))remote.addTrack(e.track);$('#remoteAudio').srcObject=remote;$('#remoteAudio').play().catch(()=>alertBox('Tap Meet Lumen again if your browser blocked audio playback.','warning'));if(!outContext)outContext=analyse(remote,true)};pc.onconnectionstatechange=()=>{const state=pc?.connectionState||'closed';$('#connectionState').textContent=state;if(state==='connected'){clearTimeout(recoveryTimer);setPhase('idle');startStats()}else if(state==='disconnected'){setPhase('recovering');$('#connectionState').textContent='recovering';clearTimeout(recoveryTimer);recoveryTimer=setTimeout(()=>{if(pc?.connectionState!=='connected')markRecoverable('The connection was interrupted.')},4500)}else if(state==='failed')markRecoverable('The peer connection failed.')};
if(textMode)pc.addTransceiver('audio',{direction:'recvonly'});else{micStream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:selectedConstraint(),echoCancellation:true,noiseSuppression:true,autoGainControl:true}});micStream.getTracks().forEach(t=>pc.addTrack(t,micStream));micContext=analyse(micStream,false)}
dc=pc.createDataChannel('oai-events');dc.onmessage=m=>{try{handleEvent(JSON.parse(m.data))}catch{alertBox('Unreadable realtime event')}};dc.onclose=()=>{if(!userEnded&&connected)markRecoverable('The realtime channel closed.')};
const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);const sdp=pc.localDescription?.sdp||offer.sdp;if(!sdp)throw new Error('Browser did not create an SDP offer.');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),25000);const resp=await fetch('/api/realtime',{method:'POST',headers:{'Content-Type':'application/sdp','X-Lumen-Language':$('#language').value,'X-Lumen-Name':encodeURIComponent($('#userName').value||'the user'),'X-Lumen-Memory':$('#memoryEnabled').checked?b64(JSON.stringify(memories.slice(-12))):'','X-Lumen-Encounter':String(profile.encounters+1),'X-Lumen-Turn-Mode':$('#turnMode').value},body:sdp,signal:controller.signal});clearTimeout(timer);const elapsed=Math.round(performance.now()-started);$('#latency').textContent=elapsed+'ms';if(!resp.ok)throw new Error(`Session ${resp.status}: ${await resp.text()}`);callId=resp.headers.get('X-Lumen-Call-Id')||'';await pc.setRemoteDescription({type:'answer',sdp:await resp.text()});await waitDataChannel();setConnectedUI(true);$('#connectionState').textContent='connected';setPhase('idle');if($('#memoryEnabled').checked){profile.encounters++;profile.lastEncounter=new Date().toISOString();saveData();$('#encounterState').textContent='#'+profile.encounters}send({type:'response.create',response:{instructions:`First call set_presence, then greet ${$('#userName').value||'the user'} warmly in ${$('#language').value==='de'?'German':'English'}. Confirm the live connection in one short sentence and invite them to begin.`}})}catch(err){await disconnect('error');const message=err.name==='AbortError'?'Connection timed out. Please try again.':err.message;alertBox(message);$('#connectionState').textContent='recovering';$('#connect').textContent='Reconnect Lumen';updateConnectAvailability()}}
async function hangup(){const id=callId;callId='';if(id)fetch('/api/hangup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({callId:id}),keepalive:true}).catch(()=>{})}
async function disconnect(reason='user'){clearTimeout(resumeTimer);clearTimeout(recoveryTimer);clearInterval(statsTimer);connectAbort?.abort();connectAbort=null;const oldPc=pc;dc?.close();oldPc?.getSenders().forEach(s=>s.track?.stop());oldPc?.close();pc=dc=null;micStream?.getTracks().forEach(t=>t.stop());micStream=null;micContext?.close().catch(()=>{});micContext=null;outContext?.close().catch(()=>{});outContext=null;cancelAnimationFrame(micRAF);cancelAnimationFrame(outRAF);mouthLevel=0;micLevel=0;$('#liveMeter').style.width='3%';await hangup();setConnectedUI(false);if(reason==='user'){setPhase('offline');$('#connectionState').textContent='offline';$('#quality').textContent='—'}else{setPhase('recovering');$('#connectionState').textContent='recovering'}}
function markRecoverable(message){if(userEnded)return;disconnect('error');alertBox(message+' Reconnect when ready.','warning');$('#connect').textContent='Reconnect Lumen';updateConnectAvailability()}
$('#connect').onclick=connect;$('#interrupt').onclick=()=>{send({type:'response.cancel'});send({type:'output_audio_buffer.clear'});mouthLevel=0;setPhase('idle')};
function sendText(textOverride=''){const text=(textOverride||$('#textInput').value).trim();if(!text||dc?.readyState!=='open')return;addTurn('user',text);$('#userTranscript').textContent='You: '+text;send({type:'conversation.item.create',item:{type:'message',role:'user',content:[{type:'input_text',text}]}});send({type:'response.create'});$('#textInput').value=''}$('#send').onclick=()=>sendText();$('#textInput').onkeydown=e=>{if(e.key==='Enter')sendText()};$$('[data-prompt]').forEach(b=>b.onclick=()=>sendText(b.dataset.prompt));$('#closeEncounter').onclick=()=>sendText($('#language').value==='de'?'Hilf mir, diese Begegnung mit genau einem konkreten nächsten Schritt für mein reales Leben zu beenden. Sei kurz.':'Help me close this encounter with exactly one concrete next step for my real life. Be brief.');
$$('[data-scene]').forEach(b=>b.onclick=()=>{world={...world,scene:b.dataset.scene,focus:'none',actionLabel:`You opened the ${b.textContent}.`};updateWorld()});
fetch('/api/health',{cache:'no-store'}).then(r=>r.json()).then(h=>{const ready=!!h.openaiConfigured;$('#engine').textContent=ready?'ready':'missing key';$('#mindState').textContent=ready?'realtime ready':'blocked';updateConnectAvailability()}).catch(()=>{$('#engine').textContent='unreachable';$('#mindState').textContent='blocked';alertBox('Lumen’s server healthcheck is unreachable.')});
addEventListener('beforeunload',()=>{userEnded=true;if(callId)navigator.sendBeacon?.('/api/hangup',new Blob([JSON.stringify({callId})],{type:'application/json'}));pc?.close();micStream?.getTracks().forEach(t=>t.stop())});renderPresence();updateWorld();setPhase('offline');
