const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const MEMORY_KEY='lumen-v11-memories', MEMORY_ENABLED_KEY='lumen-v11-memory-enabled', PROFILE_KEY='lumen-v11-profile';
let pc=null,dc=null,micStream=null,micContext=null,outContext=null,micRAF=0,outRAF=0,statsTimer=0,recoveryTimer=0,connectAbort=null,callId='',micReady=false,textMode=false,connected=false,userEnded=false,memories=[],turns=[],processed=new Set(),resumeTimer=0,resumeDeadline=0,profile={encounters:0,lastEncounter:null},mouthLevel=0,micLevel=0,pointer={x:0,y:0};
let world={scene:'cosmos',focus:'none',ambience:.48,actionLabel:'The room is quiet.'};
let presence={phase:'offline',emotion:'warm',gesture:'still',gaze:'user',intensity:.42,pauseMs:180};
const canvas=$('#presenceCanvas'),ctx=canvas.getContext('2d');
function clamp(v,a=0,b=1){return Math.max(a,Math.min(b,v))}function lerp(a,b,t){return a+(b-a)*t}function escapeHtml(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resizeCanvas);resizeCanvas();
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer.x=clamp((e.clientX-r.left)/r.width*2-1,-1,1);pointer.y=clamp((e.clientY-r.top)/r.height*2-1,-1,1)});canvas.addEventListener('pointerleave',()=>pointer={x:0,y:0});
const palettes={calm:['#8ea0c8','#d7c9c3'],warm:['#a18db8','#ead7c8'],playful:['#8a91d9','#f0c8d5'],compassionate:['#7fa7a6','#ecd8c8'],curious:['#7998bf','#dfd7cb'],solemn:['#737c9e','#d4c8c6'],joyful:['#a48ac7','#f2d6b4']};
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}function line(points,width,color){ctx.beginPath();ctx.moveTo(points[0][0],points[0][1]);for(let i=1;i<points.length;i++)ctx.lineTo(points[i][0],points[i][1]);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=width;ctx.strokeStyle=color;ctx.stroke()}
let blink=0,nextBlink=performance.now()+2200,lastFrame=performance.now();
function draw(now){requestAnimationFrame(draw);const rect=canvas.getBoundingClientRect(),w=rect.width,h=rect.height;if(!w||!h)return;const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;const reduced=$('#motionMode').value==='reduced'||matchMedia('(prefers-reduced-motion: reduce)').matches;const t=now/1000;ctx.clearRect(0,0,w,h);
const sceneColors={cosmos:['#11152b','#070914'],moon_garden:['#102a31','#061316'],sunset_temple:['#3a223f','#100c1b']}[world.scene];const bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,sceneColors[0]);bg.addColorStop(1,sceneColors[1]);ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
if(world.scene==='cosmos'){ctx.globalAlpha=.5;for(let i=0;i<70;i++){const x=(i*97.3%997)/997*w,y=(i*53.7%773)/773*h*.8,r=(i%4===0?1.4:.7);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
if(world.scene!=='sunset_temple'){const fx=w*.78,fy=h*.22+(reduced?0:Math.sin(t*.5)*5),focus=world.focus==='moon'?1.18:1;const g=ctx.createRadialGradient(fx,fy,3,fx,fy,70*focus);g.addColorStop(0,'#f7fbff');g.addColorStop(.2,'#c8d9ff');g.addColorStop(1,'#7892d800');ctx.fillStyle=g;ctx.beginPath();ctx.arc(fx,fy,72*focus,0,Math.PI*2);ctx.fill();ctx.fillStyle='#dbe7ff';ctx.beginPath();ctx.arc(fx,fy,27*focus,0,Math.PI*2);ctx.fill()}
if(world.scene==='moon_garden'){const lx=w*.22,ly=h*.77,focus=world.focus==='lotus'?1.25:1;ctx.save();ctx.translate(lx,ly);ctx.scale(focus,focus);for(let i=0;i<10;i++){ctx.save();ctx.rotate(i/10*Math.PI*2);ctx.fillStyle=i%2?'#efb0d0':'#df8fbe';ctx.beginPath();ctx.ellipse(0,-15,9,23,0,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.fillStyle='#f5d58b';ctx.beginPath();ctx.arc(0,0,7,0,Math.PI*2);ctx.fill();ctx.restore()}
if(world.scene==='sunset_temple'){const fx=w*.78,fy=h*.77,focus=world.focus==='flame'?1.23:1;const pulse=reduced?1:1+Math.sin(t*4)*.07;const g=ctx.createRadialGradient(fx,fy,2,fx,fy,80);g.addColorStop(0,'#ffd695aa');g.addColorStop(1,'#ff704000');ctx.fillStyle=g;ctx.beginPath();ctx.arc(fx,fy,80,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffb45e';ctx.beginPath();ctx.ellipse(fx,fy,13*focus*pulse,31*focus*pulse,-.12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff0b0';ctx.beginPath();ctx.ellipse(fx,fy+5,6*focus,17*focus,0,0,Math.PI*2);ctx.fill()}
const cx=w*.5,baseY=h*.53+(reduced?0:Math.sin(t*1.35)*3),scale=Math.min(w/650,h/600),[cloth,skin]=palettes[presence.emotion]||palettes.warm;ctx.save();ctx.translate(cx,baseY);ctx.scale(scale,scale);
const aura=ctx.createRadialGradient(0,-30,30,0,-20,180);aura.addColorStop(0,(presence.emotion==='compassionate'?'#8fe1bd':'#aab5f1')+Math.round((.18+presence.intensity*.16)*255).toString(16).padStart(2,'0'));aura.addColorStop(1,'#00000000');ctx.fillStyle=aura;ctx.beginPath();ctx.arc(0,-20,185,0,Math.PI*2);ctx.fill();
ctx.save();ctx.translate(0,-165);ctx.scale(1,.28);ctx.strokeStyle='#e8c873';ctx.lineWidth=5;ctx.shadowColor='#e8c873';ctx.shadowBlur=16;ctx.beginPath();ctx.arc(0,0,76,0,Math.PI*2);ctx.stroke();ctx.restore();ctx.shadowBlur=0;
const bodyG=ctx.createLinearGradient(-90,-60,90,160);bodyG.addColorStop(0,cloth);bodyG.addColorStop(1,'#333959');ctx.fillStyle=bodyG;roundRect(-82,-35,164,210,70);ctx.fill();
let left=[[-66,10],[-94,70],[-82,142]],right=[[66,10],[94,70],[82,142]];if(['open_palms','inviting'].includes(presence.gesture)){left=[[-66,10],[-118,58],[-145,88]];right=[[66,10],[118,58],[145,88]]}if(presence.gesture==='hand_to_heart'){left=[[-66,10],[-48,58],[-15,70]];right=[[66,10],[50,58],[18,72]]}if(presence.gesture==='amused'){left=[[-66,10],[-105,70],[-92,125]];right=[[66,10],[95,45],[74,2]]}line(left,27,cloth);line(right,27,cloth);for(const p of [left.at(-1),right.at(-1)]){ctx.fillStyle=skin;ctx.beginPath();ctx.arc(p[0],p[1],15,0,Math.PI*2);ctx.fill()}
let headTilt=presence.gesture==='curious_tilt'?-0.08:presence.phase==='listening'?-0.035:0;if(presence.gesture==='gentle_nod'&&!reduced)headTilt+=Math.sin(t*3)*.035;ctx.save();ctx.translate(0,-77);ctx.rotate(headTilt);const faceG=ctx.createRadialGradient(-18,-38,7,0,0,90);faceG.addColorStop(0,'#f7e9de');faceG.addColorStop(.65,skin);faceG.addColorStop(1,'#9b9ab5');ctx.fillStyle=faceG;ctx.beginPath();ctx.ellipse(0,0,58,69,0,0,Math.PI*2);ctx.fill();
if(now>nextBlink&&blink===0){blink=1;setTimeout(()=>blink=0,115);nextBlink=now+2400+Math.random()*3500}const eyeOpen=blink?0.12:1;const gazeX=presence.gaze==='reflective'?-4:presence.gaze==='object'?5:pointer.x*3,gazeY=pointer.y*2;for(const ex of [-21,21]){ctx.fillStyle='#fffaf5';ctx.beginPath();ctx.ellipse(ex,-5,13,7*eyeOpen,0,0,Math.PI*2);ctx.fill();if(eyeOpen>.3){ctx.fillStyle='#6faac5';ctx.beginPath();ctx.arc(ex+gazeX,-5+gazeY,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#182132';ctx.beginPath();ctx.arc(ex+gazeX,-5+gazeY,2.2,0,Math.PI*2);ctx.fill()}}
ctx.strokeStyle='#6d6178';ctx.lineWidth=2.2;ctx.beginPath();ctx.moveTo(-34,-20);ctx.quadraticCurveTo(-22,-27-(presence.emotion==='curious'?3:0),-9,-20);ctx.moveTo(9,-20);ctx.quadraticCurveTo(22,-27-(presence.emotion==='curious'?3:0),34,-20);ctx.stroke();const open=clamp(.04+(presence.phase==='speaking'?mouthLevel*1.35:.02),.04,.82);ctx.fillStyle='#754d61';ctx.beginPath();ctx.ellipse(0,28,14,3+open*12,0,0,Math.PI*2);ctx.fill();if(presence.emotion==='joyful'||presence.emotion==='playful'){ctx.strokeStyle='#6e4a58';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,20,18,.25,Math.PI-.25);ctx.stroke()}ctx.restore();ctx.restore();
}
requestAnimationFrame(draw);
