let KB=null,EVAL=null,lastHits=[];const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const stop='ich du er sie es wir ihr der die das ein eine einen und oder ist bin sind was wie wo wann muss brauche mit zu für fuer nach in von am im beim bitte hallo'.split(' ');
function tok(s=''){return s.toLowerCase().replace(/[ä]/g,'ae').replace(/[ö]/g,'oe').replace(/[ü]/g,'ue').replace(/[ß]/g,'ss').replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>2&&!stop.includes(w))}
function score(q,c){const T=tok(q),H=tok([c.topic,c.title,c.department,c.text,(c.steps||[]).join(' ')].join(' '));let n=0;T.forEach(t=>{if(H.includes(t))n+=3;else if(H.some(h=>h.includes(t)||t.includes(h)))n+=1});return n}
function retrieve(q){let rows=KB.chunks.map(c=>({...c,score:score(q,c)})).sort((a,b)=>b.score-a.score);return rows[0]?.score?rows.slice(0,3):[{id:'fallback',topic:'unklar',title:'Rückfrage nötig',department:'Telefonzentrale',action:'callback',text:'Ich bin mir nicht sicher, welches Anliegen gemeint ist. Ich würde eine kurze Rückfrage stellen oder eine Rückrufbitte vorbereiten, statt eine unsichere Auskunft zu geben.',steps:['Rückfrage stellen','keine Antwort erfinden','menschliche Übergabe anbieten'],source:'Fallback-Regel',score:0}]}
function actionLabel(a){return {appointment:'Termin',ticket:'Ticket',callback:'Rückruf',appointment_or_callback:'Termin/Rückruf',eval:'Eval',answer:'Auskunft'}[a]||'Auskunft'}
function renderLocal(q){lastHits=retrieve(q);const c=lastHits[0];$('citizen').textContent=c.text;$('intent').textContent=c.title;$('dept').textContent=c.department;$('action').textContent=actionLabel(c.action);$('conf').textContent=c.score>7?'92%':c.score>3?'76%':'41%';$('sources').innerHTML=lastHits.map(h=>`<li><b>${esc(h.id)}</b> · Score ${h.score}<br>${esc(h.source)}</li>`).join('');$('steps').innerHTML=(c.steps||[]).map(s=>`<li>${esc(s)}</li>`).join('');$('receipt').textContent=`Local RAG · ${c.topic} · ${c.source} · Routing zu ${c.department} · Aktion ${actionLabel(c.action)}.`}
async function renderLlm(q){$('citizen').textContent='LLM/RAG läuft…';$('intent').textContent='…';$('dept').textContent='…';$('action').textContent='…';$('conf').textContent='…';try{const res=await fetch('/api/charly',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})});const data=await res.json();if(!res.ok)throw new Error(data.error||data.detail||'API not available');$('citizen').textContent=data.citizen_answer||data.answer||'Keine Antwort.';$('intent').textContent=data.intent||'–';$('dept').textContent=data.department||'–';$('action').textContent=data.action||'–';$('conf').textContent=String(data.confidence??'–');$('sources').innerHTML=(data.sources||data.retrieved||[]).map(s=>`<li><b>${esc(s.id)}</b><br>${esc(s.source||s.title||'')}</li>`).join('');$('steps').innerHTML=(data.next_steps||[]).map(s=>`<li>${esc(s)}</li>`).join('');$('receipt').innerHTML=`${esc(data.receipt||'')}${data.model?`<br><br><b>Model:</b> ${esc(data.model)} · <b>Provider:</b> ${esc(data.provider)}`:''}`}catch(e){$('citizen').textContent='Das Vercel-Backend ist hier noch nicht erreichbar. Lokal läuft die Demo trotzdem.';$('intent').textContent='local fallback';$('dept').textContent='–';$('action').textContent='lokal testen';$('conf').textContent='–';$('receipt').textContent='Für echten LLM-Modus: auf der Vercel-URL öffnen und OPENROUTER_API_KEY setzen. Fehler: '+e.message;renderLocal(q)}}
function runEval(){let ok=0;const items=EVAL.tests.map(t=>{const h=retrieve(t.q)[0],pass=h.topic===t.expectTopic&&h.action===t.expectAction;if(pass)ok++;return `<li>${pass?'✅':'⚠️'} ${esc(t.q)} → ${esc(h.topic)} / ${esc(h.action)}</li>`}).join('');$('receipt').innerHTML=`Eval Score: <b>${ok}/${EVAL.tests.length}</b><ul>${items}</ul>`}
function bind(){document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('question').value=b.dataset.q;renderLocal(b.dataset.q)});$('local').onclick=()=>renderLocal($('question').value);$('llm').onclick=()=>renderLlm($('question').value);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')renderLocal($('question').value)});document.querySelector('#proof .sendbox').addEventListener('click',runEval)}
document.addEventListener('DOMContentLoaded',async()=>{KB=await fetch('../zaitgeist-v2/knowledge.json').then(r=>r.json());EVAL=await fetch('../zaitgeist-v2/eval.json').then(r=>r.json());bind();renderLocal($('question').value)});