'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORAGE='hyperspace-out-of-panel-v5';let PORTABLE_SOURCE='<!doctype html>'+document.documentElement.outerHTML;const IS_PORTABLE=!document.querySelector('script[src]');
let localOK=true,persisted={};try{persisted=JSON.parse(localStorage.getItem(STORAGE)||localStorage.getItem('hyperspace-out-of-panel-v4')||localStorage.getItem('hyperspace-out-of-panel-v3')||'{}')||{}}catch{localOK=false}
if(typeof persisted!=='object'||Array.isArray(persisted))persisted={};
const session={returned:persisted.returned===true,discovered:persisted.discovered===true,taken:persisted.taken===true,page:Number.isInteger(persisted.page)&&persisted.page>=0&&persisted.page<8?persisted.page:0,sound:persisted.sound===true,reduced:persisted.reduced===true,surface:['paper','walnut','midnight'].includes(persisted.surface)?persisted.surface:'paper',completed:Math.max(0,Math.min(1e6,Number(persisted.completed)||0))};
const reduced=()=>session.reduced||matchMedia('(prefers-reduced-motion:reduce)').matches;
let view='encounter',dialogFocus=null,viewEpoch=0,toastTimer,gameReady=false;
$('#encounter-art').innerHTML=ENCOUNTER_ART;
const coinEl=$('#coin'),stage=$('#stage');let coinCanvas=$('#coin-canvas');coinCanvas.width=coinCanvas.height=512;let coinRenderer=CoinStudio.create(coinCanvas);coinCanvas=coinRenderer.canvas||coinCanvas;
let coin={x:0,y:0,size:150,tx:0,ty:0,ts:150,yaw:.18,pitch:-.25,roll:-.12,tyaw:.18,tpitch:-.25,troll:-.12,ink:session.taken?0:.92,tink:session.taken?0:.92,initialized:false,drag:null,renderDirty:true};
const dialog=$('#dialog'),readerDialog=$('#reader-dialog');
function announce(t){$('#live-action').textContent=t}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3800)}
function save(){if(!gameReady)return;try{localStorage.setItem(STORAGE,JSON.stringify({...session,game:packGame()}));localOK=true}catch{localOK=false}$('#save-status').textContent=localOK?'Your game stays on this device.':'Saving unavailable in this browser.';$('#reading-note').textContent=localOK?'Your place is saved on this device.':'Your place lasts for this visit only.'}
function download(name,data,type='application/octet-stream'){const a=document.createElement('a'),url=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function modal(html){dialogFocus=document.activeElement;$('#dialog-body').innerHTML=html;dialog.showModal();tickTime=performance.now();cancelAI();}
function closeModal(){dialog.close()}
$('#dialog-close').onclick=closeModal;
dialog.addEventListener('close',()=>{tickTime=performance.now();if(dialogFocus?.isConnected&&!dialogFocus.closest('[inert]'))dialogFocus.focus({preventScroll:true});scheduleAI()});
dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()});
async function copy(text,message='Copied. Ready to pass on.'){try{if(!navigator.clipboard)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(text);toast(message)}catch{modal('<p class="dialog-kicker">READY TO SHARE</p><h2 id="dialog-title">A little thing to pass on.</h2><p>Select and copy the text below. Nothing has been sent.</p><label class="form-field">YOUR MESSAGE<textarea id="copy-area" readonly></textarea></label>');$('#copy-area').value=text;$('#copy-area').focus();$('#copy-area').select()}}
let audioCtx;
function contact(kind='metal'){if(!session.sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();let t=audioCtx.currentTime;if(kind==='paper'){let n=audioCtx.createBuffer(1,audioCtx.sampleRate*.075,audioCtx.sampleRate),d=n.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()-.5)*Math.pow(1-i/d.length,2)*.08;let s=audioCtx.createBufferSource(),f=audioCtx.createBiquadFilter(),g=audioCtx.createGain();f.type='lowpass';f.frequency.value=1700;g.gain.value=.34;s.buffer=n;s.connect(f);f.connect(g);g.connect(audioCtx.destination);s.start();return}
 const base=kind==='wood'?330:kind==='win'?610:820;[1,2.17,3.43].forEach((m,i)=>{let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(base*m,t);o.frequency.exponentialRampToValueAtTime(base*m*.96,t+.11);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime((i===0?.07:.021)*(kind==='wood'?.7:1),t+.003);g.gain.exponentialRampToValueAtTime(.0001,t+(i===0?.22:.095));o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(t+.26)})}catch{}}
function updateSound(){const b=$('#sound-toggle');b.setAttribute('aria-pressed',String(session.sound));b.setAttribute('aria-label',session.sound?'Mute sound':'Enable sound');b.title=session.sound?'Sound is on':'Sound is off';b.innerHTML=session.sound?'<svg viewBox="0 0 24 24"><path d="M11 5L6 9H3v6h3l5 4V5ZM16 8q5 4 0 8m3-11q7 7 0 14"/></svg>':'<svg viewBox="0 0 24 24"><path d="M11 5L6 9H3v6h3l5 4V5ZM16 9l5 6m0-6-5 6"/></svg>'}
$('#sound-toggle').onclick=()=>{session.sound=!session.sound;updateSound();save();if(session.sound)contact('metal')};
function cancelDrag(){if(coin.drag){const d=coin.drag;coin.drag=null;coinEl.classList.remove('is-dragging');try{if(coinEl.hasPointerCapture(d.id))coinEl.releasePointerCapture(d.id)}catch{}}}
function syncEncounter(){document.body.classList.toggle('taken',session.taken);$('#speech').innerHTML=session.taken?'<span>Hey.</span><b>I was using that.</b><i aria-hidden="true"></i>':'<span>Psst.</span><b>Catch.</b><i aria-hidden="true"></i>';$('#speech').style.fontSize=session.taken?'11px':'';$('#speech b').style.fontSize=session.taken?'13px':'';coinEl.setAttribute('aria-label',view==='object'?'First Light coin. Drag or use arrow keys to rotate.':session.taken?'Inspect the First Light coin':'Take the coin out of the comic')}
function activateCopy(id){$$('.copy-panel').forEach(p=>{let a=p.id===id;p.classList.toggle('active',a);p.inert=!a})}
function switchView(next,{focus=false,scroll=true}={}){if(!['encounter','play','read','object','return'].includes(next))return;const previous=view;view=next;viewEpoch++;cancelDrag();cancelAI();tickTime=performance.now();if(next==='play'||next==='object'||next==='return'){session.taken=true;coin.tink=0}document.body.dataset.view=next;document.body.classList.toggle('reduce-motion',session.reduced);syncEncounter();activateCopy(next==='encounter'?(session.taken?'taken-copy':'intro-copy'):next+'-copy');$$('.scene').forEach(el=>{const is=el.id===(next==='play'?'game-scene':next==='object'?'object-scene':next==='read'?'read-scene':next==='return'?'return-scene':'encounter-scene');el.classList.toggle('active',is);el.inert=!is});$$('.main-nav [data-view]').forEach(b=>{if(b.dataset.view===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$$('.step').forEach(b=>b.classList.toggle('active',b.dataset.view===next));coinEl.tabIndex=next==='read'?-1:0;
 if(next==='object'){coin.tyaw=.28;coin.tpitch=-.22;coin.troll=-.06;$('#renderer-note').textContent=coinRenderer.kind==='WebGL'?'LIVE 3D · STUDIO LIGHTING':'SOFTWARE 3D · NO GPU REQUIRED'}
 if(next==='return'){coin.tyaw=.1;coin.tpitch=-.08;coin.troll=-.04}
 if(next==='play'){coin.tyaw=.08;coin.tpitch=-.13;coin.troll=0;resizeBoard();scheduleAI()}if(next==='read')renderComic();positionCoin();save();window.dispatchEvent(new CustomEvent('oop-view',{detail:{view:next}}));
 if(focus){const epoch=viewEpoch;setTimeout(()=>{if(epoch!==viewEpoch)return;const el=next==='play'?$('#board'):next==='read'?$('#next-page'):next==='object'?coinEl:session.taken?$('#first-move'):$('#take-coin');el?.focus({preventScroll:true})},reduced()?0:400)}
 if(scroll&&innerWidth<=760&&previous!==next)window.scrollTo({top:0,behavior:reduced()?'instant':'smooth'});
}
$$('button[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
function initialAnchor(){const r=stage.getBoundingClientRect(),svg=$('#encounter-art svg');try{let p=svg.createSVGPoint();p.x=268;p.y=659;let t=p.matrixTransform(svg.getScreenCTM());return{x:t.x-r.left,y:t.y-r.top,size:Math.max(105,Math.min(177,r.width*.23))}}catch{return{x:r.width*.65,y:r.height*.69,size:140}}}
function positionCoin(){if(coin.drag)return;const r=stage.getBoundingClientRect();let p;if(view==='encounter'){p=!session.taken?initialAnchor():{x:r.width*.78,y:r.height*.77,size:Math.max(129,Math.min(200,r.width*.28))};coin.tink=session.taken?0:.92}
 else if(view==='play'){const a=$('#game-coin-anchor').getBoundingClientRect();p={x:a.left+a.width/2-r.left,y:a.top+a.height/2-r.top,size:innerWidth<=760?43:63}}
 else if(view==='return'){const b=stage.getBoundingClientRect();const t=$('#return-target').getBoundingClientRect();p=session.returned?{x:t.x+t.width/2-b.x,y:t.y+t.height/2-b.y,size:t.width*1.35}:{x:r.width*.82,y:r.height*.81,size:Math.max(112,Math.min(170,r.width*.27))}}
 else if(view==='object'&&document.body.classList.contains('world-open')){p={x:r.width*.17,y:r.height*.76,size:Math.min(160,r.width*.27)}}
 else if(view==='object'){p={x:r.width*.5,y:r.height*.425,size:Math.min(r.width*.82,r.height*.67,510)}}else p={x:coin.x,y:coin.y,size:coin.size};
 coin.tx=p.x;coin.ty=p.y;coin.ts=p.size;if(!coin.initialized||reduced()){coin.x=coin.tx;coin.y=coin.ty;coin.size=coin.ts;coin.initialized=true}coin.renderDirty=true;}
function takeCoin(at=null){if(view!=='encounter')return;if(!session.taken){session.taken=true;syncEncounter();activateCopy('taken-copy');contact('paper');announce('You took the coin out of the comic. Now make your first move, or inspect it.');save()}coin.tink=0;coin.tyaw=.3;coin.tpitch=-.24;coin.troll=-.08;coin.ts=Math.max(129,Math.min(200,stage.clientWidth*.28));if(at){coin.tx=at.x;coin.ty=at.y;coin.x=at.x;coin.y=at.y}else positionCoin();coin.renderDirty=true;}
$('#take-coin').onclick=()=>takeCoin();$('#first-move').onclick=()=>switchView('play',{focus:true});$('#reset-encounter').onclick=()=>{cancelDrag();session.taken=false;coin.tink=.92;coin.tyaw=.18;coin.tpitch=-.25;coin.troll=-.12;syncEncounter();activateCopy('intro-copy');positionCoin();announce('The coin is back in the page.');save()};
let suppressedClick=false;
coinEl.addEventListener('pointerdown',e=>{if(coin.drag||e.button!==0||view==='read'||(view==='return'&&session.returned))return;const r=stage.getBoundingClientRect();coin.drag={id:e.pointerId,mode:view,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,t:performance.now(),origin:{x:coin.x,y:coin.y,yaw:coin.tyaw,pitch:coin.tpitch},dx:0,dy:0,moved:false,wasTaken:session.taken};coinEl.setPointerCapture(e.pointerId);coinEl.classList.add('is-dragging');e.preventDefault()});
coinEl.addEventListener('pointermove',e=>{const d=coin.drag;if(!d||d.id!==e.pointerId)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.hypot(dx,dy)>5)d.moved=true;if(d.mode==='object'){coin.tyaw=d.origin.yaw+dx*.009;coin.tpitch=Math.max(-1.1,Math.min(1.1,d.origin.pitch+dy*.007))}else if(d.mode==='encounter'||d.mode==='return'){const pad=coin.size*.26;coin.x=coin.tx=Math.max(pad,Math.min(stage.clientWidth-pad,d.origin.x+dx));coin.y=coin.ty=Math.max(pad,Math.min(stage.clientHeight-pad,d.origin.y+dy));coin.tyaw=.18+Math.max(-.4,Math.min(.4,dx*.002));coin.tpitch=-.25+Math.max(-.2,Math.min(.2,dy*.001));coin.tink=d.wasTaken?0:Math.max(0,.92-Math.hypot(dx,dy)/92);coin.ink=coin.tink;}d.dx=e.clientX-d.lastX;d.dy=e.clientY-d.lastY;d.lastX=e.clientX;d.lastY=e.clientY;d.t=performance.now();coin.renderDirty=true});
function releaseCoin(e,cancel=false){const d=coin.drag;if(!d||d.id!==e.pointerId)return;coin.drag=null;coinEl.classList.remove('is-dragging');if(coinEl.hasPointerCapture(e.pointerId))coinEl.releasePointerCapture(e.pointerId);suppressedClick=true;setTimeout(()=>suppressedClick=false,100);
 if(cancel){coin.tyaw=d.origin.yaw;coin.tpitch=d.origin.pitch;if(d.mode==='encounter'||d.mode==='return'){coin.tx=d.origin.x;coin.ty=d.origin.y;coin.tink=d.wasTaken?0:.92}coin.renderDirty=true;return}
 if(d.mode==='return'){const r=$('#return-target').getBoundingClientRect(),s=stage.getBoundingClientRect();const distance=Math.hypot(coin.x-(r.x+r.width/2-s.x),coin.y-(r.y+r.height/2-s.y));if(distance<Math.max(54,r.width*.85)||!d.moved)window.OutOfPanelWonder?.giveBack();else positionCoin();return}
 if(d.mode==='object'){if(!d.moved)flipObject();return}if(d.mode==='play'){switchView('object');return}
 if(d.moved){const dist=Math.hypot(coin.x-d.origin.x,coin.y-d.origin.y);if(dist>20||d.wasTaken){takeCoin({x:coin.x,y:coin.y});const fresh=performance.now()-d.t<70;if(fresh){coin.tyaw+=Math.max(-.13,Math.min(.13,d.dx*.012));coin.tpitch+=Math.max(-.07,Math.min(.07,d.dy*.008))}contact('metal')}else positionCoin()}else if(session.taken)switchView('object');else takeCoin();
}
coinEl.addEventListener('pointerup',e=>releaseCoin(e));coinEl.addEventListener('pointercancel',e=>releaseCoin(e,true));coinEl.addEventListener('lostpointercapture',e=>{if(coin.drag?.id===e.pointerId)releaseCoin(e,true)});
coinEl.addEventListener('click',e=>{if(suppressedClick||e.detail!==0)return;if(view==='return')window.OutOfPanelWonder?.giveBack();else if(view==='object')flipObject();else if(session.taken)switchView('object');else takeCoin()});
coinEl.addEventListener('keydown',e=>{if(view==='object'&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')coin.tyaw-=.25;if(e.key==='ArrowRight')coin.tyaw+=.25;if(e.key==='ArrowUp')coin.tpitch=Math.max(-1.1,coin.tpitch-.16);if(e.key==='ArrowDown')coin.tpitch=Math.min(1.1,coin.tpitch+.16);coin.renderDirty=true}});
function flipObject(){coin.tyaw+=Math.PI;coin.tpitch=-.18;coin.renderDirty=true;contact('metal');announce('Coin turned over.')}
$('#flip-object').onclick=flipObject;$('#rotate-left').onclick=()=>{coin.tyaw-=.45;coin.renderDirty=true};$('#rotate-right').onclick=()=>{coin.tyaw+=.45;coin.renderDirty=true};
$('#export-object').onclick=async()=>{try{const b=$('#export-object');b.disabled=true;const data=await CoinStudio.exportGLB();download('FIRST-LIGHT-Object-Study-002.glb',data,'model/gltf-binary');toast('3D design saved. A visual model, not manufacturing CAD.');b.disabled=false}catch{$('#export-object').disabled=false;toast('Export did not complete. Your game and story are unaffected.')}};
stage.addEventListener('renderer-lost',()=>toast('3D rendering paused. The game and comic remain available. Reload to restore the object.'));
const resizeObs=new ResizeObserver(()=>{positionCoin();if(gameReady)resizeBoard()});resizeObs.observe(stage);matchMedia('(prefers-reduced-motion:reduce)').addEventListener('change',()=>{coin.renderDirty=true;positionCoin()});
let lastFrame=performance.now(),boardAnim=false;
let frameRequest;
function frame(t){frameRequest=requestAnimationFrame(frame);if(document.hidden)return;const dt=Math.max(0,(t-lastFrame)/1000);lastFrame=t;const k=reduced()?1:1-Math.exp(-dt*9.8),r=reduced()?1:1-Math.exp(-dt*12);let moving=false;for(const [key,tar]of[['x','tx'],['y','ty'],['size','ts']]){const delta=coin[tar]-coin[key];if(Math.abs(delta)>.03){coin[key]+=delta*k;moving=true}else coin[key]=coin[tar]}for(const[key,tar]of[['yaw','tyaw'],['pitch','tpitch'],['roll','troll'],['ink','tink']]){const d=coin[tar]-coin[key];if(Math.abs(d)>.0008){coin[key]+=d*r;moving=true}else coin[key]=coin[tar]}
 if(view!=='read'&&(moving||coin.renderDirty)){coinEl.style.left=coin.x+'px';coinEl.style.top=coin.y+'px';coinEl.style.width=coin.size+'px';coinEl.style.height=coin.size+'px';const res=Math.max(192,Math.min(720,Math.ceil(coin.size*Math.min(devicePixelRatio||1,1.65))));if(Math.abs(coinCanvas.width-res)>28){coinCanvas.width=coinCanvas.height=res}if(!(view==='object'&&document.body.classList.contains('journey-ready')))coinRenderer.render(coin.yaw,coin.pitch,coin.ink,0,coin.roll);coin.renderDirty=false}window.OutOfPanelJourney ? window.OutOfPanelJourney.tick(t) : window.OutOfPanelWonder?.tick(t);if(gameReady&&view==='play'&&boardAnim)drawBoard(t);
}frameRequest=requestAnimationFrame(frame);document.addEventListener('visibilitychange',()=>{cancelAnimationFrame(frameRequest);if(!document.hidden){lastFrame=performance.now();frameRequest=requestAnimationFrame(frame)}});
// ---- Infinite Four: validated integer grid, bounded casual matches; no remote opponent. ----
const dirs=[[1,0],[0,1],[1,1],[1,-1]],key=(x,y)=>x+','+y;
function winAt(b,x,y,p){for(const[dx,dy]of dirs){let a=[[x,y]];for(const s of[-1,1])for(let i=1;i<=3;i++){const xx=x+dx*i*s,yy=y+dy*i*s;if(b.get(key(xx,yy))!==p)break;a.push([xx,yy])}if(a.length>=4)return a}return null}
function urgency(b,x,y,p){let score=0;for(const[dx,dy]of dirs)for(let start=-3;start<=0;start++){let own=0,other=0;for(let n=0;n<4;n++){const q=b.get(key(x+(start+n)*dx,y+(start+n)*dy));if(q===p)own++;else if(q)other++}if(!other)score+=[1,5,65,5000,1e8][own];if(!own)score+=[0,4,52,4500,9e7][other]}return score}
function candidates(b,p,limit=10){if(!b.size)return[{x:0,y:0,s:0}];const m=new Map();for(const k of b.keys()){const[x,y]=k.split(',').map(Number);for(let dx=-2;dx<=2;dx++)for(let dy=-2;dy<=2;dy++){const xx=x+dx,yy=y+dy,kk=key(xx,yy);if(!b.has(kk)&&!m.has(kk))m.set(kk,{x:xx,y:yy,s:urgency(b,xx,yy,p)})}}return[...m.values()].sort((a,b)=>b.s-a.s||Math.abs(a.x)+Math.abs(a.y)-Math.abs(b.x)-Math.abs(b.y)).slice(0,limit)}
function randomInt(n){if(!Number.isSafeInteger(n)||n<1||n>0x100000000)throw new RangeError('Invalid range');const max=Math.floor(0x100000000/n)*n,a=new Uint32Array(1);do{crypto.getRandomValues(a)}while(a[0]>=max);return a[0]%n}
function chooseAI(b,level){const cs=candidates(b,2,level==='easy'?20:12);for(const c of cs){b.set(key(c.x,c.y),2);const win=winAt(b,c.x,c.y,2);b.delete(key(c.x,c.y));if(win)return c}let block=null;for(const c of cs){b.set(key(c.x,c.y),1);const win=winAt(b,c.x,c.y,1);b.delete(key(c.x,c.y));if(win){block=c;break}}if(block&&(level!=='easy'||randomInt(4)!==0))return block;if(level==='easy')return cs[randomInt(Math.min(10,cs.length))];if(level==='medium')return cs[0];const end=performance.now()+130,depth=level==='expert'?4:3;let best=cs[0],bestScore=-Infinity;const evaluate=()=>{const own=candidates(b,2,1)[0],opp=candidates(b,1,1)[0];return(own?.s||0)-(opp?.s||0)*1.06};function search(d,p,alpha,beta){if(!d||performance.now()>end)return evaluate();const picks=candidates(b,p,d>2?6:5);let val=p===2?-Infinity:Infinity;for(const c of picks){const k=key(c.x,c.y);b.set(k,p);const win=winAt(b,c.x,c.y,p);let v=win?(p===2?1:-1)*(1e7+d*1e4):search(d-1,3-p,alpha,beta);b.delete(k);if(p===2){val=Math.max(val,v);alpha=Math.max(alpha,v)}else{val=Math.min(val,v);beta=Math.min(beta,v)}if(beta<=alpha||performance.now()>end)break}return val}for(const c of cs.slice(0,8)){const k=key(c.x,c.y);b.set(k,2);const s=search(depth-1,1,-Infinity,Infinity);b.delete(k);if(s>bestScore){bestScore=s;best=c}if(performance.now()>end)break}return best}
const board=$('#board'),ctx=board.getContext('2d');let sprites;try{sprites=CoinStudio.getSprites()}catch{sprites=null}
let cells=new Map(),moves=[],turn=1,winner=0,winLine=[],gameMode='solo',difficulty='medium',clockMode='off',seconds=[Infinity,Infinity],increment=0,started=false,gameVersion=0,aiPending=false,aiTimer=null,aiWorker=null,workerTimeout=null,tickTime=performance.now(),tickSave=0,pan={x:0,y:0},scale=48,cursor={x:0,y:0},boardPointer=null,lastPlacement=null,resultHidden=false;
const dpr=()=>Math.min(devicePixelRatio||1,2);
function packGame(){return{v:3,moves:moves.map(m=>[m.x,m.y]),mode:gameMode,difficulty,clock:clockMode,seconds:seconds.map(n=>Number.isFinite(n)?n:null),winner,pan,scale}}
function parseGame(g){if(!g||typeof g!=='object'||!Array.isArray(g.moves)||g.moves.length>120)throw new Error('Invalid match');const b=new Map(),ms=[];let p=1,w=0,line=[];for(const m of g.moves){if(w||!Array.isArray(m)||m.length!==2||!m.every(n=>Number.isSafeInteger(n)&&Math.abs(n)<=1e6)||b.has(key(...m)))throw new Error('Invalid position');b.set(key(...m),p);ms.push({x:m[0],y:m[1],p});const l=winAt(b,...m,p);if(l){w=p;line=l}p=3-p}if(!w&&ms.length===120)w=3;return{b,ms,p,w,line}}
function restoreGame(g){try{const parsed=parseGame(g);cancelAI();cells=parsed.b;moves=parsed.ms;turn=parsed.p;winner=parsed.w;winLine=parsed.line;gameMode=['solo','local'].includes(g.mode)?g.mode:'solo';difficulty=['easy','medium','hard','expert'].includes(g.difficulty)?g.difficulty:'medium';clockMode=['off','3+2','5+3'].includes(g.clock)?g.clock:'off';const base=clockMode==='3+2'?180:clockMode==='5+3'?300:Infinity;increment=clockMode==='3+2'?2:clockMode==='5+3'?3:0;seconds=[0,1].map(i=>Number.isFinite(base)&&Array.isArray(g.seconds)&&Number.isFinite(g.seconds[i])&&g.seconds[i]>=0&&g.seconds[i]<=36000?g.seconds[i]:base);if(!winner&&clockMode!=='off'&&seconds[turn-1]===0)winner=3-turn;if(!winner&&[1,2].includes(g.winner)&&clockMode!=='off'&&seconds[3-g.winner-1]===0)winner=g.winner;started=moves.length>0;pan=g.pan&&Number.isFinite(g.pan.x)&&Math.abs(g.pan.x)<1e7&&Number.isFinite(g.pan.y)&&Math.abs(g.pan.y)<1e7?g.pan:{x:0,y:0};scale=Number.isFinite(g.scale)?Math.max(24,Math.min(84,g.scale)):innerWidth<=760?36:48;resultHidden=true;return true}catch{return false}}
function resetGame(){cancelAI();cells=new Map();moves=[];turn=1;winner=0;winLine=[];pan={x:0,y:0};cursor={x:0,y:0};scale=innerWidth<=760?36:48;started=false;resultHidden=false;lastPlacement=null;const b=clockMode==='3+2'?180:clockMode==='5+3'?300:Infinity;increment=clockMode==='3+2'?2:clockMode==='5+3'?3:0;seconds=[b,b];tickTime=performance.now();$('#board-result').hidden=true;renderGame();drawBoard();save()}
function cancelAI(){gameVersion++;clearTimeout(aiTimer);clearTimeout(workerTimeout);if(aiWorker){aiWorker.terminate();aiWorker=null}aiPending=false}
function finish(p,reason='line'){winner=p;cancelAI();resultHidden=false;session.completed++;$('#result-kicker').textContent=reason==='clock'?'TIME, WELL SPENT.':'A LITTLE CONNECTION.';$('#result-title').textContent=p===3?'A shared horizon.':gameMode==='local'?(p===1?'First Light found it.':'Still Water found it.'):p===1?'You found it.':'A different ending.';$('#result-copy').textContent=reason==='clock'?'The clock reached zero. Ready for another?':p===3?'120 moves. Let’s call this one a draw.':'Four in a row. A small, good thing.';$('#board-result').hidden=false;contact('win');renderGame();boardAnim=true;drawBoard();save()}
function applyMove(x,y,{fromAI=false}={}){if(winner||!Number.isSafeInteger(x)||!Number.isSafeInteger(y)||Math.abs(x)>1e6||Math.abs(y)>1e6||cells.has(key(x,y))||(!fromAI&&gameMode==='solo'&&(turn===2||aiPending)))return false;const p=turn;cells.set(key(x,y),p);moves.push({x,y,p});started=true;seconds[p-1]+=increment;lastPlacement={x,y,p,time:performance.now()};cursor={x,y};contact(session.surface==='walnut'?'wood':'metal');const w=winAt(cells,x,y,p);if(w){winLine=w;finish(p);return true}if(moves.length>=120){finish(3);return true}turn=3-turn;tickTime=performance.now();boardAnim=true;renderGame();drawBoard();save();scheduleAI();return true}
function place(x,y){return applyMove(x,y)}
function scheduleAI(){if(!gameReady||gameMode!=='solo'||turn!==2||winner||aiPending||view!=='play'||document.hidden||dialog.open||readerDialog.open)return;aiPending=true;renderGame();const version=gameVersion;aiTimer=setTimeout(()=>{if(version!==gameVersion)return;const done=c=>{if(version!==gameVersion)return;clearTimeout(workerTimeout);if(aiWorker){aiWorker.terminate();aiWorker=null}aiPending=false;if(view!=='play'||document.hidden||dialog.open||readerDialog.open){renderGame();return}if(c)applyMove(c.x,c.y,{fromAI:true});else{renderGame();toast('The other side paused. Undo or start a new round.')}};
 const fallback=()=>{if(version!==gameVersion)return;done(chooseAI(new Map(cells),'medium'))};
 try{const code='const dirs='+JSON.stringify(dirs)+';const key=(x,y)=>x+","+y;'+[winAt,urgency,candidates,randomInt,chooseAI].map(f=>f.toString()).join('\n')+';onmessage=e=>{try{postMessage(chooseAI(new Map(e.data.cells),e.data.level))}catch{postMessage(null)}};';const url=URL.createObjectURL(new Blob([code],{type:'application/javascript'}));aiWorker=new Worker(url);URL.revokeObjectURL(url);aiWorker.onmessage=e=>done(e.data||candidates(cells,2,1)[0]);aiWorker.onerror=()=>{fallback()};workerTimeout=setTimeout(fallback,1800);aiWorker.postMessage({cells:[...cells],level:difficulty})}catch{fallback()}
 },reduced()?60:350)}
function renderGame(){let text=winner?(winner===3?'A draw. A good place to begin again.':gameMode==='local'?(winner===1?'First Light connects four.':'Still Water connects four.'):winner===1?'Four connected. That was yours.':'The other side connected four.'):aiPending?'The other side is thinking…':gameMode==='solo'&&turn===2?'The other side resumes when you return.':gameMode==='local'?(turn===1?'First Light to move.':'Still Water to move.'):(moves.length?'Your move. Find the connection.':'Your move. Begin anywhere.');$('#game-status').textContent=text;$('#move-number').textContent='MOVE '+String(Math.min(moves.length+1,120)).padStart(2,'0');$('#board-empty').hidden=moves.length>0;$('#player-one').classList.toggle('active',turn===1&&!winner);$('#player-two').classList.toggle('active',turn===2&&!winner);$('#player-one-name').textContent=gameMode==='local'?'First Light':'You';$('#player-two-name').textContent=gameMode==='local'?'Still Water':'The other side';$('#opponent-label').textContent=gameMode==='local'?'Local pass & play':({easy:'Easygoing',medium:'Thoughtful',hard:'Challenging',expert:'Expert'})[difficulty]+' · computer';$('#undo').disabled=moves.length===0;updateClocks();if(!winner||resultHidden)$('#board-result').hidden=true}
function updateClocks(){[0,1].forEach(i=>{let s=seconds[i];$('#clock-'+(i===0?'one':'two')).textContent=Number.isFinite(s)?Math.floor(Math.ceil(Math.max(0,s))/60)+':'+String(Math.ceil(Math.max(0,s))%60).padStart(2,'0'):'∞'})}
setInterval(()=>{const now=performance.now(),dt=Math.min((now-tickTime)/1000,2);tickTime=now;if(!gameReady||view!=='play'||document.hidden||dialog.open||readerDialog.open||winner||!started)return;seconds[turn-1]-=dt;if(seconds[turn-1]<=0){seconds[turn-1]=0;finish(3-turn,'clock')}updateClocks();if(now-tickSave>4000){tickSave=now;save()}},100);
document.addEventListener('visibilitychange',()=>{tickTime=performance.now();lastFrame=performance.now();if(document.hidden){cancelAI();save()}else{coin.renderDirty=true;scheduleAI()}});window.addEventListener('pagehide',save);
function newGame(){if(moves.length&&!winner){modal('<p class="dialog-kicker">A NEW BEGINNING</p><h2 id="dialog-title">A clean slate?</h2><p>This replaces your current local match. The comic and your preferences stay.</p><div class="row"><button id="confirm-new" class="primary">Start fresh ↗</button><button id="keep-playing" class="outline-btn">Keep playing</button></div>');$('#confirm-new').onclick=()=>{resetGame();closeModal()};$('#keep-playing').onclick=closeModal}else resetGame()}
$('#new-game').onclick=newGame;$('#result-again').onclick=resetGame;$('#result-dismiss').onclick=()=>{resultHidden=true;$('#board-result').hidden=true;board.focus()};
$('#undo').onclick=()=>{cancelAI();let count=gameMode==='solo'&&moves.length>1&&moves[moves.length-1].p===2?2:1;for(let i=0;i<count&&moves.length;i++){const m=moves.pop();cells.delete(key(m.x,m.y));turn=m.p}winner=0;winLine=[];lastPlacement=null;resultHidden=true;started=moves.length>0;tickTime=performance.now();renderGame();drawBoard();save();scheduleAI();announce('Last turn undone. Practice clocks are not restored.')};
$('#game-settings').onclick=()=>{modal('<p class="dialog-kicker">MAKE YOURSELF AT HOME</p><h2 id="dialog-title">Your kind of game.</h2><label class="form-field">PLAY WITH<select id="setting-mode"><option value="solo">The computer</option><option value="local">A friend, on this device</option></select></label><label class="form-field">DIFFICULTY<select id="setting-difficulty"><option value="easy">Easy · a gentle beginning</option><option value="medium">Medium · thoughtful</option><option value="hard">Hard · look ahead</option><option value="expert">Expert · a sharper challenge</option></select></label><label class="form-field">PACE<select id="setting-clock"><option value="off">Unhurried · no clock</option><option value="3+2">3 minutes + 2 seconds per move</option><option value="5+3">5 minutes + 3 seconds per move</option></select></label><p class="form-note">Applying changed rules starts a new match. Expert is a heuristic opponent, not proven optimal. Clocks pause away from the game; undo is for practice.</p><button class="primary" id="apply-settings">Set the table ↗</button>');$('#setting-mode').value=gameMode;$('#setting-difficulty').value=difficulty;$('#setting-clock').value=clockMode;$('#setting-difficulty').disabled=gameMode==='local';$('#setting-mode').onchange=e=>$('#setting-difficulty').disabled=e.target.value==='local';$('#apply-settings').onclick=()=>{const m=$('#setting-mode').value,d=$('#setting-difficulty').value,c=$('#setting-clock').value;const changed=m!==gameMode||d!==difficulty||c!==clockMode;gameMode=m;difficulty=d;clockMode=c;if(changed)resetGame();closeModal();renderGame();save()}};
$('#game-rules').onclick=()=>modal('<p class="dialog-kicker">INFINITE FOUR / HOW TO PLAY</p><h2 id="dialog-title">Four. Anywhere.</h2><p>Take turns placing a coin on an empty intersection. Connect four or more consecutive coins horizontally, vertically or diagonally to win. There is no gravity and no fixed board edge.</p><p><strong>Touch or mouse:</strong> tap to place, drag the board to explore. Use + and − to zoom, or ⌖ to return to the opening.</p><p><strong>Keyboard:</strong> focus the board, use the arrow keys to choose an intersection, then press Enter or Space to place. + and − zoom; Home centres.</p><p>Each casual match ends after 120 moves if no one has won. Undo is a practice aid and does not restore spent time. The computer is a local heuristic—not an online person or an unbeatable solver.</p><p class="legal-note">A playable prototype. No stakes, gambling, payouts or ownership claims.</p>');
function resizeBoard(){const r=board.getBoundingClientRect();if(!r.width||!r.height)return;const d=dpr();board.width=Math.round(r.width*d);board.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);drawBoard()}
const patterns={};function grainPattern(surface){if(patterns[surface])return patterns[surface];const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');let seed=31;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647};for(let i=0;i<2000;i++){x.fillStyle=surface==='midnight'?`rgba(165,180,139,${rand()*.025})`:`rgba(37,50,23,${rand()*.033})`;x.fillRect(rand()*256,rand()*256,rand()*2+1,rand()*1.5+.3)}if(surface==='walnut'){for(let i=0;i<256;i+=3){x.strokeStyle=`rgba(41,30,19,${.03+rand()*.1})`;x.lineWidth=rand()+.4;x.beginPath();x.moveTo(0,i);x.bezierCurveTo(80,i-5,160,i+7,256,i);x.stroke()}}patterns[surface]=ctx.createPattern(c,'repeat');return patterns[surface]}
function drawBoard(now=performance.now()){const w=board.clientWidth,h=board.clientHeight;if(!w||!h)return;const surf=session.surface,d=dpr();ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const pal={paper:['#e7dfc8','#d7cfb6','#68784e','#6c765339'],walnut:['#947454','#705435','#eadcc0','#261a1150'],midnight:['#2a4034','#1c3028','#acba8a','#c2cbaa1e']}[surf];const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,pal[0]);bg.addColorStop(1,pal[1]);ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.fillStyle=grainPattern(surf);ctx.fillRect(0,0,w,h);const ox=w/2+pan.x,oy=h/2+pan.y;ctx.strokeStyle=pal[3];ctx.lineWidth=.65;ctx.beginPath();for(let x=((ox%scale)+scale)%scale;x<w;x+=scale){ctx.moveTo(x,0);ctx.lineTo(x,h)}for(let y=((oy%scale)+scale)%scale;y<h;y+=scale){ctx.moveTo(0,y);ctx.lineTo(w,y)}ctx.stroke();ctx.fillStyle=pal[2];ctx.globalAlpha=.22;for(let x=((ox%(scale*4))+scale*4)%(scale*4);x<w;x+=scale*4)for(let y=((oy%(scale*4))+scale*4)%(scale*4);y<h;y+=scale*4){ctx.beginPath();ctx.arc(x,y,1.6,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
 boardAnim=false;for(const m of moves){let x=ox+m.x*scale,y=oy+m.y*scale;if(x<-scale||x>w+scale||y<-scale||y>h+scale)continue;const isLast=lastPlacement&&lastPlacement.x===m.x&&lastPlacement.y===m.y,elapsed=isLast?now-lastPlacement.time:1e4;let a=reduced()?1:Math.min(1,elapsed/280);if(a<1)boardAnim=true;const ease=1-Math.pow(1-a,3),size=scale*1.06*(1+.18*(1-ease));ctx.save();ctx.globalAlpha=Math.min(1,a*3+.2);ctx.shadowColor=surf==='midnight'?'#02070499':'#222b1b55';ctx.shadowBlur=3+(1-ease)*9;ctx.shadowOffsetY=2+(1-ease)*9;
 if(sprites)ctx.drawImage(sprites[m.p-1],x-size/2,y-size/2-(1-ease)*12,size,size);else{ctx.fillStyle=m.p===1?'#bda165':'#537763';ctx.beginPath();ctx.arc(x,y,scale*.34,0,Math.PI*2);ctx.fill()}ctx.restore();
 const winning=winLine.some(p=>p[0]===m.x&&p[1]===m.y);if(winning){ctx.strokeStyle=surf==='midnight'?'#e4c27a':'#7e7748';ctx.lineWidth=1.4;ctx.beginPath();ctx.arc(x,y,scale*.40,0,Math.PI*2);ctx.stroke()}if(m===moves[moves.length-1]&&!winning){ctx.fillStyle=surf==='midnight'?'#c6cfb1':'#5b6446';ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(x,y+scale*.43,1.6,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}}
 if(cursor&&!winner&&!aiPending&&!(gameMode==='solo'&&turn===2)&&!cells.has(key(cursor.x,cursor.y))){const x=ox+cursor.x*scale,y=oy+cursor.y*scale;ctx.save();ctx.globalAlpha=document.activeElement===board?.57:.25;ctx.strokeStyle=pal[2];ctx.lineWidth=1;ctx.setLineDash([2,3]);ctx.beginPath();ctx.arc(x,y,scale*.34,0,Math.PI*2);ctx.stroke();ctx.restore()}
 $('#board-empty').style.opacity=moves.length?'0':'.75';
}
function boardPoint(e){const r=board.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function gridPoint(p){return{x:Math.round((p.x-board.clientWidth/2-pan.x)/scale),y:Math.round((p.y-board.clientHeight/2-pan.y)/scale)}}
board.addEventListener('pointerdown',e=>{if(boardPointer||e.button!==0)return;const p=boardPoint(e);boardPointer={id:e.pointerId,start:p,last:p,drag:false,pan:{...pan}};board.setPointerCapture(e.pointerId);board.focus({preventScroll:true})});
board.addEventListener('pointermove',e=>{const p=boardPoint(e);if(boardPointer){const q=boardPointer;if(q.id!==e.pointerId)return;const dist=Math.hypot(p.x-q.start.x,p.y-q.start.y);if(dist>7)q.drag=true;if(q.drag){pan.x=Math.max(-1e7,Math.min(1e7,q.pan.x+p.x-q.start.x));pan.y=Math.max(-1e7,Math.min(1e7,q.pan.y+p.y-q.start.y))}q.last=p}cursor=gridPoint(p);drawBoard()});
function boardRelease(e,cancel=false){const p=boardPointer;if(!p||p.id!==e.pointerId)return;boardPointer=null;if(board.hasPointerCapture(e.pointerId))board.releasePointerCapture(e.pointerId);if(!cancel&&!p.drag){const g=gridPoint(boardPoint(e));place(g.x,g.y)}else if(cancel){pan=p.pan;drawBoard()}save()}
board.addEventListener('pointerup',e=>boardRelease(e));board.addEventListener('pointercancel',e=>boardRelease(e,true));board.addEventListener('lostpointercapture',e=>{if(boardPointer?.id===e.pointerId)boardRelease(e,true)});board.addEventListener('pointerleave',()=>{if(!boardPointer&&document.activeElement!==board){cursor=null;drawBoard()}});
function zoom(f){const before=scale;scale=Math.max(24,Math.min(84,scale*f));pan.x*=scale/before;pan.y*=scale/before;drawBoard();save()}
$('#zoom-in').onclick=()=>zoom(1.18);$('#zoom-out').onclick=()=>zoom(1/1.18);$('#recenter').onclick=()=>{pan={x:0,y:0};cursor={x:0,y:0};drawBoard();save()};
board.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey)return;e.preventDefault();zoom(e.deltaY<0?1.06:1/1.06)},{passive:false});
board.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter',' ','+','=','-','Home'].includes(e.key))e.preventDefault();cursor=cursor||{x:0,y:0};if(e.key==='ArrowLeft')cursor.x--;if(e.key==='ArrowRight')cursor.x++;if(e.key==='ArrowUp')cursor.y--;if(e.key==='ArrowDown')cursor.y++;if(e.key==='Enter'||e.key===' ')place(cursor.x,cursor.y);if(e.key==='+'||e.key==='=')zoom(1.18);if(e.key==='-')zoom(1/1.18);if(e.key==='Home'){pan={x:0,y:0};cursor={x:0,y:0}}const x=board.clientWidth/2+pan.x+cursor.x*scale,y=board.clientHeight/2+pan.y+cursor.y*scale;if(x<scale)pan.x+=scale-x;if(x>board.clientWidth-scale)pan.x-=x-(board.clientWidth-scale);if(y<scale)pan.y+=scale-y;if(y>board.clientHeight-scale)pan.y-=y-(board.clientHeight-scale);drawBoard();if(e.key.startsWith('Arrow'))announce('Intersection '+cursor.x+', '+cursor.y+'. '+(cells.has(key(cursor.x,cursor.y))?'Occupied.':'Empty.'))});board.addEventListener('focus',()=>drawBoard());board.addEventListener('blur',()=>drawBoard());
$$('[data-surface]').forEach(b=>b.onclick=()=>{session.surface=b.dataset.surface;$$('[data-surface]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));$('#board-frame').style.borderColor=session.surface==='paper'?'#b3a57e':session.surface==='walnut'?'#7e694e':'#52614b';drawBoard();save()});
// ---- The reading edition: crisp editable SVG, page persistence, optional zoom. ----
const comicNames=['Front cover','Before the beginning','A long night','An unlikely landing','First day','Something small','A beginning','Back cover'];
function pageSVG(n,suffix){return COMIC_PAGES[n].replace(/id="([^"]+)"/g,(_,id)=>`id="${id}-${suffix}"`).replace(/url\(#([^\)]+)\)/g,(_,id)=>`url(#${id}-${suffix})`).replace(/href="#([^"]+)"/g,(_,id)=>`href="#${id}-${suffix}"`)}
function renderComic(){const p=session.page;$('#page-four-secret').hidden=p!==3;$('#comic-page').innerHTML=pageSVG(p,'normal');$('#page-count').textContent=String(p+1).padStart(2,'0')+' / 08';$('#page-title').textContent=comicNames[p];$('#prev-page').disabled=p===0;$('#next-page').disabled=p===7;$('#next-page').innerHTML=p===7?'The end <span>✦</span>':'Next page <span>→</span>';$('#page-dots').innerHTML=comicNames.map((n,i)=>`<button data-page="${i}" aria-label="Page ${i+1}: ${n}"${p===i?' aria-current="page"':''}></button>`).join('');$$('[data-page]').forEach(b=>b.onclick=()=>goPage(Number(b.dataset.page)));if(readerDialog.open){$('#focus-page').innerHTML=pageSVG(p,'focus');$('#focus-count').textContent=(p+1)+' / 8 · '+comicNames[p];$('#focus-prev').disabled=p===0;$('#focus-next').disabled=p===7;$('#focus-scroll').scrollTo(0,0)}save()}
let pageTimer;
function goPage(n){if(!Number.isInteger(n)||n<0||n>7||n===session.page)return;clearTimeout(pageTimer);session.page=n;contact('paper');if(reduced()||readerDialog.open){renderComic();return}$('.reader-stage').classList.add('turning');pageTimer=setTimeout(()=>{renderComic();$('.reader-stage').classList.remove('turning')},120)}
$('#prev-page').onclick=()=>goPage(session.page-1);$('#next-page').onclick=()=>goPage(session.page+1);
function openReader(){cancelAI();readerDialog.showModal();renderComic();$('#close-reader').focus()}
$('#focus-read').onclick=openReader;$('#page-surface').onclick=openReader;$('#close-reader').onclick=()=>readerDialog.close();readerDialog.addEventListener('close',()=>{tickTime=performance.now();scheduleAI()});$('#focus-prev').onclick=()=>goPage(session.page-1);$('#focus-next').onclick=()=>goPage(session.page+1);$('#reader-zoom').onclick=()=>{const z=readerDialog.classList.toggle('zoomed');$('#reader-zoom').setAttribute('aria-pressed',String(z));$('#reader-zoom').textContent=z?'Fit page':'Zoom +';$('#focus-scroll').scrollTo(0,0)};readerDialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();goPage(session.page+1)}if(e.key==='ArrowLeft'){e.preventDefault();goPage(session.page-1)}});
// ---- Clearly labelled concept and local-only feedback. No phantom sales funnel. ----
const physicalMarkup='<p class="dialog-kicker">THE HANDHELD EDITION</p><span class="badge">DESIGN CONCEPT · NOT FOR SALE</span><h2 id="dialog-title">There is a little world inside.</h2><div class="gift-concept" role="img" aria-label="Packaging design study: a small First Light book and a removable coin."><div class="gift-book">FIRST<br><i>LIGHT</i><small>A SMALL BEGINNING · 00</small></div><div class="gift-coin"></div></div><p>The idea: a printed comic with a real coin tucked into the panel. Take it out. Underneath: <em>“Oh, good. You made it.”</em></p><p>The public QR code returns to this playable world. A future private claim, if offered, would be separate from access to the story.</p><p>There are no manufactured samples, orders, shipping promises or redeemable tokens in this release. Materials, safety, pricing and fulfilment still need testing.</p><button class="primary" id="physical-feedback">Tell Michael what you think ↗</button>';
$('#physical-open').onclick=()=>{modal(physicalMarkup);$('#physical-feedback').onclick=feedbackModal};
function feedbackModal(){modal('<p class="dialog-kicker">A WORK IN WONDER</p><h2 id="dialog-title">How did it feel?</h2><p>What made you reach for it? What broke the spell?</p><div class="local-feedback-buttons"><button data-feeling="Curious" aria-pressed="false">Curious</button><button data-feeling="Delighted" aria-pressed="false">Delighted</button><button data-feeling="Not quite yet" aria-pressed="false">Not quite yet</button></div><label class="form-field">A NOTE FOR MICHAEL<textarea id="feedback-note" maxlength="4000" placeholder="The moment that stayed with me…"></textarea></label><button class="primary" id="copy-feedback">Copy my feedback ↗</button><p class="legal-note">Local only. This copies a message for you to send; it does not submit a form or collect your email.</p>');let feeling='';$$('[data-feeling]').forEach(b=>b.onclick=()=>{feeling=b.dataset.feeling;$$('[data-feeling]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)))});$('#copy-feedback').onclick=()=>copy('OUT OF PANEL · 0.5 feedback\nFeeling: '+(feeling||'Not selected')+'\n\n'+$('#feedback-note').value,'Feedback copied. Send it to Michael when you’re ready.')}
$('#feedback-open').onclick=feedbackModal;
$('#about-open').onclick=()=>{modal('<p class="dialog-kicker">OUT OF PANEL / RELEASE 0.5</p><h2 id="dialog-title">A work in wonder.</h2><p>A comic you can take something out of. An object you can use. A small experiment in storytelling, design and play, by Michael Ninh with AI-assisted development.</p><label class="toggle-row"><input type="checkbox" id="reduce-toggle">Prefer reduced motion</label><p>Your browser’s reduced-motion preference is also respected. Sound starts off for new visitors and is always optional.</p><p>Progress, preferences and your current game are stored only on this device when storage is available. There are no third-party requests, analytics, remote AI calls or background feedback submissions in this app.</p><p>The computer opponent is local and heuristic. Match clocks pause when away. This is not online multiplayer. The artwork is a reading/design study, not approved visual canon for other HYPERSPACE series.</p><p class="legal-note">No wallet connection, NFT verification, purchase, physical claim or scarcity promise. The 3D object is a visual model, not production CAD. The playable release connects back to Michael’s Beyond the CV.</p><div class="version-code" id="runtime-info"></div><button id="clear-data" class="outline-btn">Reset this device’s saved progress</button>');$('#reduce-toggle').checked=session.reduced;$('#reduce-toggle').onchange=e=>{session.reduced=e.target.checked;document.body.classList.toggle('reduce-motion',session.reduced);positionCoin();save()};$('#runtime-info').textContent='v0.5.0 · '+(window.OutOfPanelJourney?.getState().status==='ready'?'Three.js r180 + '+coinRenderer.kind:coinRenderer.kind)+' · storage '+(localOK?'available':'unavailable');$('#clear-data').onclick=()=>{modal('<p class="dialog-kicker">LOCAL PROGRESS ONLY</p><h2 id="dialog-title">Begin again?</h2><p>This clears the saved game, reading position and preferences on this browser. No external account is affected.</p><div class="row"><button id="confirm-clear" class="primary">Reset progress</button><button id="cancel-clear" class="outline-btn">Keep it</button></div>');$('#cancel-clear').onclick=closeModal;$('#confirm-clear').onclick=()=>{session.taken=false;session.page=0;session.sound=false;session.reduced=false;session.surface='paper';session.completed=0;session.returned=false;session.discovered=false;window.dispatchEvent(new Event('oop-reset'));gameMode='solo';difficulty='medium';clockMode='off';try{localStorage.removeItem(STORAGE)}catch{}resetGame();updateSound();renderComic();closeModal();switchView('encounter');toast('A fresh beginning on this device.')}}};
function shareURL(position=false){const u=new URL(location.href);u.search='';u.hash=position?'play':'encounter';if(position)u.searchParams.set('position',btoa(JSON.stringify({v:3,moves:moves.map(m=>[m.x,m.y]),mode:'local',difficulty:'medium',clock:'off'})));return u.href}
function portableCopy(position=false){
 if(!IS_PORTABLE){toast('Use the self-contained OUT-OF-PANEL.html file in the release package to share offline.');return}
 // Parse inertly: a regex over this document would also match literals in its source.
 const doc=new DOMParser().parseFromString(PORTABLE_SOURCE,'text/html');
 doc.getElementById('starting-position')?.remove();
 if(position){const seed=doc.createElement('script');seed.type='application/json';seed.id='starting-position';seed.textContent=JSON.stringify({v:3,moves:moves.map(m=>[m.x,m.y]),mode:'local',clock:'off'});doc.head.appendChild(seed)}
 const html='<!doctype html>'+doc.documentElement.outerHTML;
 download(position?'OUT-OF-PANEL-Your-Position.html':'HYPERSPACE-OUT-OF-PANEL.html',html,'text/html');
 toast(position?'Playable position saved. Send the HTML file to a friend.':'Portable experience saved. Send the HTML file to a friend.')
}
function shareDialog(position=false){if(/^https?:$/.test(location.protocol)&&!['localhost','127.0.0.1','0.0.0.0'].includes(location.hostname)){copy(shareURL(position),position?'Position link copied. This is a shared board, not live multiplayer.':'Experience link copied. Pass the little impossibility on.')}else{modal('<p class="dialog-kicker">PASS A LITTLE WORLD ON</p><h2 id="dialog-title">Better with a witness.</h2><p>This is the portable edition, not a public website. A local file address will not work on someone else’s device.</p><p>Save the '+(position?'current position as a playable':'self-contained')+' HTML file, then send that file to a friend. It opens without installation or an internet connection.</p><button id="save-portable" class="primary">Save playable file ↓</button><button id="copy-invitation" class="outline-btn">Copy a little invitation</button><p class="legal-note">Sharing a position is pass-and-play, not online multiplayer. Nothing is sent automatically.</p>');$('#save-portable').onclick=()=>portableCopy(position);$('#copy-invitation').onclick=()=>copy('I found a comic you can take things out of. Open the attached HTML, take the coin, and make your first move. — HYPERSPACE / OUT OF PANEL')}}
$('#share').onclick=()=>shareDialog();$('#share-footer').onclick=()=>shareDialog();$('#share-position').onclick=()=>shareDialog(true);
// Guest utility adapter: ownership must never be inferred from local preferences.
window.HyperspacePreview=Object.freeze({version:'0.5.0',connectCollection:async()=>({provider:'guest',session:'local-preview'}),verifyOwnership:async()=>({verified:false,reason:'No external ownership integration is installed.'}),getAsset:async()=>({assetId:'hyp:first-light:coin-study-002',uses:['infinite-four','object-inspection','story'],physicalClaim:false,verified:false}),exportAsset:()=>CoinStudio.exportGLB()});
window.OutOfPanel=Object.freeze({version:'0.5.0',winAt,candidates,chooseAI,parseGame,place,resetGame,switchView,takeCoin,getState:()=>({view,taken:session.taken,page:session.page,mode:gameMode,difficulty,clock:clockMode,moves:moves.map(m=>({...m})),turn,winner,aiPending,seconds:[...seconds],pan:{...pan},scale,coin:{x:coin.x,y:coin.y,size:coin.size,drag:!!coin.drag},renderer:coinRenderer.kind,localOK}),newLocalGame:()=>{gameMode='local';resetGame()},goPage});
resetGame();if(persisted.game)restoreGame(persisted.game);gameReady=true;let shared=false;
try{const raw=new URL(location.href).searchParams.get('position'),embedded=$('#starting-position');if(raw&&raw.length>25000)throw new Error('Too large');const g=raw?JSON.parse(atob(raw)):embedded?JSON.parse(embedded.textContent):null;if(g){if(!restoreGame(g))throw new Error('Invalid shared position');gameMode='local';clockMode='off';seconds=[Infinity,Infinity];increment=0;shared=true;session.taken=true}}catch{toast('That shared position was invalid. Your local game is still available.')}
updateSound();renderComic();renderGame();$$('[data-surface]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.surface===session.surface)));document.body.classList.toggle('reduce-motion',session.reduced);switchView(shared?'play':['encounter','play','read','object','return'].includes(location.hash.slice(1))?location.hash.slice(1):'object',{scroll:false});positionCoin();resizeBoard();setTimeout(()=>{positionCoin();coin.renderDirty=true},300);window.addEventListener('resize',()=>{positionCoin();resizeBoard()});
