from pathlib import Path
import json, math, time
from playwright.sync_api import sync_playwright
P=Path(__file__).parent;HTML=(P/'OUT-OF-PANEL-04.html').read_text();results=[];errors=[]
def check(name,ok,detail=''):
 results.append({'name':name,'pass':bool(ok),'detail':detail})
 print(('PASS ' if ok else 'FAIL ')+name,detail)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
 c=b.new_context(viewport={'width':1440,'height':1000},device_scale_factor=1)
 page=c.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content(HTML,wait_until='load');page.wait_for_timeout(700)
 check('No runtime errors at boot',not errors,str(errors));check('Default view is the coin',page.evaluate('OutOfPanel.getState().view')=='object')
 check('Full model engine retained',page.evaluate("coinRenderer.kind==='Software 3D'||coinRenderer.kind==='WebGL'"))
 y0=page.evaluate('coin.yaw');page.locator('#spin-object').click();page.wait_for_timeout(90);y1=page.evaluate('coin.yaw');page.wait_for_timeout(1100);y2=page.evaluate('coin.yaw')
 check('Spin has visible intermediate rotation',.05<y1-y0<6.2,f'initial={y0:.3f}, middle={y1:.3f}, final={y2:.3f}')
 check('Spin completes a full turn',abs((y2-y0)-math.tau)<.015)
 page.locator('#flip-object').click();page.wait_for_timeout(1000);check('Flip rotates half a turn',abs(page.evaluate('coin.yaw')-y2-math.pi)<.02)
 box=page.locator('#coin').bounding_box();x=box['x']+box['width']*.5;y=box['y']+box['height']*.5
 base=page.evaluate('coin.tyaw');page.mouse.move(x,y);page.mouse.down();page.mouse.move(x+70,y+30,steps=10);page.mouse.up();page.wait_for_timeout(650)
 check('Real mouse drag rotates model',page.evaluate('coin.yaw')>base+.5)
 page.locator('#coin').focus();old=page.evaluate('coin.tyaw');page.keyboard.press('ArrowRight');page.wait_for_timeout(450);check('Keyboard rotation works',page.evaluate('coin.yaw')>old+.20)
 # Real drag then pointer cancellation preserves ownership and original orientation.
 box=page.locator('#coin').bounding_box();x=box['x']+box['width']*.5;y=box['y']+box['height']*.5
 old=page.evaluate('coin.tyaw');page.mouse.move(x,y);page.mouse.down();page.mouse.move(x+90,y,steps=8);pid=page.evaluate('coin.drag.id');page.locator('#coin').dispatch_event('pointercancel',{'pointerId':pid});page.mouse.up();page.wait_for_timeout(500)
 check('Pointer cancellation restores orientation',abs(page.evaluate('coin.tyaw')-old)<.01)
 check('Aperture matches a projected 64-sided opening',page.evaluate('OutOfPanelWonder.project([.235,.25,0],512).every(Number.isFinite)'))
 page.locator('#look-inside').click();page.wait_for_timeout(850)
 check('Window opens into the rooftop',page.evaluate('OutOfPanelWonder.getState().inside'))
 check('Hidden world has accessible description','black cat' in page.locator('#world-canvas').get_attribute('aria-label'))
 shot1=page.locator('#world-canvas').screenshot();page.wait_for_timeout(220);shot2=page.locator('#world-canvas').screenshot();check('Rooftop has live movement',shot1!=shot2)
 page.screenshot(path=str(P/'04-world.png'),full_page=True)
 page.keyboard.press('Escape');check('Escape closes the world',not page.evaluate('OutOfPanelWonder.getState().inside'))
 page.locator('#return-page').click();page.wait_for_timeout(800);check('Return is an actual scene',page.evaluate('OutOfPanel.getState().view')=='return')
 page.locator('#give-back').click();page.evaluate('OutOfPanel.switchView("play")');page.wait_for_timeout(1050);check('Leaving mid-return cancels reward',not page.evaluate('OutOfPanelWonder.getState().returned'))
 page.evaluate('OutOfPanelWonder.visitReturn()');page.wait_for_timeout(850)
 a=page.locator('#coin').bounding_box();d=page.locator('#return-target').bounding_box()
 page.mouse.move(a['x']+a['width']/2,a['y']+a['height']/2);page.mouse.down();page.mouse.move(d['x']+d['width']/2,d['y']+d['height']/2,steps=18);page.mouse.up();page.wait_for_timeout(1250)
 check('Drag-and-drop returns coin',page.evaluate('OutOfPanelWonder.getState().returned'))
 check('Thank-you star becomes visible',page.locator('#paper-star').is_visible())
 check('Coin no longer captures touch after return',page.locator('#coin').evaluate('(el)=>getComputedStyle(el).pointerEvents')=='none')
 with page.expect_download() as dl:page.locator('#keep-star').click()
 star=dl.value;star.save_as(str(P/'FIRST-LIGHT-paper-star.svg'));check('Keepsake export has honest provenance','No ownership or physical claim' in (P/'FIRST-LIGHT-paper-star.svg').read_text())
 page.screenshot(path=str(P/'04-star.png'),full_page=True)
 page.locator('#return-replay').click();page.wait_for_timeout(500);check('Return is reversible',not page.evaluate('OutOfPanelWonder.getState().returned'))
 page.locator('#give-back').click();page.wait_for_timeout(1050);check('Button alternative to drag works',page.evaluate('OutOfPanelWonder.getState().returned'))
 page.evaluate('OutOfPanel.switchView("play");OutOfPanel.newLocalGame()')
 check('Occupied cell is rejected',page.evaluate('OutOfPanel.place(0,0)&&!OutOfPanel.place(0,0)'))
 page.evaluate('OutOfPanel.resetGame();[[0,0],[0,2],[1,0],[1,2],[2,0],[2,2],[3,0]].forEach(m=>OutOfPanel.place(...m))')
 check('Local four-in-a-row wins',page.evaluate('OutOfPanel.getState().winner')==1)
 for dx,dy in [(1,0),(0,1),(1,1),(1,-1)]:
  ok=page.evaluate('([dx,dy])=>{let b=new Map;for(let i=0;i<4;i++)b.set(`${i*dx},${i*dy}`,1);return !!OutOfPanel.winAt(b,0,0,1)}',[dx,dy]);check(f'Win direction {dx},{dy}',ok)
 check('Invalid duplicate positions rejected',page.evaluate('(()=>{try{OutOfPanel.parseGame({moves:[[0,0],[0,0]]});return false}catch{return true}})()'))
 check('Unsafe giant coordinates rejected',page.evaluate('(()=>{try{OutOfPanel.parseGame({moves:[[1e12,0]]});return false}catch{return true}})()'))
 page.evaluate('gameMode="solo";difficulty="medium";OutOfPanel.resetGame();OutOfPanel.place(0,0)');page.wait_for_timeout(900)
 check('Local computer responds',page.evaluate('OutOfPanel.getState().moves.length')==2)
 page.screenshot(path=str(P/'04-game.png'),full_page=True)
 page.evaluate('OutOfPanel.switchView("read")');page.wait_for_timeout(300);check('Eight-page comic is present',page.locator('#page-dots button').count()==8)
 for i in range(8):
  page.evaluate('(n)=>OutOfPanel.goPage(n)',i);page.wait_for_timeout(160)
  check(f'Comic page {i+1} renders',page.locator('#comic-page svg').count()==1 and page.locator('#page-count').inner_text().startswith(f'{i+1:02d}'))
 page.evaluate('OutOfPanel.goPage(3)');page.wait_for_timeout(180);check('Page 04 links to the return',page.locator('#page-four-secret').is_visible())
 page.locator('#focus-read').click();check('Focused reader opens',page.locator('#reader-dialog').evaluate('(el)=>el.open'));page.locator('#reader-zoom').click();check('Reader zoom works',page.locator('#reader-zoom').get_attribute('aria-pressed')=='true');page.locator('#close-reader').click()
 page.locator('#feedback-open').click();check('Real feedback destination is shown','mikel_ninh@yahoo.de' in page.locator('#feedback-state').inner_text())
 page.locator('#email-feedback').click();check('Empty feedback is not drafted','Add a sentence' in page.locator('#feedback-state').inner_text())
 page.locator('#feedback-note').fill('I loved the coin. The portal felt good.');page.evaluate("document.addEventListener('click',e=>{let a=e.target.closest('a');if(a?.href.startsWith('mailto:')){e.preventDefault();window.testMail=a.href}},true)")
 page.locator('#email-feedback').click();check('Email action prepares user-reviewed draft',page.evaluate('window.testMail.startsWith("mailto:mikel_ninh@yahoo.de?")') and 'Nothing has been sent' in page.locator('#feedback-state').inner_text())
 check('Device details excluded by default','Browser%3A' not in page.evaluate('window.testMail'))
 page.locator('#feedback-device').check();page.locator('#email-feedback').click();check('Device details are explicitly opt-in','Browser%3A' in page.evaluate('window.testMail'))
 page.locator('#dialog-close').click();page.locator('#share').click();check('Offline sharing offers real portable file',page.locator('#save-gift').is_visible())
 with page.expect_download() as dl:page.locator('#save-gift').click()
 gift=dl.value;gift.save_as(str(P/'test-invitation.html'));check('Gift file contains arrival marker','id="gift-arrival"' in (P/'test-invitation.html').read_text())
 g=c.new_page();g.on('pageerror',lambda e:errors.append('Gift: '+str(e)));g.set_content((P/'test-invitation.html').read_text(),wait_until='load');g.wait_for_timeout(500)
 check('Recipient gets the promised greeting','They sent' in g.locator('#wonder-title').inner_text());g.close()
 # Test local-memory save/reload under an explicit simulated Storage shim.
 store={};st=c.new_page();shim="""<script>window.fakeStorage={};Object.defineProperty(window,'localStorage',{value:{getItem:k=>window.fakeStorage[k]||null,setItem:(k,v)=>window.fakeStorage[k]=v,removeItem:k=>delete window.fakeStorage[k]}});</script>"""
 st.set_content(HTML.replace('<body data-view=',shim+'<body data-view='),wait_until='load');st.wait_for_timeout(300);st.evaluate('session.returned=true;session.discovered=true;OutOfPanel.switchView("play");OutOfPanel.newLocalGame();OutOfPanel.place(2,3);save()');stored=st.evaluate('fakeStorage["hyperspace-out-of-panel-v4"]');parsed=json.loads(stored);check('Saved state includes story and board',parsed['returned'] and parsed['discovered'] and parsed['game']['moves']==[[2,3]],'Simulated storage; browser restricts local storage at about:blank.')
 st.close();page.locator('#dialog-close').click()
 for width in [320,360,390,768,1440]:
  page.set_viewport_size({'width':width,'height':844 if width<760 else 1000});page.evaluate('OutOfPanel.switchView("object")');page.wait_for_timeout(260)
  check(f'No horizontal overflow at {width}px',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
  if width==390:page.screenshot(path=str(P/'04-mobile.png'),full_page=True);page.locator('#look-inside').click();page.wait_for_timeout(700);page.screenshot(path=str(P/'04-mobile-world.png'),full_page=True);page.keyboard.press('Escape')
 page.emulate_media(reduced_motion='reduce');page.set_viewport_size({'width':390,'height':844});page.evaluate('OutOfPanel.switchView("object")');page.wait_for_timeout(120);y0=page.evaluate('coin.yaw');page.locator('#spin-object').click();page.wait_for_timeout(90);check('Reduced motion makes discrete turns',abs(page.evaluate('coin.yaw')-y0-math.pi)<.002)
 page.locator('#look-inside').click();page.wait_for_timeout(150);im1=page.locator('#world-canvas').screenshot();page.wait_for_timeout(150);im2=page.locator('#world-canvas').screenshot();check('Reduced motion keeps world still',im1==im2)
 check('No external runtime assets in portable build','<script src=' not in HTML and 'rel="stylesheet"' not in HTML)
 check('No runtime errors across tested flows',not errors,str(errors))
 b.close()
report={'release':'0.4.0','environment':'Chromium, software 3D fallback; inline portable build at about:blank; emulated viewport sizes. No Safari or physical device/GPU test. Storage persistence uses an explicit shim.','passed':sum(r['pass'] for r in results),'failed':sum(not r['pass'] for r in results),'tests':results,'errors':errors}
(P/'QA-results.json').write_text(json.dumps(report,indent=2));print(json.dumps({k:report[k] for k in ['passed','failed','errors']}))
