/* OUT OF PANEL 0.5 — the Window, the Return, the Invitation.
 * Deterministic vector scenery; no external renderer, tracking or ownership fiction.
 * Drawn into the same model aperture in both the GPU and software paths.
 */
(()=>{
'use strict';
const $=s=>document.querySelector(s),TAU=Math.PI*2,clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const world=$('#world-canvas'),wx=world.getContext('2d'),mini=$('#aperture-canvas'),mx=mini.getContext('2d'),paw=$('#paw-canvas'),px=paw.getContext('2d');
let inside=false,returning=false,returnTimer=0,returnEpoch=0,lastPaint=0,openAt=0,aim={x:0,y:0},pointer={x:0,y:0},activeTime=0,lastT=0,pawStarted=false;
const $coin=$('#coin'),S=960;
const art=$('#return-art');art.innerHTML=ENCOUNTER_ART.replace(/id="([^"]+)"/g,(_,id)=>`id="ret-${id}"`).replace(/url\(#([^\)]+)\)/g,(_,id)=>`url(#ret-${id})`).replace(/href="#([^"]+)"/g,(_,id)=>`href="#ret-${id}"`);
const sky=document.createElement('canvas');sky.width=sky.height=S;const k=sky.getContext('2d');
const rand=(()=>{let s=752;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}})();
function poly(c,points,fill,stroke,l=1){c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=l;c.stroke()}}
function line(c,points,col,width=1){c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.strokeStyle=col;c.lineWidth=width;c.stroke()}
function ellipse(c,x,y,rx,ry,color,rot=0){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,rot,0,TAU);c.fill()}
function plant(c,x,y,scale=1){c.save();c.translate(x,y);c.scale(scale,scale);poly(c,[[-28,0],[29,0],[21,45],[-22,45]],'#b3734b','#273f36',3);ellipse(c,0,1,29,7,'#714d36');c.strokeStyle='#4c7355';c.lineWidth=5;c.beginPath();c.moveTo(0,0);c.quadraticCurveTo(9,-67,-6,-133);c.stroke();for(let i=0;i<7;i++){let yy=-20-i*15,side=i%2?-1:1;ellipse(c,side*(15+i*2),yy-10,25,9,['#486650','#719061','#8a9f62'][i%3],side*.75)}c.restore()}
function backdrop(){let g=k.createLinearGradient(0,0,0,S);g.addColorStop(0,'#1a4147');g.addColorStop(.3,'#587171');g.addColorStop(.56,'#d3946b');g.addColorStop(.74,'#e1b37f');g.addColorStop(1,'#b2a37a');k.fillStyle=g;k.fillRect(0,0,S,S);
 const glow=k.createRadialGradient(631,358,15,631,358,325);glow.addColorStop(0,'#ffe5ac91');glow.addColorStop(.5,'#eac09326');glow.addColorStop(1,'#e0a57400');k.fillStyle=glow;k.fillRect(0,0,S,S);ellipse(k,631,351,112,112,'#ecd29c');ellipse(k,631,351,99,99,'#f3d9a3');
 // Long, quiet cloud ribbons.
 for(let j=0;j<11;j++){let y=145+j*35+rand()*15,x=rand()*950;ellipse(k,x,y,80+rand()*120,3+rand()*7,j%2?'#ddb78b39':'#ebc49a23',-.04)}
 for(let layer=0;layer<3;layer++){let x=-15;while(x<980){const w=26+rand()*51,h=35+rand()*(70+layer*52),base=555+layer*64,col=['#64766a','#4c655d','#304d45'][layer];k.fillStyle=col;k.fillRect(x,base-h,w,h+85);poly(k,[[x-3,base-h],[x+w*.2,base-h-9],[x+w+3,base-h-4],[x+w,base-h+2]],col);if(rand()>.53){line(k,[[x+w*.6,base-h],[x+w*.6,base-h-32]],col,2);line(k,[[x+w*.4,base-h-23],[x+w*.8,base-h-23]],col,2)}for(let yy=base-h+13;yy<base-5;yy+=15)for(let xx=x+7;xx<x+w-5;xx+=11){if(rand()>.49){k.fillStyle=rand()>.5?'#dbb87977':'#839b794f';k.fillRect(xx,yy,3,6)}}x+=w+4+rand()*12}}
 // Courtyard roof, foreground, doors and a place to sit.
 poly(k,[[0,646],[960,583],[960,960],[0,960]],'#596658');poly(k,[[0,701],[960,635],[960,960],[0,960]],'#7e8061');poly(k,[[0,615],[962,564],[962,593],[0,656]],'#98a080','#263f34',3);poly(k,[[0,655],[960,593],[960,655],[0,717]],'#3c5647');
 line(k,[[0,660],[960,599]],'#d6be89',3);line(k,[[0,714],[960,651]],'#b5a276',3);
 for(let i=0;i<7;i++)line(k,[[-40,770+i*51],[980,690+i*63]],'#394c394a',2);for(let i=0;i<10;i++)line(k,[[i*118-80,676],[i*167-176,1020]],'#42513c4a',2);
 poly(k,[[66,512],[258,490],[259,839],[58,891]],'#354d3e','#233d32',3);poly(k,[[74,524],[230,508],[231,823],[70,866]],'#213d34','#748567',2);poly(k,[[93,542],[207,531],[209,687],[90,707]],'#d2af7559');line(k,[[91,706],[210,687]],'#baa87a',4);line(k,[[152,537],[151,697]],'#baa87a',4);ellipse(k,214,737,5,5,'#c6b27e');
 // A warm lamp, invitation rather than neon.
 const lamp=k.createRadialGradient(331,641,4,331,641,132);lamp.addColorStop(0,'#f5c47342');lamp.addColorStop(1,'#ebbb6900');k.fillStyle=lamp;k.fillRect(185,492,300,300);line(k,[[330,598],[330,681]],'#c4ab7c',3);poly(k,[[310,604],[348,604],[359,634],[300,634]],'#e6b776','#314734',2);ellipse(k,330,636,25,5,'#f3d79b');
 poly(k,[[352,754],[571,723],[611,740],[388,779]],'#b99160','#293f31',3);poly(k,[[388,779],[611,740],[611,757],[388,797]],'#8c684a');line(k,[[405,791],[400,850]],'#364737',7);line(k,[[582,761],[589,813]],'#364737',7);
 // One waiting cup.
 ellipse(k,446,752,20,5,'#43503c');poly(k,[[432,730],[453,728],[452,749],[435,751]],'#e1cd9f','#45533e',2);ellipse(k,442,730,11,3,'#675c3d');k.strokeStyle='#e1cd9f';k.lineWidth=3;k.beginPath();k.arc(457,736,6,-1.6,1.6);k.stroke();
 plant(k,308,840,1.0);plant(k,875,731,1.3);plant(k,827,772,.75);
 // Hand-drawn texture is generated once, never random on every frame.
 for(let i=0;i<16500;i++){const x=rand()*S,y=rand()*S;k.fillStyle=rand()>.5?'#fff2b509':'#0d352110';k.fillRect(x,y,rand()*2+.5,rand()*2+.4)}
}
backdrop();
function cat(c,x,y,scale,t){c.save();c.translate(x,y);c.scale(scale,scale);ellipse(c,0,80,79,17,'#1b322960');c.lineCap='round';c.strokeStyle='#172f29';c.lineWidth=19;c.beginPath();c.moveTo(35,64);c.bezierCurveTo(111,84,118,11+Math.sin(t*.9)*6,76,23);c.stroke();ellipse(c,0,35,46,65,'#19372f',-.1);ellipse(c,-21,80,26,13,'#152f29');ellipse(c,31,79,22,12,'#152f29');poly(c,[[-43,-17],[-43,-66],[-17,-47],[12,-49],[39,-70],[42,-15]],'#18342d','#759076',1.5);ellipse(c,0,-16,47,40,'#19372f');poly(c,[[-36,-45],[-35,-58],[-20,-46]],'#637b65');poly(c,[[21,-48],[34,-60],[34,-44]],'#637b65');
 const blink=reduced()?1:Math.sin(t*.53)> .995?.09:1;ellipse(c,-19,-17,10,6.5*blink,'#d9c481',-.1);ellipse(c,20,-18,10,6.5*blink,'#d9c481',.1);ellipse(c,-17+pointer.x*2,-17,2,5.3*blink,'#132f29');ellipse(c,22+pointer.x*2,-18,2,5.3*blink,'#132f29');poly(c,[[-4,-4],[4,-4],[0,1]],'#b99375');line(c,[[0,2],[-4,7]],'#8a9e7b',1.2);line(c,[[0,2],[5,7]],'#8a9e7b',1.2);for(const side of[-1,1]){line(c,[[side*14,0],[side*53,-2]],'#819b7766',1.1);line(c,[[side*15,6],[side*56,14]],'#819b7766',1.1)}c.restore()}
function paintWorld(t){wx.clearRect(0,0,S,S);wx.save();wx.translate(pointer.x*-12,pointer.y*-7);wx.drawImage(sky,-16,-10,S+32,S+20);wx.restore();
 // Clothesline reacts to the same small breeze, not the cursor in unrelated ways.
 const wave=reduced()?0:Math.sin(t*.8)*3;wx.strokeStyle='#263f3580';wx.lineWidth=2;wx.beginPath();wx.moveTo(150,320);wx.quadraticCurveTo(500,419,940,326);wx.stroke();
 for(const [x,y,col,len]of[[270,355,'#bd9e79',94],[373,373,'#8aa096',109],[477,383,'#d6bf92',76]]){const sway=wave*(x/150);poly(wx,[[x,y],[x+50,y+4],[x+52+sway,y+len],[x+7+sway,y+len-5]],col,'#29473c55',1.3);line(wx,[[x+12,y],[x+12,y+7]],'#bea177',4);line(wx,[[x+41,y+3],[x+41,y+10]],'#bea177',4);line(wx,[[x+18,y+10],[x+22+sway,y+len-6]],'#29473c35',1)}
 for(let j=0;j<3;j++){const x=220+j*65,y=176+Math.sin(t*.7+j)*4;wx.strokeStyle='#233e3d80';wx.lineWidth=1.6;wx.beginPath();wx.moveTo(x-7,y+2);wx.quadraticCurveTo(x-2,y-4,x,y);wx.quadraticCurveTo(x+3,y-4,x+8,y);wx.stroke()}
 // Our small witness — tail, breathing, and one unhurried blink.
 cat(wx,680+pointer.x*-4,779+Math.sin(t*1.5)*.8,1.04,t);
 for(let i=0;i<6;i++){let x=390+Math.sin(t*.34+i*2.1)*200,y=566+Math.cos(t*.42+i*1.7)*102,a=.14+(Math.sin(t+i*1.7)+1)*.16;wx.globalAlpha=a;ellipse(wx,x,y,2.7,2.7,'#ffe4a7');wx.globalAlpha=a*.17;ellipse(wx,x,y,13,13,'#ffe4a7')}wx.globalAlpha=1;
 // A little living detail beside the cup.
 if(!reduced()){wx.strokeStyle='#f0d4a447';wx.lineWidth=1.5;wx.beginPath();wx.moveTo(444,726);wx.bezierCurveTo(430+Math.sin(t)*4,708,456,701,443,686);wx.stroke()}
}
function rotate(p){const a=coin.pitch,b=coin.yaw,z=coin.roll;let x=p[0],y=p[1]*Math.cos(a)-p[2]*Math.sin(a),zz=p[1]*Math.sin(a)+p[2]*Math.cos(a);const xx=x*Math.cos(b)+zz*Math.sin(b),Z=-x*Math.sin(b)+zz*Math.cos(b);return[xx*Math.cos(z)-y*Math.sin(z),xx*Math.sin(z)+y*Math.cos(z),Z]}
function project(p,size){const [x,y,z]=rotate(p),f=coinRenderer.kind==='WebGL'?1.5/(4.3-z):.355;return[size*.5+x*f*size,size*.5-y*f*size]}
function paintAperture(t){const size=coinCanvas.width;if(mini.width!==size){mini.width=mini.height=size;paw.width=paw.height=size}mx.clearRect(0,0,size,size);px.clearRect(0,0,size,size);if(view!=='object'||coin.ink>.5)return;const points=[];for(let i=0;i<64;i++){let a=TAU*i/64;points.push(project([.235+.214*Math.cos(a),.25+.214*Math.sin(a),0],size))}const minX=Math.min(...points.map(p=>p[0])),minY=Math.min(...points.map(p=>p[1])),maxX=Math.max(...points.map(p=>p[0])),maxY=Math.max(...points.map(p=>p[1])),w=maxX-minX,h=maxY-minY;if(w<2||h<2)return;mx.save();mx.beginPath();points.forEach((p,i)=>i?mx.lineTo(...p):mx.moveTo(...p));mx.closePath();mx.clip();const box=Math.max(w,h)*1.38;mx.drawImage(world,minX+(w-box)/2-pointer.x*box*.03,minY+(h-box)/2,box,box);mx.restore();
 // A paw overlaps the rim. It is drawn after the metal, in that same projection.
 const front=rotate([0,0,1])[2]>.22;if(front&&!inside&&(pawStarted||activeTime>2.5)){pawStarted=true;const q=project([.235,.062,.155],size),factor=reduced()?1:clamp((activeTime-2.5)/1.6,0,1),r=size*.024;px.save();px.translate(q[0],q[1]+r*(1-factor));px.rotate(-coin.roll);px.globalAlpha=factor;ellipse(px,0,0,r,r*.76,'#162e27');for(let i=-1;i<=1;i++)line(px,[[i*r*.39,-r*.12],[i*r*.4,r*.28]],'#9bae807a',Math.max(.7,size*.0015));px.restore()}
}
function tick(t){if(document.hidden)return;const dt=lastT?Math.min((t-lastT)/1000,.06):0;lastT=t;if(view!=='object'){mx.clearRect(0,0,mini.width,mini.height);px.clearRect(0,0,paw.width,paw.height);return}activeTime+=dt;const rate=inside?32:60;if(t-lastPaint<rate&&!reduced())return;lastPaint=t;pointer.x+=(aim.x-pointer.x)*.08;pointer.y+=(aim.y-pointer.y)*.08;const seconds=reduced()?5.1:activeTime;paintWorld(seconds);paintAperture(seconds);if(!session.discovered&&activeTime>3.5){session.discovered=true;save();$('#portal-hint').textContent='There you are. Try looking a little closer.'}}
function enterWorld(){if(view!=='object')switchView('object');inside=true;document.body.classList.add('world-open');$('#close-world').hidden=false;$('#portal-theatre').setAttribute('aria-hidden','false');$('#world-canvas').setAttribute('role','img');$('#world-canvas').setAttribute('aria-label','A tiny sunset rooftop inside the coin: a black cat, laundry, plants and a waiting cup of tea.');$('#wonder-title').innerHTML='Oh.<br><em>Someone’s<br>home.</em>';$('#wonder-lead').innerHTML='A rooftop. A warm light.<br>A cat with questions.';$('#wonder-note').innerHTML='Some worlds are waiting<br>for someone to look closer.';$('#look-inside').hidden=true;coin.tyaw=.1;coin.tpitch=-.15;positionCoin();session.discovered=true;save();announce('Inside the coin is a rooftop at sunset, with a black cat watching you.');contact('paper');openAt=performance.now()}
function exitWorld(){inside=false;document.body.classList.remove('world-open');$('#close-world').hidden=true;$('#portal-theatre').setAttribute('aria-hidden','true');$('#wonder-title').innerHTML='There’s more<br>on the<br><em>inside.</em>';$('#wonder-lead').innerHTML='A small coin.<br>A suspiciously large world.';$('#wonder-note').innerHTML='Turn it. Watch the opening.<br>Someone in there might notice you.';$('#look-inside').hidden=false;positionCoin()}
$('#look-inside').onclick=enterWorld;$('#close-world').onclick=()=>{exitWorld();$('#look-inside').focus({preventScroll:true})};$('#spin-object').onclick=()=>{coin.tyaw+=reduced()?Math.PI:TAU;coin.tpitch=-.18;coin.renderDirty=true;contact('metal');announce(reduced()?'Coin turned with reduced motion.':'A full spin. The world inside stays with it.')};
world.addEventListener('pointermove',e=>{const r=world.getBoundingClientRect();aim={x:clamp((e.clientX-r.x)/r.width*2-1,-1,1),y:clamp((e.clientY-r.y)/r.height*2-1,-1,1)}});world.addEventListener('pointerleave',()=>aim={x:0,y:0});
function syncReturn(){document.body.classList.toggle('returned',session.returned);$('#paper-star').hidden=!session.returned;$('#keep-star').hidden=!session.returned;$('#return-replay').hidden=!session.returned;$('#give-back').hidden=session.returned;$('#give-back').disabled=false;$('#return-speech').innerHTML=session.returned?'“You found it.<br>Here. For the trouble.”':'“I was wondering<br>where that went.”';$('#return-title').innerHTML=session.returned?'A little<br><em>something<br>in return.</em>':'Some things<br><em>find their<br>way back.</em>';$('#return-lead').textContent=session.returned?'A paper star. From their world to yours.':'The inscription wasn’t decoration.';$('#return-note').innerHTML=session.returned?'Keep it as a small reminder.<br>Not everything. Something.':'Drag the coin into the empty circle.<br>Or let the button lend a hand.';$('#return-caption').textContent=session.returned?'It turns out giving something back is a kind of magic, too.':'An empty space is sometimes an invitation.';coinEl.tabIndex=view==='return'&&session.returned?-1:view==='read'?-1:0}
function visitReturn(){exitWorld();switchView('return',{focus:false});syncReturn();$('#give-back').focus({preventScroll:true})}
function giveBack(){if(view!=='return'||session.returned||returning)return;returning=true;returnEpoch++;const epoch=returnEpoch;$('#give-back').disabled=true;document.body.classList.add('returning');const r=$('#return-target').getBoundingClientRect(),s=stage.getBoundingClientRect();coin.tx=r.x+r.width/2-s.x;coin.ty=r.y+r.height/2-s.y;coin.ts=r.width*1.36;coin.tyaw=0;coin.tpitch=0;coin.troll=-.03;coin.renderDirty=true;returnTimer=setTimeout(()=>{if(epoch!==returnEpoch||view!=='return')return;returning=false;session.returned=true;document.body.classList.remove('returning');syncReturn();save();contact('paper');announce('You returned the coin. A paper star appears as a thank-you.');$('#keep-star').focus({preventScroll:true})},reduced()?0:920)}
function abortReturn(){returnEpoch++;clearTimeout(returnTimer);returning=false;document.body.classList.remove('returning');$('#give-back').disabled=false}
$('#return-page').onclick=visitReturn;$('#give-back').onclick=giveBack;$('#page-four-secret').onclick=visitReturn;$('#return-read').onclick=()=>{session.page=3;switchView('read')};$('#return-replay').onclick=()=>{abortReturn();session.returned=false;syncReturn();positionCoin();save()};
const starSVG=`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="1000" viewBox="0 0 800 1000"><rect width="800" height="1000" fill="#172c25"/><rect x="30" y="30" width="740" height="940" rx="2" fill="none" stroke="#baab7940"/><text x="400" y="120" text-anchor="middle" font-family="sans-serif" font-size="13" letter-spacing="4" fill="#baa77e">A LITTLE SOMETHING IN RETURN</text><g transform="translate(175 245) scale(2.8)"><path d="M80 8 99 57 152 61 111 96 124 149 80 119 36 149 49 96 8 61 61 57Z" fill="#efd39b" stroke="#ad9360"/><path d="M80 8V81L152 61 80 81 124 149 80 81 36 149 80 81 8 61" fill="#e7be77" stroke="#b99a63" stroke-width=".5"/></g><text x="400" y="760" text-anchor="middle" font-family="Georgia,serif" font-style="italic" font-size="37" fill="#ebd5a9">Not everything. Something.</text><text x="400" y="825" text-anchor="middle" font-family="sans-serif" font-size="12" letter-spacing="2" fill="#a4b197">OUT OF PANEL · FIRST LIGHT · PAGE 04</text><text x="400" y="918" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#80947b">A digital keepsake from Michael Ninh’s HYPERSPACE. No ownership or physical claim.</text></svg>`;
function keepStar(){if(!session.returned)return;download('A-little-something-FIRST-LIGHT.svg',starSVG,'image/svg+xml');toast('Your paper star is saved as an SVG. A little piece of this world.');contact('paper')}
$('#keep-star').onclick=keepStar;$('#paper-star').onclick=keepStar;
// A real destination, without pretending an email draft is a form submission.
function feedback(){modal('<p class="dialog-kicker">HELP SHAPE THE NEXT CHAPTER</p><h2 id="dialog-title">What stayed with you?</h2><p>A moment you loved. A bug. Something that got in the way. Michael reads the replies.</p><div class="local-feedback-buttons"><button data-feeling="The coin" aria-pressed="false">The coin</button><button data-feeling="The hidden world" aria-pressed="false">The hidden world</button><button data-feeling="The game" aria-pressed="false">The game</button><button data-feeling="The story" aria-pressed="false">The story</button></div><label class="form-field">YOUR NOTE<textarea id="feedback-note" maxlength="1800" placeholder="I felt… / I got stuck when…"></textarea></label><label class="feedback-check"><input type="checkbox" id="feedback-device"> Include browser, screen size and renderer to help reproduce a bug.</label><div class="feedback-actions"><button id="email-feedback" class="primary">Open email draft <span>↗</span></button><button id="copy-feedback" class="outline-btn">Copy instead</button><button id="save-feedback" class="outline-btn">Save .txt</button></div><p id="feedback-state" role="status">Nothing is sent from this page. The email draft goes to mikel_ninh@yahoo.de; review it and press Send in your mail app.</p><p class="legal-note">No email app? Copy or save your note, then send it manually. Please don’t include sensitive information.</p>');let feeling='';document.querySelectorAll('[data-feeling]').forEach(b=>b.onclick=()=>{feeling=b.dataset.feeling;document.querySelectorAll('[data-feeling]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)))});
 const message=()=>`OUT OF PANEL 0.5 / Feedback\nAbout: ${feeling||'The experience'}\n\n${$('#feedback-note').value.trim()}\n\n${$('#feedback-device').checked?'Screen: '+innerWidth+' × '+innerHeight+'\nRenderer: '+coinRenderer.kind+'\nBrowser: '+navigator.userAgent+'\n':''}Page: ${view}`;
 $('#email-feedback').onclick=()=>{if(!$('#feedback-note').value.trim()){ $('#feedback-state').textContent='Add a sentence first — even a small one is helpful.';$('#feedback-note').focus();return}const a=document.createElement('a');a.href='mailto:mikel_ninh@yahoo.de?subject='+encodeURIComponent('OUT OF PANEL 0.5 — a little feedback')+'&body='+encodeURIComponent(message());a.hidden=true;document.body.appendChild(a);a.click();a.remove();$('#feedback-state').textContent='Email draft requested. Nothing has been sent yet; finish by pressing Send in your email app.'};$('#copy-feedback').onclick=()=>copy(message(),'Feedback copied. Send it to mikel_ninh@yahoo.de.');$('#save-feedback').onclick=()=>download('OUT-OF-PANEL-feedback.txt',message(),'text/plain');
}
$('#feedback-open').onclick=feedback;$('#physical-open').onclick=()=>{modal(physicalMarkup);$('#physical-feedback').onclick=feedback};
function giftURL(){const u=new URL(location.href);u.search='';u.searchParams.set('gift','window');u.hash='object';return u.href}
function invitation(){return 'I found a world hiding inside a coin. Turn it, look inside, and return it to page 04.\n'+giftURL()}
function savePassedFile(){if(!IS_PORTABLE){toast('Use the public link to pass on this release.');return}const doc=new DOMParser().parseFromString(PORTABLE_SOURCE,'text/html');doc.querySelector('#starting-position')?.remove();doc.querySelector('#gift-arrival')?.remove();const gift=doc.createElement('script');gift.id='gift-arrival';gift.type='application/json';gift.textContent='{"gift":"window"}';doc.head.appendChild(gift);download('HERE-CATCH-OUT-OF-PANEL.html','<!doctype html>'+doc.documentElement.outerHTML,'text/html');toast('Invitation saved. Send the HTML file to a friend.')}
function passOn(){if(!reduced()&&view==='object'){$coin.classList.add('pass-going');setTimeout(()=>$coin.classList.remove('pass-going'),850)}const publicPage=/^https?:$/.test(location.protocol)&&!['localhost','127.0.0.1','0.0.0.0'].includes(location.hostname);modal('<p class="dialog-kicker">HERE. CATCH.</p><canvas id="pass-coin" class="pass-coin" width="256" height="256" aria-hidden="true"></canvas><h2 id="dialog-title">A small world.<br>Better with a witness.</h2><p>Your friend arrives with a coin and a new greeting: <em>“Ah. They sent you.”</em> Let them discover the rest.</p><div class="pass-actions">'+(publicPage?'<button id="copy-gift" class="primary">Copy the invitation <span>↗</span></button><button id="native-share" class="outline-btn">Share via your device</button>':'<button id="save-gift" class="primary">Save a playable invitation <span>↓</span></button>')+'<button id="position-share" class="outline-btn">Share my board position</button></div><p class="legal-note pass-boundary">'+(publicPage?'A public experience link.':'This is the offline edition. Send the saved HTML file, not its local address.')+' This passes on an encounter, not ownership. No account, wallet or live multiplayer.</p>');try{const c=$('#pass-coin');c.getContext('2d').drawImage(coinCanvas,0,0,256,256)}catch{}
 if(publicPage){$('#copy-gift').onclick=()=>copy(invitation(),'Invitation copied. Nothing has been sent automatically.');$('#native-share').hidden=!navigator.share;$('#native-share').onclick=async()=>{try{await navigator.share({title:'Here. Catch. — OUT OF PANEL',text:'There’s a world hiding inside this coin.',url:giftURL()})}catch(e){if(e.name!=='AbortError')copy(invitation())}}}else $('#save-gift').onclick=savePassedFile;
 $('#position-share').onclick=()=>{closeModal();shareDialog(true)};
}
$('#share').onclick=passOn;$('#share-footer').onclick=passOn;
function arrived(){let gift;try{gift=new URL(location.href).searchParams.get('gift')==='window'||JSON.parse($('#gift-arrival')?.textContent||'{}').gift==='window'}catch{}if(!gift)return;switchView('object',{scroll:false});$('#wonder-title').innerHTML='Ah.<br><em>They sent<br>you.</em>';$('#wonder-lead').innerHTML='Someone thought you’d like this.<br>They might be right.';if(!reduced()){$coin.classList.add('shared-arrival');setTimeout(()=>$coin.classList.remove('shared-arrival'),1700)}announce('A coin has arrived for you. Turn it, then look inside.')}
window.addEventListener('oop-view',e=>{if(e.detail.view!=='object'&&inside)exitWorld();if(e.detail.view!=='return')abortReturn();syncReturn()});window.addEventListener('oop-reset',()=>{exitWorld();abortReturn();syncReturn()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&inside&&!dialog.open&&!readerDialog.open){exitWorld();$('#look-inside').focus()}});
// Non-invasive, deterministic hooks for release tests and integrations.
window.OutOfPanelWonder=Object.freeze({version:'0.5.0',tick,enterWorld,exitWorld,visitReturn,giveBack,feedback,passOn,getState:()=>({inside,returning,returned:session.returned,discovered:session.discovered,renderer:coinRenderer.kind,activeTime}),project,starSVG});
try{const im=document.createElement('canvas');im.width=im.height=192;im.getContext('2d').drawImage(CoinStudio.getSprites()[0],0,0);$('.printed-coin').replaceChildren(im)}catch{}
paintWorld(5.1);syncReturn();arrived();
PORTABLE_SOURCE='<!doctype html>'+document.documentElement.outerHTML;
})();
