const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const stamp=()=>new Date().toLocaleString('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
let currentCase='careos',currentRole='clinical',proofMode=false;
const stateByCase={};
const $=s=>document.querySelector(s);
function cloneInitial(c){return Object.fromEntries(Object.entries(c.initial).map(([id,x])=>[id,{...x,events:[{at:x.updated,text:x.event}]}]));}
function state(){if(!stateByCase[currentCase])stateByCase[currentCase]=cloneInitial(cases[currentCase]);return stateByCase[currentCase];}
function taskStatus(id){return state()[id]?.status||'assigned';}
function stageDone(c,s){return s.tasks.every(id=>taskStatus(id)==='verified');}
function currentStageIndex(c){return c.stages.findIndex(s=>!stageDone(c,s));}
function roleAccess(){return cases[currentCase].roles[currentRole]?.access||'public';}
function allOpenOwners(c,s){return s.tasks.filter(id=>taskStatus(id)!=='verified').map(id=>c.tasks[id].owner);}
function effectiveDisputes(c){return (c.disputes||[]).map(d=>({...d,effectiveState:d.resolutionTask&&taskStatus(d.resolutionTask)==='verified'?'gelöst':d.state}));}
function taskViewForRole(c){const i=currentStageIndex(c);if(i===-1)return{kind:'complete'};const stage=c.stages[i];for(const id of stage.tasks){const t=c.tasks[id],s=taskStatus(id);if(t.ownerRole===currentRole&&['assigned','in_progress','rejected','expired','reopened'].includes(s))return{kind:'owner',id,t,status:s};if(t.ownerRole===currentRole&&s==='submitted')return{kind:'submitted',id,t,status:s};if(t.verifierRole===currentRole&&s==='submitted')return{kind:'verifier',id,t,status:s};if(t.receipt&&t.ownerRole===currentRole&&s==='submitted')return{kind:'receipt',id,t,status:s};}
for(const id of stage.tasks){const t=c.tasks[id],s=taskStatus(id);if(t.verifierRole===currentRole&&['assigned','in_progress'].includes(s))return{kind:'wait-verifier',id,t,status:s,waitFor:[t.owner]};}
for(let j=i+1;j<c.stages.length;j++){for(const id of c.stages[j].tasks){const t=c.tasks[id];if(t.ownerRole===currentRole||t.verifierRole===currentRole)return{kind:'wait',id,t,status:taskStatus(id),waitFor:allOpenOwners(c,stage)};}}
for(const id of stage.tasks){const t=c.tasks[id];if((t.ownerRole===currentRole||t.verifierRole===currentRole)&&taskStatus(id)==='verified')return{kind:'done',id,t,status:'verified'};}
return{kind:'wait',id:null,t:null,status:'assigned',waitFor:allOpenOwners(c,stage)};}
function setStatus(id,status,text){const s=state()[id];s.status=status;s.updated=stamp();s.event=text;s.events.unshift({at:s.updated,text});const t=cases[currentCase].tasks[id];if(status==='submitted'){s.evidenceRef=s.evidenceRef||t.evidence;s.hash=s.hash||'sha256:'+Math.random().toString(16).slice(2,8)+'…'+Math.random().toString(16).slice(2,5);s.signature=s.signature||t.owner;}if(status==='verified')s.signature=t.verifier;}
function renderSelectors(){const c=cases[currentCase];$('#caseSelect').innerHTML=Object.entries(cases).map(([id,x])=>`<option value="${id}" ${id===currentCase?'selected':''}>${x.label}</option>`).join('');$('#roleSelect').innerHTML=Object.entries(c.roles).map(([id,r])=>`<option value="${id}" ${id===currentRole?'selected':''}>${r.name}</option>`).join('');}
function renderShared(){const c=cases[currentCase],i=currentStageIndex(c),complete=i===-1;$('#nowTitle').textContent=complete?'Ziel erreicht':c.stages[i].label;$('#nowText').textContent=complete?c.outcome:`${c.stages[i].tasks.filter(id=>taskStatus(id)!=='verified').length} notwendige ${c.stages[i].tasks.filter(id=>taskStatus(id)!=='verified').length===1?'Arbeit ist':'Arbeiten sind'} noch nicht verifiziert.`;$('#etaText').textContent=complete?'Erreicht':c.forecast[i]||c.stages[i].eta;const ids=complete?c.stages.at(-1).tasks:c.stages[i].tasks;const latest=ids.map(id=>state()[id]).sort((a,b)=>String(b.updated).localeCompare(String(a.updated)))[0];$('#etaNote').textContent=complete?'Alle Completion-Kriterien erfüllt.':`Planwert · keine Garantie${latest?' · letzter State '+latest.updated:''}`;$('#nowList').innerHTML=ids.map(id=>{const t=c.tasks[id],s=taskStatus(id),st=state()[id],mine=t.ownerRole===currentRole||t.verifierRole===currentRole;return`<div class="now-row s-${s} ${mine?'mine':''}"><span class="dot"></span><div><b>${t.title}</b><div class="meta">Owner: ${t.owner} · prüft: ${t.verifier} · ${st.updated}</div></div><span class="state">${STATUS[s]}</span></div>`}).join('');$('#sharedCount').textContent=complete?'Terminaler Outcome ist verifiziert.':`${c.stages[i].tasks.filter(id=>taskStatus(id)==='verified').length}/${c.stages[i].tasks.length} in diesem Schritt verifiziert`;$('#sharedTruth').textContent=complete?'Grün = Outcome nachgewiesen':'Grün = DoD + Evidence + Verifier';}
function renderProof(t,v){const r=cases[currentCase].roles[currentRole],s=v.id?state()[v.id]:null;$('#proof').classList.toggle('show',proofMode);$('#proof').innerHTML=`<div class="proof-grid"><div class="proof-card"><small>Identität & Befugnis</small><b>${r.authority}</b><span>Rolle aus autoritativer Identity-/Mandatsquelle.</span></div><div class="proof-card"><small>Scope & Gültigkeit</small><b>${t.scope||'gesamter Case'}</b><span>${t.validity||'bis relevante Änderung'}</span></div><div class="proof-card"><small>Evidence Source</small><b>${t.source||'autoritative Quelle'}</b><span>${s?.evidenceRef||t.evidence||'noch kein Evidence-Receipt'}</span></div><div class="proof-card"><small>Integrität</small><b>${s?.hash||'noch nicht gehasht'}</b><span>${s?.signature?`bestätigt/signiert durch ${s.signature}`:'noch keine verifizierte Signatur'}</span></div></div>`;}
function renderAction(){const c=cases[currentCase],r=c.roles[currentRole],v=taskViewForRole(c),box=$('#action');$('#avatar').textContent=r.short;$('#roleName').textContent=r.name;let title='',text='',kicker='',cls='',task=null,primary='',secondary=false,disabled=false;if(currentRole==='public'||currentRole==='audit'){kicker=currentRole==='public'?'Transparenzansicht':'Audit-Perspektive';title='Keine operative Aufgabe.';text=currentRole==='public'?'Du siehst veröffentlichbare Zustände, Geldflüsse, Meilensteine und Evidence-IDs desselben Projektgraphen.':'Du prüfst Evidence, Authority, Finanzfluss und Änderungen, ohne operativen State zu verändern.';cls='done';disabled=true;primary='Nur lesen';}else if(v.kind==='complete'){kicker='Case abgeschlossen';title='Das Ziel ist verifiziert erreicht.';text=c.outcome;cls='done';disabled=true;primary='Keine Aktion nötig';}else if(v.kind==='owner'){task=v.t;kicker=['rejected','expired','reopened'].includes(v.status)?'Erneut offen · deine Aufgabe':'Deine Aufgabe jetzt';title=task.title;text=v.status==='rejected'?'Der Verifier hat den Nachweis zurückgewiesen. Überarbeite genau diesen Punkt.':v.status==='expired'?'Die frühere Bestätigung ist abgelaufen. Dieser Scope muss erneut geprüft werden.':task.text;cls=['rejected','expired','reopened'].includes(v.status)?'problem':'';primary=['assigned','rejected','expired','reopened'].includes(v.status)?'Arbeit beginnen':'Mit Nachweis einreichen';}else if(v.kind==='submitted'){task=v.t;kicker='Eingereicht · wartet auf Prüfung';title='Dein Nachweis ist abgegeben.';text=`${task.verifier} prüft jetzt gegen die Definition of Done. Du musst nichts erneut senden, solange keine Rückfrage kommt.`;cls='wait';disabled=true;primary=`Wartet auf ${task.verifier}`;}else if(v.kind==='verifier'){task=v.t;kicker='Du prüfst jetzt';title=`Prüfe: ${task.title}`;text=`${task.owner} hat Evidence eingereicht. Bestätige nur, wenn Definition of Done, Scope und Evidence zusammenpassen.`;primary='Prüfen & verifizieren';secondary=true;}else if(v.kind==='receipt'){task=v.t;kicker='Autoritativer Abschluss';title=`Bestätige: ${task.title}`;text='Der autoritative Receipt ist der Abschlussnachweis für diesen Schritt.';primary='Receipt bestätigen';}else if(v.kind==='done'){task=v.t;kicker='Für diesen Stand erledigt';title='Dein Beitrag ist verifiziert.';text='OpenAction aktiviert dich erst wieder bei relevanter Änderung, Ablauf oder neuer Aufgabe.';cls='done';disabled=true;primary='Keine Aktion nötig';}else{kicker='Du musst gerade nichts tun';title='Der Case ist bei anderen Rollen.';text=`Aktuell wartet der gemeinsame Schritt auf ${[...new Set(v.waitFor||[])].join(', ')||'andere Rollen'}.`;cls='wait';disabled=true;primary='Noch nicht an der Reihe';task=v.t;}
box.className='action '+cls;$('#actionKicker').textContent=kicker;$('#taskTitle').textContent=title;$('#taskText').textContent=text;const t=task||{dod:c.outcomeDod,verifier:'Outcome-Verifier',eta:'—',evidence:'Outcome receipt',source:'autoritative Quelle',scope:'gesamter Case',validity:'final'};$('#dodText').textContent=t.dod;$('#verifyText').textContent=t.verifier;$('#taskEta').textContent=t.eta;$('#actionBtn').textContent=primary;$('#actionBtn').disabled=disabled;$('#actionBtn').dataset.task=v.id||'';$('#actionBtn').dataset.kind=v.kind;$('#rejectBtn').hidden=!secondary;$('#rejectBtn').dataset.task=v.id||'';$('#impactTitle').textContent=v.kind==='owner'?'Dein Nachweis geht an den Verifier.':v.kind==='submitted'?'Keine weitere Aktion bis Review.':v.kind==='verifier'||v.kind==='receipt'?'Bei Bestätigung verändert sich der gemeinsame State.':v.kind==='complete'?'Keine offenen Pflichtarbeiten mehr.':'Keine künstliche Busy Work.';$('#impactText').textContent=v.kind==='owner'?`Erst ${t.verifier} kann diesen Knoten grün machen.`:v.kind==='submitted'?`${t.verifier} sieht denselben Evidence-Receipt und kann verifizieren oder gezielt zurückweisen.`:v.kind==='verifier'||v.kind==='receipt'?'Verifizieren kann den nächsten Meilenstein freischalten; Zurückweisen öffnet genau diesen Knoten wieder.':v.kind==='complete'?c.outcomeDod:'Du wirst sichtbar aktiviert, wenn deine Rolle wirklich gebraucht wird.';renderProof(t,v);}
function renderJourney(){const c=cases[currentCase],i=currentStageIndex(c),complete=i===-1;const items=[...c.past.map(label=>({label,eta:'verifiziert',state:'done'})),...c.stages.map((s,idx)=>({label:s.label,eta:s.eta,state:stageDone(c,s)?'done':idx===i?'now':'future'})),{label:'Ziel erreicht',eta:c.outcome,state:complete?'done':'future',final:true}];$('#journey').style.setProperty('--route-count',items.length);$('#journey').innerHTML=items.map(x=>`<div class="route-step ${x.state} ${x.final?'final':''}"><div class="route-icon">${x.state==='done'?'✓':x.state==='now'?'●':x.final?'◎':'○'}</div><b>${x.label}</b><small>${x.eta}</small>${x.state==='now'?'<span class="here">Du bist hier</span>':''}</div>`).join('');}
function renderMoney(){const c=cases[currentCase],f=c.financeFlow,el=$('#moneyInfo');if(!f){el.innerHTML='<p>Für diesen Case wird kein Projektbudget als relevanter Teil des OpenAction-Graphen dargestellt.</p>';return;}const stats=[['Bewilligt',f.budget],['Gebunden',f.committed],['Bezahlt',f.paid],['Abgeglichen',f.reconciled]];el.innerHTML=`<div class="flow-summary">${stats.map(([l,v])=>`<div class="flow-stat"><small>${l}</small><b>${euro(v)}</b></div>`).join('')}</div>${f.forecast>f.budget?`<p><strong>⚠ Forecast ${euro(f.forecast)}</strong> liegt über dem bewilligten Budget ${euro(f.budget)}.</p>`:''}<div>${f.nodes.map(n=>{const [icon,label,amount,status,evidence,source,visibility]=n,visible=ACCESS[roleAccess()]>=ACCESS[visibility];return`<div class="money-line"><div class="money-icon">${icon}</div><div><b>${label}</b><span>${status} · ${visible?source:'geschützte Quelle'} · Evidence ${evidence}</span></div><em class="${visible?'':'redacted'}">${visible?euro(amount):'geschützt'}</em></div>`}).join('')}</div><p>${f.note}</p>`;}
function renderEvidence(){const c=cases[currentCase],events=[];for(const [id,t] of Object.entries(c.tasks)){const s=state()[id];for(const e of s.events||[])events.push({at:e.at,text:e.text,task:t.title,status:s.status});}events.sort((a,b)=>String(b.at).localeCompare(String(a.at)));$('#historyInfo').innerHTML=`<div class="timeline">${events.slice(0,15).map(e=>`<div class="event"><time>${e.at}</time><div><b>${e.text}</b><span>${e.task} · ${STATUS[e.status]}</span></div></div>`).join('')}</div>`;}
function renderTrust(){const c=cases[currentCase],ds=effectiveDisputes(c),open=ds.filter(d=>d.effectiveState==='offen');$('#trustInfo').innerHTML=`<div class="trust"><div class="trust-card"><small>Authority</small><b>Rollen an Identity/Mandat gebunden</b></div><div class="trust-card"><small>Change Impact</small><b>${c.changes.length} gezielte Reopen-Regeln</b></div><div class="trust-card"><small>Disputes</small><b>${open.length?`${open.length} offen`:'keine offen'}</b></div></div>${c.changes.length?`<p><strong>Change Impact:</strong> ${c.changes.map(x=>`${x[0]} → ${x[1]}`).join(' · ')}</p>`:''}${ds.length?`<p><strong>Disputes:</strong> ${ds.map(x=>`${x.label}: ${x.effectiveState}${x.resolutionTask?' · Abschluss über '+c.tasks[x.resolutionTask].title:''}`).join(' · ')}</p>`:''}<p>Expiry, Scope Change oder Dispute öffnen nur betroffene Knoten. Jeder Reopen wird als neues Event protokolliert.</p>`;}
function render(){const c=cases[currentCase];renderSelectors();$('#caseTitle').textContent=c.title;$('#caseGoal').textContent=c.goal;$('#caseNote').textContent=c.note;renderShared();renderAction();renderJourney();renderMoney();renderEvidence();renderTrust();$('#simpleMode').classList.toggle('active',!proofMode);$('#proofMode').classList.toggle('active',proofMode);}
$('#caseSelect').onchange=e=>{currentCase=e.target.value;currentRole=Object.keys(cases[currentCase].roles)[0];proofMode=false;render();};
$('#roleSelect').onchange=e=>{currentRole=e.target.value;render();};
$('#resetBtn').onclick=()=>{delete stateByCase[currentCase];currentRole=Object.keys(cases[currentCase].roles)[0];proofMode=false;render();toast('Demo zurückgesetzt');};
$('#simpleMode').onclick=()=>{proofMode=false;render();};
$('#proofMode').onclick=()=>{proofMode=true;render();};
$('#actionBtn').onclick=e=>{const id=e.currentTarget.dataset.task,kind=e.currentTarget.dataset.kind;if(!id)return;if(kind==='owner'){const s=taskStatus(id);if(['assigned','rejected','expired','reopened'].includes(s))setStatus(id,'in_progress',`${cases[currentCase].tasks[id].owner} hat die Arbeit angenommen`);else if(s==='in_progress')setStatus(id,'submitted',`${cases[currentCase].tasks[id].owner} hat Evidence eingereicht`);}else if(kind==='verifier'||kind==='receipt'){setStatus(id,'verified',`${cases[currentCase].tasks[id].verifier} hat Definition of Done + Evidence verifiziert`);}render();toast('Shared State aktualisiert');};
$('#rejectBtn').onclick=e=>{const id=e.currentTarget.dataset.task;if(!id)return;setStatus(id,'rejected',`${cases[currentCase].tasks[id].verifier} hat zurückgewiesen · Überarbeitung nötig`);render();toast('Zurückgewiesen · Owner ist wieder dran');};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500);}
render();