const STATUS={assigned:'Zugewiesen',in_progress:'In Arbeit',submitted:'Eingereicht',verified:'Verifiziert',rejected:'Zurückgewiesen',expired:'Abgelaufen',reopened:'Wieder offen'};
const ACCESS={public:0,internal:1,restricted:2};
const R=(short,name,access,authority)=>({short,name,access,authority});
const T=(ownerRole,owner,verifierRole,verifier,title,dod,evidence,source,eta,scope,validity,extra={})=>({ownerRole,owner,verifierRole,verifier,title,dod,evidence,source,eta,scope,validity,text:extra.text||title,receipt:!!extra.receipt});
const I=(status,event,updated,extra={})=>({status,event,updated,...extra});
const cases={
  careos:{
    label:'CareOS',title:'CareOS Pilot im Krankenhaus',goal:'Bis zu einem verifizierten Shadow-Pilot-Ergebnis kommen, das eine sichere 5-User-Entscheidung erlaubt.',outcome:'Shadow-Ergebnis verifiziert · 5-User Pilot ist entscheidbar',outcomeDod:'Alle Pflichtreviews verifiziert, Pilotentscheidung dokumentiert und 50/50 Shadow Cases gegen die Safety-Grenzen geprüft.',note:'Synthetisches Krankenhaus-Beispiel. Planzeiten und Beträge sind illustrative Werte, keine Freigabe oder Garantie.',past:['Scope definiert'],forecast:['26.–27. Aug 2026 · illustrativer Plan','27.–28. Aug 2026 · nach Reviews','31. Aug–2. Sep 2026 · nach Pilotentscheid'],
    stages:[{label:'Reviews',eta:'1–2 AT',tasks:['clinical','privacy','security','contract','finance']},{label:'Pilotentscheidung',eta:'≤ 1 AT',tasks:['sponsor']},{label:'Shadow Mode',eta:'2–3 AT',tasks:['shadow']}],
    roles:{clinical:R('CL','Clinical Owner','internal','Hospital IAM · Clinical Owner Assignment'),clinicalSafety:R('CS','Clinical Safety','internal','Hospital IAM · Safety Reviewer'),privacy:R('DS','Datenschutz Vorbereitung','restricted','Hospital IAM · Privacy Working Role'),dpo:R('DP','Datenschutzbeauftragte:r','restricted','DPO role registry'),security:R('IT','IT & Security','restricted','Hospital IAM · Security Engineer'),securityLead:R('SL','Security Lead','restricted','Security approval group'),contract:R('EK','Einkauf','restricted','Procurement role registry'),legal:R('LG','Legal','restricted','Legal approval group'),finance:R('FI','Finanzen / Controlling','restricted','Finance role registry'),sponsor:R('SP','Pilot-Sponsor','internal','Named pilot sponsor mandate')},
    tasks:{
      clinical:T('clinical','Clinical','clinicalSafety','Clinical Safety','3 klinisch kritische Fehler definieren','3 Fehlerklassen + Schwellenwerte dokumentiert','Clinical boundary v1','CareOS evaluation repository','≤ 4 h','CareOS Shadow Pilot v1','bis Scope/Modell/Safety-Grenze geändert wird',{text:'Die klinische Grenze des Piloten wird vorbereitet.'}),
      privacy:T('privacy','Datenschutz','dpo','DPO','DPIA-Screening abschließen','Risiken, Datenfluss und Entscheidung dokumentiert','DPIA screening receipt','Privacy management system','≤ 1 AT','Read-only Shadow Pilot','bis Datenfluss/Hosting/Zweck geändert wird'),
      security:T('security','Security','securityLead','Security Lead','Security Review bestätigen','Kontrollen geprüft + Abweichungen dokumentiert','Security review #SEC-17','Security GRC','erledigt','Read-only integration v1','90 Tage oder bis relevante Änderung'),
      contract:T('contract','Einkauf','legal','Legal','DPA / AVV und Exit klären','DPA/AVV + Exit-Bedingungen akzeptabel','Contract review package v3','Contract system','≤ 1 AT','30-Tage Pilot','für Vertragsversion v3'),
      finance:T('finance','Controlling','sponsor','Pilot-Sponsor','Pilotbudget bestätigen','Budgetquelle + Obergrenze + Kostenstellenbezug verifiziert','Budget approval #CARE-26-04','Finance / Kostenstelle','erledigt','Pilotbudget max. €60.000','bis Budget-/Scope-Änderung'),
      sponsor:T('sponsor','Sponsor','finance','Controlling','Bounded Shadow Pilot entscheiden','Scope + Conditions + Stop + Rollback + Budgetlimit dokumentiert','Approval Receipt','OpenAction receipt + hospital authority','≤ 2 h nach Reviews','30 Tage · read-only · keine autonome Versorgung','bis Scope/Modell/Datenfluss wesentlich geändert wird'),
      shadow:T('clinicalSafety','Clinical Safety','clinical','Clinical Owner','50 Shadow Cases reviewen','50/50 Cases geprüft + kritische Findings dispositioniert','Shadow evaluation receipt','CareOS evaluation repository','2–3 AT','50 reale Shadow Cases','für getestete Modell-/Prompt-/Workflow-Version')
    },
    initial:{clinical:I('in_progress','Clinical begann · Draft geöffnet','24.08. 10:20'),privacy:I('assigned','Zugewiesen · noch kein Nachweis','24.08. 09:15'),security:I('verified','Security Lead verifiziert · #SEC-17','23.08. 16:10',{evidenceRef:'SEC-17',hash:'sha256:a83…19c',signature:'Security Lead'}),contract:I('submitted','Eingereicht · Contract package v3','24.08. 11:05',{evidenceRef:'CTR-v3',hash:'sha256:7be…44a',signature:'Einkauf'}),finance:I('verified','Budget verifiziert · #CARE-26-04','22.08. 14:30',{evidenceRef:'CARE-26-04',hash:'sha256:92e…c10',signature:'Pilot-Sponsor'}),sponsor:I('assigned','Wartet auf verifizierte Reviews','24.08. 09:00'),shadow:I('assigned','Wartet auf Pilotentscheidung','24.08. 09:00')},
    financeFlow:{budget:60000,committed:32000,invoiced:11500,paid:8000,reconciled:8000,forecast:52000,note:'OpenAction referenziert autoritative Finanzquellen; es führt kein zweites Hauptbuch.',nodes:[['◎','Innovationsbudget',60000,'bewilligt','CARE-26-04','Finance / Kostenstelle','internal'],['↗','Pilotmittel gebunden',32000,'gebunden','PO + Vertrag v3','Einkauf','internal'],['▤','Lieferantenrechnung',11500,'abgerechnet','INV-204','Kreditorenbuchhaltung','restricted'],['→','Zahlung',8000,'bezahlt','TX-884','Zahlungsledger','restricted'],['✓','Zahlung + Leistung abgeglichen',8000,'abgeglichen','REC-41 + milestone','Controlling','internal']]},
    changes:[['Modellversion geändert','Clinical + Shadow Evaluation reopen'],['Hosting geändert','Privacy + Security reopen'],['nur UI-Text geändert','keine Approval-Reopen']],disputes:[]
  },
  naturalization:{
    label:'Einbürgerung',title:'Einbürgerungsantrag',goal:'Bis zu einer dokumentierten Entscheidung kommen — mit klaren Übergaben und belegbarem Status.',outcome:'Entscheidung dokumentiert und Zustellung ausgelöst',outcomeDod:'Fachprüfung abgeschlossen, autoritativer Bescheid erstellt und Zustellung dokumentiert.',note:'Synthetisches Verwaltungsbeispiel. Anforderungen und Zeiten variieren nach Fall und Behörde.',past:['Antrag eingegangen'],forecast:['nach Dokumentprüfung · Fachverfahren liefert ETA','behördlicher SLA · keine Demo-Schätzung','nach Fachprüfung · Zustellweg bestimmt ETA'],stages:[{label:'Vollständigkeit',eta:'nach Eingang',tasks:['citizenDoc']},{label:'Fachprüfung',eta:'behördlicher SLA',tasks:['review']},{label:'Entscheidung',eta:'nach Prüfung',tasks:['decision']}],
    roles:{citizen:R('AN','Antragsteller:in','public','eID / verifizierter Antragsteller'),clerk:R('SB','Sachbearbeitung','internal','Behörden-IAM'),reviewer:R('FP','Fachprüfung','internal','Behörden-IAM'),authority:R('BE','Entscheidungsstelle','restricted','Entscheidungsbefugnis im Fachverfahren')},
    tasks:{citizenDoc:T('citizen','Antragsteller','clerk','Sachbearbeitung','Einkommensnachweis einreichen','aktueller Nachweis lesbar und dem richtigen Fall zugeordnet','Dokument + Eingangsbeleg','Dokumenten-/Fachverfahren','nach Einreichung','dieser Antrag','bis Aktualisierung erforderlich'),review:T('reviewer','Fachprüfung','authority','Entscheidungsstelle','Fachprüfung abschließen','Prüfpunkte abgearbeitet + Ergebnis begründet','Prüfvermerk','Fachverfahren','behördlicher SLA','dieser Antrag','bis entscheidungsrelevante Tatsachen geändert werden'),decision:T('authority','Entscheidungsstelle',null,'Authoritativer Bescheid','Entscheidung dokumentieren','Bescheid erstellt + Zustellung ausgelöst','Bescheid / Zustellnachweis','Fachverfahren / Zustelldienst','nach Prüfung','dieser Antrag','autoritativer Outcome',{receipt:true})},
    initial:{citizenDoc:I('submitted','Nachweis eingegangen · upload #INC-44','24.08. 09:40',{evidenceRef:'INC-44',hash:'sha256:31a…77d',signature:'eID session'}),review:I('assigned','Wartet auf Vollständigkeit','24.08. 09:41'),decision:I('assigned','Wartet auf Fachprüfung','24.08. 09:41')},financeFlow:null,changes:[['neuer Wohnsitz','betroffene Zuständigkeit/Prüfschritte neu bewerten']],disputes:[]
  },
  housing:{
    label:'Wohngeld',title:'Wohngeldantrag',goal:'Vom fehlenden Nachweis bis zum dokumentierten Bescheid kommen.',outcome:'Bescheid erstellt und Zustellung dokumentiert',outcomeDod:'Nachweise verifiziert, Berechnung geprüft, Bescheid erzeugt und Zustellung dokumentiert.',note:'Synthetisches Verwaltungsbeispiel. Keine Anspruchs- oder Zeitgarantie.',past:['Antrag eingegangen'],forecast:['nach Upload + Dokumentprüfung','behördlicher SLA · keine Demo-Schätzung','nach Prüfung · Zustellweg bestimmt ETA'],stages:[{label:'Nachweise',eta:'nach Upload',tasks:['paySlip']},{label:'Prüfung',eta:'behördlicher SLA',tasks:['income']},{label:'Bescheid',eta:'nach Prüfung',tasks:['decision']}],
    roles:{citizen:R('AN','Antragsteller:in','public','eID / verifizierter Antragsteller'),clerk:R('SB','Sachbearbeitung','internal','Behörden-IAM'),specialist:R('FP','Fachprüfung','internal','Behörden-IAM')},
    tasks:{paySlip:T('citizen','Antragsteller','clerk','Sachbearbeitung','Gehaltsabrechnung hochladen','lesbare Abrechnung für den richtigen Monat zugeordnet','Dokument + Eingangsbeleg','Dokumentenservice','durch Antragsteller','dieser Antrag','für angeforderten Zeitraum'),income:T('clerk','Sachbearbeitung','specialist','Fachprüfung','Einkommensprüfung abschließen','Einkommen geprüft + Abweichungen geklärt','Prüfvermerk Einkommen','Fachverfahren','behördlicher SLA','dieser Antrag','bis neue Einkommensdaten relevant werden'),decision:T('specialist','Fachprüfung',null,'Authoritativer Bescheid','Bescheid dokumentieren','Bescheid erzeugt + Zustellung ausgelöst','Bescheid / Zustellnachweis','Fachverfahren','nach Prüfung','dieser Antrag','autoritativer Outcome',{receipt:true})},
    initial:{paySlip:I('assigned','Nachforderung versendet · noch kein Eingang','24.08. 08:10'),income:I('assigned','Wartet auf Nachweis','24.08. 08:10'),decision:I('assigned','Wartet auf Prüfung','24.08. 08:10')},financeFlow:null,changes:[],disputes:[]
  },
  company:{
    label:'UG-Gründung',title:'UG-Gründung',goal:'Bis zur nachgewiesenen Registereintragung kommen.',outcome:'Registereintragung verifiziert',outcomeDod:'Kapitalnachweis verifiziert, formales Paket eingegangen und Registereintrag autoritativ bestätigt.',note:'Synthetisches Gründungsbeispiel. Keine Rechts- oder Steuerberatung.',past:['Gründungsunterlagen'],forecast:['nach Bankbestätigung','nach Notariats-/Registereingang','Register-SLA · keine Demo-Schätzung'],stages:[{label:'Kapitalnachweis',eta:'nach Bank',tasks:['bank']},{label:'Einreichung',eta:'Notariat',tasks:['file']},{label:'Register',eta:'Register-SLA',tasks:['register']}],
    roles:{founder:R('GR','Gründer:in','internal','verifizierte Gründeridentität'),notary:R('NO','Notariat','restricted','Notariatsidentität / Mandat'),registry:R('RG','Register','restricted','autoritative Registerstelle')},
    tasks:{bank:T('founder','Gründer','notary','Notariat','Banknachweis bereitstellen','Nachweis authentisch + Gesellschaft eindeutig zugeordnet','Banknachweis','Bank / Dokumentenraum','abhängig von Bank','diese UG','für Gründungsvorgang'),file:T('notary','Notariat','registry','Register','Einreichung vorbereiten','formal vollständiges Paket beim Register eingegangen','Einreichungs-/Eingangsbeleg','Notariat/Register','Notariat','diese UG','für eingereichte Fassung'),register:T('registry','Register',null,'Registereintrag','Eintragung dokumentieren','Registereintrag veröffentlicht / bestätigt','Registerauszug','Handelsregister','Register-SLA','diese UG','autoritativer Outcome',{receipt:true})},
    initial:{bank:I('submitted','Banknachweis eingereicht · bank-proof.pdf','24.08. 12:00',{evidenceRef:'bank-proof.pdf',hash:'sha256:54d…e21',signature:'Founder eID'}),file:I('assigned','Wartet auf verifizierten Banknachweis','24.08. 12:00'),register:I('assigned','Wartet auf Einreichung','24.08. 12:00')},financeFlow:null,changes:[],disputes:[]
  },
  gov:{
    label:'Government Projekt',title:'Digitales Bürgerportal',goal:'Öffentlich finanziertes Digitalprojekt vom Budget bis zum verifizierten Nutzen transparent verfolgen.',outcome:'Lieferung abgenommen · Zahlungen abgeglichen · Outcome veröffentlicht',outcomeDod:'Vertrag verifiziert, Lieferung unabhängig abgenommen, Finanzfluss abgeglichen und Outcome-Metrik veröffentlicht.',note:'Synthetisches Government-Projekt. Beträge, Rollen und Planzeiten sind illustrative Daten.',past:['Bedarf & Budget'],forecast:['Sep–Okt 2026 · Demo-Plan','danach ca. 8 Wochen','danach ca. 1 Woche','30 Tage nach Launch'],stages:[{label:'Vergabe & Vertrag',eta:'3–6 Wochen',tasks:['procurement','budget']},{label:'Lieferung',eta:'8 Wochen',tasks:['delivery']},{label:'Abnahme',eta:'1 Woche',tasks:['acceptance']},{label:'Outcome',eta:'30 Tage',tasks:['outcome']}],
    roles:{owner:R('PO','Projektleitung','internal','Behörden-IAM · Project Owner mandate'),procurement:R('VG','Vergabe / Einkauf','restricted','eVergabe role assignment'),finance:R('FI','Finanzen / Controlling','restricted','Finance role registry'),supplier:R('AN','Auftragnehmer','internal','Contracted supplier identity'),qa:R('QA','Unabhängige Abnahme','internal','Independent acceptance mandate'),public:R('ÖF','Öffentliche Transparenzansicht','public','öffentliche Projektion · keine Schreibrechte'),audit:R('AU','Audit / Rechnungshof','restricted','Audit mandate / read authority')},
    tasks:{procurement:T('procurement','Vergabe','owner','Projektleitung','Vergabe und Vertrag abschließen','Award + Vertrag + Scope + Wert dokumentiert','OCDS contracting record OCID-DE-DEMO-1','eVergabe / Vertragsregister','3–6 Wochen','Vergabe Los 1','für Vertragsfassung v1'),budget:T('finance','Controlling','owner','Projektleitung','Budgetbindung bestätigen','Budgetquelle + Bindung + Obergrenze verifiziert','Budget line B-2026-4711','Haushaltssystem','≤ 1 AT nach Vertrag','Projektbudget','bis Haushalts-/Vertragsänderung'),delivery:T('supplier','Auftragnehmer','qa','Unabhängige QA','MVP liefern','vereinbarte Funktionen + Tests + Dokumentation geliefert','Milestone M1 package','Delivery repository / artifact store','8 Wochen','Milestone M1','für abgenommene Version'),acceptance:T('qa','Unabhängige QA','owner','Projektleitung','Leistung abnehmen','Akzeptanzkriterien bestanden oder Abweichungen dispositioniert','Acceptance receipt AR-1','Acceptance register','1 Woche','Milestone M1','für geprüfte Version'),outcome:T('owner','Projektleitung','finance','Controlling / Audit','Outcome und Finanzabschluss bestätigen','Zahlungen abgeglichen + Outcome-Metrik veröffentlicht','Outcome report + reconciliation','Outcome dashboard + finance ledger','30 Tage nach Launch','Projektabschluss','finaler Abschluss für Messzeitraum')},
    initial:{procurement:I('submitted','Vergabeakte eingereicht · OCID-DE-DEMO-1','21.08. 16:40',{evidenceRef:'OCID-DE-DEMO-1',hash:'sha256:91c…a40',signature:'eVergabe'}),budget:I('in_progress','Budgetabgleich läuft · B-2026-4711','24.08. 11:30'),delivery:I('assigned','Wartet auf verifizierten Vertrag','24.08. 08:00'),acceptance:I('assigned','Wartet auf Lieferung','24.08. 08:00'),outcome:I('assigned','Wartet auf Abnahme','24.08. 08:00')},
    financeFlow:{budget:3000000,committed:2100000,invoiced:750000,paid:500000,reconciled:500000,forecast:3400000,note:'Öffentliche und geschützte Ansichten sind Projektionen desselben Graphen. Bank- und personenbezogene Details bleiben in den Quellsystemen.',nodes:[['◎','Bundes-/Landesbudget',3000000,'bewilligt','B-2026-4711','Haushaltssystem','public'],['◆','Vertragswert',2100000,'gebunden','OCID-DE-DEMO-1','eVergabe','public'],['▤','Rechnungen',750000,'abgerechnet','Invoice batch Q3','Kreditorenbuchhaltung','internal'],['→','Zahlungen',500000,'bezahlt','Payment batch Q3','Zahlungsledger','internal'],['✓','Zahlung + Leistung abgeglichen',500000,'abgeglichen','AR-0 + REC-GOV-1','Controlling','public']]},
    changes:[['Change Request +€400k','Budget + Procurement + Owner reopen'],['Scope reduziert ohne Vertragswertänderung','Acceptance Criteria + Value-for-money review reopen']],disputes:[{label:'Forecast über bewilligtem Budget',state:'offen',owner:'Projektleitung + Controlling',evidence:'Forecast 3,4 Mio. vs. Budget 3,0 Mio.',resolutionTask:'outcome'}]
  }
};