const $=s=>document.querySelector(s), avatar=$('#avatar'), caption=$('#caption'), mouth=$('#mouth'), log=$('#log'), dot=$('#dot'), stageStatus=$('#stageStatus'), world=$('#world');
const DB={prefs:'lumen-v1-prefs',mem:'lumen-v1-memories',conv:'lumen-v1-conversation',feedback:'lumen-v1-feedback'};
let micPassed=false,typingMode=false,awake=false,speaking=false,recognition=null,meterRAF=null,micStream=null,recorder=null,chunks=[],continuousWanted=false,restartTimer=null,conversation=[],memories=[];
const safeParse=(value,fallback)=>{try{return JSON.parse(value)||fallback}catch{return fallback}};
const escapeText=t=>String(t??'');
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function savePrefs(){localStorage.setItem(DB.prefs,JSON.stringify({name:$('#userName').value.trim()||'Friend',lang:$('#language').value,memory:$('#memory').checked,continuous:$('#continuous').checked,motion:$('#motion').value,voice:$('#voiceSelect').value}))}
function loadState(){conversation=safeParse(localStorage.getItem(DB.conv),[]);memories=safeParse(localStorage.getItem(DB.mem),[]);const p=safeParse(localStorage.getItem(DB.prefs),{});if(p.name)$('#userName').value=p.name;if(p.lang)$('#language').value=p.lang;if(typeof p.memory==='boolean')$('#memory').checked=p.memory;if(typeof p.continuous==='boolean'){$('#continuous').checked=p.continuous;continuousWanted=p.continuous}if(p.motion)$('#motion').value=p.motion;document.body.classList.toggle('reduced-motion',$('#motion').value==='reduced');renderConversation();renderMemories();updateContinuousUI()}
function setState(phase,emotion='warm',gesture='stillness'){ $('#phaseChip').textContent=phase;$('#emotionChip').textContent=emotion;$('#gestureChip').textContent=gesture;stageStatus.textContent=phase==='offline'?'Schläft':phase==='idle'?'Anwesend':phase==='listening'?'Hört zu':phase==='thinking'?'Reflektiert':'Spricht';dot.classList.toggle('live',phase!=='offline');avatar.className='avatar-wrap '+(phase==='listening'?'listening ':phase==='thinking'?'thinking ':'')+(gesture==='open hands'?'open':gesture==='hand to heart'?'heart':emotion==='playful'?'playful':'')}
function add(who,text,{persist=true}={}){const d=document.createElement('div');d.className='msg '+(who==='Du'||who==='You'?'user':'lumen');const b=document.createElement('b');b.textContent=who;const content=document.createTextNode(text);d.append(b,content);log.appendChild(d);log.scrollTop=log.scrollHeight;if(persist){conversation.push({who,text,at:new Date().toISOString()});localStorage.setItem(DB.conv,JSON.stringify(conversation.slice(-100)))} }
function renderConversation(){log.innerHTML='';if(!conversation.length){add('Lumen','Ich bin noch nicht wach. Aber ich übe bereits, nicht so dramatisch darüber zu sein.',{persist:false});return}conversation.slice(-24).forEach(m=>add(m.who,m.text,{persist:false}))}
function remember(text){if(!$('#memory').checked)return;const compact=text.trim().slice(0,180);if(!compact)return;memories.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),text:compact,at:new Date().toISOString()});memories=memories.slice(0,20);localStorage.setItem(DB.mem,JSON.stringify(memories));renderMemories()}
function renderMemories(){const panel=$('#memoryPanel');panel.innerHTML='';if(!memories.length){panel.innerHTML='<div class="footer-note">Noch keine Erinnerungen.</div>';return}memories.forEach(m=>{const item=document.createElement('div');item.className='memory-item';const wrap=document.createElement('div'),p=document.createElement('p'),small=document.createElement('small'),del=document.createElement('button');p.textContent=m.text;small.textContent=new Date(m.at).toLocaleString();wrap.append(p,small);del.textContent='×';del.title='Erinnerung löschen';del.onclick=()=>{memories=memories.filter(x=>x.id!==m.id);localStorage.setItem(DB.mem,JSON.stringify(memories));renderMemories();toast('Erinnerung gelöscht.')};item.append(wrap,del);panel.appendChild(item)})}
function blink(){document.querySelectorAll('.eye').forEach(e=>e.style.height='3px');setTimeout(()=>document.querySelectorAll('.eye').forEach(e=>e.style.height='26px'),125);setTimeout(blink,2500+Math.random()*4200)}blink();
document.addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*8,y=(e.clientY/innerHeight-.5)*5;document.querySelectorAll('.iris').forEach(i=>i.style.transform=`translate(${x}px,${y}px)`) });
function stopMic(){if(meterRAF)cancelAnimationFrame(meterRAF);meterRAF=null;micStream?.getTracks().forEach(t=>t.stop());micStream=null;$('#meterFill').style.width='3%';$('#levelLabel').textContent='0%'}
function micError(err){const map={NotAllowedError:'Mikrofon blockiert. Klicke links neben der URL auf das Schloss und erlaube den Zugriff.',NotFoundError:'Kein Mikrofon gefunden. Prüfe, ob ein Gerät angeschlossen ist.',NotReadableError:'Das Mikrofon wird möglicherweise von einem anderen Programm blockiert.',SecurityError:'Mikrofonzugriff braucht HTTPS und eine sichere Browserfreigabe.'};$('#micStatus').textContent=map[err.name]||('Mic Check fehlgeschlagen: '+err.message);$('#micStatus').className='status-msg bad';$('#retry').hidden=false;stopMic()}
async function runMicCheck(){stopMic();$('#micCheck').disabled=true;$('#retry').hidden=true;$('#playback').hidden=true;$('#micStatus').textContent='Bitte sprich drei Sekunden lang ganz normal …';$('#micStatus').className='status-msg';try{micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const devices=await navigator.mediaDevices.enumerateDevices(),track=micStream.getAudioTracks()[0];$('#deviceLabel').textContent=track.label||devices.find(d=>d.kind==='audioinput')?.label||'Mikrofon aktiv';const ctx=new AudioContext(),source=ctx.createMediaStreamSource(micStream),analyser=ctx.createAnalyser();analyser.fftSize=256;analyser.smoothingTimeConstant=.72;source.connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);let peak=0;const tick=()=>{analyser.getByteFrequencyData(data);const mean=data.reduce((a,b)=>a+b,0)/data.length/255;peak=Math.max(peak,mean);const pct=Math.min(100,Math.round(mean*350));$('#meterFill').style.width=Math.max(3,pct)+'%';$('#levelLabel').textContent=pct+'%';meterRAF=requestAnimationFrame(tick)};tick();chunks=[];recorder=new MediaRecorder(micStream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'}),url=URL.createObjectURL(blob);$('#playback').src=url;$('#playback').hidden=false;micPassed=peak>.006;typingMode=false;$('#micStatus').textContent=micPassed?'Mic Check bestanden. Höre kurz hinein: Klingst du klar?':'Wir haben kaum Signal erkannt. Prüfe Eingabegerät und Lautstärke.';$('#micStatus').className='status-msg '+(micPassed?'ok':'bad');$('#awaken').disabled=!micPassed;$('#retry').hidden=false;$('#micCheck').hidden=true;$('#step1').classList.add('done');if(micPassed)$('#step2').classList.add('active');stopMic();ctx.close()};recorder.start();setTimeout(()=>recorder?.state==='recording'&&recorder.stop(),3000)}catch(err){micError(err)}finally{$('#micCheck').disabled=false}}
function enableTypingOnly(){typingMode=true;micPassed=true;$('#micStatus').textContent='Textmodus aktiviert. Mikrofon und Sprachaufnahme bleiben ausgeschaltet.';$('#micStatus').className='status-msg ok';$('#awaken').disabled=false;$('#listen').disabled=true;$('#step1').classList.add('done');$('#step2').classList.add('active');toast('Textmodus bereit.')}
function analyse(t){const x=t.toLowerCase();if(/mutter|vater|tod|trauer|schmerz|heartbreak|sad|alone|suffer|pain|grief/.test(x))return{emotion:'compassionate',gesture:'hand to heart',pace:.82};if(/haha|witz|funny|joke|laugh|spiel|silly/.test(x))return{emotion:'playful',gesture:'open hands',pace:1.02};if(/wütend|angry|hate|furious|falsch|stupid/.test(x))return{emotion:'grounded',gesture:'stillness',pace:.84};if(/warum|how|curious|neugierig|frage/.test(x))return{emotion:'curious',gesture:'open hands',pace:.93};return{emotion:'warm',gesture:'open hands',pace:.92}}
function changeWorld(name){document.querySelectorAll('.world-btn').forEach(x=>x.classList.toggle('active',x.dataset.world===name));world.className='world '+name;$('#moon').classList.toggle('visible',name==='garden');$('#lotus').classList.toggle('visible',name==='garden');$('#flame').classList.toggle('visible',name==='sunset')}
function worldIntent(t){const x=t.toLowerCase();if(/garten|garden|mond/.test(x)){changeWorld('garden');return true}if(/tempel|sunset|abend|feuer|flame/.test(x)){changeWorld('sunset');return true}if(/kosmos|void|space|sterne/.test(x)){changeWorld('void');return true}return false}
