(() => {
const $=id=>document.getElementById(id);const KEY='hk_v03_state';
const rarityOrder=['COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','MYTHIC'];
const rarityColor={COMMON:'#a4abba',UNCOMMON:'#78f3c1',RARE:'#72f7ff',EPIC:'#9b82ff',LEGENDARY:'#ffd789',MYTHIC:'#ff7adf'};
let C=null,openingCards=[],revealIndex=-1,dragging=false,dragStart=0,tear=0,holdTimer=null;
const defaultState={openedStory:false,packCount:0,legendaryPity:0,mythicPity:0,customItems:[],inventory:{'GENESIS-CORE':{id:'GENESIS-CORE',name:'GENESIS CORE',rarity:'GENESIS',category:'CORE',origin_world:'THE NEXUS'}},stardust:0,ledger:[],nexusUnlocked:false,awakened:false};
let state=load();
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function uid(){return 'evt_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function event(type,data={}){state.ledger.unshift({id:uid(),type,ts:new Date().toISOString(),...data});state.ledger=state.ledger.slice(0,100);save();renderLedger()}
function toast(title,body){const t=$('toast');t.querySelector('b').textContent=title;t.querySelector('span').textContent=body;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2800)}
function audio(){if(!window.AudioContext&&!window.webkitAudioContext)return null;audio.ctx ||= new (window.AudioContext||window.webkitAudioContext)();return audio.ctx}
function tone(freq=440,d=.12,type='sine',gain=.035,delay=0){const ctx=audio();if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,ctx.currentTime+delay);g.gain.linearRampToValueAtTime(gain,ctx.currentTime+delay+.015);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+delay+d);o.connect(g).connect(ctx.destination);o.start(ctx.currentTime+delay);o.stop(ctx.currentTime+delay+d+.03)}
function noise(d=.16,gain=.018){const ctx=audio();if(!ctx)return;const len=Math.floor(ctx.sampleRate*d),b=ctx.createBuffer(1,len,ctx.sampleRate),data=b.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const s=ctx.createBufferSource(),g=ctx.createGain();s.buffer=b;g.gain.value=gain;s.connect(g).connect(ctx.destination);s.start()}
function chime(r){const i=rarityOrder.indexOf(r);const base=[290,340,410,520,660,880][Math.max(0,i)];tone(base,.18,'sine',.035);tone(base*1.5,.28,'triangle',.018,.05);if(i>=4)tone(base*2,.45,'sine',.016,.09)}
function minIdx(r){return rarityOrder.indexOf(r)}
function randFrom(arr,rng=Math.random){return arr[Math.floor(rng()*arr.length)]}
function weighted(items,rng=Math.random){const sum=items.reduce((a,x)=>a+x.w,0);let n=rng()*sum;for(const x of items){n-=x.w;if(n<=0)return x.v}return items.at(-1).v}
function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function chooseRarity(min='COMMON',rng=Math.random,forceMythic=false,forceLegendary=false){if(forceMythic)return'MYTHIC';if(forceLegendary)return weighted([{v:'LEGENDARY',w:85},{v:'MYTHIC',w:15}],rng);const floor=minIdx(min);const opts=rarityOrder.slice(floor).map(r=>({v:r,w:C.rarities[r].weight}));return weighted(opts,rng)}
function generatePack(packId='GENESIS_001',opts={}){const p=C.packs[packId],seed=opts.seed??Math.floor(Math.random()*2**31),rng=mulberry32(seed),cards=[];const forceMythic=state.mythicPity>=C.pity.mythic_after_packs-1;const forceLegendary=state.legendaryPity>=C.pity.legendary_or_better_after_packs-1;
 p.recipe.forEach((slot,ix)=>{let rarity=chooseRarity(slot.min_rarity,rng,forceMythic&&ix===p.recipe.length-1,forceLegendary&&ix===p.recipe.length-1&&!forceMythic);let pool=C.items.filter(x=>slot.allowed.includes(x.category)&&minIdx(x.rarity)>=minIdx(slot.min_rarity));if(slot.featured&&rng()<(slot.featured_weight||0)){const f=slot.featured.map(id=>C.items.find(x=>x.id===id)).filter(Boolean);if(f.length){cards.push({...randFrom(f,rng),slot:slot.slot});return}}let byR=pool.filter(x=>x.rarity===rarity);if(!byR.length)byR=pool.filter(x=>minIdx(x.rarity)>=minIdx(rarity));if(!byR.length)byR=pool;cards.push({...randFrom(byR,rng),slot:slot.slot})});return{packId,seed,cards}}
function storyPack(){const ids=['HK-0046','HK-0042','HK-0043','HK-0044','HK-0045'];return{packId:'GENESIS_001',seed:4821,cards:ids.map((id,i)=>({...C.items.find(x=>x.id===id),slot:C.packs.GENESIS_001.recipe[i].slot}))}}
function bindPack(pack){let highest='COMMON',dupes=[];for(const item of pack.cards){if(minIdx(item.rarity)>minIdx(highest))highest=item.rarity;if(state.inventory[item.id]){const dust=C.duplicate_policy.stardust_by_rarity[item.rarity]||0;state.stardust+=dust;dupes.push({id:item.id,dust});event('DUPLICATE_CONVERTED',{item:item.id,rarity:item.rarity,stardust:dust})}else{state.inventory[item.id]=item;event('ITEM_BOUND',{item:item.id,rarity:item.rarity,category:item.category,pack:pack.packId,seed:pack.seed})}if(item.bind_effect==='UNLOCK_NEXUS')state.nexusUnlocked=true}
 state.packCount++;if(minIdx(highest)>=minIdx('LEGENDARY'))state.legendaryPity=0;else state.legendaryPity++;if(highest==='MYTHIC')state.mythicPity=0;else state.mythicPity++;if(pack.seed===4821){state.openedStory=true;state.awakened=true}event('PACK_OPENED',{pack:pack.packId,seed:pack.seed,cards:pack.cards.map(x=>x.id),highest,duplicates:dupes.length});save();renderAll();return dupes}
function renderInventory(){const inv=Object.values(state.inventory);$('inventoryGrid').innerHTML='';const slots=[...inv,...Array(Math.max(0,12-inv.length)).fill(null)];slots.slice(0,18).forEach(x=>{const d=document.createElement('div');d.className='slot'+(!x?' empty':'');if(!x)d.innerHTML='<div class="glyph">＋</div><div><strong>EMPTY SLOT</strong><span>WAITING FOR A SIGNAL</span></div>';else d.innerHTML=`<div class="glyph" style="color:${rarityColor[x.rarity]||'#fff'};border-color:${rarityColor[x.rarity]||'#fff'}33">${glyph(x.category)}</div><div><strong>${x.name}</strong><span>${x.rarity} · ${x.category}</span></div>`;$('inventoryGrid').appendChild(d)});$('stardust').textContent=state.stardust}
function glyph(c){return({CORE:'◎',WEARABLE:'◒',COMPANION:'✦',RELIC:'◇',MEMORY:'◌',WORLD_KEY:'⌁',CHARACTER_FRAGMENT:'◐'})[c]||'✧'}
function renderLedger(){if(!$('ledger'))return;$('ledgerCount').textContent=state.ledger.length;$('ledger').innerHTML=state.ledger.length?state.ledger.slice(0,18).map(e=>`<div class="event"><span>${new Date(e.ts).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span><b>${e.type.replaceAll('_',' ')}</b><code>${e.id.slice(-8)}</code></div>`).join(''):'<div class="event"><span>—</span><b>NO EVENTS YET</b><code>OPEN A PACK</code></div>'}
function renderGenesis(){const root=$('genesisGrid');root.innerHTML=C.genesis_candidates.map(c=>`<div class="candidate"><div class="cand-art" style="--h:${c.hue}"><div class="cand-head"></div><div class="cand-mask"></div><div class="cand-body"></div></div><div class="cand-meta"><strong>#${c.id} · ${c.codename}</strong><span>${c.origin_world} · ${c.archetype}<br>${c.mask} MASK · ${c.temperament}</span><span class="pill">${c.ability}</span></div></div>`).join('')}
function renderSchema(){$('schemaGrid').innerHTML=C.categories.map(x=>`<div class="schema-item"><b>${x.replaceAll('_',' ')}</b>${C.items.filter(i=>i.category===x).length} prototype objects</div>`).join('');$('itemCount').textContent=C.items.length;$('catCount').textContent=C.categories.length;$('candCount').textContent=C.genesis_candidates.length;$('versionChip').textContent=`COLLECTION ENGINE // V${C.version}`}
function renderAll(){$('kid').classList.toggle('awake',state.awakened);$('kidState').textContent=state.awakened?'LVL 02 · AWAKENED':'LVL 01 · DORMANT';$('packCountMicro').textContent=state.packCount;$('nexusCard').classList.toggle('locked',!state.nexusUnlocked);$('nexusStatus').textContent=state.nexusUnlocked?'RIFT SEED DETECTED · PORTAL ONLINE':'SIGNAL NOT FOUND';$('nexusText').textContent=state.nexusUnlocked?'#4821 can now perceive a stable transit line into The Nexus. This is the first collection item that changes world access.':'Open GENESIS // 001. Something inside is broadcasting from a place that does not exist yet.';renderInventory();renderLedger()}
function openOpening(){openingCards=[];revealIndex=-1;tear=0;$('premiumPack').style.setProperty('--tear',0);$('premiumPack').classList.remove('torn');$('premiumPack').style.display='block';$('revealStage').classList.remove('active');$('revealProgress').style.width='0';$('opening').classList.add('open');$('opening').setAttribute('aria-hidden','false');$('openingLabel').textContent=state.openedStory?'GENESIS // 001 · ENGINE MODE':'GENESIS // 001 · SEALED';tone(160,.16,'sine',.018)}
function closeOpening(){$('opening').classList.remove('open');$('opening').setAttribute('aria-hidden','true')}
function completeTear(){if($('premiumPack').classList.contains('torn'))return;tear=1;$('premiumPack').style.setProperty('--tear',1);$('tearZone').setAttribute('aria-valuenow','100');noise(.23,.035);tone(120,.18,'sawtooth',.018);if(navigator.vibrate)navigator.vibrate([25,15,35]);$('premiumPack').classList.add('torn');$('openingLabel').textContent='SEAL BROKEN · SIGNAL ACQUIRED';const pack=state.openedStory?generatePack('GENESIS_001'):storyPack();openingCards=pack.cards;openingCards._pack=pack;setTimeout(()=>{$('premiumPack').style.display='none';$('revealStage').classList.add('active');revealIndex=-1;nextReveal()},850)}
function nextReveal(){revealIndex++;if(revealIndex>=openingCards.length){const dupes=bindPack(openingCards._pack);$('revealTitle').textContent='PACK BOUND TO #4821';$('revealLore').textContent=dupes.length?`${dupes.length} duplicate${dupes.length>1?'s':''} converted into Stardust. The ledger has recorded this opening.`:'All five discoveries now belong to #4821. The ledger has recorded provenance for the opening.';$('nextHint').textContent='TAP TO RETURN TO YOUR INVENTORY';$('collectCard').onclick=()=>{closeOpening();document.querySelector('#inventory').scrollIntoView({behavior:'smooth'})};return}
 const c=openingCards[revealIndex];const card=$('collectCard');card.classList.remove('show');card.style.setProperty('--c',rarityColor[c.rarity]);$('cardSerial').textContent=`GENESIS // ${String(revealIndex+1).padStart(2,'0')}/05`;$('cardRarity').textContent=c.rarity;$('cardName').textContent=c.name;$('cardCat').textContent=c.category.replaceAll('_',' ');$('cardWorld').textContent=c.origin_world;$('revealTitle').textContent=`DISCOVERY ${revealIndex+1} OF 5`;$('revealLore').textContent=c.lore;$('nextHint').textContent=revealIndex===4?'TAP TO BIND THE PACK':'TAP / SPACE TO CONTINUE';$('revealProgress').style.width=`${(revealIndex+1)*20}%`;$('openingLabel').textContent=`GENESIS // 001 · ${c.rarity}`;
 const show=()=>{void card.offsetWidth;card.classList.add('show');chime(c.rarity);if(navigator.vibrate)navigator.vibrate(c.rarity==='MYTHIC'?[35,35,55,35,90]:22)};
 if(c.rarity==='MYTHIC'){setTimeout(()=>{$('mythicBlack').classList.add('on');tone(72,.55,'sine',.035);setTimeout(()=>{$('mythicBlack').classList.remove('on');$('mythicBurst').classList.remove('go');void $('mythicBurst').offsetWidth;$('mythicBurst').classList.add('go');show()},720)},220)}else setTimeout(show,80);
 card.onclick=()=>{card.onclick=null;card.classList.remove('show');setTimeout(nextReveal,260)}
}
function simulate(){const n=Math.max(100,Math.min(50000,Number($('simCount').value)||5000)),packId=$('simPack').value,counts=Object.fromEntries(rarityOrder.map(r=>[r,0]));let localLegend=0,localMythic=0;for(let i=0;i<n;i++){const oldL=state.legendaryPity,oldM=state.mythicPity;state.legendaryPity=localLegend;state.mythicPity=localMythic;const p=generatePack(packId,{seed:100000+i});state.legendaryPity=oldL;state.mythicPity=oldM;let high='COMMON';p.cards.forEach(c=>{counts[c.rarity]++;if(minIdx(c.rarity)>minIdx(high))high=c.rarity});localLegend=minIdx(high)>=minIdx('LEGENDARY')?0:localLegend+1;localMythic=high==='MYTHIC'?0:localMythic+1}const total=n*C.packs[packId].cards_per_pack;$('simResults').innerHTML=rarityOrder.map(r=>{const pct=counts[r]/total*100;return`<div class="barrow"><span>${r}</span><div class="bar"><i style="width:${Math.max(.4,pct)}%"></i></div><b>${pct.toFixed(r==='MYTHIC'?2:1)}%</b></div>`}).join('')+`<p class="odds">${n.toLocaleString()} packs · ${(total).toLocaleString()} cards · pity logic included · deterministic simulation seeds.</p>`}
function addAdminItem(){const name=$('adminName').value.trim(),cat=$('adminCat').value,rarity=$('adminRarity').value,world=$('adminWorld').value.trim()||'THE NEXUS',lore=$('adminLore').value.trim()||'A newly authored signal awaiting a story.';if(!name){toast('NAME REQUIRED','Give the new collectible a name first.');return}const item={id:'LOCAL-'+Date.now().toString(36).toUpperCase(),name:name.toUpperCase(),category:cat,rarity,origin_world:world.toUpperCase(),set:'LOCAL_LAB',lore,bind_effect:null};state.customItems.push(item);C.items.push(item);save();renderSchema();event('CONTENT_ITEM_CREATED',{item:item.id,rarity,category:cat});$('adminName').value='';$('adminLore').value='';toast('ITEM ADDED TO THE POOL',`${item.name} can now be pulled by compatible pack slots.`)}
function enterNexus(){if(!state.nexusUnlocked){toast('NO RIFT SIGNAL','The Nexus is still outside #4821’s perception. Open the first signal.');document.querySelector('#signal').scrollIntoView({behavior:'smooth'});return}toast('THE NEXUS IS ONLINE','Phase 7 will turn this unlocked state into our first explorable room.');tone(180,.28,'sine',.03);tone(360,.45,'sine',.02,.12)}
function resetStory(){if(!confirm('Reset local Hyperspace prototype state and reseal the first pack?'))return;state=structuredClone(defaultState);save();renderAll();toast('TIMELINE RESET','GENESIS // 001 is sealed again.')}
async function init(){C=buildCollection();if(state.customItems?.length)C.items.push(...state.customItems.filter(x=>!C.items.some(i=>i.id===x.id)));renderSchema();renderGenesis();renderAll();simulate();event('SESSION_READY',{version:C.version})}
$('heroOpen').onclick=$('openPack').onclick=openOpening;$('addItem').onclick=addAdminItem;$('packCard').onclick=openOpening;$('packCard').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openOpening()}};$('closeOpening').onclick=closeOpening;$('resetStory').onclick=resetStory;$('simulate').onclick=simulate;$('enterNexus').onclick=enterNexus;
const tz=$('tearZone');tz.addEventListener('pointerdown',e=>{dragging=true;dragStart=e.clientX-tear*tz.clientWidth;tz.setPointerCapture(e.pointerId);tone(90,.08,'triangle',.01)});tz.addEventListener('pointermove',e=>{if(!dragging)return;tear=Math.max(0,Math.min(1,(e.clientX-dragStart)/tz.clientWidth));$('premiumPack').style.setProperty('--tear',tear);tz.setAttribute('aria-valuenow',Math.round(tear*100));if(tear>.92){dragging=false;completeTear()}});tz.addEventListener('pointerup',()=>{dragging=false;if(tear<.92){tear=0;$('premiumPack').style.setProperty('--tear',0);tz.setAttribute('aria-valuenow','0')}});tz.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){tear=Math.min(1,tear+.2);$('premiumPack').style.setProperty('--tear',tear);if(tear>=.9)completeTear()}});
$('fallbackOpen').addEventListener('pointerdown',()=>{holdTimer=setTimeout(completeTear,650)});['pointerup','pointerleave','pointercancel'].forEach(x=>$('fallbackOpen').addEventListener(x,()=>clearTimeout(holdTimer)));
$('collectCard').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')nextReveal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOpening();if(e.key===' '&&$('revealStage').classList.contains('active')){e.preventDefault();$('collectCard').click()}});
$('packCard').addEventListener('pointermove',e=>{const r=e.currentTarget.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;e.currentTarget.style.setProperty('--mx',x*8);e.currentTarget.style.setProperty('--my',y*8)});$('packCard').addEventListener('pointerleave',e=>{e.currentTarget.style.setProperty('--mx',0);e.currentTarget.style.setProperty('--my',0)});
init().catch(err=>{console.error(err);$('versionChip').textContent='COLLECTION ENGINE // LOAD ERROR';toast('COLLECTION DATA FAILED','Refresh the page. If this persists, the public asset route is not ready yet.')});
})();
