function buildCollection(){
 const rarities={COMMON:{weight:58,score:1},UNCOMMON:{weight:24,score:2},RARE:{weight:11,score:4},EPIC:{weight:5,score:8},LEGENDARY:{weight:1.7,score:16},MYTHIC:{weight:.3,score:40}};
 const categories=['WEARABLE','COMPANION','RELIC','MEMORY','WORLD_KEY','CHARACTER_FRAGMENT'];
 const worlds=['NEON-7','EDEN','AQUARIA','THE VOID','SOLARA','GLASS MOON','KAIROS','ORBITAL-3'];
 const adjs=['Neon','Astral','Silent','Void','Solar','Quantum','Echo','Prism','Lunar','Rift','Velvet','Ghost'];
 const nouns={WEARABLE:['Visor','Cap','Jacket','Boots','Mask','Gloves','Mantle','Harness','Halo','Shell'],COMPANION:['Fox','Moth','Koi','Gecko','Crow','Cat','Orb','Drake','Jelly','Sprite'],RELIC:['Seed','Shard','Compass','Lens','Key','Coin','Totem','Beacon','Ring','Core'],MEMORY:['First Contact','Blue Hour','Gravity Lesson','Lost Signal','Home Frequency','Afterimage','One Kind Act','Skyfall'],WORLD_KEY:['Gate Sigil','Transit Pass','World Fragment','Portal Thread','Nexus Token','Orbit Stamp'],CHARACTER_FRAGMENT:['Origin Fragment','Archetype Echo','Temperament Trace','Ability Spark','Mask Pattern','Companion Bond']};
 const baseR=['COMMON','COMMON','UNCOMMON','UNCOMMON','RARE','RARE','EPIC','LEGENDARY','COMMON','UNCOMMON','RARE','EPIC','COMMON','MYTHIC'];let items=[],idx=1;
 categories.forEach(cat=>{const count=['MEMORY','WORLD_KEY','CHARACTER_FRAGMENT'].includes(cat)?10:14;for(let i=0;i<count;i++){let rarity=baseR[i%14];if(cat==='WORLD_KEY'&&rarity==='COMMON')rarity='UNCOMMON';if(cat==='MEMORY'&&rarity==='MYTHIC')rarity='LEGENDARY';items.push({id:`HK-${String(idx).padStart(4,'0')}`,name:`${adjs[(i*3+cat.length)%adjs.length]} ${nouns[cat][i%nouns[cat].length]}`.toUpperCase(),category:cat,rarity,origin_world:worlds[(i+idx)%worlds.length],set:'GENESIS_SIGNAL',lore:`A ${cat.toLowerCase().replaceAll('_',' ')} recovered from ${worlds[(i+idx)%worlds.length]}.`,bind_effect:null});idx++}});
 const specials=[['HK-0042','NEON VISOR','WEARABLE','RARE','NEON-7','Eyes attune to hidden transit lines.','RIFT_SENSE'],['HK-0043','VOID FOX','COMPANION','EPIC','THE VOID','A companion that appears one heartbeat before danger.','COMPANION_VOID_FOX'],['HK-0044','FIRST CONTACT','MEMORY','LEGENDARY','THE NEXUS','The moment the universe answered back.','MEMORY_FIRST_CONTACT'],['HK-0045','RIFT SEED','RELIC','MYTHIC','THE NEXUS','A dormant world folded into something smaller than a thought.','UNLOCK_NEXUS'],['HK-0046','STAR MAP 7A','WORLD_KEY','UNCOMMON','ORBITAL-3','Coordinates to a route that should not exist.','MAP_7A']];
 specials.forEach(([id,name,category,rarity,origin_world,lore,bind_effect])=>{let x=items.find(i=>i.id===id);if(x)Object.assign(x,{name,category,rarity,origin_world,lore,bind_effect});else items.push({id,name,category,rarity,origin_world,set:'GENESIS_SIGNAL',lore,bind_effect})});
 const masks=['RIFT','HALO','VOIDLINE','PRISM','ECHO','SPLIT','MONO','SUNSPOT'],arch=['EXPLORER','BUILDER','MESSENGER','GUARDIAN','DREAMER','TRICKSTER'],abilities=['RIFT SENSE','GRAVITY STEP','ECHO READ','LIGHT FOLD','MEMORY WALK','SIGNAL WEAVE','TIME SKIP','KINETIC BLOOM'],temps=['CURIOUS','CALM','BOLD','MISCHIEVOUS','COMPASSIONATE','RESTLESS','OBSERVANT','JOYFUL'],align=['LUMINOUS','WILD','BALANCED','TIDAL','SOLAR','VOID-TILTED'],codes=['FIRST TRAVELLER','RIFT RUNNER','QUIET COMET','NEON PILGRIM','SOFT GLITCH','STAR THIEF','MOON KEEPER','SIGNAL KID'];
 let genesis_candidates=Array.from({length:48},(_,n)=>({id:String(4801+n),codename:codes[n%8],origin_world:worlds[(n*5+1)%8],archetype:arch[(n*3+2)%6],mask:masks[(n*7)%8],ability:abilities[(n*5)%8],temperament:temps[(n*3)%8],alignment:align[(n*5+1)%6],hue:(104+n*97+n*n*13)%360,genesis_candidate:true}));let first=genesis_candidates.find(x=>x.id==='4821');Object.assign(first,{codename:'THE FIRST TRAVELLER',origin_world:'UNKNOWN',archetype:'EXPLORER',mask:'RIFT',ability:'DORMANT',temperament:'CURIOUS',alignment:'LUMINOUS',hue:42});
 return {version:'0.3.0',collection_id:'hyperspace-kids-genesis-signal',name:'HYPERSPACE KIDS',set:'GENESIS SIGNAL',rarities,categories,duplicate_policy:{first_copy:'keep',duplicate:'convert_to_stardust',stardust_by_rarity:{COMMON:5,UNCOMMON:10,RARE:25,EPIC:60,LEGENDARY:150,MYTHIC:500}},pity:{legendary_or_better_after_packs:8,mythic_after_packs:30,resets_on_hit:true},packs:{GENESIS_001:{name:'GENESIS // 001',subtitle:'FIRST SIGNAL',cards_per_pack:5,recipe:[{slot:'SIGNAL',allowed:['MEMORY','WORLD_KEY','RELIC'],min_rarity:'UNCOMMON'},{slot:'GEAR',allowed:['WEARABLE','RELIC'],min_rarity:'COMMON'},{slot:'LIFE',allowed:['COMPANION','CHARACTER_FRAGMENT'],min_rarity:'UNCOMMON'},{slot:'MEMORY',allowed:['MEMORY','RELIC','WORLD_KEY'],min_rarity:'RARE'},{slot:'RIFT',allowed:categories,min_rarity:'RARE',featured:['HK-0045'],featured_weight:.08}]},NEON_007:{name:'NEON // 007',subtitle:'AFTER DARK',cards_per_pack:5,recipe:[{slot:'GEAR',allowed:['WEARABLE'],min_rarity:'UNCOMMON'},{slot:'GEAR',allowed:['WEARABLE','RELIC'],min_rarity:'COMMON'},{slot:'LIFE',allowed:['COMPANION'],min_rarity:'UNCOMMON'},{slot:'MEMORY',allowed:['MEMORY'],min_rarity:'RARE'},{slot:'RIFT',allowed:categories,min_rarity:'RARE'}]}},items,genesis_candidates};
}
