(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE='hk_v020'; let saved={}; try{saved=JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{};
const state={opened:!!saved.opened,awakened:!!saved.awakened,memory:!!saved.memory,index:0};
const DATA=[
{id:'HK-0046',name:'UNMAPPED MERIDIAN',rarity:'UNCOMMON',origin:'ORBITAL-3',color:'#a9ffd8',glow:'#a9ffd82d',lore:'Coordinates written by a place that refuses to exist.',image:'https://v3b.fal.media/files/b/0aa8ae74/2VbFvx6SHNo5krtv6kAOl_gkReO67k.webp'},
{id:'HK-0042',name:'PARALLAX VISOR',rarity:'RARE',origin:'NEON-7',color:'#a6edff',glow:'#a6edff38',lore:'It reveals disagreements in reality.',image:'https://v3b.fal.media/files/b/0aa8ae7a/BuYvXtt_3_EX1thRWaU_P_4LvPpStj.webp'},
{id:'HK-0043',name:'VOID FOX',rarity:'EPIC',origin:'THE VOID',color:'#c1a9ff',glow:'#c1a9ff3e',lore:'It arrives one heartbeat before danger.',image:'https://v3b.fal.media/files/b/0aa8ae7b/hi0dStdWO9xUXQ9oD0T3G_lYUCwsi0.webp'},
{id:'HK-0044',name:'THE FIRST REPLY',rarity:'LEGENDARY',origin:'THE NEXUS',color:'#ffe4ad',glow:'#ffe4ad43',lore:'Proof that the silence was listening.',image:'https://v3b.fal.media/files/b/0aa8ae7d/5K7COXNO1TzhnLsaPRAEQ_J5gzt3xE.webp'},
{id:'HK-0045',name:'RIFT SEED',rarity:'MYTHIC',origin:'THE NEXUS',color:'#ffd0ec',glow:'#ffd0ec50',lore:'A world compressed to the size of a thought.',image:'https://v3b.fal.media/files/b/0aa8ae5f/zZAU3r0lqP_n_KKD5Ocxs_og5MLCeG.webp'}];
const save=()=>{try{localStorage.setItem(STORAGE,JSON.stringify({opened:state.opened,awakened:state.awakened,memory:state.memory}))}catch{}};
const CHARACTER='https://v3b.fal.media/files/b/0aa8ac76/5hZ3ANgNqmzH2Bn_cBYY6_befXbBwzY-yPnWXNE7g-6_rnd6HjUR.webp';
function fallbackKid(){return `<svg viewBox="0 0 320 520" aria-hidden="true"><ellipse cx="160" cy="485" rx="95" ry="15" fill="#000"/><path d="M92 468c8-80 24-143 45-174l23-15 23 15c22 31 38 94 45 174H92Z" fill="#0c0d13" stroke="#ffffff20"/><ellipse cx="160" cy="165" rx="79" ry="110" fill="#090a0e" stroke="#ffffff25"/><path d="M93 138c42-58 103-74 153-32-44-2-75 7-108 22-17 8-31 11-45 10Z" fill="#151720"/><path d="M102 151c42-22 84-22 117 0l-8 54c-35 22-70 23-106 1l-3-55Z" fill="#030407" stroke="#bffcff88"/><path d="M116 176c30-9 55-8 84 0" stroke="#dffcff" stroke-width="5" stroke-linecap="round"/><circle cx="160" cy="337" r="52" fill="url(#g)"/><defs><radialGradient id="g"><stop stop-color="#fff"/><stop offset=".2" stop-color="#bffcff" stop-opacity=".9"/><stop offset="1" stop-color="#7f77ff" stop-opacity="0"/></radialGradient></defs></svg>`}
function mountTraveller(sel){const host=$(sel);if(!host)return;host.innerHTML=fallbackKid();const img=new Image();img.className='candidate-character';img.alt='Hyperspace Kid #4821';img.onload=()=>{host.innerHTML='';host.appendChild(img)};img.src=CHARACTER}mountTraveller('#travellerDormant');mountTraveller('#travellerAwake');
let ctx=null;function ac(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;ctx ||= new A();if(ctx.state==='suspended')ctx.resume();return ctx}catch{return null}}
function tone(f,d=.2,type='sine',gain=.016,delay=0){const c=ac();if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,c.currentTime+delay);g.gain.exponentialRampToValueAtTime(gain,c.currentTime+delay+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+delay+d);o.connect(g).connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+d+.03)}
function sonicLogo(){tone(174,.42,'sine',.014);tone(261,.5,'triangle',.012,.08);tone(392,.65,'sine',.009,.18)}
function noiseBurst(seconds=.4,gain=.06,cut=2200){const c=ac();if(!c)return;const n=Math.floor(c.sampleRate*seconds),b=c.createBuffer(1,n,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/n,1.6);const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=b;f.type='bandpass';f.frequency.value=cut;f.Q.value=.55;g.gain.value=gain;s.connect(f).connect(g).connect(c.destination);s.start()}
function ripSound(){noiseBurst(.55,.08,2500);setTimeout(()=>noiseBurst(.22,.035,900),90);tone(68,.5,'sawtooth',.015)}function cardWhoosh(){noiseBurst(.28,.035,1100)}function rarityChime(r){const m={UNCOMMON:[220,330],RARE:[262,440],EPIC:[294,494,740],LEGENDARY:[330,554,831],MYTHIC:[55,440,660,990]}[r]||[220];m.forEach((f,i)=>tone(f,.55+i*.08,i?'triangle':'sine',r==='MYTHIC'?.016:.01,i*.09))}const vib=p=>{try{navigator.vibrate?.(p)}catch{}};
$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
const ritual=$('#ritual'),ripPack=$('#ripPack'),tearRange=$('#tearRange'),tearProgress=$('#tearProgress');let prog=0,ripped=false;
function openRitual(){ritual.classList.add('active');ritual.setAttribute('aria-hidden','false');document.body.classList.add('locked');resetRitual();tone(130,.22,'triangle',.012)}function closeRitual(){ritual.classList.remove('active');ritual.setAttribute('aria-hidden','true');document.body.classList.remove('locked')}
$('#openPack').onclick=openRitual;$('#heroPack').onclick=openRitual;$('#heroPack').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openRitual()}};$('#closeRitual').onclick=closeRitual;
function resetRitual(){prog=0;ripped=false;ripPack.classList.remove('opened');ripPack.style.setProperty('--rip',0);tearRange.disabled=false;tearRange.value=0;tearProgress.style.width='0';$('#ripInstruction').innerHTML='<strong>TAKE THE TAB.</strong> PULL ACROSS THE SEAL.';$('#openForMe').style.display='inline-block';ritual.classList.remove('ready')}
tearRange.addEventListener('input',()=>{if(ripped)return;prog=Number(tearRange.value)/100;ripPack.style.setProperty('--rip',prog);tearProgress.style.width=`${prog*100}%`;if(prog>=.76)finishRip()});tearRange.addEventListener('change',()=>{if(!ripped&&Number(tearRange.value)<76){tearRange.value=0;prog=0;tearProgress.style.width='0';ripPack.style.setProperty('--rip',0)}});
function finishRip(){if(ripped)return;ripped=true;prog=1;tearRange.value=100;ripPack.style.setProperty('--rip',1);tearProgress.style.width='100%';ripSound();vib([16,8,22,12,32]);tearRange.disabled=true;$('#openForMe').style.display='none';$('#ripInstruction').innerHTML='<strong>SEAL BROKEN.</strong> FIVE CARDS. ONE MEMORY.';setTimeout(()=>{ripPack.classList.add('opened');cardWhoosh()},180);setTimeout(()=>ritual.classList.add('ready'),1050)}$('#openForMe').onclick=finishRip;
$('#beginReveal').onclick=()=>{closeRitual();state.index=0;showReveal()};
const reveal=$('#reveal');function showReveal(){const c=DATA[state.index];reveal.classList.add('active');reveal.setAttribute('aria-hidden','false');document.body.classList.add('locked');reveal.classList.toggle('mythic',c.rarity==='MYTHIC');reveal.style.setProperty('--revealGlow',c.glow);const sc=$('#signalCard'),front=$('#cardFrontImg'),stage=$('.reveal-stage');sc.dataset.rarity=c.rarity.toLowerCase();sc.style.setProperty('--cardGlow',c.glow);front.src=c.image;front.alt=c.name;sc.classList.remove('dealt','flipped');stage.classList.remove('card-landed');void sc.offsetWidth;sc.classList.add('dealt');$('#revealMeta').textContent=`SIGNAL ${String(state.index+1).padStart(2,'0')} / 05`;$('#revealKicker').textContent=`${c.rarity} · ${c.id}`;$('#revealCount').textContent=`${String(state.index+1).padStart(2,'0')} / 05`;$('#revealOrigin').innerHTML=`<strong>${c.name}</strong><br>${c.origin}<br><span style="opacity:.65">${c.lore}</span>`;$('#revealHeadline').innerHTML=c.rarity==='MYTHIC'?'Reality<br><em>opens.</em>':c.rarity==='LEGENDARY'?'The silence<br><em>answered.</em>':state.index===0?'The first<br><em>signal.</em>':'Another<br><em>world.</em>';$('#revealBars').innerHTML=DATA.map((_,i)=>`<i class="${i<=state.index?'on':''}" style="--cardColor:${c.color}"></i>`).join('');const next=$('#nextReveal');next.disabled=true;next.style.opacity='.22';next.style.pointerEvents='none';next.querySelector('.cta-label').textContent=state.index===4?'BIND RIFT SEED':'DRAW NEXT CARD';cardWhoosh();vib([7]);setTimeout(()=>{sc.classList.add('flipped');rarityChime(c.rarity);vib(c.rarity==='MYTHIC'?[12,18,22,35,45]:[8])},c.rarity==='MYTHIC'?900:650);setTimeout(()=>{stage.classList.add('card-landed');next.disabled=false;next.style.opacity='1';next.style.pointerEvents='auto'},c.rarity==='MYTHIC'?2300:c.rarity==='LEGENDARY'?1800:1400);if(c.rarity==='MYTHIC'){setTimeout(()=>{$('#flash').classList.remove('hit');void $('#flash').offsetWidth;$('#flash').classList.add('hit')},860);tone(44,1.8,'sine',.035,.6)}}
function closeReveal(){reveal.classList.remove('active','mythic');reveal.setAttribute('aria-hidden','true');document.body.classList.remove('locked')}$('#closeReveal').onclick=closeReveal;
function bindMythic(){const orb=$('#riftTransfer'),btn=$('#nextReveal');btn.disabled=true;orb.classList.remove('fly');void orb.offsetWidth;orb.classList.add('fly');vib([22,30,34,50,54]);tone(72,1.25,'sine',.045);setTimeout(()=>{state.opened=true;state.awakened=true;save();closeReveal();applyState(true);sonicLogo();$('#awakening').scrollIntoView({behavior:'smooth'})},1650)}$('#nextReveal').onclick=()=>{if(state.index<4){state.index++;showReveal()}else bindMythic()};
function applyState(animate=false){if(state.awakened){document.body.classList.add('awakened');$('#awakeWord').textContent='is awake.';$('#awakeLede').innerHTML='RIFT SEED left the card and entered the traveller. <strong>RIFT SENSE</strong> is now permanent.';$('#signalBox').innerHTML='<span>NEW SIGNAL RECEIVED</span><b>WORLD 00 · THE NEXUS</b>';$('#firstWords').innerHTML='“I remember the sound of the seal breaking.”<small>#4821 · FIRST WORDS</small>';$('#nexusCopy').textContent='The first room has stabilised around your pull. What #4821 carries now changes which doors can exist.';const rb=$('#recordMemory');rb.disabled=false;rb.classList.remove('secondary');rb.querySelector('.cta-label').textContent=state.memory?'MEMORY RECORDED':'KEEP THIS MEMORY';rb.querySelector('.cta-orb').textContent=state.memory?'✓':'↗';$('#memoryText').textContent=state.memory?'GENESIS // 001 opened. Five signals recovered. RIFT SEED crossed from card to traveller. WORLD 00 stabilised. #4821 remembers the exact first opening.':'The event is ready to become part of #4821’s permanent history.';if(animate)document.body.animate([{filter:'brightness(.6)'},{filter:'brightness(1.35)'},{filter:'brightness(1)'}],{duration:1100,easing:'ease-out'})}}
$('#recordMemory').onclick=()=>{if(!state.awakened)return;state.memory=true;save();applyState();sonicLogo();$('#memory').scrollIntoView({behavior:'smooth'})};applyState();
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('seen')}),{threshold:.15});$$('[data-reveal]').forEach(x=>obs.observe(x));addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('#scrollProgress').style.width=h>0?(scrollY/h*100)+'%':'0%'},{passive:true});
const canvas=$('#ambient'),x=canvas.getContext('2d');let pts=[];function resize(){const d=Math.min(devicePixelRatio||1,1.5);canvas.width=innerWidth*d;canvas.height=innerHeight*d;x.setTransform(d,0,0,d,0,0);pts=Array.from({length:innerWidth<600?70:130},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.3+Math.random()*.8,a:.06+Math.random()*.22,v:.02+Math.random()*.06}))}resize();addEventListener('resize',resize);let last=0;(function loop(t){if(t-last<32){requestAnimationFrame(loop);return}last=t;x.fillStyle='#030407';x.fillRect(0,0,innerWidth,innerHeight);for(const p of pts){p.y+=p.v;if(p.y>innerHeight)p.y=0;x.globalAlpha=p.a;x.fillStyle='#dffcff';x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill()}x.globalAlpha=1;requestAnimationFrame(loop)})(0);
})();