(()=>{'use strict';
const A={rip:'https://v3b.fal.media/files/b/0aa8b17c/7Sg89SpUPhS4D7SdMxBCB_sound_effect.mp3',slide:'https://v3b.fal.media/files/b/0aa8b17d/6b1XXnac6rBVMXy9gazpx_sound_effect.mp3',myth:'https://v3b.fal.media/files/b/0aa8b17e/3gRD-PLka4m5H4rZXXIhM_sound_effect.mp3',portal:'https://v3b.fal.media/files/b/0aa8b195/6NPFfXrkRiaXgTXikC0Wv_sound_effect.mp3'};
const cards=[
{name:'UNMAPPED MERIDIAN',rarity:'UNCOMMON',id:'HK-0046',origin:'ORBITAL-3',lore:'Coordinates written by a place that refuses to exist.',accent:'#a9ffd8',img:'https://v3b.fal.media/files/b/0aa8b174/q9Bvi2akFpB5vyy35_kO0_6GNeABIw.webp'},
{name:'PARALLAX VISOR',rarity:'RARE',id:'HK-0042',origin:'NEON-7',lore:'It reveals disagreements in reality.',accent:'#a6edff',img:'https://v3b.fal.media/files/b/0aa8b175/hN0jvlydQFXhya2q8Z5Gw_zG5eyXhu.webp'},
{name:'VOID FOX',rarity:'EPIC',id:'HK-0043',origin:'THE VOID',lore:'It arrives one heartbeat before danger.',accent:'#c1a9ff',img:'https://v3b.fal.media/files/b/0aa8b176/BHp5_58BdalX6TyC4P5V9_LFVA8Vz1.webp'},
{name:'THE FIRST REPLY',rarity:'LEGENDARY',id:'HK-0044',origin:'THE NEXUS',lore:'Proof that the silence was listening.',accent:'#ffe4ad',img:'https://v3b.fal.media/files/b/0aa8b18e/_3JiZ7WFvhM9E__-Okbtp_7D788tcN.webp'},
{name:'RIFT SEED',rarity:'MYTHIC',id:'HK-0045',origin:'THE NEXUS',lore:'A world compressed to the size of a thought.',accent:'#ffd0ec',img:'https://v3b.fal.media/files/b/0aa8b16d/7I6vdNLEs9m99S3M1x8N2_whaE8uLl.webp'}];
const $=s=>document.querySelector(s), ritual=$('#ritual'),truth=$('#truth'),range=$('#range'),prog=$('#prog'),ritualActions=$('#ritualActions'),reveal=$('#reveal'),card=$('#card'),front=$('#front'),main=$('#revealMain'),next=$('#next');let idx=0,phase='idle',ripped=false;const play=(u,v=.65)=>{try{const a=new Audio(u);a.volume=v;a.play().catch(()=>{})}catch{}};const vib=p=>{try{navigator.vibrate?.(p)}catch{}};
function lock(on){document.body.classList.toggle('lock',on)}function show(el){el.classList.add('on');lock(true)}function hide(el){el.classList.remove('on');if(!document.querySelector('.ov.on'))lock(false)}function resetRip(){ripped=false;range.value=0;range.disabled=false;truth.classList.remove('open');truth.style.setProperty('--p',0);prog.style.width='0';$('#ripcopy').innerHTML='<strong>TAKE THE TAB.</strong> PULL ACROSS THE SEAL.';$('#autoOpen').style.display='inline-block';ritualActions.classList.remove('ready')}
function openRitual(){resetRip();show(ritual)}$('#openPack').onclick=openRitual;$('#heroPack').onclick=openRitual;$('#heroPack').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openRitual()}};$('#closeRitual').onclick=()=>hide(ritual);
range.oninput=()=>{if(ripped)return;const p=Number(range.value)/100;truth.style.setProperty('--p',p);prog.style.width=(p*100)+'%';if(p>=.78)finishRip()};range.onchange=()=>{if(!ripped&&Number(range.value)<78){range.value=0;truth.style.setProperty('--p',0);prog.style.width='0'}};
function finishRip(){if(ripped)return;ripped=true;range.value=100;range.disabled=true;truth.style.setProperty('--p',1);prog.style.width='100%';play(A.rip,.85);vib([14,10,24,12,34]);$('#autoOpen').style.display='none';$('#ripcopy').innerHTML='<strong>SEAL BROKEN.</strong> FIVE SIGNALS INSIDE.';setTimeout(()=>truth.classList.add('open'),180);setTimeout(()=>ritualActions.classList.add('ready'),1150)}$('#autoOpen').onclick=finishRip;$('#draw').onclick=()=>{hide(ritual);idx=0;phase='card';showCard()};
function setBars(){$('#bars').innerHTML=cards.map((_,i)=>`<i class="${i<=idx?'on':''}"></i>`).join('');document.documentElement.style.setProperty('--accent',cards[idx].accent)}
function setupCopy(c){$('#rmeta').textContent=`SIGNAL ${String(idx+1).padStart(2,'0')} / 05`;$('#rk').textContent=`${c.rarity} · ${c.id}`;$('#rc').textContent=`${String(idx+1).padStart(2,'0')} / 05`;$('#ro').innerHTML=`<strong>${c.name}</strong><br>${c.origin}<br><span style="opacity:.62">${c.lore}</span>`;$('#rh').innerHTML=idx===0?'The first<br><em>signal.</em>':idx===3?'The silence<br><em>answered.</em>':'Another<br><em>world.</em>';setBars()}
function revealNormal(c){main.classList.remove('finalMode');reveal.classList.remove('mythicMode');$('#copy').style.display='block';$('#finalLabel').textContent='FINAL SIGNAL // 05';front.src=c.img;card.classList.remove('flip','deal');void card.offsetWidth;card.classList.add('deal');setupCopy(c);next.disabled=true;next.style.opacity='.25';next.querySelector('span').textContent=idx===3?'FINAL SIGNAL':'DRAW NEXT CARD';play(A.slide,.55);setTimeout(()=>card.classList.add('flip'),520);setTimeout(()=>{next.disabled=false;next.style.opacity='1'},1250)}
function finalPending(){phase='final-pending';main.classList.add('finalMode');reveal.classList.remove('mythicMode');$('#copy').style.display='block';front.src=cards[4].img;card.classList.remove('flip','deal');void card.offsetWidth;card.classList.add('deal');$('#rmeta').textContent='FINAL SIGNAL // 05';$('#finalLabel').textContent='FINAL SIGNAL DETECTED · IDENTITY LOCKED';next.disabled=false;next.style.opacity='1';next.querySelector('span').textContent='REVEAL FINAL SIGNAL';setBars();play(A.slide,.4)}
function revealMythic(){phase='mythic';reveal.classList.add('mythicMode');$('#finalLabel').textContent='MYTHIC · HK-0045 · RIFT SEED';card.classList.add('flip');play(A.myth,.85);vib([12,18,24,32,50]);next.disabled=true;next.style.opacity='.22';setTimeout(()=>{next.querySelector('span').textContent='BIND RIFT SEED';next.disabled=false;next.style.opacity='1'},3000)}
function showCard(){show(reveal);phase='card';revealNormal(cards[idx])}$('#closeReveal').onclick=()=>hide(reveal);
next.onclick=()=>{if(phase==='card'){if(idx<3){idx++;revealNormal(cards[idx]);return}if(idx===3){idx=4;finalPending();return}}if(phase==='final-pending'){revealMythic();return}if(phase==='mythic'){bind();return}};
function bind(){hide(reveal);show($('#consequence'));play(A.portal,.85);vib([24,30,36,45,60]);setTimeout(()=>{hide($('#consequence'));document.body.classList.add('awake');$('#awakeWord').textContent='is awake.';$('#awakeText').innerHTML='RIFT SEED crossed from card to traveller. <strong>RIFT SENSE</strong> is now permanent.';$('#awakePill').textContent='LVL 02 · RIFT SENSE';$('#quote').textContent='“I remember the sound of the seal breaking.”';$('#nexusText').textContent='The first room has stabilised around your pull. What #4821 carries now changes which doors can exist.';const b=$('#memoryBtn');b.disabled=false;b.querySelector('span').textContent='KEEP THIS MEMORY';b.querySelector('.orb').textContent='↗';$('#awakening').scrollIntoView({behavior:'smooth'})},2500)}
$('#memoryBtn').onclick=()=>{$('#memoryText').textContent='GENESIS // 001 opened. Five signals recovered. RIFT SEED crossed from card to traveller. WORLD 00 stabilised. #4821 remembers the exact first opening.';$('#memory').scrollIntoView({behavior:'smooth'})};
})();