(()=>{'use strict';
const AUDIO={rip:'https://v3b.fal.media/files/b/0aa8b17c/7Sg89SpUPhS4D7SdMxBCB_sound_effect.mp3',slide:'https://v3b.fal.media/files/b/0aa8b17d/6b1XXnac6rBVMXy9gazpx_sound_effect.mp3',myth:'https://v3b.fal.media/files/b/0aa8b17e/3gRD-PLka4m5H4rZXXIhM_sound_effect.mp3',portal:'https://v3b.fal.media/files/b/0aa8b195/6NPFfXrkRiaXgTXikC0Wv_sound_effect.mp3'};
const cards=[
{name:'UNMAPPED MERIDIAN',rarity:'UNCOMMON',id:'HK-0046',origin:'ORBITAL-3',lore:'Coordinates written by a place that refuses to exist.',accent:'#a9ffd8',img:'https://v3b.fal.media/files/b/0aa8b2c6/UUEVYQVmBfKudTJOeojqY_result.png',cls:'WORLD KEY / SCAN',effect:'REVEALS HIDDEN COORDINATES',action:'SCAN MERIDIAN',done:'SCANNED'},
{name:'PARALLAX VISOR',rarity:'RARE',id:'HK-0042',origin:'NEON-7',lore:'It reveals disagreements in reality.',accent:'#a6edff',img:'https://v3b.fal.media/files/b/0aa8b2c7/g6xWtHo71RyE4K0AjVkt__result.png',cls:'WEARABLE / VISION',effect:'UNLOCKS PARALLAX SIGHT',action:'EQUIP VISOR',done:'EQUIPPED'},
{name:'VOID FOX',rarity:'EPIC',id:'HK-0043',origin:'THE VOID',lore:'It arrives one heartbeat before danger.',accent:'#c1a9ff',img:'https://v3b.fal.media/files/b/0aa8b2c9/EZ9LK3bUnEdi3I0DJn8vf_result.png',cls:'COMPANION / SCOUT',effect:'FINDS SECRETS ON EXPEDITIONS',action:'BOND VOID FOX',done:'BONDED'},
{name:'THE FIRST REPLY',rarity:'LEGENDARY',id:'HK-0044',origin:'THE NEXUS',lore:'Proof that the silence was listening.',accent:'#ffe4ad',img:'https://v3b.fal.media/files/b/0aa8b2e1/5cznvgvdatHBkf7lHEynr_result.png',cls:'MEMORY / DIALOGUE',effect:'UNLOCKS A NEW CONVERSATION',action:'KEEP THE REPLY',done:'REMEMBERED'},
{name:'RIFT SEED',rarity:'MYTHIC',id:'HK-0045',origin:'THE NEXUS',lore:'A world compressed to the size of a thought.',accent:'#ffd0ec',img:'https://v3b.fal.media/files/b/0aa8b2e2/vdWdTxRRDtlEdiRiB9lkV_result.png',cls:'MYTHIC WORLD OBJECT',effect:'OPENS NEW WORLD ACCESS',action:'BIND RIFT SEED',done:'BOUND'}];
const $=s=>document.querySelector(s),ritual=$('#ritual'),truth=$('#truth'),range=$('#range'),prog=$('#prog'),ritualActions=$('#ritualActions'),reveal=$('#reveal'),card=$('#card'),front=$('#front'),main=$('#revealMain'),next=$('#next'),useItem=$('#useItem');
let idx=0,phase='idle',ripped=false;const used=new Set();
const play=(u,v=.65)=>{try{const a=new Audio(u);a.volume=v;a.play().catch(()=>{})}catch{}};const vib=p=>{try{navigator.vibrate?.(p)}catch{}};const lock=on=>document.body.classList.toggle('lock',on);const show=el=>{el.classList.add('on');lock(true)};const hide=el=>{el.classList.remove('on');if(!document.querySelector('.ov.on'))lock(false)};
function resetRip(){ripped=false;range.value=0;range.disabled=false;truth.classList.remove('open');truth.style.setProperty('--p',0);prog.style.width='0';$('#ripcopy').innerHTML='<strong>TAKE THE LEFT TAB.</strong> PULL ACROSS THE SEAL.';$('#autoOpen').style.display='inline-block';ritualActions.classList.remove('ready')}
function openRitual(){resetRip();show(ritual)}$('#openPack').onclick=openRitual;$('#heroPack').onclick=openRitual;$('#heroPack').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openRitual()}};$('#closeRitual').onclick=()=>hide(ritual);
range.oninput=()=>{if(ripped)return;const p=Number(range.value)/100;truth.style.setProperty('--p',p);prog.style.width=(p*100)+'%';if(p>=.82)finishRip()};range.onchange=()=>{if(!ripped&&Number(range.value)<82){range.value=0;truth.style.setProperty('--p',0);prog.style.width='0'}};
function finishRip(){if(ripped)return;ripped=true;range.value=100;range.disabled=true;truth.style.setProperty('--p',1);prog.style.width='100%';play(AUDIO.rip,.86);vib([12,8,20,10,28]);$('#autoOpen').style.display='none';$('#ripcopy').innerHTML='<strong>SEAL BROKEN.</strong> FIVE USABLE OBJECTS INSIDE.';setTimeout(()=>truth.classList.add('open'),360);setTimeout(()=>ritualActions.classList.add('ready'),1050)}$('#autoOpen').onclick=finishRip;$('#draw').onclick=()=>{hide(ritual);idx=0;phase='card';showCard()};
function setBars(){$('#bars').innerHTML=cards.map((_,i)=>`<i class="${i<=idx?'on':''}"></i>`).join('');document.documentElement.style.setProperty('--accent',cards[idx].accent)}
function updateFunction(c){$('#itemClass').textContent=c.cls;$('#itemEffect').textContent=c.effect;useItem.classList.toggle('done',used.has(idx));useItem.querySelector('span').textContent=used.has(idx)?c.done:c.action;useItem.querySelector('small').textContent=used.has(idx)?'ACTIVE / SAVED':'OPTIONAL · KEEP OR USE NOW';useItem.style.display=idx===4?'none':'block'}
function setupCopy(c){$('#rmeta').textContent=`SIGNAL ${String(idx+1).padStart(2,'0')} / 05`;$('#rk').textContent=`${c.rarity} · ${c.id}`;$('#rc').textContent=`${String(idx+1).padStart(2,'0')} / 05`;$('#ro').innerHTML=`<strong>${c.name}</strong><br>${c.origin}<br><span style="opacity:.62">${c.lore}</span>`;$('#rh').innerHTML=idx===0?'The first<br><em>signal.</em>':idx===1?'See what<br><em>isn’t there.</em>':idx===2?'You are not<br><em>alone.</em>':idx===3?'The silence<br><em>answered.</em>':'Reality<br><em>opens.</em>';setBars();updateFunction(c)}
function prepareCard(c){front.src=c.img;card.classList.remove('flip','deal');void card.offsetWidth;card.classList.add('deal');setupCopy(c);play(AUDIO.slide,.5)}
function revealNormal(c){phase='card';main.classList.remove('finalMode');reveal.classList.remove('mythicMode');$('#finalLabel').textContent='FINAL SIGNAL // 05';prepareCard(c);next.disabled=true;next.style.opacity='.25';next.querySelector('span').textContent=idx===3?'FINAL SIGNAL':'DRAW NEXT CARD';setTimeout(()=>card.classList.add('flip'),430);setTimeout(()=>{next.disabled=false;next.style.opacity='1'},1050)}
function finalPending(){phase='final-pending';main.classList.add('finalMode');reveal.classList.remove('mythicMode');front.src=cards[4].img;card.classList.remove('flip','deal');void card.offsetWidth;card.classList.add('deal');$('#rmeta').textContent='FINAL SIGNAL // 05';$('#rk').textContent='IDENTITY LOCKED';$('#rh').innerHTML='One last<br><em>signal.</em>';$('#ro').innerHTML='The object refuses classification.';$('#itemClass').textContent='UNKNOWN';$('#itemEffect').textContent='SIGNAL REQUIRES DIRECT REVEAL';$('#rc').textContent='05 / 05';$('#finalLabel').textContent='FINAL SIGNAL DETECTED · IDENTITY LOCKED';useItem.style.display='none';next.disabled=true;next.style.opacity='.22';next.querySelector('span').textContent='REVEAL FINAL SIGNAL';setBars();play(AUDIO.slide,.38);setTimeout(()=>{next.disabled=false;next.style.opacity='1'},950)}
function revealMythic(){phase='mythic';reveal.classList.add('mythicMode');$('#finalLabel').textContent='MYTHIC · HK-0045 · RIFT SEED';$('#rk').textContent='MYTHIC · HK-0045';$('#rh').innerHTML='Reality<br><em>opens.</em>';$('#ro').innerHTML='<strong>RIFT SEED</strong><br>THE NEXUS<br><span style="opacity:.7">A world compressed to the size of a thought.</span>';$('#itemClass').textContent=cards[4].cls;$('#itemEffect').textContent=cards[4].effect;card.classList.add('flip');play(AUDIO.myth,.88);vib([12,18,24,32,48]);next.disabled=true;next.style.opacity='.18';next.querySelector('span').textContent='MYTHIC ACQUIRED';setTimeout(()=>{next.querySelector('span').textContent='BIND RIFT SEED';next.disabled=false;next.style.opacity='1'},3500)}
function showCard(){show(reveal);revealNormal(cards[idx])}$('#closeReveal').onclick=()=>hide(reveal);next.onclick=()=>{if(phase==='card'){if(idx<3){idx++;revealNormal(cards[idx]);return}if(idx===3){idx=4;finalPending();return}}if(phase==='final-pending'){revealMythic();return}if(phase==='mythic'){bind();return}};
useItem.onclick=()=>{if(idx===4)return;used.add(idx);const c=cards[idx];useItem.classList.add('done');useItem.querySelector('span').textContent=c.done;useItem.querySelector('small').textContent='ACTIVE / SAVED';vib([10]);if(idx===0)$('#slotWorld').textContent='MERIDIAN ONLINE';if(idx===1)$('#slotVision').textContent='PARALLAX VISOR';if(idx===2)$('#slotCompanion').textContent='VOID FOX';if(idx===3)$('#slotMemory').textContent='FIRST REPLY'};
function bind(){used.add(4);hide(reveal);show($('#consequence'));play(AUDIO.portal,.9);vib([24,30,36,45,60]);setTimeout(()=>{hide($('#consequence'));document.body.classList.add('awake');$('#awakeWord').textContent='is awake.';$('#awakeText').innerHTML='RIFT SEED crossed from card to traveller. <strong>RIFT SENSE</strong> is now permanent. The other recovered objects remain usable inventory.';$('#awakePill').textContent='LVL 02 · RIFT SENSE';$('#slotCore').textContent='RIFT SEED · BOUND';$('#quote').textContent=used.has(3)?'“You heard me before you knew I could answer.”':'“I remember the sound of the seal breaking.”';const bonuses=[];if(used.has(0))bonuses.push('hidden coordinates are visible');if(used.has(1))bonuses.push('Parallax sight is active');if(used.has(2))bonuses.push('Void Fox is scouting');$('#nexusText').textContent='WORLD 00 stabilised around your pull.'+(bonuses.length?' '+bonuses.join(' · ')+'.':' Your recovered objects can now change how you explore it.');const b=$('#memoryBtn');b.disabled=false;b.querySelector('span').textContent='OPEN MEMORY // 0001';b.querySelector('.orb').textContent='↗';writeMemory();$('#awakening').scrollIntoView({behavior:'smooth'})},2500)}
function writeMemory(){$('#memoryStamp').textContent='RECORDED · GENESIS // 001';$('#memoryStamp').classList.add('recorded');$('#memoryText').textContent='You opened the first GENESIS signal, recovered five objects, revealed RIFT SEED and permanently changed #4821. This record preserves what you chose to activate during the opening.';$('#memoryQuote').textContent=used.has(3)?'“Proof that the silence was listening.”':'“I remember the sound of the seal breaking.”';$('#memoryState').textContent='LVL 02 · RIFT SENSE';$('#memoryWorld').textContent='WORLD 00 · THE NEXUS ONLINE';$('#memoryObjectList').innerHTML=cards.map((c,i)=>`<div class="memoryObj" style="--c:${c.accent}"><i></i><b>${c.name}</b><small>${c.cls}<br>${used.has(i)?c.done:'STORED'}</small></div>`).join('');const mission=$('#nextMission');mission.disabled=false;mission.querySelector('span').textContent=used.has(0)?'TRACE UNMAPPED MERIDIAN':'ENTER WORLD 00';mission.querySelector('.orb').textContent='→'}
$('#memoryBtn').onclick=()=>{$('#memory').scrollIntoView({behavior:'smooth'})};$('#nextMission').onclick=()=>{$('#nexus').scrollIntoView({behavior:'smooth'});$('#nexus').animate?.([{filter:'brightness(1)'},{filter:'brightness(1.25)'},{filter:'brightness(1)'}],{duration:900})};
})();