window.addEventListener('error',function(){var t=document.getElementById('tier');if(t)t.textContent='SAFE';document.getElementById('arrival')?.classList.add('active');});

(()=>{
'use strict';
const $=s=>document.querySelector(s);const scenes=[...document.querySelectorAll('.scene')];
const STORY=[
{id:'HK-0046',slot:'SIGNAL',name:'UNMAPPED MERIDIAN',category:'WORLD KEY',rarity:'UNCOMMON',origin:'ORBITAL-3',lore:'Coordinates written by a place that does not exist.',glyph:'⌁'},
{id:'HK-0042',slot:'GEAR',name:'PARALLAX VISOR',category:'WEARABLE',rarity:'RARE',origin:'NEON-7',lore:'It does not improve sight. It reveals disagreements in reality.',glyph:'◒'},
{id:'HK-0043',slot:'LIFE',name:'VOID FOX',category:'COMPANION',rarity:'EPIC',origin:'THE VOID',lore:'It arrives one heartbeat before danger.',glyph:'✦'},
{id:'HK-0044',slot:'MEMORY',name:'THE FIRST REPLY',category:'MEMORY',rarity:'LEGENDARY',origin:'THE NEXUS',lore:'Proof that the silence was listening.',glyph:'◌'},
{id:'HK-0045',slot:'RIFT',name:'RIFT SEED',category:'RELIC',rarity:'MYTHIC',origin:'THE NEXUS',lore:'A world compressed to the size of a thought.',glyph:'◇'}];
const ART={
'HK-0046':`<svg viewBox="0 0 180 180" aria-hidden="true"><circle class="thin spinart" cx="90" cy="90" r="58"/><path class="thin" d="M24 122 62 72l34 20 56-58M33 42l41 39 44-22 31 66"/><circle class="fill" cx="62" cy="72" r="3"/><circle class="fill pulseart" cx="118" cy="59" r="4"/><circle class="fill" cx="96" cy="92" r="2.5"/><path class="st" d="M35 126c35-12 59-36 78-72"/><path class="st" d="M109 52l10 7-3-12"/></svg>`,
'HK-0042':`<svg viewBox="0 0 180 180" aria-hidden="true"><path class="soft" d="M24 72c38-22 94-22 132 0l-7 48c-40 21-78 21-118 0z"/><path class="st" d="M27 78c36-19 90-19 126 0l-5 34c-38 18-76 18-116 0z"/><path class="st pulseart" d="M42 91c24-8 46-9 65-4M119 87c11 0 20 2 28 5"/><path class="thin" d="M52 57 35 128M127 55l18 72"/></svg>`,
'HK-0043':`<svg viewBox="0 0 180 180" aria-hidden="true"><path class="soft" d="M45 126c-15-34 4-69 35-78l10 20 13-28 15 29c30 12 39 48 19 73-19 23-72 18-92-16z"/><path class="st" d="M47 124c-13-31 5-62 34-70l9 19 13-27 14 28c26 10 34 42 17 64-18 22-68 17-87-14z"/><path class="st" d="M74 101c10-8 22-10 32-2M122 101c-6-5-11-7-17-6"/><circle class="fill pulseart" cx="78" cy="102" r="2.5"/><circle class="fill pulseart" cx="118" cy="102" r="2.5"/><path class="thin" d="M53 132c27 10 58 7 81-10"/></svg>`,
'HK-0044':`<svg viewBox="0 0 180 180" aria-hidden="true"><circle class="thin" cx="90" cy="90" r="55"/><circle class="thin pulseart" cx="90" cy="90" r="37"/><circle class="thin" cx="90" cy="90" r="19"/><path class="st" d="M22 92h28l10-18 16 38 15-57 16 57 15-38 10 18h26"/><circle class="fill pulseart" cx="90" cy="90" r="4"/></svg>`,
'HK-0045':`<svg viewBox="0 0 180 180" aria-hidden="true"><circle class="soft pulseart" cx="90" cy="90" r="58"/><circle class="thin spinart" cx="90" cy="90" r="57"/><circle class="thin" cx="90" cy="90" r="39"/><path class="st" d="M92 29 75 71l16 12-13 27 12 41 17-43-16-12 14-28z"/><circle class="fill pulseart" cx="91" cy="91" r="6"/><path class="thin" d="M29 91h34M117 91h34"/></svg>`};
const RC={UNCOMMON:'#9affd4',RARE:'#8deaff',EPIC:'#baa5ff',LEGENDARY:'#ffe1a5',MYTHIC:'#ffd0ec'};

function packInner(el){el.innerHTML='<div class="pack-top"><b>HK</b><span>GENESIS SIGNAL / OBJECT 001</span></div><div class="pack-sigil"><i></i><b>01</b></div><div class="pack-name"><small>THE FIRST SIGNAL</small><strong>GENESIS</strong></div><div class="pack-foot"><span>00004821</span><span>THE NEXUS</span></div>'}
packInner($('#heroPack'));packInner($('#ritualPackFace'));
let current=0,idx=-1,revealed=false,tearP=0,drag=false,startX=0,ctx=null;
let state;try{state=JSON.parse(localStorage.getItem('hk_v06')||'{}')}catch{state={}};
function save(){localStorage.setItem('hk_v06',JSON.stringify(state))}
function go(n){const old=scenes[current];if(old&&old!==scenes[n]){old.classList.add('leaving');setTimeout(()=>old.classList.remove('active','leaving'),650)}current=n;const s=scenes[n];setTimeout(()=>s.classList.add('active'),old===s?0:360);$('#globalProgress').style.width=((n)/(scenes.length-1)*100)+'%';if(n===4)setTimeout(()=>speakFirstWords(),1000)}
function ac(){const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;ctx ||= new A();if(ctx.state==='suspended')ctx.resume();return ctx}
function tone(f=300,d=.15,type='sine',gain=.02,delay=0){const c=ac();if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,c.currentTime+delay);g.gain.exponentialRampToValueAtTime(gain,c.currentTime+delay+.015);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+delay+d);o.connect(g).connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+d+.03)}
function rip(){const c=ac();if(!c)return;const n=Math.floor(c.sampleRate*.4),b=c.createBuffer(1,n,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*(1-i/n);const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=b;f.type='bandpass';f.frequency.value=2100;f.Q=.55;g.gain.value=.085;s.connect(f).connect(g).connect(c.destination);s.start();tone(84,.3,'sawtooth',.018)}
function revealTone(r){const m={UNCOMMON:330,RARE:420,EPIC:520,LEGENDARY:660,MYTHIC:880};const f=m[r];tone(f,.22,'sine',.025);tone(f*1.5,.36,'triangle',.012,.06);if(r==='LEGENDARY'||r==='MYTHIC')tone(f*2,.6,'sine',.01,.13);if(r==='MYTHIC'){tone(55,1.0,'sine',.05);tone(1300,1.2,'sine',.006,.22)}}
function vibrate(p){navigator.vibrate?.(p)}
$('#begin').onclick=()=>{tone(180,.15,'triangle',.015);go(1)};$('#startRitual').onclick=()=>{tone(170,.12,'triangle',.013);resetRitual();go(2);setTimeout(()=>{if(current===2){$('#hint').textContent='OPENING…';finishTear()}},900)};$('#skipToOpened').onclick=()=>{state.awakened=true;save();go(3)};$('#ritualClose').onclick=()=>go(1);$('#enterNexus').onclick=()=>{tone(120,.5,'sine',.03);tone(240,.7,'sine',.018,.12);go(4)};$('#recordMemory').onclick=()=>{state.memory=true;save();tone(440,.5,'sine',.02);tone(660,.7,'triangle',.012,.11);go(5)};$('#again').onclick=()=>{go(0)};
function resetRitual(){idx=-1;revealed=false;tearP=0;$('#ritual').classList.remove('mythic');$('#ritualPack').className='ritual-pack';$('#ritualPack').style.display='block';$('#tear').style.transform='translateX(0)';const ts=$('#tear span');if(ts)ts.textContent='AUTO-OPENING';$('#stack').className='stack';$('#summary').className='summary';$('#card').classList.remove('flip');$('#hint').textContent='OPENING…';$('#ritualLabel').textContent='GENESIS // 001 · SEALED';$('#ritualProgress').style.width='0'}
const tear=$('#tear');let pointerType='mouse';tear.onpointerdown=e=>{pointerType=e.pointerType||'mouse';drag=true;startX=e.clientX-tearP*$('#ritualPack').clientWidth;tear.setPointerCapture?.(e.pointerId);tone(100,.06,'triangle',.009)};tear.onpointermove=e=>{if(!drag||pointerType==='touch')return;tearP=Math.max(0,Math.min(1,(e.clientX-startX)/($('#ritualPack').clientWidth*.9)));tear.style.transform=`translateX(${tearP*100}%)`;if(tearP>.72)finishTear()};tear.onpointerup=()=>{const touch=pointerType==='touch';drag=false;if(touch){finishTear();return}if(tearP<.72){tearP=0;tear.style.transform='translateX(0)'}};tear.onpointercancel=()=>{drag=false;tearP=0;tear.style.transform='translateX(0)'};tear.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();finishTear()}};$('#mobileOpen')?.addEventListener('click',e=>{e.preventDefault();finishTear()});
$('#ritualPack')?.addEventListener('click',e=>{if($('#ritualPack').classList.contains('torn'))return;e.preventDefault();finishTear()});
function finishTear(){if($('#ritualPack').classList.contains('torn'))return;drag=false;rip();vibrate([18,12,28]);$('#ritualPack').classList.add('torn');$('#ritualLabel').textContent='SEAL BROKEN';setTimeout(()=>{$('#ritualPack').style.display='none';$('#stack').classList.add('active');$('#hint').textContent='TAP TO TURN THE FIRST OBJECT';prime()},850)}
$('#stack').onclick=()=>advance();$('#stack').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();advance()}};$('#stack').tabIndex=0;
function prime(){idx++;if(idx>=STORY.length){showSummary();return}const c=STORY[idx];$('#cardSlot').textContent=c.slot;$('#cardCode').textContent=c.id;$('#glyph').innerHTML=ART[c.id]||c.glyph;$('#glyph').style.color=RC[c.rarity];$('#rarity').textContent=c.rarity;$('#rarity').style.color=RC[c.rarity];$('#cardName').textContent=c.name;$('#lore').textContent=c.lore;$('#origin').textContent=c.origin;$('#ritualProgress').style.width=(idx/STORY.length*100)+'%';revealed=false;setTimeout(()=>{$('#card').classList.add('flip');revealTone(c.rarity);vibrate(c.rarity==='MYTHIC'?[18,30,18,50,40]:[10]);if(c.rarity==='MYTHIC'){$('#ritual').classList.add('mythic');$('#flash').classList.remove('hit');void $('#flash').offsetWidth;setTimeout(()=>$('#flash').classList.add('hit'),520)}revealed=true;$('#ritualLabel').textContent=`${c.rarity} SIGNAL · ${String(idx+1).padStart(2,'0')}/05`;$('#hint').textContent=idx===STORY.length-1?'TAP TO COMPLETE SIGNAL':'TAP FOR NEXT OBJECT'},430)}
function advance(){if(!$('#stack').classList.contains('active'))return;if(revealed){$('#card').classList.remove('flip');revealed=false;if(idx>=STORY.length-1){setTimeout(showSummary,420)}else setTimeout(prime,420)}}
function showSummary(){$('#stack').className='stack';$('#ritualProgress').style.width='100%';$('#ritualLabel').textContent='SIGNAL COMPLETE';$('#miniCards').innerHTML=STORY.map(c=>`<div class="mini-card"><i style="color:${RC[c.rarity]}">${c.glyph}</i><div><span>${c.rarity}</span><b>${c.name}</b></div></div>`).join('');$('#summary').classList.add('active');tone(220,.3,'sine',.018);tone(440,.5,'sine',.012,.09)}
$('#bind').onclick=()=>{state.awakened=true;state.objects=STORY.map(x=>x.id);state.firstOpened=true;save();document.body.classList.add('awakened');tone(65,.8,'sine',.04);tone(390,.7,'sine',.015,.15);vibrate([20,30,35]);go(3)};
function speakFirstWords(){tone(174,.8,'sine',.012);tone(261,.8,'sine',.009,.13)}
function depth(stage,target,max=12){stage.addEventListener('pointermove',e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=stage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;target.style.transform=`rotateY(${x*max}deg) rotateX(${-y*max*.65}deg) translateZ(0)`});stage.addEventListener('pointerleave',()=>target.style.transform='')}
depth($('#plinth'),$('#heroPack'),11);depth($('#arrivalStage'),$('#kidArrival'),7);
window.addEventListener('deviceorientation',e=>{if(current!==1||e.gamma==null)return;const g=Math.max(-20,Math.min(20,e.gamma)),b=Math.max(-20,Math.min(20,e.beta-45));$('#heroPack').style.transform=`rotateY(${g*.35-6}deg) rotateX(${-b*.18+4}deg) rotateZ(-1deg)`},{passive:true});
const canvas=$('#fx'),gl=canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'high-performance'});let tier='SAFE';
if(gl){tier='HIGH';const vs=`attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}`;const fs=`precision mediump float;uniform vec2 r;uniform float t;uniform float m;float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){vec2 uv=(gl_FragCoord.xy-.5*r)/r.y;float d=length(uv);vec3 col=vec3(.012,.013,.02);float glow=.018/(abs(d-.33)+.08);col+=vec3(.14,.19,.32)*glow*.09;float stars=step(.9977,h(floor((uv+3.)*120.)));col+=stars*(.35+.65*h(floor((uv+2.)*90.)));float wave=.5+.5*sin(8.*d-t*.12);col+=m*vec3(.13,.06,.2)*wave*.08/(d+.5);gl_FragColor=vec4(col,1.);}`;function sh(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);return s}const pr=gl.createProgram();gl.attachShader(pr,sh(gl.VERTEX_SHADER,vs));gl.attachShader(pr,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(pr);gl.useProgram(pr);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(pr,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);const ur=gl.getUniformLocation(pr,'r'),ut=gl.getUniformLocation(pr,'t'),um=gl.getUniformLocation(pr,'m');function resize(){const d=Math.min(devicePixelRatio||1,1.6);canvas.width=innerWidth*d;canvas.height=innerHeight*d;gl.viewport(0,0,canvas.width,canvas.height)}addEventListener('resize',resize);resize();let start=performance.now();(function loop(now){gl.uniform2f(ur,canvas.width,canvas.height);gl.uniform1f(ut,(now-start)/1000);gl.uniform1f(um,current>=3?1:0);gl.drawArrays(gl.TRIANGLES,0,6);requestAnimationFrame(loop)})(start)} else {const x=canvas.getContext('2d');function resize(){canvas.width=innerWidth;canvas.height=innerHeight}addEventListener('resize',resize);resize();let pts=Array.from({length:90},()=>({x:Math.random(),y:Math.random(),a:.08+Math.random()*.35,r:.2+Math.random()*.8}));(function loop(){x.globalAlpha=1;x.fillStyle='#030305';x.fillRect(0,0,canvas.width,canvas.height);for(const p of pts){x.globalAlpha=p.a;x.fillStyle='#fff';x.beginPath();x.arc(p.x*canvas.width,p.y*canvas.height,p.r,0,7);x.fill()}requestAnimationFrame(loop)})()}
$('#tier').textContent=tier;
if(state.awakened){document.body.classList.add('awakened');$('#arrivalState').textContent='LVL 02 · AWAKENED';$('#arrivalState').classList.add('live')}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&current===2)go(1)});
})();