(()=>{
'use strict';
const app=document.getElementById('app');
const DATA=[
 {id:'HK-0046',slot:'SIGNAL',name:'UNMAPPED MERIDIAN',rarity:'UNCOMMON',origin:'ORBITAL-3',color:'#9affd4',glow:'#9affd430',lore:'Coordinates written by a place that does not exist.',art:'map'},
 {id:'HK-0042',slot:'GEAR',name:'PARALLAX VISOR',rarity:'RARE',origin:'NEON-7',color:'#8deaff',glow:'#8deaff38',lore:'It does not improve sight. It reveals disagreements in reality.',art:'visor'},
 {id:'HK-0043',slot:'LIFE',name:'VOID FOX',rarity:'EPIC',origin:'THE VOID',color:'#baa5ff',glow:'#baa5ff3c',lore:'It arrives one heartbeat before danger.',art:'fox'},
 {id:'HK-0044',slot:'MEMORY',name:'THE FIRST REPLY',rarity:'LEGENDARY',origin:'THE NEXUS',color:'#ffe1a5',glow:'#ffe1a540',lore:'Proof that the silence was listening.',art:'wave'},
 {id:'HK-0045',slot:'RIFT',name:'RIFT SEED',rarity:'MYTHIC',origin:'THE NEXUS',color:'#ffd0ec',glow:'#ffd0ec48',lore:'A world compressed to the size of a thought.',art:'seed'}
];
let state={scene:'arrival',idx:0,awakened:false,memory:false};
try{state={...state,...JSON.parse(localStorage.getItem('hk_v07')||'{}')}}catch{}
const save=()=>{try{localStorage.setItem('hk_v07',JSON.stringify(state))}catch{}};
const shell=(content)=>`<div class="shell"><header class="topbar"><div class="brand"><span class="sigil"></span>HYPERSPACE KIDS</div><div class="meta">THE FIRST SIGNAL<br>SIGNAL//ULTRA · 0.7.0</div></header><main class="viewport"><div class="stage">${content}</div></main><footer class="footerline"><span>ONE SCENE · ONE ACTION · <b id="tierLabel">SAFE</b></span><span>${state.awakened?'TRAVELLER AWAKE':'TRAVELLER DORMANT'}</span></footer></div>`;
function travellerSVG(awake=false){return `<svg viewBox="0 0 540 680" aria-hidden="true"><defs><linearGradient id="s${awake?'a':'d'}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#30323a"/><stop offset=".36" stop-color="#14161c"/><stop offset="1" stop-color="#040508"/></linearGradient><linearGradient id="v${awake?'a':'d'}" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#91a9ff"/><stop offset=".28" stop-color="#d9fff8"/><stop offset=".5" stop-color="#fff3d4"/><stop offset=".72" stop-color="#e7cbff"/><stop offset="1" stop-color="#8beaff"/></linearGradient><radialGradient id="c${awake?'a':'d'}"><stop offset="0" stop-color="#fff"/><stop offset=".18" stop-color="#ddfff8"/><stop offset=".48" stop-color="#718cff" stop-opacity=".78"/><stop offset="1" stop-color="#526dff" stop-opacity="0"/></radialGradient><filter id="g${awake?'a':'d'}"><feGaussianBlur stdDeviation="${awake?10:5}" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><ellipse cx="270" cy="650" rx="155" ry="20" fill="#000" opacity=".72"/><path d="M122 640c18-145 55-219 148-232 94 16 131 89 148 232H122Z" fill="url(#s${awake?'a':'d'})" stroke="#ffffff18"/><path d="M162 225c8-102 56-156 127-156 84 0 132 61 131 168-1 118-54 199-136 199-84 0-132-92-122-211Z" fill="#08090d" stroke="#ffffff24" stroke-width="2"/><path d="M157 158c39-66 94-95 163-90 48 3 80 18 111 45-51 1-93 9-132 23-54 21-99 33-142 22Z" fill="url(#s${awake?'a':'d'})" stroke="#ffffff1d"/><path d="M305 69c52-3 105 8 145 35-4 12-12 21-22 28-51-14-93-18-135-12l12-51Z" fill="#090a0e"/><path d="M179 226c66-34 152-36 225-2l-7 94c-70 36-145 39-220 1l2-93Z" fill="#040507" stroke="#ffffff2d" stroke-width="2"/><path d="M192 251c60-21 129-21 191-1l-3 35c-62 24-125 25-186 1l-2-35Z" fill="#0d0e13" stroke="url(#v${awake?'a':'d'})" stroke-width="${awake?4:2.4}" filter="url(#g${awake?'a':'d'})"/><path d="M208 268c34-7 59-8 84-4M316 264c20-1 36 1 50 5" stroke="url(#v${awake?'a':'d'})" stroke-width="${awake?8:5}" stroke-linecap="round" filter="url(#g${awake?'a':'d'})"/><path d="M235 355c34 15 68 15 103-1" stroke="#ffffff28" stroke-width="2" stroke-linecap="round"/><circle cx="272" cy="531" r="${awake?108:74}" fill="url(#c${awake?'a':'d'})" opacity="${awake?.9:.24}"/><circle cx="272" cy="531" r="18" fill="#050609" stroke="#d8fff8" stroke-width="1.5"/><circle cx="272" cy="531" r="${awake?7:4}" fill="#f2fff9" filter="url(#g${awake?'a':'d'})"/></svg>`}
function packHTML(){return `<div class="pack-top"><span>HK</span><span>GENESIS SIGNAL / OBJECT 001</span></div><div class="pack-core"><div class="rings"><i></i><i></i><i></i></div></div><div class="pack-title"><small>THE FIRST SIGNAL</small><strong>GENESIS</strong></div><div class="pack-bottom"><span>00004821</span><span>THE NEXUS</span></div>`}
function art(type,color){const common=`stroke="${color}" fill="none" stroke-width="2" vector-effect="non-scaling-stroke"`;
 if(type==='map')return `<svg viewBox="0 0 180 180"><circle ${common} cx="90" cy="90" r="58" opacity=".5"/><path ${common} d="M24 122 62 72l34 20 56-58M33 42l41 39 44-22 31 66"/><circle cx="62" cy="72" r="4" fill="${color}"/><circle cx="118" cy="59" r="5" fill="${color}"/><path ${common} d="M35 126c35-12 59-36 78-72"/></svg>`;
 if(type==='visor')return `<svg viewBox="0 0 180 180"><path d="M24 72c38-22 94-22 132 0l-7 48c-40 21-78 21-118 0z" fill="${color}14" stroke="${color}"/><path ${common} d="M30 79c35-17 87-17 120 0l-5 31c-36 16-74 16-110 0zM44 92c25-8 47-9 66-4M120 88c11 0 20 2 27 5"/></svg>`;
 if(type==='fox')return `<svg viewBox="0 0 180 180"><path d="M47 124c-13-31 5-62 34-70l9 19 13-27 14 28c26 10 34 42 17 64-18 22-68 17-87-14z" fill="${color}12" stroke="${color}"/><circle cx="78" cy="102" r="3" fill="${color}"/><circle cx="118" cy="102" r="3" fill="${color}"/><path ${common} d="M53 132c27 10 58 7 81-10"/></svg>`;
 if(type==='wave')return `<svg viewBox="0 0 180 180"><circle ${common} cx="90" cy="90" r="55" opacity=".4"/><circle ${common} cx="90" cy="90" r="34" opacity=".7"/><path ${common} d="M20 92h30l10-18 16 38 15-57 16 57 15-38 10 18h28"/><circle cx="90" cy="90" r="5" fill="${color}"/></svg>`;
 return `<svg viewBox="0 0 180 180"><circle cx="90" cy="90" r="58" fill="${color}10" stroke="${color}"/><circle ${common} cx="90" cy="90" r="39" opacity=".7"/><path ${common} d="M92 29 75 71l16 12-13 27 12 41 17-43-16-12 14-28z"/><circle cx="91" cy="91" r="7" fill="${color}"/></svg>`}
function button(id,label){return `<button class="cta" id="${id}"><span class="label">${label}</span><span class="orb">↗</span></button>`}
function detectTier(){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const mem=navigator.deviceMemory||4;const cores=navigator.hardwareConcurrency||4;if(reduced||mem<=2||cores<=2)return 'SAFE';if(mem<=4||cores<=4)return 'STANDARD';return 'ULTRA'}
const deviceTier=detectTier();document.documentElement.dataset.tier=deviceTier.toLowerCase();
function render(){
 let content='';
 if(state.scene==='arrival') content=`<section class="scene arrival"><div class="arrival-copy"><div class="eyebrow">SIGNAL DETECTED · 00:00:01</div><h1 class="display">The first<br><em>traveller.</em></h1><p class="copy">One character. One sealed object. One memory that will never happen twice. <strong>This is where Hyperspace begins.</strong></p><div class="actions">${button('approach','APPROACH #4821')}</div><div class="micro"><span>NO WALLET</span><span>NO DOWNLOAD</span><span>ONE MEMORY</span></div></div><div class="traveller-wrap"><div class="traveller-card"><div class="traveller-art">${travellerSVG(false)}</div><div class="spec"><small>SPECIMEN</small><strong>#4821</strong><small>THE FIRST TRAVELLER</small></div><div class="state">LVL 01 · DORMANT</div></div></div></section>`;
 if(state.scene==='object') content=`<section class="scene object-scene"><div class="pack-zone"><div class="pack" id="pack">${packHTML()}</div><div class="pack-hint">TAP THE OBJECT</div></div><div class="object-copy"><div class="eyebrow">OBJECT 001 · AUTHENTICATED</div><h2>GENESIS<br><span>// 001</span></h2><p class="copy">Five discoveries sealed in vacuum foil. One will permanently alter what #4821 can perceive.</p><div class="spec-grid"><div class="spec-item"><span>CONTENTS</span><b>5 SIGNAL OBJECTS</b></div><div class="spec-item"><span>FIRST OPEN</span><b>AUTHORED ONCE</b></div><div class="spec-item"><span>PROVENANCE</span><b>MEMORY-BEARING</b></div><div class="spec-item"><span>OUTCOME</span><b>WORLD CHANGE</b></div></div><div class="actions">${button('open','OPEN GENESIS // 001')}</div></div></section>`;
 if(state.scene==='opening') content=`<section class="scene open-scene"><div class="open-wrap"><div class="open-label">GENESIS // 001 · SEAL BREAK</div><div class="ripping"><div class="stackrise">FIVE SIGNALS DETECTED</div><div class="half top">${packHTML()}</div><div class="half bottom">${packHTML()}</div><div class="riplight"></div></div><h2 class="open-copy">The object<br><em>gives way.</em></h2></div></section>`;
 if(state.scene==='reveal') {const c=DATA[state.idx];const bars=DATA.map((_,i)=>`<i class="${i<=state.idx?'on':''}"></i>`).join('');content=`<section class="scene reveal-scene" style="--rarityField:${c.rarity==='MYTHIC'?'#ffd0ec16':c.rarity==='LEGENDARY'?'#ffe1a50e':'transparent'}"><div class="reveal-wrap"><div class="cardobj" style="--rarity:${c.color};--rarityGlow:${c.glow}"><div class="cardhead"><span>${c.slot}</span><span>${c.id}</span></div><div class="object-art">${art(c.art,c.color)}</div><div class="cardbody"><div class="rarity">${c.rarity}</div><div class="cardname">${c.name}</div><p class="lore">${c.lore}</p></div></div><div class="reveal-copy"><div class="eyebrow">SIGNAL RECOVERED · ${String(state.idx+1).padStart(2,'0')}/05</div><h3>${c.rarity==='MYTHIC'?'Reality<br><em>responds.</em>':'Something<br><em>was inside.</em>'}</h3><p class="copy"><strong>${c.name}</strong><br>${c.origin}</p><div class="count">${String(state.idx+1).padStart(2,'0')} / 05</div><div class="reveal-strip">${bars}</div><div class="actions">${button('next',state.idx===4?'BIND TO #4821':'REVEAL NEXT')}</div></div></div></section>`}
 if(state.scene==='awake') content=`<section class="scene awake-scene"><div class="awake-visual"><div class="portal"></div><div class="awake-kid">${travellerSVG(true)}</div></div><div class="awake-copy"><div class="eyebrow">STATE CHANGE CONFIRMED</div><h2>#4821<br><em>is awake.</em></h2><p class="copy">The Rift Seed has bound to the traveller. A new sense has appeared: <strong>RIFT SENSE</strong>.</p><div class="signalbox"><span>NEW SIGNAL RECEIVED</span><b>WORLD 00 · THE NEXUS</b></div><div class="actions">${button('nexus','FOLLOW THE SIGNAL')}</div></div></section>`;
 if(state.scene==='nexus') content=`<section class="scene nexus-scene"><div class="nexus"><div class="horizon"></div><div class="nexus-door"></div><div class="firstwords">“I remember the sound of the seal breaking.”<small>#4821 · FIRST WORDS</small></div><div class="nexus-copy"><div class="eyebrow">WORLD 00 · ONLINE</div><h2>The<br>Nexus.</h2><p>Not a map. A threshold. The first room in a world that will grow around what you discover.</p><div class="actions">${button('memory','KEEP THIS MEMORY')}</div></div></div></section>`;
 if(state.scene==='memory') content=`<section class="scene memory-scene"><div class="memory-card"><div class="eyebrow" style="justify-content:center">MEMORY WRITTEN</div><h2>The First<br><em>Signal.</em></h2><div class="memory-id">MEMORY // 0001 · #4821</div><p>GENESIS // 001 was opened. Five signals were recovered. The Rift Seed awakened #4821. The Nexus answered.</p><div class="seal"></div><div class="actions" style="justify-content:center">${button('restart','EXPERIENCE AGAIN')}</div></div></section>`;
 app.innerHTML=shell(content); const tl=document.getElementById('tierLabel');if(tl)tl.textContent=deviceTier; bind();
}
function haptic(p){try{navigator.vibrate?.(p)}catch{}}
let ctx; function tone(f=220,d=.14,g=.012){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;ctx ||= new A();if(ctx.state==='suspended')ctx.resume();const o=ctx.createOscillator(),v=ctx.createGain();o.frequency.value=f;v.gain.setValueAtTime(.0001,ctx.currentTime);v.gain.exponentialRampToValueAtTime(g,ctx.currentTime+.01);v.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+d);o.connect(v).connect(ctx.destination);o.start();o.stop(ctx.currentTime+d+.03)}catch{}}
function signature(){tone(174,.34,.012);setTimeout(()=>tone(261,.42,.010),110);setTimeout(()=>tone(392,.56,.009),240)}
function enterOpening(){state.scene='opening';save();render();tone(90,.5,.02);haptic([12,20,18]);setTimeout(()=>{if(state.scene==='opening'){state.scene='reveal';state.idx=0;save();render();tone(330,.35,.014)}},1900)}
function bind(){
 const $=id=>document.getElementById(id);
 $('approach')?.addEventListener('click',()=>{state.scene='object';save();render();tone(180)});
 const open=()=>enterOpening(); $('open')?.addEventListener('click',open); $('pack')?.addEventListener('click',open);
 $('next')?.addEventListener('click',()=>{if(state.idx<4){state.idx++;save();render();const c=DATA[state.idx];tone({UNCOMMON:330,RARE:420,EPIC:520,LEGENDARY:660,MYTHIC:880}[c.rarity]||440,.32,c.rarity==='MYTHIC'?.03:.014);haptic(c.rarity==='MYTHIC'?[15,25,15,40,28]:[8])}else{state.scene='awake';state.awakened=true;save();render();tone(70,.8,.025);haptic([15,20,30])}});
 $('nexus')?.addEventListener('click',()=>{state.scene='nexus';save();render();signature()});
 $('memory')?.addEventListener('click',()=>{state.scene='memory';state.memory=true;save();render();tone(440,.5,.018);setTimeout(()=>tone(660,.6,.012),100)});
 $('restart')?.addEventListener('click',()=>{state={scene:'arrival',idx:0,awakened:false,memory:false};save();render()});
 const pack=$('pack');if(pack){pack.addEventListener('pointermove',e=>{if(innerWidth<760)return;const r=pack.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;pack.style.transform=`rotateY(${x*10-4}deg) rotateX(${-y*7+2}deg)`});pack.addEventListener('pointerleave',()=>pack.style.transform='rotateY(-6deg) rotateX(3deg)')}
}
render();
const c=document.getElementById('ambient'),x=c.getContext('2d');let pts=[];function resize(){const d=Math.min(devicePixelRatio||1,1.5);c.width=innerWidth*d;c.height=innerHeight*d;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.setTransform(d,0,0,d,0,0);const cap=deviceTier==='SAFE'?45:deviceTier==='STANDARD'?80:130;pts=Array.from({length:Math.min(cap,Math.floor(innerWidth*innerHeight/7000))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*.9+.2,a:Math.random()*.32+.05}))}resize();addEventListener('resize',resize);let t=0;(function loop(){t+=.003;x.fillStyle='#050507';x.fillRect(0,0,innerWidth,innerHeight);const g=x.createRadialGradient(innerWidth*.62,innerHeight*.36,10,innerWidth*.62,innerHeight*.36,Math.max(innerWidth,innerHeight)*.7);g.addColorStop(0,'rgba(85,105,150,.08)');g.addColorStop(.35,'rgba(55,35,90,.035)');g.addColorStop(1,'rgba(5,5,7,0)');x.fillStyle=g;x.fillRect(0,0,innerWidth,innerHeight);for(const p of pts){x.globalAlpha=p.a*(.72+.28*Math.sin(t*3+p.x));x.fillStyle='#fff';x.beginPath();x.arc(p.x,p.y,p.r,0,Math.PI*2);x.fill()}x.globalAlpha=1;requestAnimationFrame(loop)})();
})();