let KB=null,EVAL=null,imported=null;const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const stop='ich du er sie es wir ihr der die das ein eine einen und oder ist bin sind was wie wo wann muss brauche mit zu für fuer nach in von am im beim bitte hallo'.split(' ');
function tok(s=''){return s.toLowerCase().replace(/[ä]/g,'ae').replace(/[ö]/g,'oe').replace(/[ü]/g,'ue').replace(/[ß]/g,'ss').replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>2&&!stop.includes(w))}
function score(q,c){const T=tok(q),H=tok([c.topic,c.title,c.department,c.text,(c.steps||[]).join(' ')].join(' '));let n=0;T.forEach(t=>{if(H.includes(t))n+=3;else if(H.some(h=>h.includes(t)||t.includes(h)))n+=1});return n}
function confidence(n){return n>7?0.92:n>3?0.76:n>0?0.55:0.32}
function retrieve(q){return KB.chunks.map(c=>({...c,score:score(q,c)})).sort((a,b)=>b.score-a.score).slice(0,3)}
function fillReview(chunk){$('title').value=chunk.title||'';$('source').value=chunk.source||'';$('dept').value=chunk.department||'';$('topic').value=chunk.topic||'';$('action').value=chunk.action||'answer';$('chunkText').value=chunk.text||'';$('types').textContent=(chunk.statement_types||[]).join(' · ');$('status').textContent=chunk.status||'suggested_admin_review_required';$('warnings').textContent='Admin muss Aktualität, Zuständigkeit, Vollständigkeit und Quelle prüfen.'}
async function importSource(){const url=$('url').value.trim(),text=$('rawText').value.trim();$('importResult').textContent='Import läuft…';try{const r=await fetch('/api/import-source',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,text})});const d=await r.json();if(!r.ok)throw new Error(d.error||d.detail||'Import failed');imported=d;$('importResult').textContent=JSON.stringify(d,null,2);fillReview(d.chunks[0])}catch(e){$('importResult').textContent='Importer-Backend nicht erreichbar oder Quelle blockiert. Fallback: Text einfügen und auf Vercel testen.\n\n'+e.message}}
function sample(){ $('rawText').value='Für einen neuen Personalausweis ist ein Termin beim Bürgeramt erforderlich. Bitte bringen Sie den bisherigen Personalausweis oder Reisepass und ein aktuelles biometrisches Passfoto mit. Bei Verlust des Ausweises kann eine Verlustanzeige erforderlich sein. Für Minderjährige wird die Zustimmung der Sorgeberechtigten benötigt. Die Bearbeitungszeit und Gebühren können je nach Kommune abweichen.'; $('url').value=''; }
function publish(){const chunk={id:'local-'+Date.now(),title:$('title').value,source:$('source').value,department:$('dept').value,topic:$('topic').value,action:$('action').value,text:$('chunkText').value,steps:inferSteps($('chunkText').value,$('topic').value),status:'approved_local_demo'};KB.chunks.unshift(chunk);localStorage.setItem('charlykit-v5-kb',JSON.stringify(KB));$('importResult').textContent='Lokal veröffentlicht:\n'+JSON.stringify(chunk,null,2)}
function inferSteps(text,topic){if(topic.includes('personalausweis'))return['Terminwunsch und Bürgeramt klären','Unterlagencheck durchführen','Sonderfälle wie Verlust oder Minderjährige prüfen','Termin- oder Rückruf-Payload vorbereiten'];if(topic.includes('ummeld'))return['Einzugsdatum klären','neue Adresse erfassen','Wohnungsgeberbestätigung prüfen','Termin oder Rückruf vorbereiten'];if(topic.includes('maengel'))return['Standort aufnehmen','Kategorie bestimmen','Dringlichkeit prüfen','Ticket vorbereiten'];return['Quelle prüfen','Bürgerfrage beantworten','Fachbereich dokumentieren','Receipt erzeugen']}
function test(){const q=$('question').value,h=retrieve(q),top=h[0],conf=confidence(top?.score||0);$('testResult').textContent=JSON.stringify({question:q,top_answer:top?.text||'Keine Quelle',top_source:top?.source,department:top?.department,action:top?.action,raw_score:top?.score||0,retrieval_confidence:conf,note:'Confidence ist Trefferstärke, kein Wahrheitswert.',top3:h.map(x=>({title:x.title,source:x.source,score:x.score}))},null,2)}
function runEval(){let ok=0;const rows=EVAL.tests.map(t=>{let h=retrieve(t.q)[0],pass=h&&h.topic===t.expectTopic&&h.action===t.expectAction;if(pass)ok++;return `${pass?'✅':'⚠️'} ${t.q} → ${h?.topic}/${h?.action} score=${h?.score}`});$('testResult').textContent='Eval Score: '+ok+'/'+EVAL.tests.length+'\n\n'+rows.join('\n')}
function clearLocal(){localStorage.removeItem('charlykit-v5-kb');KB=structuredClone(window.KB0);$('importResult').textContent='Lokale Imports gelöscht.'}
function bind(){$('importBtn').onclick=importSource;$('sampleBtn').onclick=sample;$('publishBtn').onclick=publish;$('clearBtn').onclick=clearLocal;$('testBtn').onclick=test;$('evalBtn').onclick=runEval}
document.addEventListener('DOMContentLoaded',async()=>{window.KB0=await fetch('../zaitgeist-v2/knowledge.json').then(r=>r.json());EVAL=await fetch('../zaitgeist-v2/eval.json').then(r=>r.json());KB=JSON.parse(localStorage.getItem('charlykit-v5-kb')||'null')||structuredClone(window.KB0);bind();sample()});