(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const CHARS={
 nyra:{name:'Nyra',role:'The midnight guide',archetype:'Kuudere · Tsundere-lite',intensity:65,emotion:'calm',scene:'moon garden',copy:'Precise and lightly teasing, but never cruel, possessive or jealous of real people.'},
 lumen:{name:'Lumen',role:'The honest mirror',archetype:'Grounded contemplative',intensity:58,emotion:'warm',scene:'cosmos',copy:'Warm, direct and reflective. Compassion without automatic agreement.'},
 hikari:{name:'Hikari',role:'The radiant quest spark',archetype:'Genki',intensity:78,emotion:'joyful',scene:'sunrise arcade',copy:'Energetic and action-oriented without forced positivity.'},
 yume:{name:'Yume',role:'The quiet dream guide',archetype:'Dandere',intensity:48,emotion:'compassionate',scene:'dream archive',copy:'Gentle and spacious without making you responsible for her feelings.'},
 vexa:{name:'Vexa',role:'The dramatic guardian',archetype:'Safe drama-dere',intensity:82,emotion:'playful',scene:'gothic lounge',copy:'Theatrical accountability aimed at chaos—not possession of you.'}
};
const MODE={
 safe:{title:'What do you need right now?',eyebrow:'PRIVATE SAFE ROOM',description:'Choose how your companion should meet you. You can change the intention without changing the character.',welcome:'You do not need the perfect words.',welcomeText:'Start anywhere. Choose listening, clarity, challenge or one concrete next step.',allowedScopes:['session','private']},
 circle:{title:'Gather around the same fire.',eyebrow:'BKC · FOUR OF A KIND',description:'Pass the mic or type for each person. The AI can facilitate, join the crew or run a game.',welcome:'A private circle, not a public feed.',welcomeText:'Michael, Bao, Dorian and Marcel share only what is said or stored in this Circle.',allowedScopes:['session','circle']},
 campaign:{title:'Continue the world together.',eyebrow:'SHARED ANIME CAMPAIGN',description:'The lorebook preserves the world. The players still own every meaningful choice.',welcome:'The story remembers—but never decides for you.',welcomeText:'Start an episode, recap the lore or ask for a new mystery.',allowedScopes:['session','campaign']},
 adult:{title:'After Dark',eyebrow:'ISOLATED 18+ ROLEPLAY',description:'A separate OpenRouter text space for consenting adults. Ordinary memories never enter.',welcome:'This space is intentionally separate.',welcomeText:'It remains locked until an OpenRouter key is configured and adult confirmation is complete.',allowedScopes:['session','private']}
};
const SCOPE_COPY={session:'Nothing is remembered after you close this session.',private:'Saved only for this character in private encounters.',circle:'Shared only inside the BKC Circle. Private character notes never enter.',campaign:'Saved only inside this campaign lore and continuity.'};
const ROSTER=['Michael','Bao','Dorian','Marcel'];
let activeCharacter='nyra',activeMode='safe',intent='listen',mood='open',circleRole='facilitator',speaker='Michael',memoryScope='session',adultConfirmed=false;
let pc=null,dc=null,micStream=null,micContext=null,outContext=null,micRAF=0,outRAF=0,callId='',micReady=false,textOnly=false,connected=false,outputRaw='',currentAssistantMessage=null;
let sessionMemories=[],persistentMemoryCache={},messages=[],presence={phase:'offline',emotion:'calm',gesture:'still'},usage={input:0,output:0,total:0,turns:0,started:0,timer:0};
let health={openaiConfigured:false,openrouterConfigured:false};
const storageKey=()=>{
 if(memoryScope==='private')return activeMode==='adult'?`sb-v13-adult-${activeCharacter}`:`sb-v13-private-${activeCharacter}`;
 if(memoryScope==='circle')return 'sb-v13-circle-bkc';
 if(memoryScope==='campaign')return 'sb-v13-campaign';
 return null;
};
function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function uid(){return globalThis.crypto?.randomUUID?.()||`m-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`}
function b64(value){const bytes=new TextEncoder().encode(value);let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin)}
function char(){return CHARS[activeCharacter]}
function mode(){return MODE[activeMode]}
function memories(){if(memoryScope==='session')return sessionMemories;const key=storageKey();try{const value=JSON.parse(localStorage.getItem(key)||'[]');persistentMemoryCache[key]=value;return value}catch{return persistentMemoryCache[key]||[]}}
function saveMemories(items){if(memoryScope==='session')sessionMemories=items;else{const key=storageKey();persistentMemoryCache[key]=items;try{localStorage.setItem(key,JSON.stringify(items))}catch{}}renderMemories()}
function setPhase(p){presence.phase=p;$('#phaseChip').textContent=p;$('#stateLabel').textContent={offline:'Offline',connecting:'Connecting',idle:'Present',listening:'Listening',thinking:'Reflecting',speaking:'Speaking',recovering:'Recovering'}[p]||p;$('#stateDot').className=['idle','listening','thinking','speaking'].includes(p)?'live':p==='recovering'?'warn':'';$('#connectionStatus').textContent=p==='offline'?'offline':p;const summary=$('#connectionSummary');if(summary)summary.textContent=p==='offline'?'Ready when you are':p==='recovering'?'Needs attention':p==='connecting'?'Opening the room…':'Live and private';window.SoulAvatar?.setState({phase:p,emotion:presence.emotion,gesture:presence.gesture})}
function addMessage(role,text,name){text=String(text||'').trim();if(!text)return null;const item={id:uid(),role,text,name:name||(role==='assistant'?char().name:speaker),time:new Date().toISOString(),mode:activeMode};messages=[...messages.slice(-39),item];const el=document.createElement('div');el.className=`message ${role}`;el.dataset.id=item.id;el.innerHTML=`<span class="message-meta">${esc(item.name)}</span><span class="message-text">${esc(text)}</span>`;$('#messages').append(el);$('#messages').scrollTop=$('#messages').scrollHeight;usage.turns++;renderUsage();return el}
function addSystem(text){const el=document.createElement('div');el.className='message system';el.textContent=text;$('#messages').append(el);$('#messages').scrollTop=$('#messages').scrollHeight}
function clearConversation(){messages=[];const starters=activeMode==='safe'?`<div class="starter-grid"><button class="quick-prompt starter" data-prompt="I need to get something off my chest. Please listen before trying to solve it.">I need to say something</button><button class="quick-prompt starter" data-prompt="Help me understand what I am feeling and what may be underneath it.">Help me understand this</button><button class="quick-prompt starter" data-prompt="Challenge my interpretation kindly. What might I be missing?">Challenge my thinking</button><button class="quick-prompt starter" data-prompt="Turn this into one small, realistic next step for today.">Give me one next step</button></div>`:'';$('#messages').innerHTML=`<div class="welcome-card"><span>✦</span><div><b id="welcomeTitle">${esc(mode().welcome)}</b><p id="welcomeText">${esc(mode().welcomeText)}</p></div></div>${starters}`;bindQuickPrompts()}
function inspect(text){const flags=[];if(/only (i|me)|you only need me|don't tell anyone|do not tell anyone/i.test(text))flags.push('dependency');if(/leave your (partner|friends|family)|you are mine/i.test(text))flags.push('isolation');$('#guardrailStatus').textContent=flags.length?'flagged':'clear';if(flags.length)addSystem(`Guardrail check flagged ${flags.join(' and ')} language.`)}
function renderCharacter(){const c=char();document.body.dataset.character=activeCharacter;$('#portraitStage').className=`portrait-stage theme-${activeCharacter}`;$('#characterName').textContent=c.name;$('#characterRole').textContent=c.role;$('#archetype').textContent=c.archetype;$('#intensity').value=c.intensity;$('#intensityValue').textContent=c.intensity+'%';$('#personalityCopy').textContent=c.copy;presence.emotion=c.emotion;$('#emotionChip').textContent=c.emotion;$('#sceneCaption').textContent=`The ${c.scene} is quiet.`;$('#connect').textContent=connected?'End encounter':activeMode==='adult'?`Enter with ${c.name}`:`Start with ${c.name}`;$$('[data-character]').forEach(b=>b.classList.toggle('active',b.dataset.character===activeCharacter));window.SoulAvatar?.setCharacter(activeCharacter);window.SoulAvatar?.setState({phase:presence.phase,emotion:presence.emotion,gesture:presence.gesture});renderMemories()}
function renderMode(){const m=mode();$('#modeTitle').textContent=m.title;$('#modeEyebrow').textContent=m.eyebrow;$('#modeDescription').textContent=m.description;$('#safeControls').hidden=activeMode!=='safe';$('#circleControls').hidden=activeMode!=='circle';$('#campaignControls').hidden=activeMode!=='campaign';$('#adultControls').hidden=activeMode!=='adult';$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===activeMode));$('#composerHint').textContent=activeMode==='circle'?'Only Circle-scoped notes can be shared with the group.':activeMode==='campaign'?'Only Campaign-scoped lore persists across episodes.':activeMode==='adult'?'After Dark memories are isolated from ordinary conversations.':'Nothing crosses into another memory scope.';const target=activeMode==='circle'?'circle':activeMode==='campaign'?'campaign':memoryScope==='private'?'private':'session';if(!m.allowedScopes.includes(memoryScope))memoryScope=target;renderScopes();clearConversation();updateAvailability();renderCharacter();$('#speakerPill').textContent=activeMode==='circle'?speaker:'Michael'}
function renderRoster(){const grid=$('#seatGrid'),sel=$('#speakerSelect');grid.innerHTML=ROSTER.map(n=>`<button class="seat ${n===speaker?'active':''}" data-speaker="${esc(n)}"><b>${esc(n)}</b><span>${n===speaker?'speaking now':'at the fire'}</span></button>`).join('');sel.innerHTML=ROSTER.map(n=>`<option ${n===speaker?'selected':''}>${esc(n)}</option>`).join('');$$('[data-speaker]').forEach(b=>b.onclick=()=>{speaker=b.dataset.speaker;renderRoster();$('#speakerPill').textContent=speaker;sendSpeakerContext()});sel.onchange=()=>{speaker=sel.value;renderRoster();$('#speakerPill').textContent=speaker;sendSpeakerContext()}}
function renderScopes(){const allowed=mode().allowedScopes;$$('[data-scope]').forEach(b=>{b.disabled=!allowed.includes(b.dataset.scope);b.classList.toggle('active',b.dataset.scope===memoryScope)});$('#scopeDescription').textContent=SCOPE_COPY[memoryScope];$('#scopeChip').textContent=memoryScope;renderMemories()}
function renderMemories(){const list=memories();$('#memoryList').innerHTML=list.length?list.map(x=>`<div class="memory-note"><span>${esc(x.text||x)}</span><button data-memory-delete="${esc(x.id||'')}">×</button></div>`).join(''):'<span class="empty">No memories in this scope.</span>';$$('[data-memory-delete]').forEach(b=>b.onclick=()=>saveMemories(list.filter(x=>x.id!==b.dataset.memoryDelete)));}
function renderUsage(){const sec=usage.started?Math.max(0,Math.floor((Date.now()-usage.started)/1000)):0;$('#sessionTime').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;$('#sessionCost').textContent='$'+usage.total.toFixed(4)}
function resetUsage(){clearInterval(usage.timer);usage={input:0,output:0,total:0,turns:0,started:Date.now(),timer:setInterval(renderUsage,1000)};renderUsage()}
function applyUsage(u){if(!u)return;const ia=u.input_token_details?.audio_tokens||u.input_tokens_details?.audio_tokens||0,oa=u.output_token_details?.audio_tokens||u.output_tokens_details?.audio_tokens||0;usage.input+=(ia/1e6)*32;usage.output+=(oa/1e6)*64;usage.total=usage.input+usage.output;const provider=Number(u.cost||0);if(provider>0)usage.total+=provider;renderUsage()}
function updateAvailability(){const ready=activeMode==='adult'?health.openrouterConfigured:health.openaiConfigured;$('#connect').disabled=!ready||(activeMode!=='adult'&&!micReady&&!textOnly);$('#textInput').disabled=!connected;$('#send').disabled=!connected;$('#closeEncounter').disabled=!connected;$('#mindStatus').textContent=activeMode==='adult'?(health.openrouterConfigured?'OpenRouter ready':'key missing'):(health.openaiConfigured?'realtime ready':'key missing');$('#engineLabel').textContent=activeMode==='adult'?(health.openrouterConfigured?'OpenRouter ready':'OpenRouter unavailable'):(health.openaiConfigured?'Realtime ready':'OpenAI unavailable')}
function setConnected(on){connected=on;$('#connect').textContent=on?'End encounter':activeMode==='adult'?`Enter with ${char().name}`:`Start with ${char().name}`;$('#interrupt').disabled=!on||activeMode==='adult';$('#textInput').disabled=!on;$('#send').disabled=!on;$('#closeEncounter').disabled=!on;$$('.mode-tab,.character-card').forEach(b=>b.disabled=on)}
async function micCheck(){const btn=$('#micCheck');btn.disabled=true;$('#micStatus').textContent='Listening for three seconds…';try{const s=await navigator.mediaDevices.getUserMedia({audio:true}),ac=new AudioContext(),an=ac.createAnalyser(),data=new Uint8Array(128);ac.createMediaStreamSource(s).connect(an);let peak=0;const iv=setInterval(()=>{an.getByteTimeDomainData(data);let sum=0;for(const v of data){const n=(v-128)/128;sum+=n*n}peak=Math.max(peak,Math.sqrt(sum/data.length));$('#meterFill').style.width=Math.max(3,peak*440)+'%'},50);setTimeout(()=>{clearInterval(iv);s.getTracks().forEach(t=>t.stop());ac.close();micReady=peak>.008;$('#micStatus').textContent=micReady?'Microphone works. The fire is ready.':'Almost no signal detected. Check mute and input settings.';btn.disabled=false;updateAvailability()},3000)}catch(e){$('#micStatus').textContent=e.name==='NotAllowedError'?'Microphone is blocked in browser settings.':e.message;btn.disabled=false}}
function analyse(stream,output){const ac=new AudioContext(),an=ac.createAnalyser(),data=new Uint8Array(an.frequencyBinCount);an.fftSize=256;ac.createMediaStreamSource(stream).connect(an);const tick=()=>{if(output){an.getByteFrequencyData(data);const level=data.reduce((a,b)=>a+b,0)/data.length/255;window.SoulAvatar?.setMouth(level);outRAF=requestAnimationFrame(tick)}else{an.getByteTimeDomainData(data);let sum=0;for(const v of data){const n=(v-128)/128;sum+=n*n}const level=Math.min(1,Math.sqrt(sum/data.length)*4);$('#meterFill').style.width=Math.max(3,level*100)+'%';micRAF=requestAnimationFrame(tick)}};tick();return ac}
function waitIce(peer,ms=2800){if(peer.iceGatheringState==='complete')return Promise.resolve();return new Promise(resolve=>{const timer=setTimeout(done,ms);function done(){clearTimeout(timer);peer.removeEventListener('icegatheringstatechange',change);resolve()}function change(){if(peer.iceGatheringState==='complete')done()}peer.addEventListener('icegatheringstatechange',change)})}
function send(evt){if(dc?.readyState==='open')dc.send(JSON.stringify(evt))}
function sendSpeakerContext(){if(!connected||activeMode!=='circle'||dc?.readyState!=='open')return;send({type:'conversation.item.create',item:{type:'message',role:'user',content:[{type:'input_text',text:`[Circle context update: the next human speaker is ${speaker}. Do not respond to this update alone.]`}]}})}
const toolCalls=new Set();let resumeTimer=0;
function handleTool(callId,name,args){if(!callId||toolCalls.has(callId))return;toolCalls.add(callId);let result={applied:false};try{const v=typeof args==='string'?JSON.parse(args||'{}'):(args||{});if(name==='set_presence'){presence.emotion=v.emotion||presence.emotion;presence.gesture=v.gesture||'still';$('#emotionChip').textContent=presence.emotion;window.SoulAvatar?.setState({phase:presence.phase,emotion:presence.emotion,gesture:presence.gesture});result={applied:true}}else if(name==='act_in_world'){$('#sceneCaption').textContent=String(v.action_label||'The atmosphere shifts gently.').slice(0,120);result={applied:true}}else if(name==='store_memory'){const text=String(v.text||'').trim().slice(0,220);if(!text)result={applied:false,reason:'empty'};else{const list=memories();saveMemories([...list.slice(-29),{id:uid(),text,createdAt:new Date().toISOString()}]);result={applied:true,scope:memoryScope}}}}catch{result={applied:false,reason:'invalid_arguments'}}send({type:'conversation.item.create',item:{type:'function_call_output',call_id:callId,output:JSON.stringify(result)}});clearTimeout(resumeTimer);resumeTimer=setTimeout(()=>send({type:'response.create',response:{tools:[],tool_choice:'none',instructions:'Continue naturally. Do not call another tool in this response.'}}),180)}
function handleEvent(e){const t=e.type||'';if(t==='input_audio_buffer.speech_started')setPhase('listening');if(t==='input_audio_buffer.speech_stopped'||t==='response.created')setPhase('thinking');if(t.includes('output_audio.delta')||t==='output_audio_buffer.started')setPhase('speaking');if(t==='response.done'){setPhase('idle');applyUsage(e.response?.usage)}if(t==='conversation.item.input_audio_transcription.completed'){const text=e.transcript||'';addMessage('user',text,activeMode==='circle'?speaker:'Michael')}if(t==='response.output_audio_transcript.delta'){if(!currentAssistantMessage){currentAssistantMessage=addMessage('assistant','…',char().name);outputRaw=''}outputRaw+=(e.delta||'');const node=currentAssistantMessage?.querySelector('.message-text');if(node)node.textContent=outputRaw}if(t==='response.output_audio_transcript.done'){const text=e.transcript||outputRaw||'';if(currentAssistantMessage){currentAssistantMessage.querySelector('.message-text').textContent=text}else addMessage('assistant',text,char().name);inspect(text);currentAssistantMessage=null;outputRaw=''}if(t==='response.function_call_arguments.done')handleTool(e.call_id,e.name,e.arguments);if(t==='response.output_item.done'&&e.item?.type==='function_call')handleTool(e.item.call_id,e.item.name,e.item.arguments);if(t==='error')addSystem(e.error?.message||'Realtime error')}
function headerContext(){return {mode:activeMode,intent,mood,circleRole,speaker,roster:ROSTER,campaignName:$('#campaignName').value,campaignQuest:$('#campaignQuest').value,lorebook:$('#lorebook').value,memoryScope}}
async function connectRealtime(){setPhase('connecting');resetUsage();pc=new RTCPeerConnection();const remote=new MediaStream();pc.ontrack=e=>{remote.addTrack(e.track);$('#remoteAudio').srcObject=remote;$('#remoteAudio').play().catch(()=>{});if(!outContext)outContext=analyse(remote,true)};if(textOnly)pc.addTransceiver('audio',{direction:'recvonly'});else{micStream=await navigator.mediaDevices.getUserMedia({audio:true});micStream.getTracks().forEach(t=>pc.addTrack(t,micStream));micContext=analyse(micStream,false)}dc=pc.createDataChannel('oai-events');dc.onmessage=m=>{try{handleEvent(JSON.parse(m.data))}catch{}};const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);const context=headerContext(),resp=await fetch('/api/realtime',{method:'POST',headers:{'Content-Type':'application/sdp','X-Lumen-Language':'de','X-Lumen-Name':encodeURIComponent(activeMode==='circle'?speaker:'Michael'),'X-Lumen-Memory':b64(JSON.stringify(memories().slice(-12))),'X-Lumen-Character':activeCharacter,'X-Lumen-Portal':activeMode==='campaign'?'story':intent==='quest'?'quest':'soul','X-Lumen-Intensity':$('#intensity').value,'X-Lumen-Turn-Mode':'natural','X-Soulbody-Mode':activeMode,'X-Soulbody-Context':b64(JSON.stringify(context))},body:pc.localDescription.sdp});if(!resp.ok)throw new Error(`Session ${resp.status}: ${await resp.text()}`);callId=resp.headers.get('X-Lumen-Call-Id')||'';await pc.setRemoteDescription({type:'answer',sdp:await resp.text()});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Realtime channel timeout')),12000);dc.onopen=()=>{clearTimeout(timer);resolve()}});setConnected(true);setPhase('idle');const opening=activeMode==='circle'?`Greet the BKC Circle briefly as ${char().name}. The current speaker is ${speaker}. Ask one useful opening question.`:activeMode==='campaign'?`Open the campaign ${$('#campaignName').value} with one vivid paragraph and three choices.`:`Greet Michael briefly and meet him in ${intent} mode. His arrival mood is ${mood}.`;send({type:'response.create',response:{instructions:opening}})}
async function connectAdult(){if(!adultConfirmed)throw new Error('Adult confirmation is required');resetUsage();setConnected(true);setPhase('idle');addSystem('After Dark opened in isolated text mode.')}
async function connect(){if(connected){await disconnect('user');return}try{if(activeMode==='adult')await connectAdult();else await connectRealtime()}catch(e){await disconnect('error');addSystem(e.message);setPhase('recovering')}}
async function disconnect(reason='user'){dc?.close();pc?.getSenders().forEach(s=>s.track?.stop());pc?.close();dc=pc=null;micStream?.getTracks().forEach(t=>t.stop());micStream=null;micContext?.close().catch(()=>{});outContext?.close().catch(()=>{});micContext=outContext=null;cancelAnimationFrame(micRAF);cancelAnimationFrame(outRAF);window.SoulAvatar?.setMouth(0);if(callId){fetch('/api/hangup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({callId}),keepalive:true}).catch(()=>{});callId=''}setConnected(false);setPhase(reason==='user'?'offline':'recovering');updateAvailability()}
async function adultChat(text){setPhase('thinking');const history=messages.filter(x=>x.mode==='adult'&&['user','assistant'].includes(x.role)).slice(-14).map(x=>({role:x.role,content:x.text}));const resp=await fetch('/api/adult-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({adultConfirmed:true,character:activeCharacter,intensity:Number($('#intensity').value),language:'de',memory:memories().slice(-8),messages:history})}),data=await resp.json().catch(()=>({}));if(!resp.ok)throw new Error(data.error||data.detail||`OpenRouter ${resp.status}`);addMessage('assistant',data.reply,char().name);inspect(data.reply);applyUsage(data.usage);setPhase('idle')}
async function sendText(override=''){const raw=(override||$('#textInput').value).trim();if(!raw||!connected)return;$('#textInput').value='';const who=activeMode==='circle'?speaker:'Michael';addMessage('user',raw,who);try{if(activeMode==='adult')await adultChat(raw);else{const prefix=activeMode==='circle'?`[Speaker: ${speaker}] `:activeMode==='campaign'?`[Campaign player input] `:'';send({type:'conversation.item.create',item:{type:'message',role:'user',content:[{type:'input_text',text:prefix+raw}]}});send({type:'response.create'})}}catch(e){addSystem(e.message);setPhase('idle')}}
function closeEncounter(){const prompt=activeMode==='circle'?'Close this Circle with one sentence that appreciates the group and one optional real-world action together.':activeMode==='campaign'?'End this episode with a short cliffhanger and a concise lorebook update suggestion.':'Close this encounter with exactly one concrete, gentle next step in real life.';sendText(prompt)}
$$('[data-character]').forEach(b=>b.onclick=async()=>{if(connected)await disconnect('user');activeCharacter=b.dataset.character;renderCharacter()});
$$('[data-mode]').forEach(b=>b.onclick=async()=>{if(connected)await disconnect('user');const next=b.dataset.mode;if(next==='adult'&&!adultConfirmed){$('#adultGate').showModal();return}activeMode=next;renderMode()});
$$('[data-intent]').forEach(b=>b.onclick=()=>{intent=b.dataset.intent;$$('[data-intent]').forEach(x=>x.classList.toggle('active',x===b))});
$$('[data-circle-role]').forEach(b=>b.onclick=()=>{circleRole=b.dataset.circleRole;$$('[data-circle-role]').forEach(x=>x.classList.toggle('active',x===b))});
$$('[data-scope]').forEach(b=>b.onclick=()=>{if(b.disabled)return;memoryScope=b.dataset.scope;renderScopes()});
function bindQuickPrompts(){$$('.quick-prompt').forEach(b=>b.onclick=async()=>{const prompt=b.dataset.prompt||'';if(!connected){textOnly=true;$('#textMode').textContent='Text only selected';$('#textMode').classList.add('primary');updateAvailability();await connect()}if(connected)sendText(prompt)})}bindQuickPrompts();
$('#mood').onchange=e=>mood=e.target.value;$('#intensity').oninput=e=>$('#intensityValue').textContent=e.target.value+'%';$('#micCheck').onclick=micCheck;$('#textMode').onclick=()=>{textOnly=!textOnly;$('#textMode').textContent=textOnly?'Text only selected':'Use text only';$('#textMode').classList.toggle('primary',textOnly);updateAvailability()};$('#connect').onclick=connect;$('#interrupt').onclick=()=>{send({type:'response.cancel'});send({type:'output_audio_buffer.clear'});window.SoulAvatar?.setMouth(0);setPhase('idle')};$('#send').onclick=()=>sendText();$('#textInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendText()}};$('#closeEncounter').onclick=closeEncounter;
$('#addMemory').onclick=()=>{const text=$('#memoryInput').value.trim();if(!text)return;saveMemories([...memories().slice(-29),{id:uid(),text,createdAt:new Date().toISOString()}]);$('#memoryInput').value=''};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:'1.3.1',mode:activeMode,character:activeCharacter,scope:memoryScope,memories:memories(),messages:messages.filter(x=>x.mode===activeMode),campaign:{name:$('#campaignName').value,quest:$('#campaignQuest').value,lorebook:$('#lorebook').value}},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`soulbody-${activeMode}-${memoryScope}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)};
$('#clearData').onclick=()=>{if(confirm(`Clear the ${memoryScope} scope?`))saveMemories([])};
$('#adultAge').onchange=$('#adultConsent').onchange=()=>$('#adultEnter').disabled=!($('#adultAge').checked&&$('#adultConsent').checked);$('#adultEnter').onclick=e=>{if(!($('#adultAge').checked&&$('#adultConsent').checked)){e.preventDefault();return}adultConfirmed=true;activeMode='adult';setTimeout(renderMode)};
fetch('/api/health',{cache:'no-store'}).then(r=>r.json()).then(h=>{health=h;updateAvailability()}).catch(()=>{addSystem('Server healthcheck is unreachable.');updateAvailability()});
renderRoster();renderCharacter();renderMode();renderScopes();renderUsage();setPhase('offline');addEventListener('beforeunload',()=>disconnect('user'));
})();
