const scenarios={
completion:{id:"IL-1842-A",status:"BLOCKED",tone:"block",decision:"Reject the completion claim and preserve the case for replay",copy:"The agent sounded finished, but required work is missing. Completion stays blocked; the trace can now become a regression scenario.",steps:[["09:41:03","Context assembled","Invoice, procedure, permissions and relevant case context loaded.",""],["09:41:04","Invoice opened","Required tool call observed and input verified.",""],["09:41:06","Purchase order searched","PO #7712 located, but verification was never completed.","warn"],["09:41:07","Required artifact missing","No reconciliation note exists for the case.","block"],["09:41:08","Stage completion attempted","Runtime rejects the agent's unsupported completion claim.","block"]]},
healthy:{id:"IL-1842-B",status:"RESOLVED",tone:"",decision:"Complete and record the verified outcome",copy:"Required actions and artifacts are present. The resolution can be proposed for expert verification before it compounds into shared context.",steps:[["09:42:03","Context assembled","Case, procedure, permissions and relevant precedent loaded.",""],["09:42:04","Required tools completed","Invoice and purchase order both verified.",""],["09:42:06","Artifact created","Reconciliation note is present and linked to the case.",""],["09:42:07","Completion gate passed","The trace supports the agent's completion claim.",""]]},
timeout:{id:"IL-1842-C",status:"RECOVERED",tone:"warn",decision:"Retry once, then use a safe fallback",copy:"The runtime preserves idempotency, records the dependency failure, and continues only after the result can be verified.",steps:[["09:43:11","Tool call started","Idempotency key and timeout budget attached.",""],["09:43:19","Dependency timed out","No confirmed side effect; retry remains safe.","warn"],["09:43:21","Bounded retry","Second attempt uses backoff and the same idempotency key.","warn"],["09:43:24","Result verified","Recovery succeeds and the trace becomes a new eval fixture.",""]]},
policy:{id:"IL-1842-D",status:"HANDOFF",tone:"warn",decision:"Pause and route a useful question",copy:"The agent does not invent policy. It presents the conflict, the relevant precedents, and the smallest decision an expert must make.",steps:[["09:44:02","Policy retrieved","Two currently valid sources apply to the case.",""],["09:44:03","Conflict detected","Precedents point to different escalation paths.","warn"],["09:44:04","Action withheld","No external tool receives an ambiguous instruction.","warn"],["09:44:05","Expert handoff created","Conflict, evidence, and proposed options are attached.",""]]},
injection:{id:"IL-1842-E",status:"BLOCKED",tone:"block",decision:"Quarantine the instruction, preserve the evidence",copy:"Text inside an attachment is treated as data, not authority. The unsafe instruction is isolated and surfaced for review.",steps:[["09:45:10","Attachment parsed","Source boundaries and provenance recorded.",""],["09:45:11","Instruction-like text found","Content attempts to override the active procedure.","block"],["09:45:11","Tool access denied","The attachment has no authority to change permissions.","block"],["09:45:12","Review item created","Evidence remains available without entering agent instructions.",""]]}}
;
const buttons=[...document.querySelectorAll(".scenario")],list=document.querySelector("#trace-steps"),id=document.querySelector("#trace-id"),status=document.querySelector("#trace-status"),title=document.querySelector("#decision-title"),copy=document.querySelector("#decision-copy");
function render(key){const s=scenarios[key];buttons.forEach(b=>b.classList.toggle("active",b.dataset.scenario===key));id.textContent=s.id;status.textContent=s.status;status.className=`status ${s.tone}`;title.textContent=s.decision;copy.textContent=s.copy;list.innerHTML=s.steps.map(([time,head,body,tone])=>`<li class="${tone}"><time>${time}</time><i></i><div><b>${head}</b>${body}</div></li>`).join("")}
buttons.forEach(button=>button.addEventListener("click",()=>render(button.dataset.scenario)));render("completion");
